### ISSUE TITLE
Merlin outcome printer still prints object syntax as <..>

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1002]
Repro:

```reason
type foo = {. bar: int};
```

<img width="229" alt="screenshot 2017-01-24 01 15 06" src="https://cloud.githubusercontent.com/assets/1909539/22241047/91cf0886-e1d2-11e6-8fbb-1176a5a28a37.png">

**Comment by SanderSpies** [comment]
I have a fix for this in a few minutes.

**Comment by SanderSpies** [comment]
In general `reason_oprint.ml` seems to need a lot of love.

**Comment by chenglou** [comment]
Works, awesome!
