### ISSUE TITLE
Array access sugar clash with ##

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1004]
```reason
(this##memoizedUpdaterCallbacks).(count) = 1;
```

Formats to

```reason
this##memoizedUpdaterCallbacks.(count) = 1;
```

Then throws parse error.

**Comment by SanderSpies** [comment]
Will pick this up after https://github.com/facebook/reason/pull/941 lands.

**Comment by Schmavery** [comment]
I fixed an issue similar to this in #930, but guess I must have missed a case.

**Comment by chenglou** [comment]
Bumping this slightly as we've encountered this again

**Comment by chenglou** [comment]
Fixed in master
