### ISSUE TITLE
switch to circle CI

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#1013]
Due to the huge wait time, it is almost impossible to have a good code review workflow with travis... We should switch to Circle CI as some other facebook project does.

**Comment by jordwalke** [comment]
Do they have any benefit in terms of workflows to upload binary artifacts?

**Comment by yunxing** [comment]
I assume it exposes a bash file that you can use to upload binary artifacts.

**Comment by yunxing** [comment]
@jordwalke Do you mind add Reason to CircleCI's ["add project"](https://circleci.com/add-projects)?

**Comment by yunxing** [comment]
Reason has been added to CircleCI's build list. Next step is to write a circleCI config.

**Comment by yunxing** [comment]
Thanks, @zpao!

**Comment by tekknolagi** [comment]
Can we close? Config is in master.

**Comment by jordwalke** [comment]
Thanks for doing this, @yunxing, @tekknolagi, @zpao.  This makes PRs and contributions so much easier.
