### ISSUE TITLE
Add sublime package to package control

### ISSUE THREAD

**Issue by aackerman** [facebook/reason#1014]
I wanted to install the sublime package for Reason but it doesn't look like it's been published to package control yet. I would like to help, but I don't have any experience publishing to package control, based on the [instructions](https://packagecontrol.io/docs/submitting_a_package) it seems to assume the package code would be at the root of the repo, so it might need to be extracted to a sublime-reason repo or something sensible. The source seems to be [here](https://github.com/facebook/reason/tree/e59a14d2241c30292799df9c3e322c6078420788/editorSupport/sublime-reason).

**Comment by jaredly** [comment]
https://packagecontrol.io/packages/Reason
