### ISSUE TITLE
Ask user for input for syntax errors

### ISSUE THREAD

**Issue by SanderSpies** [facebook/reason#1020]
To improve our error messages we should encourage developers to contribute and write better error messages. First step would be a tutorial on how to change the .messages file, second step would be to ask users to fix empty error messages (eg. `<SYNTAX ERROR>`).

**Comment by yunxing** [comment]
Thanks for doing this, @SanderSpies.

**Comment by chenglou** [comment]
Woah just saw this. Thanks! This'll remove a couple more questions from chat support
