### ISSUE TITLE
Rename refmt to refmt.exe

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1031]
From @bobzhang

> in case we support windows later on.

I've forgotten how node works on windows. Do all the npm binaries that don't add `.exe` not work on windows?

@jordwalke @yunxing @tekknolagi

**Comment by yunxing** [comment]
Don't know much about how node works, maybe we can also create a symlink?

**Comment by tekknolagi** [comment]
I don't know anything about Node or Windows :-

**Comment by OvermindDL1** [comment]
> I've forgotten how node works on windows. Do all the npm binaries that don't add .exe not work on windows?

Or they make a bouncer `.bat` file that redirects to the exe version...  Yes Windows is a pain...

**Comment by jordwalke** [comment]
> No symlinks on Windows without admin.

@OvermindDL1 I believe that windows can pretty reliably perform symlinks to directories, but not individual files, is this correct?

**Comment by OvermindDL1** [comment]
> @OvermindDL1 I believe that windows can pretty reliably perform symlinks to directories, but not individual files, is this correct?

On Windows Vista and higher symlinks between directories should be reliable.  Pre-vista they were *not*.
On Windows at least 10 (unsure of early, maybe back to 7) file symlinks should be reliable.

However, to do symlinks you either have to be the Guest user, or an Admin user.
Yep you read that right, you have to be the 'Guest' account or launch the program with "Administrative Privileges".  The reasoning is that Guest is locked down enough they cannot symlink to anything they cannot see anyway, but normal users can symlink to anything, bypassing certain security aspects on the system.  Yes it is stupid.  ;-)

**Comment by bobzhang** [comment]
symlink does not work across drivers though

**Comment by OvermindDL1** [comment]
> symlink does not work across drivers though

There are cases where it can (only on Windows 10 I think), but true in the general case yeah.

**Comment by chenglou** [comment]
The nit is that people have asked whether `foo.exe` is a windows binary before. Maybe it should be `refmt.exe`, and on the unix side we link `refmt` to it for convenience or something

**Comment by jaredly** [comment]
bucklescript supports windows at this point, I think we're done?
