### ISSUE TITLE
Expose just the parser/printer binary

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1032]
This profits build systems (and as of today, the bucklescript repo) in that they only need a parser that outputs binary AST. This also solves our problem of having changed `refmt` to default to printing reason code rather than binary AST. `ocamlc -pp refmt -Impl foo.re` doesn't work anymore; we now need `ocamlc -pp "refmt --print binary" -Impl foo.re`. Build system can have their own default of `ocamlc -pp reason_parser -Impl foo.re`.

There are other solutions too, but having a light parser/printer is also a good fallback in case other pieces don't build well on windows or take long.

cc @bobzhang

**Comment by tekknolagi** [comment]
Why is adding "--print binary" bad? Or do you want something that is completely stable in its behavior?

**Comment by bobzhang** [comment]
I am 100% on board with the less deps for parser

**Comment by chenglou** [comment]
Got bspacked thing now

**Comment by tekknolagi** [comment]
@chenglou link?

**Comment by chenglou** [comment]
Oh, I meant it's not a big worry anymore
