### ISSUE TITLE
SYNTAX ERROR might not be the best error message for syntax that mimics but is inconsistent with javascript.

### ISSUE THREAD

**Issue by glennsl** [facebook/reason#1037]
E.g. `[...xs, x]` causes SYNTAX ERROR on the comma, and if you're ~~a bit dense~~ more familiar with javascript it can take a while to see problems like this.

The only supported list spread syntax is `[x, ...xs]` because it will be desugared into ocaml `x :: xs` before optionally being transpiled to javascript. Which isn't quite as obvious for those who use reason more as a syntax flavor of javascript, and therefore don't care as much about the middle ocaml step and the limitations that imposes.

**Comment by chenglou** [comment]
Merging into the list concat issue!

I think we should at least warn about this, cc @SanderSpies

**Comment by chenglou** [comment]
Reopening this to track the warning. The other issue can track the actual syntax change, if we decide so.
