### ISSUE TITLE
More specialized error message based on lookahead token

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#1038]
Currently, each error message in our database represents a state in the LR(1) parser. This is not ideal as there could be multiple actions leading to the same error state. For example, the following two inputs will end up with the same error state, thus share one error message.
```
[...hd, tl]
```
and 
```
[%$#hd, tl]
```
In this case, it is hard to customize a friendly error message for the first case, as requested in #1037. The current solution is to modify our parser and add a specific rule.

One solution to this issue is to improve the error message DSL provided by menhir. The default DSL today can only attach an error message to a state (see https://github.com/facebook/reason/blob/master/src/reason_parser.messages). But what we really want is to attach an error message to a `(state, lookahead token)` pair.

**Comment by anmonteiro** [comment]
No longer an issue:

```bash
echo '[...hd, tl]' | ./_build/install/default/bin/refmt
File "", line 1, characters 1-6:
Error: Lists can only have one `...` spread, at the end.
Explanation: lists are singly-linked list, where a node contains a value and points to the next node. `[a, ...bc]` efficiently creates a new item and links `bc` as its next nodes. `[...bc, a]` would be expensive, as it'd need to traverse `bc` and prepend each item to `a` one by one. We therefore disallow such syntax sugar.
Solution: directly use `concat` or other List helpers.

echo '[%$#hd, tl]' | ./_build/install/default/bin/refmt
File "", line 1, characters 2-4:
Error: Syntax error
```
