### ISSUE TITLE
ES6-like string interpolation

### ISSUE THREAD

**Issue by glennsl** [facebook/reason#1040]
This is related to #899 but should be much more straightforward to implement.

Essentially a syntax translation from something like:
```reason
"Fifteen is ${a + b} and not ${2 * a + b}."
```
to

```reason
"Fifteen is " ^ (a + b) ^ " and not " ^ (2 * a + b) ^ "."
```

**Comment by glennsl** [comment]
This also seems like a good first issue for one to dip ones toes into contributing. If someone could give me some pointers I'd give it a shot.

**Comment by hcarty** [comment]
I have something started as a ppx.  I still need to clean the code up enough to release but it may help as a starting point if you're interested.  The target is currently format strings (`"%s"`/`"%a"`-style) but anything else could be used as a target.

**Comment by SanderSpies** [comment]
Related: https://github.com/facebook/reason/pull/366. Note the PRs to free
` are still open.

**Comment by glennsl** [comment]
Wait, so there already is syntax for string interpolation with `{|foo|}`? How do you embed an expression in it?

**Comment by vramana** [comment]
If you are looking for an example, here is one. https://github.com/reasonml/rebel/blob/master/src/merlin.re#L93

**Comment by hcarty** [comment]
@glennsl There is no interpolation in `{|foo|}` - that form is meant to allow unescaped content within a literal.

**Comment by glennsl** [comment]
@hcarty `%s` would do fine. I had that exact same idea. It doesn't matter much to me what the exact syntax is, so if `{| |}` will do the trick too, that's fine by me. Otherwise I'd be happy to take a look at the ppx you've started on.

**Comment by glennsl** [comment]
@hcarty ah, that's more commonly termed a raw string literal, no?

**Comment by hcarty** [comment]
http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec250 - "quoted strings" in the OCaml manual.

**Comment by glennsl** [comment]
BuckleScript now has a simple form of string interpolation: https://bloomberg.github.io/bucklescript/Manual.html#_unicode_support_with_string_interpolation_since_1_7_0

Some sugar would still be pretty _sweet_ though!
