### ISSUE TITLE
No location for js obj sugar

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1043]
```reason
type foo = {a: int};

let bar a => a.a;

bar {"hello": 1};
```
**Compile this with BuckleScript**.
The error should be on the last line; instead, it has no location

@bsansouci

**Comment by SanderSpies** [comment]
This already works for me.

**Comment by chenglou** [comment]
Really? Just tested on master and it still points to the 0th line (aka no location from merlin)?

**Comment by SanderSpies** [comment]
Weird tried the syntax in Nuclide, and the error was in the right location.

Anyway, I created a wiki page for those who want to fix this: https://github.com/facebook/reason/wiki/Improve-error-message-locations

**Comment by chenglou** [comment]
Update: sander's talking about a different error (uninterpreted extension) due to not using BS to compile it. I've updated my description.
