### ISSUE TITLE
Non-ascii characters destroyed by refmt

### ISSUE THREAD

**Issue by sgrove** [facebook/reason#1053]
Bit surprised this hasn't been hit yet!

When running `"中文"` through `refmt`, we get `"‰∏≠Ê\150\135"`

Not sure the cause, looks like it could hit BS as well https://github.com/reasonml/rehydrate/issues/42

**Comment by OvermindDL1** [comment]
OCaml itself's Unicode support is... basically non-existent, has to be supported via external libraries, so I think it is treating it as just normal extended ascii (single char 0-255)...

**Comment by hcarty** [comment]
It shouldn't mangle unicode literals though - the bytes should pass through unscathed.
