### ISSUE TITLE
Windows - npm postinstall - failing

### ISSUE THREAD

**Issue by TryingToImprove** [facebook/reason#1058]
When trying to install `ReasonProject` it fails while installing.

**Steps**
1) Use Windows
2) clone ReasonProject
3) run `npm i` using Windows CMD
4) failing

It seems like a issue with ocaml, but I am not sure:
`npm ERR! ocaml@4.2.3 postinstall: `./yarn-install-project.sh`

**npm-log.log**
```
.....
9468 verbose cwd C:\test\ReasonProject
9469 error Windows_NT 10.0.14393
9470 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
9471 error node v7.4.0
9472 error npm  v4.0.5
9473 error code ELIFECYCLE
9474 error ocaml@4.2.3 postinstall: `./yarn-install-project.sh`
9474 error Exit status 1
9475 error Failed at the ocaml@4.2.3 postinstall script './yarn-install-project.sh'.
9475 error Make sure you have the latest version of node.js and npm installed.
9475 error If you do, this is most likely a problem with the ocaml package,
9475 error not with npm itself.
9475 error Tell the author that this fails on your system:
9475 error     ./yarn-install-project.sh
9475 error You can get information on how to open an issue for this project with:
9475 error     npm bugs ocaml
9475 error Or if that isn't available, you can get their info via:
9475 error     npm owner ls ocaml
9475 error There is likely additional logging output above.
9476 verbose exit [ 1, true ]
```

**Comment by chenglou** [comment]
Master is currently known not to work on windows. We're actively working on the esy branch for a better generalized version of our install process. I'm leaving this comment here for near-future contributors.

**Comment by jordwalke** [comment]
You could test the early preview of the future package building workflow that we're building called `esy`:

https://github.com/andreypopp/esy-ocaml-project

This will also not work on windows right now because it uses a ton of bashisms and makefiles, but one way people can help is to test it with something like msys2 or mingw installed and let us know what does/doesn't work.

**Comment by chenglou** [comment]
This is stale. As an aside, sorry for the windows-related problems. In case you still encounter one, we've created a centralized thread here to solve it: https://github.com/reasonml/reasonml.github.io/issues/195

Closing this one. Sorry again.
