### ISSUE TITLE
Mutually Recursive Types

### ISSUE THREAD

**Issue by jacobp100** [facebook/reason#1060]
How would I define the type following type?

```reason
type atomBase = {
  superScript: mathList,
  subScript: mathList,
};

type atom =
  | Ordinary atomBase string
  | Fraction atomBase mathList mathList;

type mathList = list atom;
```

**Comment by SanderSpies** [comment]
I believe you are looking for the `and` keyword:


```

Type atom =

  | Ordinary string
  | Fraction mathList

and
type mathList = list atom;

```

**Comment by jacobp100** [comment]
Thanks! Is it possible to chain more than two statements together?

**Comment by yunxing** [comment]
@jacobp100 yes, you have have more than two type definitions together. 

Also, the "type..and..."  pattern is recursive by default. You can use "type nonrec" to make a non-recursive type definition.

**Comment by jacobp100** [comment]
Is there special syntax for more than two statements? Just using two `and`s didn’t seem to work!

**Comment by yunxing** [comment]
@jacobp100 This should work as an example:
```
type a = c
and b = a
and c = int;
```

**Comment by jacobp100** [comment]
Thanks! I was writing `and type`. Working now!
