### ISSUE TITLE
Refmt resolves octal literals to decimal literals severely hurting readability in some cases

### ISSUE THREAD

**Issue by kyldvs** [facebook/reason#1061]
For example with unix file permissions:

```
Unix.mkdir "foo" 0o755;
```

Becomes:

```
Unix.mkdir "foo" 493;
```

**Comment by yunxing** [comment]
Dup of #511: refmt changes the representation of integers

This will get fixed with 4.3.0

**Comment by kyldvs** [comment]
Ah, searched and didn't see the dupe. Sorry about that!
