### ISSUE TITLE
make release -- check if current head is on remote/master

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#1063]
We shouldn't release anything that's local only. The `make release` target should check if the current HEAD that we are about to publish is on remote.

**Comment by tekknolagi** [comment]
How does this work with people who work from forks, instead of in branches on the main tree?

**Comment by yunxing** [comment]
@tekknolagi Good point. I wonder if there is a way to say, instead of remote/master, "git@github.com:facebook/reason.git"/master?

**Comment by tekknolagi** [comment]
Will be fixed by https://github.com/facebook/reason/pull/1067.
