### ISSUE TITLE
Merging in some default ppxes

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1068]
We might wanna hide the concept of ppx to newcomers. We can simply merge our current ppxes in.

We'd have `refmt --jsx --otherflags`. After parsing we'd run the ppx over the AST internally.

**Comment by bobzhang** [comment]
This also make builds slightly faster

**Comment by tekknolagi** [comment]
@chenglou what ppxes in particular do you mean?

**Comment by yunxing** [comment]
@bobzhang how does this make build slightly faster?

**Comment by bobzhang** [comment]
Since it saves calling another processor and ast marshalling

**Comment by kennetpostigo** [comment]
Has work for this moved forward? Is so is this okay to close?

**Comment by chenglou** [comment]
the ones we care about can be bundled with bs now
