### ISSUE TITLE
Document the utop/rtop directives

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1072]
I think `#load` and `#require` should at least be on the repl startup screen. Also, the Reason logo is nice but at this point it's taking up space in which we can cram more examples (like `#require`).

Also, `man utop` didn't give me anything.

cc @tekknolagi For some tasteful re-arrangement of our rtop screen.

**Comment by hcarty** [comment]
It would get noisy after a while, but it could also be nice to provide help like the compiler does - "Foo is not in scope - if this is provided by a library it may need to be #require'd"  But with better wording.

**Comment by hcarty** [comment]
Also, `#use "topfind";;` says some of this out of the box but utop suppresses the message by default.

**Comment by chenglou** [comment]
We need https://github.com/reasonml/BetterErrors/ but plugging in the custom errors will be a pain

**Comment by kennetpostigo** [comment]
BetterErrors in there would be an amazing experience for people starting out and those learning.

**Comment by hcarty** [comment]
Improved error messages like that could be upstreamed to utop or possibly even the bare OCaml repl.

**Comment by chenglou** [comment]
Don't wanna derail the issue, but for BuckleScript we got https://github.com/bloomberg/bucklescript/issues/747#issuecomment-246137462. If we implement some custom error messages there maybe we can upstream such API proposal to ocaml proper. I'd like to see library-specific error messages that people can plug.

**Comment by tekknolagi** [comment]
@chenglou what do you mean -- just the text? Suggestions to use those?

**Comment by chenglou** [comment]
Yeah just some tasteful examples to substitute the Reason ascii art. Plus some actual man page in the future or something.
