### ISSUE TITLE
Better error for JSX without spaces

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1073]
From discord:

> So the first line compiles, but the second does not:
> `<li> <a>(ReactRe.stringToElement item)</a></li>`
> `<li><a>(ReactRe.stringToElement item)</a></li>`

Can we warn this better?

**Comment by anmonteiro** [comment]
We parse this correctly now:

```shell
$ echo '<li><a>(ReactRe.stringToElement(item))</a></li>' | ./_build/install/default/bin/refmt
<li> <a> {ReactRe.stringToElement(item)} </a> </li>;
```
