### ISSUE TITLE
Pull out Rebuild

### ISSUE THREAD

**Issue by IwanKaramazow** [facebook/reason#1074]
Does it make sense to pull out Rebuild into a separate repo?
Don't think it should be part of Reason's core.

**Comment by chenglou** [comment]
Now that we have esy, yeah.

**Comment by yunxing** [comment]
We can do that -- it's also better if we can make it upstream, much less hacks required on our side.

**Comment by rgrinberg** [comment]
jBuilder fixes the modularity issues without creating extra repos. I'd discourage you guys in general from creating too many repos. Don't you have a monorepo at facebook? You should be well aware of the benefits :)

**Comment by anmonteiro** [comment]
This is done... Rebuild is gone https://github.com/facebook/reason/pull/1956
