### ISSUE TITLE
Recovering parser for unterminated string literal.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#108]
The one issue that it seems we haven't covered with the recovering parser is the unterminated string literal. It will cause an error in `reasonfmt_merlin`.

**Comment by alok** [comment]
I'm not sure if this is the same issue, but I tried running refmt on this piece of code and got the error `Error: This comment contains an unterminated string literal`

`/* let f = x => switch (x) {| A => 0 }; */`

The `{|` needs a space in between, but I didn't know that, and only found out by randomly deleting characters until something happened.

I feel like refmt should be able to handle this, or at least there should be a clearer error message.
