### ISSUE TITLE
Bake reactjs_jsx_ppx into reason

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1081]
No more external facing ppx

**Comment by IwanKaramazow** [comment]
What if we don't want the list to array conversion?

**Comment by chenglou** [comment]
To be clear, I'm saying reactjs_jsx_ppx should be an implicit post-processing step of refmt. Like how we vendored ppx_deriving. How we change reactjs_jsx_ppx doesn't change

**Comment by jordwalke** [comment]
Does this make it more difficult for anything that doesn't need some of those features? Does any of the special jsx preprocessing change the semantics for people who are using jsx outside of ReactJS?

**Comment by chenglou** [comment]
You'd probably expose it as a refmt flag? `--use-jsx`? Otherwise it's not post-processed.

**Comment by OvermindDL1** [comment]
Or what if they use a different jsx ppx that goes to something other than react?

**Comment by bobzhang** [comment]
@OvermindDL1 it does not matter, since you can turn it off

**Comment by kennetpostigo** [comment]
I think this has landed, @chenglou is this okay to close?

**Comment by chenglou** [comment]
Yep, thanks
