### ISSUE TITLE
README says "MIT license" but License.txt says BSD 3-clause

### ISSUE THREAD

**Issue by tekknolagi** [facebook/reason#1091]

**Comment by chenglou** [comment]
[React](https://github.com/facebook/react/blob/3788654d57933461961a0296afd924493129e51d/package.json) doesn't have a license in package.json. We'll remove that line for us too.

**Comment by jakealbert** [comment]
README and LICENSE.txt still disagree.
What license is Reason under?

**Comment by tekknolagi** [comment]
@jakealbert Just cleaned up the licenses. Please see LICENSE.txt in the project root :)
