### ISSUE TITLE
`let foo to::(to: string) => 1` generates a syntax error

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1095]

**Comment by hcarty** [comment]
Because of the reserved word or is there another cause?

**Comment by chenglou** [comment]
because of the reserved word. It ends in `UIDENT LPAREN WITH`. I can provide a better error message (if we can't fix it altogether; I like the fact that js objs can contain reserved keywords) but I'm not sure which other cases fall into this and don't wanna make the message misleading.

**Comment by SanderSpies** [comment]
We should be able to create better errors for reserved words. I'll check when I have time.

**Comment by chenglou** [comment]
Fixed through #1541. Will ship this week
