### ISSUE TITLE
refmt segfault on windows

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#1097]
```
refmt.exe hi.re --in-place
```

if `hi.re` is empty, it is fine, otherwise a segfault (for a simple expression like `1;`)

**Comment by bobzhang** [comment]
I would suggest we take two steps:

1. provide a minimal reason parser interface : 
`filename -> structure/signature` shake away as much third party dependency as possible, 
very few ocaml third party libraries are tested on Windows.
2. do more logging, see where it went wrong

**Comment by jordwalke** [comment]
Wait - I was not aware that we had even the most remote windows support. What are the steps to repro:

```
git clone https://github.com/facebook/reason
cd reason
npm install
... 
refmt.exe hi.re --in-place  #segfault
```

What do we do for `...`? Are you testing with mingw/msys/cygwin?
