### ISSUE TITLE
Overeager JSX punning

### ISSUE THREAD

**Issue by rickyvetter** [facebook/reason#1099]
```reason
<Bar foo=Baz.foo />
```

refmt =>

```reason
<Bar foo />
```

Should be no change.

Seems very related to #962

**Comment by IwanKaramazow** [comment]
I'm debugging currently.

**Comment by IwanKaramazow** [comment]
PR has been made 🙌
Actual bugfix took me 3min, installing Reason on opam 40 min. 😂

**Comment by chenglou** [comment]
Fixed.
