### ISSUE TITLE
Any objection to converting the pretty printer to Reason?

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#11]

**Comment by jordwalke** [comment]
I thought this would be difficult to self-host because of the challenges in building Reason from source, when you don't have an available Reason. But then I realized we can use a simple trick. The OCaml compiler (supposedly) supports loading files that are simply serialized ASTs. (The same output that `-pp` accepts, and the same output that `refmt` spits out by default).

So we can simply check in the serialized AST for `reason_pprint_ast` and friends. Our build scripts for Reason can simply disregard the actual `.re` files and only ever build the serialized AST files. The result is that it successfully builds a version of Reason that is a binary, even if Reason was not originally installed.

**Comment by yunxing** [comment]
@jordwalke Interesting idea. If we are able to do that, I imagine we can even write parsers in reason as well (need to add a -pp option in Menhir first).

**Comment by chenglou** [comment]
Stale, will keep it in ocaml for now
