### ISSUE TITLE
Support for private extensible variants?

### ISSUE THREAD

**Issue by rickyvetter** [facebook/reason#1101]
Right now it doesn't look like private constructors are respected in reason.

Original OCaml:
```ocaml
type foo += private C of int
```
Actual:
```reason
type foo +=
  | C int;
```

Expected:
```reason
type foo +=
  | private C int; /* Error: Unbound value pri */
```

**Comment by chenglou** [comment]
Hot damn what are you trying to do

**Comment by rickyvetter** [comment]
@chenglou don't worry about it 🕵🏻

**Comment by jordwalke** [comment]
Great first task and high pri because it's regarding completeness!

**Comment by IwanKaramazow** [comment]
Should be familiar terrain for me, will look into it

**Comment by SanderSpies** [comment]
@IwanKaramazow 💪

**Comment by IwanKaramazow** [comment]
Ok, this was already implemented.

```reason
type water = ..;
type molecules = string;
type water += pri Ocean molecules;
```

Reason uses `pri` instead of `private`, this probably originates from @SanderSpies's new object syntax. Do we just document this? Or should I make it `private` in this case?

**Comment by rickyvetter** [comment]
Ahh interesting - when I refmt that code I get:

```reason
type water = ..
type molecules = string
type water +=
  | Ocean of molecules
```

So maybe it's just an issue with refmt not handling it? It doesn't work in any direction ml <=> re or self formatting.

**Comment by IwanKaramazow** [comment]
So it parses, but prints incorrectly. I'll fix it.

**Comment by SanderSpies** [comment]
In general it would be great if we could try to convert more OCaml libraries to Reason and see if it works.

**Comment by jordwalke** [comment]
Might want to do this on top of Fred's diff.

**Comment by IwanKaramazow** [comment]
Opened a PR that should be compatible with Fred's diff, cherry-picking the commit should suffice?
