### ISSUE TITLE
Single variant types

### ISSUE THREAD

**Issue by ccorcos** [facebook/reason#1106]
`refmt` will convert this:

```re
type carOwner = CarOwner string car;
```

into this: 

```re
type carOwner =
  | CarOwner string car;
```

I actually like how this is going to enable really clean git diffs. However, i think its worth mentioning this in the documentation. Otherwise its a bit confusing since its essentially superfluous syntax. When I saw that correction I thought "What's that `|` doing?".

**Comment by chenglou** [comment]
See also https://github.com/facebook/reason/issues/546#issuecomment-225034433 and https://github.com/facebook/reason/pull/571#issuecomment-243378593

cc @IwanKaramazow. We should have a unified thing for "should this break line" and "should this have a bar in front when it's on a single line", etc.

**Comment by chenglou** [comment]
Yeah I think this is fine for now
