### ISSUE TITLE
syntax highlighting on named arguments

### ISSUE THREAD

**Issue by ccorcos** [facebook/reason#1120]
Using Atom editor with `nuclide`:

<img width="213" alt="screen shot 2017-03-06 at 5 53 45 pm" src="https://cloud.githubusercontent.com/assets/1794527/23638332/e5cf6564-0295-11e7-829e-f661f144b02a.png">

**Comment by chenglou** [comment]
Yeah, the syntax highlighting hasn't been updated to include label punning feature yet.

**Comment by anmonteiro** [comment]
This is related to the old syntax. I think it highlights fine on the new syntax.
