### ISSUE TITLE
Test failing on 4.02.3

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#1129]
#1126 Introduces a new test case which is failing on 4.02.3. I think this would be fixed by https://github.com/let-def/ocaml-migrate-parsetree/commit/0e217e8f2ca6f78d3f902a4432adca120f24cd8c. 

We need a new version of ocaml-migrate-parsetree on opam so we can use that fix. @let-def could you publish a new version?

**Comment by let-def** [comment]
New version in preparation, there are still a few bugs to fix. Hopefully it will be merged by this evening (morning for pacific time people :)).

**Comment by tekknolagi** [comment]
@let-def Awesome! How are things looking?

**Comment by let-def** [comment]
ocaml-migrate-parsetree got merged. ppx_tools_versioned is still waiting.

**Comment by tekknolagi** [comment]
Swell. Looking forward to a green master.
