### ISSUE TITLE
Variant type parens

### ISSUE THREAD

**Issue by rickyvetter** [facebook/reason#1132]
are parens necessary in this case?

```reason
type t 'a =
  | A ('a => unit)
  | B ('a => int => unit);
```

seems like we can always identify the variant, so the type wouldn't need them. but maybe im missing a case?

**Comment by hcarty** [comment]
```
type t 'a =
  | A 'a => 'a tt
  | B 'a => int => unit
```
It's ambiguous if `A` wraps a function that takes `'a` and returns `'a tt` or if it returns `'a` with a value of type `tt` as as second parameter.

**Comment by bsansouci** [comment]
@chenglou we can probably close this one :)

**Comment by chenglou** [comment]
One day we'll be working in legit AST editors and side-step these
