### ISSUE TITLE
Add file type icon to editor themes

### ISSUE THREAD

**Issue by glennsl** [facebook/reason#1135]
To start with, [Seti UI](https://github.com/jesseweed/seti-ui) seems to be a popular (icon) theme for many editors, and requires the icon to be an SVG. Is the reason logo available as SVG somewhere?

**Comment by kennetpostigo** [comment]
If you install file-icons on vscode they have the reason for .re files

**Comment by glennsl** [comment]
Ah, thanks! That'll certainly do for now.  The project looks a bit iffy license-wise though.

**Comment by kennetpostigo** [comment]
This should be good to close
