### ISSUE TITLE
Issue building App

### ISSUE THREAD

**Issue by timurtu** [facebook/reason#1141]
I'm getting the following error when trying to create an app

<img width="1280" alt="screen shot 2017-03-14 at 10 11 29 pm" src="https://cloud.githubusercontent.com/assets/4442012/23930914/a946b66c-0905-11e7-91fb-02adfc533953.png">

[Here is the repo](https://github.com/timurtu/reason-react-app)

**Comment by jordwalke** [comment]
Should this issue go in the reason-react repo?

**Comment by timurtu** [comment]
This was actually resolved my bad
