### ISSUE TITLE
refmt locally abstract types that cannot compile

### ISSUE THREAD

**Issue by rickyvetter** [facebook/reason#1142]
The code in reactRe gets to a point where it cannot compile once it's been refmtted. The issue is [this function](https://github.com/reasonml/reason-react/blob/7f0aaf80e858e304db7e72f0781f46d8a0305ed5/src/reactRe.re#L208-L232).

Input:

```reason
let findFirstCallback
    (type a)
    (type b)
    (callbacks: array (Js.null (a, b)))
    (callback: a)
    :Js.null b =>
  [%bs.raw
    {|
  ...
|}
  ]
  callbacks
  callback
  [@bs];
```

Output:

```reason
let findFirstCallback (type a b) (callbacks: array (Js.null (a, b))) (callback: a) :Js.null b =>
  [%bs.raw {|
  ...
|}] callbacks callback [@bs];
```

note the `(type a) (type b)` => `(type a b)`. This makes the code fail to compile with BuckleScript.

**Comment by jordwalke** [comment]
@rickyvetter Whoa, this is really strange. `(type a b)` is simply the AST representation of locally abstract types (which Fred implemented as part of his abstraction). Nothing has changed in the actual AST representation.

**Comment by rickyvetter** [comment]
It looks like my global version of reason (which was doing the refmt) is different than the version that BuckleScript is using to compile.

Global: Reason 1.10.2 @ 92b107b

BS: Reason 1.8.2 @ ac73dea

**Comment by chenglou** [comment]
^ btw, just to be clear: this isn't an inconvenience of version disparity. It's trivial to sync both versions in bsconfig.json, we just didn't for the sake of testing this

**Comment by rickyvetter** [comment]
So it looks like I just need to be more careful about matching my editor tooling with my compiler tooling? If that's the case then this can be closed.

**Comment by chenglou** [comment]
Nono, this is a legit bug. Keep it open.
Your editor & compiler tooling can be matched by me in the bsconfig.json. Let's not match them for now to dogfood master

**Comment by jordwalke** [comment]
> Let's not match them for now to dogfood master

I don't understand that. The editor reformats to a syntax that the bsconfig.json can't understand. I think you need to match them, whether they are both on master, or both on a stable branch, right?

**Comment by chenglou** [comment]
Bumping this a bit. We'd like to track master if possible

**Comment by jordwalke** [comment]
What specifically is blocking you? Do I need to update the global `refmt` that people have installed? (I can do that as soon as they push `reason-parser 1.13` to opam).

**Comment by chenglou** [comment]
Since this doesn't parse that piece in reason-react correctly we're still at a very old version of reason

**Comment by jordwalke** [comment]
Is there anything I need to do? Can you just have bs use the installed version of Reason? (Or if we get binary npm packages, can you depend on those so you can model your package dependency versions)? It should be possible to upgrade bs, but keep an old version of reason imho. A package dependency helps there.

**Comment by chenglou** [comment]
I can. But that means we can't use master refmt

**Comment by jordwalke** [comment]
We'll see. Depending on how we build the binary releases, it could end up being automated as part of CircleCI per commit/release.

**Comment by chenglou** [comment]
Fixed in master.
