### ISSUE TITLE
Functor inline module type requires semiclon

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1144]
Repro:

```reason
module MakeSyntheticEvent (Type : {type t;}) => {...}
```

Note `{type t;}` needs the semicolon. Removing it causes the error "expects }"

Low pri

**Comment by jordwalke** [comment]
For inline expression blocks recall how we were thinking of encouraging or requiring that final semicolon to avoid confusion with record punning? Making the inline module semicolon optional seems at odds with that right?

**Comment by chenglou** [comment]
Not an issue in master anymore!
