### ISSUE TITLE
[@@nonrec] tag added from Reason -> OCaml conversion causes OCaml syntax error

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1153]
```Reason
include
  EventTargetRe.Impl {
    type nonrec t = t;
  };
```

Converts back to OCaml:

```OCaml
include EventTargetRe.Impl(struct type nonrec t = t[@@nonrec ] end)
```

Which causes a syntax error in the `[@@nonrec]` part.

**Comment by tekknolagi** [comment]
Which OCaml version?

**Comment by chenglou** [comment]
4.02.3

**Comment by jaredly** [comment]
this is an ocaml printing error, I don't think we can fix it here

**Comment by hcarty** [comment]
I realize most of these Reason -> OCaml errors are pretty old.  It may be good in general to direct users to [ocamlformat](https://github.com/ocaml-ppx/ocamlformat) if/when they need to covert from Reason to OCaml syntax.
