### ISSUE TITLE
Add reason-mode to melpa

### ISSUE THREAD

**Issue by iensu** [facebook/reason#1155]
Thanks for an awesome project!

I really would like to start using reason more, however, currently there is no clean way of installing reason-mode in Emacs using standard tools such as Cask or package.el which creates a bit of an inconvenience. 

Extracting reason-mode into its own Github repo would allow it to be linked to [Melpa](https://github.com/melpa/melpa) or even to be installed directly through [Cask](https://github.com/cask/cask).

**Comment by chenglou** [comment]
cc @anmonteiro. Not sure how to do this

**Comment by anmonteiro** [comment]
I opened this just 2 days ago https://github.com/melpa/melpa/pull/5054

**Comment by chenglou** [comment]
Cool, closing this one then!
