### ISSUE TITLE
bspacks is broken by adding ocaml-migrate-parsetree

### ISSUE THREAD

**Issue by tekknolagi** [facebook/reason#1156]
@let-def we're having trouble bspacking ocaml-migrate-parsetree. More specifically, having trouble including the appropriate files after preprocessing with `make`.

```
File "migrate_parsetree_versions.ml", line 696, characters 23-42:
Error: Unbound module OCaml_OCAML_VERSION
```

We're trying to figure how we can preprocess the source files then pack them all together as we do with result, reason, refmt, etc.

**Comment by chenglou** [comment]
Precision: `./bspacks/reason_bspack.sh` uses bspack, to which we add `-I src/paths`, to pack every file into a single file (good for cutting out intermediate tooling, for windows, etc.)

**Comment by chenglou** [comment]
Btw, somewhat related: upgrading bspack flow with #1157

**Comment by let-def** [comment]
If the version of OCaml is fixed, you can directly run sed with s/OCAML_VERSION/40x/g.

The processed files have the .pp suffix, here you want:
`ocaml-migrate-parsetree/_build/default/src/migrate_parsetree_versions.pp.ml`

**Comment by chenglou** [comment]
@let-def thanks. After patching things & renaming files & bringing `Result` into scope (I'm on 4.02.3), I get this:

```
File "ppx_deriving.ml", line 7, characters 5-24:
Error: Unbound module Ast_convenience_404
```

**Comment by let-def** [comment]
Then ppx_tools_versioned is not in scope.

**Comment by chenglou** [comment]
@let-def ok thanks. @tekknolagi and I managed to move until this point now:

```
File "reason_parser.ml", line 5, characters 2-42:
Error: Unbound value MenhirLib.StaticVersion.require_20160825
```

A bit lost here. Do you know what's happening? See the updated #1157.

**Comment by jordwalke** [comment]
Perhaps we should just get some prebuilt binaries?
