### ISSUE TITLE
Inline records in variant type definitions aren't pretty-printed properly in rtop

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#1163]
Reason 1.11.0 + OCaml 4.04.0 from opam

Inline record arguments to variant constructors are not pretty-printed properly from rtop but they do show up properly in actual values:

For example:

```reason
Reason # type t = | A { x : int };
type t = A
Reason # A { x : 1 };
- : t = A {x : 1}
```

`refmt` does the right thing so it seems to be limited to `rtop`.

**Comment by jordwalke** [comment]
Fixed here: https://github.com/facebook/reason/pull/2336
