### ISSUE TITLE
Non-recursive type by default

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1171]
See examples [here](https://github.com/reasonml/reason-react/blob/eda683568492971e314924e0eb108099305c0622/src/reactEventRe.re#L52)

Currently let bindings are non-recursive by default, and types are recursive. We should at least make it consistent.

For the purpose of our future React API, we'd like parsing type as non-recursive by default. We'd also introduce `type rec foo = foo`.

@bobzhang @jordwalke

**Comment by Schmavery** [comment]
Different than #1116?

**Comment by chenglou** [comment]
Thanks. Merging into #394
