### ISSUE TITLE
there is no easy way to express uncurried function creation

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#1172]
in ocaml it is `fun [@bs] x y -> x `, in reason, it has to be `((fun x  y=> x ) [@bs])`

**Comment by Schmavery** [comment]
Is the reason version of this happen to be made any more convenient by the decorators change? https://github.com/facebook/reason/pull/1112 @SanderSpies

**Comment by SanderSpies** [comment]
@Schmavery I believe so, it will change to `[@bs] fun x y => x`. 

Note that we want to make it even more convenient by removing the brackets for attributes with no payload (eg. `@bs fun x y => x`).

**Comment by jaredly** [comment]
now we have the dot
