### ISSUE TITLE
Make JSX pragma configurable

### ISSUE THREAD

**Issue by aweary** [facebook/reason#1177]
Currently, the JSX `ppx` transform is [coupled directly](https://github.com/facebook/reason/blob/master/src/reactjs_jsx_ppx.ml#L118) to `reason-react`. As Reason grows its more likely that interfaces will be defined for other popular libraries that also rely on JSX (Preact, Inferno), or that another UI library will be written in Reason utilizing JSX.

It would be nice if there was a way to configure what pragma function is used like you can with [`babel-plugin-transform-react-jsx`](https://babeljs.io/docs/plugins/transform-react-jsx/)

**Comment by Schmavery** [comment]
Can't you just create your own ReactDOMRe and include that (instead of depending on reason-react)?  Seems like it would be pretty straightforward to customize that way.

**Comment by aweary** [comment]
I don't think there's any good reason to force every future library that wants to utilize JSX in Reason to call itself `ReactDOMRe`. That's an acceptable workaround for now but doesn't make sense for long-term adoption.

**Comment by Schmavery** [comment]
Just to be clear, are you suggesting that we change the string `ReactDOMRe` to something more generic (say `JSXBackend` or something), or that we add an option to the compiler where you pass in a name of a module/function that you want to have substituted for the existing hardcoded call?
(I will duck out of this now as I'm no react expert, just curious)

**Comment by aweary** [comment]
> we add an option to the compiler where you pass in a name of a module/function that you want to have substituted for the existing hardcoded call?

That one. This is what the babel plugin lets you do, see https://babeljs.io/docs/plugins/transform-react-jsx/#optionspragma

**Comment by mquandalle** [comment]
Some users might also want to use JSX for non-UI related data structures as in this example: http://tolmasky.com/2016/03/24/generalizing-jsx/#data-structures

**Comment by chenglou** [comment]
Discussed in discord. Conclusion: you can either use the current non-transformed format (there was a misunderstanding that this is coupled to reason-react), or use another custom ppx. Closing!

**Comment by jordwalke** [comment]
You can fork the upcoming Reason React PPX plugin, I realize. It would not be too hard.
