### ISSUE TITLE
Omitting the fun keyword (arrow functions)

### ISSUE THREAD

**Issue by iddan** [facebook/reason#1186]
As in ES6's arrow functions I believe functions can be declared w/o the `fun` keyword:
```reason
let increment = fun (x) => x + 1;
/* should allowed to be written as */
let increment = (x) => x + 1;
```

**Comment by kennetpostigo** [comment]
@iddan you could always use this syntax:
```reason
let increment x => x + 1;
```

**Comment by iddan** [comment]
AWESOME!!! Is it in the docs? Couldn't find it.

**Comment by kennetpostigo** [comment]
@iddan not sure but I think it might be in ocaml comparison section last I remember.

**Comment by kennetpostigo** [comment]
@chenglou I think this is good to close.

**Comment by chenglou** [comment]
There's not really a big need to document these features, as the user will learn about it about a single refmt! =)

**Comment by chenglou** [comment]
@iddan try to refmt these two snippets too:

```reason
let foo = [%bs.obj {a: 1, b: "hello"}]
```

```reason
div foo::1 children::[] ()[@JSX]
```

**Comment by iddan** [comment]
@chenglou I don't think this is the right attitude. There should be a description of possibilities in the static docs in the site.

**Comment by chenglou** [comment]
@iddan sorry if that came out wrong! But reducing the initial learning overhead and explicitly and lazily teach whatever the user needs through refmt is an actual goal of ours. Also because it's unclear to lots of people that refmt is "just" a formatter, but one that can freely change between equivalent syntaxes
