### ISSUE TITLE
refmt as a toplevel directive or an extension point.  Or both!

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#1187]
It would be useful for Reason newcomers coming from OCaml to be able to `refmt` code from inside of rtop.  This would save some effort when following an OCaml tutorial, for example.

Inline OCaml code used directly as if it had been typed in Reason syntax:
```reason
Reason # [%ocaml type 'a t = 'a list];
type t 'a = list 'a
```

Live refmt, printing but not evaluating the refmt'd code:
```reason
Reason # #refmt.ocaml {|type 'a t = 'a list|};
In Reason:
type t 'a = list 'a;
```

Having both of these in reverse could be useful too for use from vanilla utop.

**Comment by jaredly** [comment]
we have an online playground now, which I think meets this need?
