### ISSUE TITLE
Merlin not recognizing reason syntax on Windows

### ISSUE THREAD

**Issue by fhelwanger** [facebook/reason#1190]
I got almost everything working on Windows. I did the following:

1. Installed `ocaml` from [here](https://fdopen.github.io/opam-repository-mingw/).
2. Installed `reason` via `opam` following the instructions on the [readme](https://github.com/facebook/reason#installing-via-opam).
3. Installed `merlin` via `opam`.
4. Installed the [vscode-reasonml](https://github.com/freebroccolo/vscode-reasonml) extension.

Then I cloned [react-reason-example](https://github.com/chenglou/reason-react-example). Almost everything worked fine, `refmt` was working, the app was built without errors, but the vscode extension isn't recognizing the reason syntax. It seems to be recognizing it as `ocaml` code instead of `reason` code. Here is a screenshot of it:

![image](https://cloud.githubusercontent.com/assets/11396047/24607130/b8ef641a-1846-11e7-8133-3919af05c2c0.png)

Here's the result of `where refmt ocamlmerlin ocamlmerlin-reason`:

```
C:\OCaml64\home\fhelwanger\.opam\4.02.3+mingw64c\bin\refmt.exe
C:\OCaml64\home\fhelwanger\.opam\4.02.3+mingw64c\bin\ocamlmerlin.exe
C:\OCaml64\home\fhelwanger\.opam\4.02.3+mingw64c\bin\ocamlmerlin-reason.exe
```

Here's the result of `ocamlmerlin -version` and `refmt --version`:

```
The Merlin toolkit version 2.5.3, for Ocaml 4.02.3
```

```
Reason 1.13.0 @ dbe5d86
```

**Comment by OlegLustenko** [comment]
you can try https://github.com/reasonml/reasonml.github.io/issues/109

it mostly works for me out of the box, only 1 requirements you need to set this in vscode settings
```json
 "reason.path.ocamlfind": "ocamlfind.cmd",
  // The path to the `ocamlmerlin` binary.
  // "reason.path.ocamlmerlin": "ocamlmerlin.cmd",
  // The path to the `opam` binary.
  "reason.path.opam": "opam.cmd",
  // The path to the `rebuild` binary.
  "reason.path.rebuild": "rebuild.cmd",
  // The path to the `refmt` binary.
  "reason.path.refmt": "refmt.cmd",
  // The path to the `refmterr` binary.
  "reason.path.refmterr": "refmterr.cmd",
  // The path to the `rtop` binary.
  "reason.path.rtop": "rtop.cmd",
```

**Comment by fhelwanger** [comment]
Yes! Actually, I created https://github.com/fhelwanger/ocaml-on-windows because of this issue but forgot to update it 😄

Thanks!

**Comment by fhelwanger** [comment]
I think that in the last `vscode-reasonml` version you don't even need to configure your reason paths anymore. It was fixed here https://github.com/freebroccolo/ocaml-language-server/pull/31
