### ISSUE TITLE
[auto printer deriving] Unable to work with types written in OCaml

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#1192]
If a reason project has a dependency on existing OCaml library, say "Easy_format", the following code will fail to compile with "--add-printer" option:

```
type format_wrapper = {format: Easy_format.t}
```

The problem is that when we generate the printer `pp_format_wrapper`, a call to `Easy_format.pp` will be generated as well in order to print the field `format`. See:

![image](https://cloud.githubusercontent.com/assets/1017689/24638114/d2f3b9de-189a-11e7-9ec7-0800cc90d49d.png).

There is no way to tell if `Easy_format.pp` exists or not during parse time. If it doesn't exist, a compile error will be generated saying `Easy_format.pp` is not implemented. 

@tekknolagi

**Comment by tekknolagi** [comment]
Is this "unable to work with types written in OCaml" or "unable to generate printers for files not known to refmt"?

**Comment by yunxing** [comment]
This is "unable to work with types written in OCaml", it fails compilation. 

See the example above: when we add printers, it looks for the `Easy_format.pp`, which is not implemented. 

We need a way to say "if Easy_format.pp exists, use it. Otherwise, don't use it and don't break the compilation". 

I haven't found a good solution to this issue though. Let me keep thinking about it.

**Comment by chenglou** [comment]
Stale
