### ISSUE TITLE
Documentation for reason-mode for emacs should list required deps

### ISSUE THREAD

**Issue by acchou** [facebook/reason#1193]
Reason-mode has dependent packages. When following the [directions](https://github.com/facebook/reason/tree/master/editorSupport/emacs), I had an error saying the package `iedit` couldn't be found, and had to install it with MELPA.

The docs for the emacs integration should enumerate all dependencies and ask the user to install them.

**Comment by yunxing** [comment]
Good find. Closing by https://github.com/facebook/reason/commit/a37a854a56b98ce79aa0321e1136f3459b9fa305

**Comment by chenglou** [comment]
Solved?
