### ISSUE TITLE
Makefile is broken

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#1205]
Haven't contributed to to reason_parser until recently. I noticed the development process becomes not very pleasant after our package splitting: After modifying a file in reason_parser, "make test" doesn't reflect the new change. I had to removed the "_build" directory in order to make the change to take effect.

**Comment by jordwalke** [comment]
cc @tekknolagi.

**Comment by tekknolagi** [comment]
I think that's because it relies on installed version of parser. Might need to add something like "opam upgrade reason-parser"

**Comment by jordwalke** [comment]
Or `opam pin`?

**Comment by yunxing** [comment]
We need to make our make process opam-agnostic. Both reason and reason-parser need to be built in the local "_build" directory instead of relying on package globally installed on opam.

We have the same problem with our rtop test, which relies on globally installed version of reason.

**Comment by IwanKaramazow** [comment]
Noticed this too, it seems all my rebuilds of the printer don't do anything. Thought it was my local setup. How do I rebuild locally? What's the workflow?

**Comment by yunxing** [comment]
@IwanKaramazow If you are using opam, you have to run `opam pin add reason-parser` to tell opam where you installed the reason-parser. 

Then when you rebuild, just use `opam upgrade reason-parser`

**Comment by IwanKaramazow** [comment]
Just did some printer-developing, the `rm -rf _build && opam upgrade reason-parser` workflow is horrible 😂 We should make this opam-agnostic.

**Comment by tekknolagi** [comment]
@IwanKaramazow what other package managers would you like to support?

**Comment by IwanKaramazow** [comment]
@tekknolagi 
Something that doesn't take 32sec. to build 😄 
```
$ time opam upgrade reason-parser -y
real	0m32.627s
user	0m24.833s
sys	0m4.883s
```
While developing, I don't even think about the existence of package managers. I just wanna build `./refmt_impl.native` or re-run the tests. 32 sec. is kind of a feedback-buzkill.
Jbuilder or bsb-native spring to mind, but I haven't got much time to switch Reason over atm.

**Comment by tekknolagi** [comment]
Then `cd`ing into the deps and building them manually should be a reasonable workaround.

**Comment by chenglou** [comment]
👍
