### ISSUE TITLE
Smie grammar for Reason

### ISSUE THREAD

**Issue by arichiardi** [facebook/reason#1210]
Hello folks!

I was wondering if someone has ever attempted to write a [`smie`](https://www.gnu.org/software/emacs/manual/html_node/elisp/SMIE.html) grammar for `reason`.
The equivalent for OCaml can be found [here](https://github.com/ocaml/tuareg/blob/master/tuareg.el#L1310).

It can be quite useful for identifying phrases and then evaluate them in `rtop` from emacs.
I might do it myself if time allows it, just don't want to duplicate effort.

Thanks!

**Comment by arichiardi** [comment]
It is probably even simpler than that.

`utop.el` defines basically [three main](https://github.com/diml/utop/blob/master/src/top/utop.el#L239) functions for communicating with an `utop` repl:

- `utop-skip-blank-and-comments'
- `utop-skip-to-end-of-phrase'
- `utop-discover-phrase'

What would be the equivalent in `reason-mode` I am still trying to discover.

**Comment by kennetpostigo** [comment]
Hey @arichiardi ! by grammar do you mean syntax? If so, I think the reason team wants to polish the current syntax as best as possible before trying to start/maintain a second one. If syntax is not what you mean maybe @chenglou can help determine whether this is something the team is actively working on.

**Comment by arichiardi** [comment]
@kennetpostigo yes SMIE is a grammar builder for Emacs, I'd say though that I have implemented now the main pieces for navigations. So I can close this.
