### ISSUE TITLE
Refmt is not working well with Jest

### ISSUE THREAD

**Issue by Jimexist** [facebook/reason#1211]
In [this file](https://github.com/BuckleTypes/bs-moment/blob/master/__tests__/moment_spec.re) `refmt` is formatting Jest style code to be quite unreadable.

I think instead of:
```reason
test
  "instantiation"
  (
    fun () => Just (Equal true (Moment.isSame (moment "2017-04-01") (moment "2017-04-01")))
  );
```

I would read better with:
```reason
test "instantiation" (fun () => 
  Just (Equal true (Moment.isSame (moment "2017-04-01") (moment "2017-04-01"))));
```

**Comment by AbsoluteZero273** [comment]
Same problem here. Not so readable.
![](https://cdn.discordapp.com/attachments/235199119747055616/304263645221748736/2017-04-19-201955_516x290_scrot.png)

**Comment by Jimexist** [comment]
i guess one way to solve it is not to insert any newline or spaces between `(` `)` and `fun` decls.

**Comment by chenglou** [comment]
Thanks. Merging this into #1211
