### ISSUE TITLE
Refmt discrepancy with the doc site

### ISSUE THREAD

**Issue by Jimexist** [facebook/reason#1213]
<img width="683" alt="screenshot 2017-04-14 12 14 47" src="https://cloud.githubusercontent.com/assets/622789/25033047/5fdec50e-210c-11e7-8e5b-ec929189a164.png">

I am sure this is a minor issue, but the indentation level of `refmt`-ed code is different from that in the [doc site](https://facebook.github.io/reason/#built-in-data-types-variant), specifically the `|` was indented with two more spaces than `switch`

**Comment by chenglou** [comment]
Thanks!
