### ISSUE TITLE
Fix Reason—ML comparison re module syntax

### ISSUE THREAD

**Issue by mheiber** [facebook/reason#1217]
The [documentation comparing Reason and ML module syntax](https://github.com/facebook/reason/blob/a87b102c3f7d75296902c80030eb4628e90bdabb/docs/mlCompared.html#L553) seems to say:

1. The module definition syntax is different in ML for local as compared to top-level/exported modules ("local" and "exported" are both used).
2. The module definition syntax for Reason and ML is different

However I'm just not seeing (1) and (2) reflected in the table:

![screen shot 2017-04-15 at 9 40 00 pm](https://cloud.githubusercontent.com/assets/4691093/25068032/1c0a654a-2224-11e7-8480-d8ccb2dcf7b5.jpg)

Also, I can't find any variation in module definition syntax in the OCaml grammar in the [OCaml docs](https://caml.inria.fr/pub/docs/manual-ocaml/modules.html), so I'm confused about what this comparison is talking about. It doesn't help that "exported module" vs. "local module" is terminology I couldn't find in the OCaml docs or Reason docs.

Thanks for your help in clearing this up and your work on Reason.

**Comment by chenglou** [comment]
Thanks for pointing this out. Not sure about this either, so I'll temporarily remove this confusing point.
