### ISSUE TITLE
please add in the documentation a section about optional argument

### ISSUE THREAD

**Issue by Jimexist** [facebook/reason#1219]
And specifically, for defs like:
```
let defOptionalAlias
    /* a::aa=10 */
    a::aa=10
    /* b::bb=10 */
    b::bb=10
    /* () => */
    () =>
  /* 10; */
  10;
```

how does the `unit` comes into play (for callers).

Thanks!

**Comment by chenglou** [comment]
This is now under https://reasonml.github.io/guide/language/function#optional-labeled-arguments
