### ISSUE TITLE
Minimal version of reason-mode for Emacs without reason-cli?

### ISSUE THREAD

**Issue by tddsg** [facebook/reason#1229]
Hi there,

I'd like to ask if there is a minimal version of `reason-mode` for Emacs without using `reason-cli`? Due to my company policy, I am unable to install `reason-cli` via the following command:

    npm -g install git://github.com/reasonml/reason-cli.git

Is there any way to make at least the syntax highlighting for `reason` in Emacs working?

Thank you for spending time looking at this issue!

**Comment by chenglou** [comment]
@tddsg we're thinking of pulling our plugin out into a dedicated location. Do you know elisp?

**Comment by tddsg** [comment]
Yes, I do know a little about elisp.

**Comment by chenglou** [comment]
cc @sgrove

**Comment by sgrove** [comment]
Yeah, that seems reasonable. Would be nice to get it on melpa as well so it could be installed through the normal channels.

**Comment by chenglou** [comment]
@tddsg sorry for the late reply, but we've already pulled out the editor integration. They're [here](https://github.com/arichiardi/reason-mode)

Would that be enough?

**Comment by jordwalke** [comment]
Also, can you let me know what it is about the npm installation that makes it difficult? Chances are you are not the only one.

Would it help if there was an option to have Reason-cli distributed as a tarball that builds itself without npm at all? If that's not enough, would prebuilt binaries make it easier?

**Comment by tddsg** [comment]
@chenglou : Thank you! I am currently using this version. It works great!

@jordwalke : yes, I also reported the errors in https://github.com/reasonml/reason-cli/issues/22

**Comment by chenglou** [comment]
Great to hear. Closing this then =)
