### ISSUE TITLE
Wrong syntax for functions in docs?

### ISSUE THREAD

**Issue by hessammehr** [facebook/reason#1230]
Hope this is not me being silly, but it looks like a couple of `fun`s on [index.html](https://github.com/facebook/reason/blob/master/docs/index.html) need to be changed to `let`s. Under the _Function_ section:

```reason
fun greet name => "Hello " ^ name;

/* - : 'a => string => string = <fun> (definitely not what you want) */

fun greetMore name => {
  let part1 = "Hello";
  part1 ^ " " ^ name
};

/* - : 'a => string => string = <fun> (again not what you want)
```

**Comment by Schmavery** [comment]
As the docs explain in the next section, functions in reason are first class, meaning you can pass them around like any other value.  I think the intention here was to show how to create a function.  The following section shows how to assign one of these functions to a name using a let binding.
ie
`fun x y => x + y` is a value
`let add = fun x y => x + y` assigns this value to the name `increment`

A little further down the page, the docs give an example of a commonly-used piece of sugar for defining functions and binding them to a name.
`let add x y => x + y;`
Hope that helps a little!

**Comment by hessammehr** [comment]
Thanks for the examples, @Schmavery. The first example of a function in the docs, ```reason fun greet name => "Hello " ^ name;```, is not a function that greets the user (as its name might suggest and the author probably intended). Rather, it takes a `greet` of time `'a` and a `string`. This looks like an error to me.

**Comment by chenglou** [comment]
Yeah I screwed up, sorry. cc @bsansouci
Thanks for pointing this out!

**Comment by hessammehr** [comment]
No worries, @chenglou,  glad I could help. At any rate, I think this is a bit of an odd introduction to functions since no invocations are shown here, which would confuse the hell out of someone without a functional background. It is kind of awkward to add examples, too:

```reason
(fun name => "Hello " ^ name) "world!";
```

Perhaps this would work better (then you explain the syntactic sugar ...):

```reason
let greet name => "Hello " ^ name;
greet "world"; /* "Hello world"
```

Just my two cents.

**Comment by chenglou** [comment]
@hessammehr thanks for the feedback. I've modified the docs to stay concise while addressing your point. Hope the new one works well!

**Comment by hessammehr** [comment]
@chenglou thanks, looks great!
