### ISSUE TITLE
Explanatory appending-to-list error message

### ISSUE THREAD

**Issue by sgrove** [facebook/reason#1232]
This works: 

`let newCards = [card, ...otherCards];`

while this 

`let newCards = [...otherCards, card];`

throws 
```
refmt errors:
File "example.re", line 147, characters 39-40:
Error: 2226: <UNKNOWN SYNTAX ERROR>
```

Probably it could be recognized and turned into, 

> It looks like you're trying to append an item to the tail of a list, which isn't supported in the default list data structure because it can be very slow. If you *really* want to do this, try `[[otherCards], card];` (but read https://facebook.github.io/reason/ on why this might not be a good idea!)

Or

> `[...otherCards, card]` should be written as `[[otherCards], card]`
>  But appending to the tail of a list can be very slow! If you *really* want to do this, read https://facebook.github.io/reason/ on why this might not be a good idea and on alternatives!

**Comment by Schmavery** [comment]
Will `[[otherCards], card]` really be what they're expecting?  I would have expected something more like `otherCards @ [card]`.  Might be worth linking to a specific place with an explanation if we're going to link, I couldn't find any explanation at the suggested link after a little looking.

**Comment by sgrove** [comment]
Even better then, a proper suggestion and link to a further explanation ;)

**Comment by knyzorg** [comment]
As someone new to Reason and ML languages in general, the `List.append(otherCards, [card])` syntax seems most familiar.

**Comment by anmonteiro** [comment]
```bash
$ ./_build/install/default/bin/refmt 
let newCards = [...otherCards, card];
File "", line 1, characters 16-29:
Error: Lists can only have one `...` spread, at the end.
Explanation: lists are singly-linked list, where a node contains a value and points to the next node. `[a, ...bc]` efficiently creates a new item and links `bc` as its next nodes. `[...bc, a]` would be expensive, as it'd need to traverse `bc` and prepend each item to `a` one by one. We therefore disallow such syntax sugar.
Solution: directly use `concat` or other List helpers.
```
