### ISSUE TITLE
Extra parentheses in variant type causing compiler errors

### ISSUE THREAD

**Issue by michaelgmcd** [facebook/reason#1243]
Same issue posted in the Discord channel,

The following snippet:
```ocaml
type t;

external on : t => [
  | `windowAllClosed (unit => unit) [@bs.as "window-all-closed"]
] [@bs.string] => unit = "on" [@@bs.send];

external v : t = "" [@@bs.val];

let () = on v (`windowAllClosed (fun _ => ()));
```
throws `Error: Unused attribute bs.as` when compiling.

The generated OCaml code looks like this:
```ocaml
type t
external on :
  t ->
    (([ `windowAllClosed of ((unit -> unit)[@bs.as "window-all-closed"]) ])
      [@bs.string ]) -> unit = "on"[@@bs.send ]
external v : t = ""[@@bs.val ]
let () = on v (`windowAllClosed (fun _  -> ()))
```
when pasting it in the bucklescript repl, the `[@bs.as "window-all-closed"]` attribute doesn't work.

removing the parentheses around `((unit -> unit)[@bs.as "window-all-closed"])` fixes the issue.

Here's another example with [@bs] attributes:
```ocaml
type t;

external on : t => [
  | `foo (unit => unit) [@bs.as "baz"]
  | `bar (unit => unit [@bs]) => unit
] [@bs.string] => unit = "on" [@@bs.send];

external v : t = "" [@@bs.val];

let () = on v (`windowAllClosed (fun ::event => ()));
```

**Comment by jordwalke** [comment]
Is this an issue with BuckleScript or Reason?

**Comment by mgmcdermott** [comment]
Posted this on my phone so it wasn't too complete. It's an issue with Reason. I haven't tried yet, but I would assume it would apply to all attributes. The parsing of the Reason code:
```
`windowAllClosed (unit => unit) [@bs.as "window-all-closed"]
```
to the OCaml code:
```
`windowAllClosed of ((unit -> unit)[@bs.as "window-all-closed"])
```
is the issue.

**Comment by mgmcdermott** [comment]
I think the generated output should look something like:
```
`windowAllClosed of unit -> unit [@bs.as "window-all-closed"]
```
I've added a failing unit test to my fork of reason failing unit test if this is the correct output:
https://github.com/mgmcdermott/reason/commit/1c9615520595ed438e0be252b2aebc2fb2bf1e02

**Comment by chenglou** [comment]
Hey @michaelgmcd! Sorry for the late reply. This is fixed in master now.
