### ISSUE TITLE
refmt drops module access

### ISSUE THREAD

**Issue by saschatimme** [facebook/reason#1248]
The following
```reason
      <UIExplorerExampleList components=ExampleList.components />
```

will be formatted to
```reason
      <UIExplorerExampleList components=components />
```

which no longer compiles since the `ExampleList.` is dropped.

Sorry for the bad issue title, didn't came up with something better...

**Comment by jordwalke** [comment]
@saschatimme I'm not able to reproduce this. Which version of `refmt` are you using? `refmt --version`.

**Comment by saschatimme** [comment]
I'm using the `refmt` from Bucklescript `1.7.3`, which is `Reason 1.8.2 @ ac73dea`.
A more self contained example would be this
```reason
module A = {
    let alt =  "hello";
};


let x = <img alt=A.alt />;
```

**Comment by fredyr** [comment]
I was able to reproduce with refmt version Reason 1.8.2 @ ac73dea, but this behaviour is gone when I tried refmt Reason 1.13.5 @ 1a03661. So upgrade should help.

**Comment by saschatimme** [comment]
Will then open an issue in the bucklescript repo

**Comment by jordwalke** [comment]
Ah, in the mean time bucklescript does allow you to specify a path to `refmt` (which is why I couldn't reproduce).
