### ISSUE TITLE
Cannot use variable named end or begin

### ISSUE THREAD

**Issue by wokalski** [facebook/reason#1257]
This was supposedly fixed in https://github.com/facebook/reason/pull/622 but it probably broke somewhere.

Today I had a funky case where I passed defined end as an argument to a function:

```reason
let f ::x ::end => {
  x;
};
```

This just causes a warning that `end` was not used. However if I use `end` in the function body I get an error.

This is also reproducible if you use `end` or `begin` as variable names although in that case the error is more obvious because it happens on the line of definition. When you name an argument using one of those errors you get an `Invalid Token` error down the line.

I am on `Reason 1.7.4` from `opam`.

**Comment by wokalski** [comment]
Just checked with `Reason 1.13.5 @ 1a03661` - the same error.

**Comment by dmueller39** [comment]
I encountered this as well, but when using end in a record.

![text_re_ _mobileeditor](https://user-images.githubusercontent.com/9422359/27146955-1c5ba6da-5109-11e7-9218-ee779b9e2a09.png)

**Comment by chenglou** [comment]
Fixed through #1541. Will ship this week
