### ISSUE TITLE
JSX parsing error:

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#1263]
This parses correctly:

```
Container.make [| <Button onClick=handleStaleClick />, <Button onClick=handleStaleClick /> |]
```

This doesn't parse correctly (only difference is no spaces)

```
Container.make [|<Button onClick=handleStaleClick />, <Button onClick=handleStaleClick />|]
```

The `[|<` are likely tripping it up, and if that's the case that's not so bad as long as the printer retains the spaces - it doesn't currently.

**Comment by IwanKaramazow** [comment]
```reason
let x = [|<Button onClick=handleStaleClick />, <Button onClick=handleStaleClick />|];

let y = [<Button onClick=handleStaleClick />, <Button onClick=handleStaleClick />];

let z = (<Button onClick=handleStaleClick />, <Button onClick=handleStaleClick />);
```
Forgot to report this one, encountered this one last week. Might have a solution, will send PR.

**Comment by IwanKaramazow** [comment]
https://github.com/facebook/reason/pull/1264

This is really a suboptimal solution, with EasyFormats current api.
Changed the `~wrap:("( ", " )"` to include a space if there's jsx inside the structure..
I really want something like: `~listConfigIfBreaks`.
If we're breaking now, we have an extra redundant space around the wrapping brackets...

**Comment by jordwalke** [comment]
I left a suggestion about how to get better spacing without wrapping in `("[ ", " ]")` but Fred might be able to suggest a lexer hack that achieves what we want.
