### ISSUE TITLE
Merlin possibly not inferring types correctly

### ISSUE THREAD

**Issue by fingermark** [facebook/reason#1290]
```
let apply_to_tuple f (first, second) => f ::first ::second; 
```

`:MerlinTypeOf` shows `'a -> 'b * 'c -> 'd -> 'e -> 'f -> 'g`

but

`rtop` show `(first::'a => second::'b => 'c) => ('a, 'b) => 'c`

```
let apply_to_tuple = fun f (first, second) => f ::first ::second;
```

`:MerlinTypeOf` shows just `'a`

**Comment by fingermark** [comment]
I think this is a vim issue.

When I `:set ft=reason` and run the command I get `'a -> 'b * 'c -> 'd -> 'e -> 'f -> 'g`, but when I save the file as `foo.re` I get  `(first::'a => second::'b => 'c) => ('a, 'b) => 'c`.

**Comment by chenglou** [comment]
Weird. I see the correct one when I paste it in a file without saving...
Btw merlin is best effort. Sometimes the diagnosis might report wrong errors. Not sure whether it's the case for type hint though

**Comment by anmonteiro** [comment]
This should be better after the new recovery in #2480.
