### ISSUE TITLE
discord link in first blog post missing "//"

### ISSUE THREAD

**Issue by Xananax** [facebook/reason#1295]
The current link here:

[[...]keeping folks up-to-date through Discord and[...]](https://github.com/facebook/reason/blob/06d77e0402f0e01b18be7dade7f0375b9d8facba/docs/blog.html#L27)

Leads to a relative url (https://facebook.github.io/reason/discord.gg/reasonml) rather than absolute (discord.gg/etc) 

(I know it's really a nit-pick but...)

**Comment by chenglou** [comment]
Hey!

It's not nit pick if it's a broken link =) (two actually)
Nits are good. We'd like to polish our docs more. Please raise anything else you find! E.g. too many links, bad phrasing, etc.

Thanks!
