### ISSUE TITLE
Make it easier to contribute error messages

### ISSUE THREAD

**Issue by saschatimme** [facebook/reason#1297]
I wanted to contribute some error messages to get rid of the `<SYNTAX ERROR>` messages, but I ran in the following problem:
All error codes were not in the `reason_parser.messages` file, so I followed the [wiki](https://github.com/facebook/reason/wiki/Add-a-Menhir-error-message) but during the generation of the complete file, my Mac runs out of RAM and crashes (It seems I was too cheap 🤔).

Would it be possible to host the complete list of error-messages somewhere?

**Comment by chenglou** [comment]
I think @SanderSpies wanted to check in the whole thing. We could do that? Any ramifications? Some of them change all the time right

**Comment by anmonteiro** [comment]
We don't check in the messages file anymore.
