### ISSUE TITLE
Feature request: Regex literal syntax

### ISSUE THREAD

**Issue by glennsl** [facebook/reason#1298]
As in JS, `/ba(na)+na/g`, or a similar syntax, could desugar into `[%re "/ba(na)+na/g"]`. See https://bloomberg.github.io/bucklescript/Manual.html#_regex_support

**Comment by jaredly** [comment]
what about `{r|ba(na)+na|r}` or similar? I'm wary of `/` because it feels like it would be a pain to parse + give good parsing errors

**Comment by glennsl** [comment]
That's a syntax that could be put straight into bucklescript even, and should work right out of the box with reason.  But where do you put the flags? I'd also be a bit wary of reserving more delimiters, there's quite a few that's reserved already.

**Comment by glennsl** [comment]
Would something like `@/<pattern>/<flags>` be less ambiguous and easier to parse? Perhaps it would collide with user-defined operators...

**Comment by kevinbarabash** [comment]
It would be nice if we could avoid having to escape backslashes within `<pattern>`.

**Comment by kevinbarabash** [comment]
Having `@/` as a starting token and `/` as a closing token should simplify the parsing.
