### ISSUE TITLE
parsing bug on infix operator

### ISSUE THREAD

**Issue by bassjacob** [facebook/reason#1308]
Hi,

When trying to define an infix operator `let (<*>) = apply` I get a syntax error, using reason with bucklescript.

going from ocaml to reason seems to have a bug where the * is escaped: <https://reasonml.github.io/reason-tools/popup.html#bW9kdWxlIEFwcGxpY2F0aXZlX2luZml4OiB7CiAgbGV0ICg8Kj4pOiB0ICgnYSA9PiAnYikgPT4gdCAnYSA9PiB0ICdiOwogIGxldCAoIDwqICk6IHQgJ2EgPT4gdCB1bml0ID0+IHQgJ2E7CiAgbGV0ICggKj4gKTogdCB1bml0ID0+IHQgJ2EgPT4gdCAnYTsKfTsKCg==>

and from reason to ocaml is a syntax error: <https://reasonml.github.io/reason-tools/popup.html#ICBtb2R1bGUgQXBwbGljYXRpdmVfaW5maXggOiBzaWcKICAgIHZhbCAoIDwqPiApIDogKCdhIC0+ICdiKSB0IC0+ICdhIHQgLT4gJ2IgdAogICAgdmFsICggPCogICkgOiAnYSB0IC0+IHVuaXQgdCAtPiAnYSB0CiAgICB2YWwgKCAgKj4gKSA6IHVuaXQgdCAtPiAnYSB0IC0+ICdhIHQKICBlbmQ=>

**Comment by chenglou** [comment]
Fixed in master

**Comment by bassjacob** [comment]
awesome, thank you 😄
