### ISSUE TITLE
refmt --in-place *.ml interleaves files

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1311]
Bad bug? Repro:

- clone https://github.com/chenglou/MariOCaml/commit/218c6be589b40af32ec970acd13d1227a94156f7
- `refmt --in-place *.ml`

See that all the files now have weird output.

**Comment by tekknolagi** [comment]
Ah shit. This is probably something to do with the buffer that the Format library maintains. I think I might have even left a comment like "if you run into trouble, try doing xyz thing".

**Comment by tekknolagi** [comment]
Nope, my comment wasn't really helpful in that regard. But there's probably some rule I broke with regard to using the Format module.

**Comment by chenglou** [comment]
I think I can't repro this anymore

**Comment by tekknolagi** [comment]
Lol oh man
