### ISSUE TITLE
Output errors in reason syntax

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1314]
We'd need the actual type error string/data structure exposed. The former can be grepped but a bit unreliable. The latter needs tweaking the compiler a little bit.

**Comment by Octachron** [comment]
Note that for type errors, ocaml type-checker constructs first an outcome tree before printing. Moreover, the printing functions for this outcome tree can be redefined using the compiler plugin interface; so it may be possible to print type error in reason syntax with just a compiler plugin.

**Comment by bsansouci** [comment]
@chenglou is this fixed now?

**Comment by chenglou** [comment]
Yeah, but I'll leave this open until we get a proper plugin

**Comment by chenglou** [comment]
Merged into #531 actually.
