### ISSUE TITLE
Init file not found: "/home/qq563/.opam/4.04.0+mingw64c/bin/rtop_init.ml".

### ISSUE THREAD

**Issue by damon-kwok** [facebook/reason#1318]
env:Windows10 +Cygwin

rtop: Init file not found: "/home/qq563/.opam/4.04.0+mingw64c/bin/rtop_init.ml".

but this file is exist.

help.

**Comment by jaredly** [comment]
sorry, this doesn't have enough information for someone to help you. You can ask in the discord channel, or in the forum https://reasonml.chat/
