### ISSUE TITLE
Inconsistencies between (-1.0) and (-. x)

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#1319]
It's a bit annoying to have that inconsistency between float literals with unary minus `(-1.0)` and float unary minus `(-. x)`.

Would it be possible to achieve consistency by allow `(- x)` to work on float and int? It wouldn't cast, it would just take the type of the expression.

It not, could we make `(-. 1.0)` at least parse?

**Comment by jaredly** [comment]
`- x` won't happen until modular implicits as I understand it

**Comment by hcarty** [comment]
For what it's worth, the fact that `(-1.0)` works at all is due to how the raw code is parsed.  `(-1.0)` is parsed as a negative floating point literal.  `(-x)` is parsed as "prefix negation applied to `x`".

**Comment by chenglou** [comment]
Yeah won't be possible within the syntax transform, sorry =/
