### ISSUE TITLE
Merge reason-parser back into reason

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1328]
cc @let-def. High pri?

I've discussed with @jordwalke and we've decided to merge reason-parser back into reason (aka kill reason-parser the independent library) to ease contribution and avoid opam pin/unpin and multiple `make`s.

If it's related: we'd like rtop out of the repo into reasonml/.

cc @SanderSpies @IwanKaramazow who've requested this as well.

**Comment by IwanKaramazow** [comment]
Yes!!!!!!!!!!! Finally!!!! 🙌  
This has been bugging me and slowed me down a lot, kept me away from contributing...
The faster this happens, the better.

**Comment by let-def** [comment]
High pri yes, that will make the workflow much easier.

**Comment by chenglou** [comment]
@let-def thanks again. Btw any other related things that'd make your workflow easier?
