### ISSUE TITLE
Refmt line wraps inconsistently with multi-line strings

### ISSUE THREAD

**Issue by TheSpyder** [facebook/reason#1333]
I'm using `{| |}` syntax to construct a multi-line string because with `" "` refmt converts the newlines to `\n`. However, when calculating line length for the purposes of code format wrapping it seems to use the entire string rather than the actual indent position of the code.

Note how making the first string shorter improves the format output:

```
let error expected actual =>
  {|Data not equal:
  ------------
  '|} ^
  expected ^ {|'
  ------------
  '|} ^ actual ^ {|'
  ------------|};

let error expected actual =>
  {|Data not equal:
  '|} ^ expected ^ {|'
  ------------
  '|} ^ actual ^ {|'
  ------------|};
```

**Comment by anmonteiro** [comment]
These seem to be correctly formatted now. Please reopen if still an issue.

**Comment by TheSpyder** [comment]
And in 3.0.4 too! Maybe I should go through more of my old tickets and see if they're already fixed 🤔
