### ISSUE TITLE
Unbound value M.pp when compiling with --add-printers

### ISSUE THREAD

**Issue by dwwoelfel** [facebook/reason#1337]
I'm trying to convert https://github.com/zoggy/ocaml-lru-cache to Reason, but hitting a problem when I try to add pretty printers. 

If I run `ocamlfind ocamlc -c -thread -pp 'refmt --print binary --add-runtime --add-printers' -o lru.cmo -intf-suffix .rei -impl lru.re`, I get the error:

```
File "_none_", line 1:
Error: Unbound value M.pp
```

I tried to reduce it as much as possible and was able to reproduce the problem with https://gist.github.com/dwwoelfel/6be6f519dc8c84cfc42cdfb35f1745a7

The fully converted Reason file is https://gist.github.com/dwwoelfel/f3102fdf1d2f1992d28fb8126884028b

**Comment by chenglou** [comment]
We're removing `--add-printers` from Reason for now, sorry... It wasn't as stable as we'd hoped.

We'll find a good alternative soon.
