### ISSUE TITLE
Watch mode doesn't pick up changes immediately

### ISSUE THREAD

**Issue by wincent** [facebook/reason#1340]
I was hesitant to post this bug as it is sporadic in nature, but chatting to @chenglou yesterday he encouraged me to go ahead as watch mode is expected to be "rock solid" at this point.

Example gif showing the issue:

- Left pane, some Reason source code.
- Top-right pane, `yarn watch` (which is effectively doing `bsb -make-world -w`).
- Bottom-right pane, running built output with `node`.

![watch-bug](https://user-images.githubusercontent.com/7074/28383914-9967b202-6c77-11e7-8e25-04e15dc961e8.gif)

In this you can see:

1. Run the code: it works and prints "Done".
2. Edit the code, introducing a bug, save: compiler picks up the change, does some work, eventually prints "no work to do", but it evidently *did* do some work because...
3. Run the code again, it (correctly) fails.
4. Edit the code, fixing the bug, save: compiler picks up the change, does some work, but doesn't actually fully rebuild, because...
5. Run the code, and it (incorrectly) still fails.
6. Go back to the code, resave the buffer (no changes, but "modified" timestamp on filesystem changes), compiler picks up the change, actually fully rebuilds this time.
7. Run the code, and it (correctly) works and prints "Done".

[Here](https://gist.github.com/wincent/b1507b75e34ac46407536ea9ac80cf19) is a log of the `bsb` watch output (sorry about all the warnings: I am bad and I should feel bad).

I can repro this fairly reliably. If I save 20 edits, do 20 builds, and run the code 20 times, 5 to 10 of the runs will exhibit behavior indicating that I'm actually running stale build output.

**Comment by chenglou** [comment]
Oh wait, could this be https://github.com/BuckleScript/bucklescript/issues/1675?

**Comment by wincent** [comment]
It could be, as I do use Vim, but I've got it configured to write temp files in a separate location (under `~/.vim/tmp/`) so I think it's unlikely but not impossible that this is the issue. I haven't seen other tool-chains tripped up in this way by the whole atomic write-and-swap thing.

(Sigh... just checked, and this doesn't repro for me with randomly-selected-alternative-editor. I'll continue investigating and if I can find out what Vim is doing.)

Thanks @chenglou.
