### ISSUE TITLE
Web site /try/ gives "require not found" error

### ISSUE THREAD

**Issue by desmond-dsouza** [facebook/reason#1342]
https://reasonml.github.io/try/ gives a `require not found` error with this: 
```
type s = R int int;

let area s => switch s {
  | R x y => x * y
};
```

**Comment by bsansouci** [comment]
Seems to be the evaluation that's failing on requiring the module for int32 operations. 
@chenglou could we use your require polyfill here?

**Comment by chenglou** [comment]
Fixed.
