### ISSUE TITLE
OCaml Bindings support

### ISSUE THREAD

**Issue by ShalokShalom** [facebook/reason#1344]
Can i use a binding like that? https://github.com/Kakadu/lablqml

**Comment by hcarty** [comment]
As long as you're using native compilation there is no binding required to use any OCaml libraries.

**Comment by ShalokShalom** [comment]
I like to use this binding, in order to get QML support?

**Comment by chenglou** [comment]
Yes you can! A Reason project works fine alongside ml files =). The usual setup should work.

Closing this. Tell me if you'd like to know more.
