### ISSUE TITLE
Semicolons 

### ISSUE THREAD

**Issue by ShalokShalom** [facebook/reason#1355]
I like to implement Reason in my head and this comparison sheet shows me clearly, that its an improvement to the old syntax, with currently one exception, namely those extra semicolons: https://reasonml.github.io/guide/ocaml/

**Comment by mrkaspa** [comment]
I aggree, semicolons everywhere

**Comment by ShalokShalom** [comment]
Which is strong bond to the .Net platform?

**Comment by mrkaspa** [comment]
Not that much you can use fable.io too

**Comment by ShalokShalom** [comment]
Yeah, I like to compile to something else as Javascript too, like QML.

**Comment by maun** [comment]
This is an issue for some newcomers. I showed reason to a friend of me (JS developer) and he really disliked the semicolons. I read that this solves some syntax ambiguities, but Swift also deals with this and has a great syntax. Now that #1357 is merged does this change things?

**Comment by ShalokShalom** [comment]
@chenglou Explained me at least in IRC, that this will change soon.

**Comment by ShalokShalom** [comment]
@mrkaspa There are actually a lot of solutions to deploy F#: QtSharp and Mono are both available for Linux.
