### ISSUE TITLE
Keyword swapping when using OCaml libraries leads to nonsensical results

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#1361]
Reason's approach of swapping keywords (`switch` <-> `match`, `pub` <-> `method`) can lead to some confusing results when using libraries written in OCaml.

A bad example is the zeromq bindings for OCaml which expose a `pub` value in reference to the pub socket in a pub/sub messaging duo.  `pub` is a keyword in Reason so this value gets translated to `method` which is confusing and undiscoverable to someone who isn't familiar with the details of this keyword swapping.

The relevant interface for the zeromq binding is here: https://github.com/issuu/ocaml-zmq/blob/1867f6a151356f9330e7f7720e7c732a5c1a1b36/src/ZMQ.mli#L35

```ocaml
(* Create a pub/sub socket pair *)
let pub = ZMQ.Socket.create ctx ZMQ.Socket.pub in
let sub = ZMQ.Socket.create ctx ZMQ.Socket.sub in
...
```
becomes
```reason
let method = ZMQ.Socket.create ctx ZMQ.Socket.method;
let sub = ZMQ.Socket.create ctx ZMQ.Socket.sub;
...
```
I've run into this keyword swapping issue a few times but this was by far the most confusing.

Would it be possible to do something less invasive like add a suffix `_` to names from OCaml which are keyword in Reason?

**Comment by chenglou** [comment]
cc @let-def would this be solved through the upcoming Reason AST refactor?

**Comment by kennetpostigo** [comment]
Docs of that existing lib could also cause confusion

**Comment by let-def** [comment]
No that wouldn't be solved. What should the name be? There is no solution if we both reserve (as a keyword) and allow (as an import) the same name. `\pub` maybe?

**Comment by let-def** [comment]
It is not something theoretical, it is a social problem. We need to stop swapping as it is today, and then to find a convention that is sensible for users.

**Comment by hcarty** [comment]
@chenglou @let-def Can we have a fix for this in with the syntax revision release?  Adding a `_` suffix would be far preferable to the current keyword swapping.

**Comment by chenglou** [comment]
Sorry missed this. Yeah that'd be great. Not sure if we can make it on time...
