### ISSUE TITLE
camelCase or snake_case?

### ISSUE THREAD

**Issue by nkrkv** [facebook/reason#1362]
Can’t find any recommendation on this bikeshedding topic. OCaml land is snake_case and JavaScript is camelCase.

If I’m going to make a library in ReasonML which would be consumed by both JS packages and other ReasonML libraries how would you recommend to name API functions?

1. Do everything in camelCase and you’ll get mixed style `.re` source files
2. Do everything in snake_case and you’ll look alien when used from within JS
3. Use snake_case but change it to camelCase when export and you’ll get much boilerplate and two versions of docs

What’s a best practice?

**Comment by xtuc** [comment]
OCaml developers use snake_case while JS developers use camelCase.

You could expose a camelCase API and use snake_case for your internals.

**Comment by nkrkv** [comment]
Thank you.

But in that case, if I’d try to use my library API in another ReasonML lib *along* with JS it would have “wrong” case. Isn’t it?

**Comment by xtuc** [comment]
Yes, you could a dedicated entrypoint for your JavaScript lib with exported camelCase functions.

**Comment by nkrkv** [comment]
OK, got it, thank you.

**Comment by Pauan** [comment]
All of the Reason docs use camelCase (except for functions which are already defined in OCaml, like `print_endline`), so it would still be useful to have an official recommendation from the Reason team about this.
