### ISSUE TITLE
`let f thing => thing##x` doesn't format to ocaml correctly

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1364]
It turns into `let f thing = ## thing x` in ocaml

**Comment by hcarty** [comment]
I'm not sure how refmt uses pprintast, but if it's inlined rather than pulled from compiler-libs the latest git version should have a fix.

**Comment by jaredly** [comment]
this is an ocaml printer problem :/

**Comment by chenglou** [comment]
We'll solve it in around 3 months
