### ISSUE TITLE
Jupyter support

### ISSUE THREAD

**Issue by ShalokShalom** [facebook/reason#1366]
OCaml is already supported: 
https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

**Comment by jaredly** [comment]
I looked into adding reason support to IOCaml at one point, but that was before I knew just about anything :P 
I also wasn't very impressed with the autocomplete that IOCaml has -- I explored bringing in UTop's autocomplete (which includes runtime-defined values, not just library values) but I wasn't able to get it working.

I think we'd want a repl that is bucklescript-based, and one that is native-based. not sure if bucklescript is ready to be repl'd though; it's currently a behemoth that's only aimed at producing bsc from what I can tell

**Comment by ShalokShalom** [comment]
Bsc? I thought Bucklescript is very precise and produce pretty readable Javascript code?

**Comment by jaredly** [comment]
This probably belongs on https://reasonml.chat/ -- any jupyter support would be implemented as a third-party package.
