### ISSUE TITLE
Callback-style printing

### ISSUE THREAD

**Issue by IwanKaramazow** [facebook/reason#1373]
```
/* original */
describe("App", () => {
  test("math", () => {
    Expect.expect(1+2) |> toBe(3)
  }); 
});

/* becomes */
describe("App", () => test("math", () => Expect.expect(1 + 2) |> toBe(3)));
```

Printing based on line-length isn't very human-friendly in above kind of code.
Ideally we want to preserve the breaking here for readability.
This might be possible we if take the `Location.t` of every node into account.

**Comment by jordwalke** [comment]
This just didn't make sense in the old syntax, so it never got any attention at the time. You can see why:

<img width="240" alt="screen shot 2017-11-13 at 2 42 36 pm" src="https://user-images.githubusercontent.com/977348/32753287-211d2bb8-c881-11e7-968b-095d5b30b1dc.png">

For the new syntax, we can just match a little deeper to see if the final function application argument is a lambda, and of so, break apart the lambda into `L => R`, and dock the lambdas `L`.
