### ISSUE TITLE
Lack of obviousness about what needs to be wrapped in parens within JSX

### ISSUE THREAD

**Issue by ckknight** [facebook/reason#1376]
I recently started playing with the syntax of the `master` branch (read: post-uniform parenthesized syntax).

Upon putting in the following code:
```
<div onClick=handle(handleClick)>
  ReasonReact.stringToElement("Oh boy!")
</div>
```
It `refmt`d into

```
<div onClick=(handle(handleClick))>
  ReasonReact.stringToElement
  "Oh boy!"
</div>
```

Which makes sense, but was initially surprising.

**Comment by chenglou** [comment]
So two things:

- `onClick=handle(foo)` should stay that way
- The content of the tag is now two elements, which is wrong.

**Comment by jaredly** [comment]
Hmm what about
```
<div>
MyThing()
(2 + 3)
</div>
```
?
I don't think we want that to mean `MyThing()(2+3)`.
It's probably best to require surrounding parens at the moment, unless we want to delimit children with semicolons, or commas, or something

**Comment by chenglou** [comment]
@jaredly that one currently formats to:

```reason
<div> (MyThing(())) (2 + 3) </div>;
```

(cc @IwanKaramazow somehow the double parens is still there?)

I've tested the following and it works as intended:

```reason
<div onClick=handle(handleClick)>
  {ReasonReact.stringToElement("Oh boy!")}
</div>
```

So we can take the occasion and accidentally move closer to JS JSX =D

**Comment by jaredly** [comment]
So you're saying that in order to have
```
<div>
MyThing()
(2 + 3)
</div>
```
be treated correctly (as two elements) under the proposed syntax change, I would need to do
```
<div>
MyThing()
{2 + 3}
</div>
```
?

**Comment by chenglou** [comment]
Nono, your example currently has the correct precedence. The issue's example doesn't.

**Comment by jaredly** [comment]
But how do you distinguish at a parser level? I think they'll be indistinguishable

**Comment by chenglou** [comment]
Your example works because it's a variant and it'll always be fully applied. I think we're just gonna suggest to surround things in `{}`

**Comment by chenglou** [comment]
I've now updated the docs on reason and reason-react to use braces.
