### ISSUE TITLE
Infix line breaks should not apply to built-in equality operators

### ISSUE THREAD

**Issue by TheSpyder** [facebook/reason#1377]
I have a series of boolean checks in a single expression that constitutes a long line, such as:

```
let example = true != false && "a" == "b" && "arbitrary" === "example" && "how long" >= "can you get" && "seriously" <= "what is the line length";
```

What I expect is:
```
let example =
  true != false
  && "a" == "b"
  && "arbitrary" === "example"
  && "how long" >= "can you get"
  && "seriously" <= "what is the line length";
```

With 1.13.6 I had something similar to that, except it would collapse multiple checks onto a single line where they fit (also the `&&` were at the end).

What 1.13.7 gives me is:
```
let example =
  true
  != false
  && "a"
  == "b"
  && "arbitrary"
  === "example"
  && "how long"
  >= "can you get"
  && "seriously"
  <= "what is the line length";
```

**Comment by TheSpyder** [comment]
I was also surprised the line breaking applied to `@@` but I guess that is not _really_ a problem (although it did result in a big function being indented by 3 characters).

**Comment by IwanKaramazow** [comment]
@TheSpyder Can you show an example of the `@@`-case? (And what you would expect?)

**Comment by TheSpyder** [comment]
@IwanKaramazow something like this from before the change:

```
let _ =
  List.length @@
  List.map
    (fun s => s ^ " example")
    ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"];
```

Is now:
```
let _ =
  List.length
  @@ List.map
       (fun s => s ^ " example")
       ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"];
```

The extra indent puts pressure on the subsequent line lengths (particularly inside the function). This particularly comes up in one of my ounit tests, which are `test_list @@ <complex function to generate test data>`

I'm not sure what I expect to be honest. This is one case where I was happy with the old style.

**Comment by IwanKaramazow** [comment]
Submitted a patch. If you have other crazy boolean/infix/equality operator chaining wishes, feel free to post them here.
