### ISSUE TITLE
Width is too long: 

### ISSUE THREAD

**Issue by fxfactorial** [facebook/reason#1378]
Using `refmt-mode` and `(refmt-before-save)` and getting this line which I think is too wide, would expect refmt to break it somewhere: 

version: Reason 2.0.0 @ 84e87c4
```ocaml
let () =
  Lwt.return (make_master ()) >>= (fun {pid, workers} => Lwt.return @@ print_endline "123") |> Lwt_main.run |> make_master |> ignore;
```

**Comment by IwanKaramazow** [comment]
Reason 2.0.0 was a wrong release. Version 1.13.7 contains https://github.com/facebook/reason/commit/ebc250ec80c0d7c9566d26d8ce2ee29f71d8fa1c which gives correct line-breaking.

I'm working on additional improvements, Refmt hasn't got the man power as Prettier receivers..
