### ISSUE TITLE
repository for refmt

### ISSUE THREAD

**Issue by ShalokShalom** [facebook/reason#1387]
So far as I see is refmt currently spread over the repo? There are two files in src, is there anything else? 

Contributors might want to write software, which use refmt as basement, so it is helpful to spend it a directory, including build instructions, if its possible to build without Reason itself. 

Its also quite difficult to find its source code at all, since there is a second [Github account](https://github.com/reasonml/) with a repository called reason-tools, where the online version of refmt is stored, which makes the story even more complicated. 

So i suggest to hint about the placement of refmt on the homepage, maybe on the comparison page to OCaml, since that is, where people land who are curious about the differences between both projects.

**Comment by chenglou** [comment]
Now documented, thanks. Reason-tools now also uses the refmt that comes with this repo
