### ISSUE TITLE
Doc comments are different in 4.02.3

### ISSUE THREAD

**Issue by IwanKaramazow** [facebook/reason#1398]
There's a CI issue, with doc comments appearing double in 4.02.3.
Doc-comments get filtered out of the comments, because they appear as attributes in the 
parsetree. And are formatted starting from the attribute in the printer, not as comment.
I tracked it down to:
https://github.com/facebook/reason/blob/master/src/reason_toolchain.ml#L348

On 4.02.3 `Hashtbl.add seen (text, loc) ();` properly filters out comments.
While for example on 4.04.2 we need `Hashtbl.add seen ("*" ^ text, loc) ();` to properly filter out comments.

@let-def is there a reason why the behaviour on 4.02.3 is different?

**Comment by let-def** [comment]
It is a bug in 4.02.3

**Comment by let-def** [comment]
There is no way but hacking around it (or if you use a custom distribution of 4.02.3, e.g bucklescript, maybe fixing it directly in the source).
