### ISSUE TITLE
include statement becomes surprisingly large

### ISSUE THREAD

**Issue by ckknight** [facebook/reason#1406]
Note: this has only been observed in the new uniform parenthesis syntax.

The following small snippet:
```reason
include Impl({ type nonrec t = t; });
```

Gets reformatted to:
```reason
include
  Impl(
    {
      type nonrec t = t;
    }
  );
```

I'd prefer if it were kept terse.

**Comment by chenglou** [comment]
Seems fixed. Larger module body still causes that though. I've filed #1836

**Comment by chenglou** [comment]
Nvm it wasn't fixed, sorry.

**Comment by chenglou** [comment]
Done.
