### ISSUE TITLE
refmt removes parens when it shouldn't

### ISSUE THREAD

**Issue by persianturtle** [facebook/reason#1410]
In index.re which uses ReactDOMRe to render a Reason-React top level component, I've added the following:

```
type foo = {
  sides: ref int
};

let bar = {sides: ref 8};

ReactDOMRe.renderToElementWithId <App sides=(!bar.sides) /> "root";
```

When saving, `sides=(!bar.sides)` is converted to `sides=!bar.sides` which results in a `Error: 19: <UNKNOWN SYNTAX ERROR>`.

**Comment by chenglou** [comment]
Dupe of #869. I'm closing that one because this one's newer.

> Thanks - for now, do `baz.contents` (which is the desugared form of `!`

**Comment by IwanKaramazow** [comment]
This is fixed with the new syntax in master:
```
type foo = {sides: ref(int)};

let bar = {sides: ref(8)};

ReactDOMRe.renderToElementWithId(<App sides=bar.sides^ />, "root");
```

**Comment by chenglou** [comment]
Is... that the new deference syntax? Woah...

**Comment by IwanKaramazow** [comment]
Yes,  we got the  `!` as in `if (! predicate(arg1, arg2)) {... }` back. Desugars to `not`.
I'm not sure however if that space is necessary, it's currently printed with an extra space after the `!`. It might have to do something with infix operators.

**Comment by chenglou** [comment]
Yeah, though I didn't think about what the new `.contents` sugar would be. That's kinda weird

**Comment by IwanKaramazow** [comment]
It should probably be changed before the next release

**Comment by chenglou** [comment]
We've decided to keep that dereference sugar. Closing this. Fixed in master
