### ISSUE TITLE
File name lost in certain syntax errors

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1421]
cc @let-def @IwanKaramazow @jchavarri

Repro:

```reason
while (current <: !(length input)) {
};
```

**Comment by IwanKaramazow** [comment]
What's the issue here exactly?

<img width="517" alt="captura de pantalla 2017-09-23 a las 11 15 53" src="https://user-images.githubusercontent.com/10634678/30771852-9e5d9d1e-a050-11e7-8c0a-64e70a1d7152.png">

**Comment by chenglou** [comment]
Aha, seems like it's fixed in master. Maybe I tested with the wrong binary yesterday. Thanks!
