### ISSUE TITLE
refmt breaks on local exceptions

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#1424]
Using OCaml 4.04.2 and Reason 1.13.7 installed via opam:
```
$ echo 'let () = let exception E in raise E' | refmt --parse=ml --print=re
refmt: internal error, uncaught exception:
       Invalid_argument("No match for unparsing expression")
```

**Comment by IwanKaramazow** [comment]
Thanks for reporting, it's one of those not yet implemented!
Will get to it this weekend.

**Comment by hcarty** [comment]
Do you think this will land before the big syntax update?

**Comment by IwanKaramazow** [comment]
I'll do my best. Looked at it two weekends & it was a lot less trivial than I thought... #parsingIsHardEvenWithMenhir

**Comment by hcarty** [comment]
Thank you for taking a look!

**Comment by IwanKaramazow** [comment]
Managed to parse & print: 
```
let () = {
  exception E;
  raise(E)
};
```
What do you think of the Reason equivalent?
Would you expect `let expression` to work?

**Comment by hcarty** [comment]
I'd prefer `exception E;` as you have it written, to mirror how local `module` definitions work.  I'm ok with `let exception E;` not working as this wasn't previously supported so there's no old syntax (aside from OCaml) to be used to.

**Comment by chenglou** [comment]
Done
