### ISSUE TITLE
refmt does not format == correctly in interfaces

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#1427]
Using OCaml 4.04.2 and Reason 1.13.7:
```
$ echo 'val ( = ) : int -> int -> bool' | refmt --parse=ml --print=re --interface=true
let (=): int => int => bool;
```
The output should be `(==)` rather than `(=)`.  This seems to be something parser-related as the following will not compile, saying that `==` is required but not provided:

`foo.re`
```reason
let (==) => (==);
```
`foo.rei`
```reason
let (==): int => int => bool;
```
It makes it impossible to properly expose a `(==)` function through an interface.

**Comment by chenglou** [comment]
Fixed by #1474
