### ISSUE TITLE
Remove the format `let foo(bar) = 1` from the printer

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1442]
Context: currently the new master syntax sugars `let foo = (bar) => 1` into `let foo(bar) = 1`. This has tripped up lots of folks testing the new syntax. To save on time, we can first remove the shortcut from the printer for now, and keep accepting the syntax in the parser.

**No syntax opinion debates please**, and don't advertise this too much. Right now, we need to focus on shipping this syntax to unblock people. Syntax bikeshedding are reserved for the next breaking change.

**Comment by jaredly** [comment]
Does this mean we'd refmt `let foo(bar) = 1` into `let foo = (bar) => 1`?

**Comment by chenglou** [comment]
Yes. But the former is only allows because I'd like us to ship a bit faster. If we can remove it from the parser then all the better
