### ISSUE TITLE
New error message for application too broad

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1454]
cc @IwanKaramazow 

```reason
let foo = 1
let bar = 2;
```

This triggers the "When applying a function, don't forget to..." message as well

**Edit**: well, we've removed the only message we had, from b31748466b8d896b095858e9db725674ea671332. So we should just put it back and avoid this issue while we're doing it

**Comment by bobzhang** [comment]
it is not  a syntax error?

**Comment by chenglou** [comment]
It is here actually, apparently

**Comment by chenglou** [comment]
Bah, the message isn't there anymore, so that's "fine" now lol
