### ISSUE TITLE
Tests are failing on master

### ISSUE THREAD

**Issue by jaredly** [facebook/reason#1455]
1. `formatTest/unit_tests/input/infix.re`
```
    x.contents = something ? hello : goodbye;
```
is formatting as
```
    (x.contents = something ? hello : goodbye);
```
2. doc comments are behaving weirdly (showing up twice, once as a standalone comment, once as a doc comment) -- see `formatTest/typeCheckedTests/actual_output/comments.rei`

3. another doc comment bug, `mlSyntax.re.4.02.3` the top comment is being attached to the type definition instead of being standalone. Although maybe it's supposed to be attached?

**Comment by chenglou** [comment]
1. Yep, that was the precedence issue I was talking about, since the comment that comes before is really an attribute

2. That's the bug from ocaml 4.02

3. Not sure
