### ISSUE TITLE
Functor parse & print with arrow

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1472]
Making functors print as `module Foo = (Bar) => Baz` rather than the current `module Foo(Bar) = Baz`. Related: #1470

**Comment by hcarty** [comment]
Will multi-argument functors take comma separated modules to be consistent with function application?

**Comment by chenglou** [comment]
I think so? Any drawback?

**Comment by hcarty** [comment]
I haven't enumerated all the possible forms, but it seems like a natural symmetry with the rest of the syntax revision.

**Comment by let-def** [comment]
See https://github.com/facebook/reason/pull/1482, I tried to be as symmetric as possible with function expressions.
