### ISSUE TITLE
[bug] Setting a js object's attribute doesn't type check :/

### ISSUE THREAD

**Issue by jaredly** [facebook/reason#1473]
For example:
```re
let x = {"a": "1"};
x##a #= "2";
```
This fails, saying that `x` has no method `a#=`.
The same behavior happens if `x` is created via `%bs.obj`, or typed as `Js.t {.a: string}`.

A workaround is to use `Obj.magic` like so:
```re
let x = {"a": "1"};
/* danger danger */
let x = Obj.magic x;
x##a #= "2";
/* back to safety */
let x: Js.t {.a:string} = x;
```

**Comment by chenglou** [comment]
@jaredly this should be filed against BS lol

cc @bobzhang

**Comment by jaredly** [comment]
@chenglou for some reason writing it in ocaml works tho

**Comment by chenglou** [comment]
Really? Got a repro?

**Comment by jaredly** [comment]
oops jk it's broke in bucklescript too

**Comment by chenglou** [comment]
Closing it here
