### ISSUE TITLE
Bad Error message

### ISSUE THREAD

**Issue by cullophid** [facebook/reason#1475]
Error: 742

> We've found a bug for you!
>   /Users/andreasmoller/repos/sentia/gain-dealership-app/src/screens/testdrive/testdriveSignatureScreen.re
> 
>   There's been an error running Reason's refmt parser on a file.
>   This was the command:

I was using the reserved keyword `sig` as a variable

**Comment by chenglou** [comment]
Fixed through #1541. Will ship this week

**Comment by cullophid** [comment]
Sweet!

**Comment by bstro** [comment]
I'm experiencing this cryptic error with the following code:

https://gist.github.com/bstro/a2108f143fd2a77bf62b27b1a7451804

**Comment by jamesporter** [comment]
Getting same error with a slightly modified example from Reprocessing:

```
open Reprocessing;

let setup = env => Env.size(~width=600, ~height=600, env);

let draw = (_state, env) => {
  let w = Env.width(env);
  let h = Env.height(env);
  let (x, y) = Env.mouse(env);
  let rx = float_of_int(x) /. float_of_int(w);
  let ry = float_of_int(y) /. float_of_int(h);
  let colour =
    Utils.color(~r=44, ~g=100, ~b=int_of_float(220.0 *. rx), ~a=255);
  let backgroundColour =
    Utils.color(
      ~r=int_of_float(200.0 *. ry),
      ~g=int_of_float(190.0 *. ry),
      ~b=int_of_float(229.0 *. ry),
      ~a=255,
    );
  Draw.background(backgroundColour, env);
  Draw.fill(colour, env);
  Draw.rect(~pos=(x / 3, y / 3), ~width=20 + x / 2, ~height=10 + y / 2, env);
};

run(~setup, ~draw, ());
```

If change to `let backgroundColour = Utils.color(~r=200, ~g=190, ~b=229, ~a=255);` i.e. no multiline/trailing comma thing then error goes away.

**Comment by bsansouci** [comment]
The trailing comma issue is because bsb-native's refmt is out of date. Working on that!

**Comment by jamesporter** [comment]
thanks
