### ISSUE TITLE
[bug] refmt format

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#1487]
reported by @yyc-git (https://github.com/BuckleScript/bucklescript/issues/2099)
before format:
```reason
let getCallArgsFromEmptyStub (stub: Js.t {..}) (index: int) => {
  let call = stub##getCall index;
  Array.to_list (Array.get call##args 0)
};
```

after format:
```reason
let getCallArgsFromEmptyStub (stub: Js.t {..}) (index: int) => {
  let call = stub##getCall index;
  Array.to_list call##args.(0)
};
```

when use "bsb -clean-world -make-world" to compile,  the "Array.to_list call##args.(0)" cause error message:
> Error: Js object ## expect syntax like obj##(paint (a,b))
> ninja: error: rebuilding 'build.ninja': subcommand failed

but this will not cause error, why?
```reason
let getCallArgsFromEmptyStub (stub: Js.t {..}) (index: int) => {
  let call = stub##getCall index;
  let args = call##args;
  Array.to_list args.(0)
};
```
or

```reason
let getCallArgsFromEmptyStub (stub: Js.t {..}) (index: int) => {
  let call = stub##getCall index;
  Array.to_list (call##args).(0)
};
```

**Comment by chenglou** [comment]
Yep, this is #1004. Fixed in master
