### ISSUE TITLE
label function with pipe operator(function compose) error!

### ISSUE THREAD

**Issue by yyc-git** [facebook/reason#1511]
```reason
let addCoordinates ::x ::y => {
  x + y;
};

6  |> addCoordinates x::5   /* error:  This expression has type y:int -> int but an expression was expected of type int -> 'a*/
```

Please help me to fix it!!!Thanks a lot~
the below case can fix it,  but it makes "y" un-labeled! how to remain "y" labeled?

```reason
let addCoordinates ::x y => {
  x + y;
};

6  |> addCoordinates x::5   /*pass compile!*/
```

**Comment by chenglou** [comment]
Hey! You can't pipe into a named argument like that, unfortunately. `|>` is a regular infix function actually. You'll have to use the second option, or in your case, not pipe it.

This makes @bobzhang's proposal for pipe-as-syntax a bit stronger. #1452

I'll close this one for now, and consider it merged into that issue =)
