### ISSUE TITLE
"| Some [x]" does not include parens with refmt in new syntax

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#1525]
Example, using e065e253:
```ocaml
let f x =
  match x with
  | None -> ()
  | Some [] -> ()
  | Some [_] -> ()
  | Some _ -> ()
```
refmts to
```reason
let f = (x) =>
  switch x {
  | None => ()
  | Some([]) => ()
  | Some [_] => () /* Not good */
  | Some(_) => ()
  };
```
which is not valid syntax in the single-element list case.

**Comment by hcarty** [comment]
The error seems to occur with any list literal.

**Comment by IwanKaramazow** [comment]
What do you mean by `with any list literal.` ?
Will fix it, shouldn't be too hard.

**Comment by hcarty** [comment]
List literal is probably the wrong terminology - I tried with longer list patterns with fixed numbers of elements and ran into the same bug. `| Some [x; y]` has the same incorrect formatting issue, for example.
