### ISSUE TITLE
Big issue for trailing comma

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1549]
Gathering a bunch of syntaxes where we don't allow trailing commas. Feel free to add yours here

**Comment by rostero1** [comment]
```
let animal: NotHuman.animal = {
  id: None,
};
```

`Error: 2539: <UNKNOWN SYNTAX ERROR>`

**Comment by chenglou** [comment]
```
type foo = {
  "a": string,
};

type foo = {
  "a": string,
  "b": string,
};
```

**Comment by jordwalke** [comment]
Option 1: Better error messages:
Options 2: Leniently parse them, even if removed upon print.

Any other ideas?

**Comment by bsansouci** [comment]
@jordwalke is there any way to allow and enforce trailing commas?

**Comment by chenglou** [comment]
Definitely option 2. No error message is better than having error + manual correction.

**Comment by jordwalke** [comment]
@bsansouci Yes, we can allow and enforce them. You'd typically only want the trailing comma if it immediately preceeds a line break. Our formatting utilities don't provide facilities for those kinds of conditional separators, but the solution is surprisingly easy. You insert some dummy text that you replace in a final post-processing stage. However, I'd like to make sure that doesn't slow down `refmt` printing significantly by adding another pass over the output. Either way, first step would be to parse it (and print it as it currently prints).

**Comment by zploskey** [comment]
I didn't see function calls yet.
```reason
let foo = baz(
  a,
  b,
);
```

**Comment by IwanKaramazow** [comment]
Does it make sense to allow them in `ConstructorExpr(1,2,3,)`?

**Comment by ckknight** [comment]
If they're allowed in function calls, I'd want them to also be allowed in Ctor instantiation. It's least surprising that way.

**Comment by TheSpyder** [comment]
Lists would be nice too

```
let foo = [
  'a',
  'b',
  'c',
];
```

**Comment by chenglou** [comment]
All solved.
