### ISSUE TITLE
`foo(()) should print to `foo()

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1550]

**Comment by IwanKaramazow** [comment]
Where are you seeing this?
Can't reproduce on master:
```
echo "foo(());" | ./refmt_impl.native
foo();
```

**Comment by chenglou** [comment]
Polymorphic variant

**Comment by IwanKaramazow** [comment]
Apparently the parser doesn't support this yet, so you might as well change the label into `GOOD FIRST SHIFT/REDUCE TASK` 😛
