### ISSUE TITLE
Hard time parsing (curNode^)##childNodes and wrong refmt

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#1554]
It seems like `curNode^##childNodes` isn't valid, so I thought of using parens which works but causes refmt to barf:

```
(curNode^)##childNodes
```

turns into

```
curNode^##childNodes
```
which gives the error:
<img width="379" alt="screen shot 2017-10-26 at 23 10 25" src="https://user-images.githubusercontent.com/4534692/32090144-ded40ae2-baa2-11e7-899d-061be54d043e.png">

and then gets turned into
```
curNode ^## childNodes
```

**Comment by nireno** [comment]
I get a similar issue with `(obj##xs)[0]` being refmt'd to `obj##xs[0]`. With the parentheses removed I get this error:  `Error: Js object ## expect syntax like obj##(paint (a,b))`.
