### ISSUE TITLE
Doc comment causes if statement to be wrapped

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#1563]
I have
```reason
/* I'm a comment. */
    if (true) {
      print_endline("true true")
    };
```
and that gets refmt-ed normally.

But if I change the comment to be `/** I'm a comment */` it gets refmt-ed to
```reason
/** I'm a comment. */
    (
      if (true) {
        print_endline("true true")
      }
    );
```

**Comment by hcarty** [comment]
This looks like it's a side effect of parsing doc comments as attributes.

**Comment by bsansouci** [comment]
Oh I see. We aren’t putting parents around the node to which the attribute applies, so I’m guessing this shouldn’t be too hard of a fix right?

**Comment by IwanKaramazow** [comment]
It's indeed because they are parsed as attributes, they follow the same rules.
Was decided to keep for after the release of the new syntax because of some unforeseen printing difficulties 😇

**Comment by bsansouci** [comment]
Oh also I'll get
```reason
thing1();
/** */ someFunction();
thing2();
```

instead of the much loved
```reason
thing1();

/** */
someFunction();
thing2();
```

**Comment by jordwalke** [comment]
Another repro:

```reason
let main = () => {
  /**
   *
   */
  Printexc.record_backtrace(true);
  Printexc.record_backtrace(true);
};
```
Gets formatted as:

```reason
let main = () => {
  /**
   *
   */ Printexc.record_backtrace(true);
  Printexc.record_backtrace(true);
};
```

**Comment by chenglou** [comment]
Ben's issue is fixed. I'll file a new issue with Jordan's thing.
