### ISSUE TITLE
[Docs] Syntax Cheatsheet: two "Blocks" headings are confusing

### ISSUE THREAD

**Issue by kohlmannj** [facebook/reason#1564]
Disclosure: I've heard of Reason before today, but I am brand new to the language!

On the [Syntax Cheatsheet](https://reasonml.github.io/guide/javascript/syntax-cheatsheet#blocks-1) page, there are two "Blocks" sections with similar code examples:

- **Javascript → Blocks**
- **Blocks**

Based on the _content_ of the latter **Blocks** section, it might benefit from a different title, depending on whether the intended audience is JavaScript developers (like me) or OCaml devs (I'm not sure what they'd think of this heading).

Some early suggestions:
- "Immediately Invoked Function Expressions" (arcane and scary, but I'd say IIFEs are relatively familiar to JS devs?)
- "Sequence Expressions" (the terminology used in Reason, which I'm not familiar with, but seems like a more specific term to use when asking for help in the future)

I'm taking the time to write this up since:
- The cheatsheet's very useful!
- The duplicate "Blocks" headings (whose contents are similar on first glance, but subtly quite difference) left me wondering which commonly used term to use in the future when referring to either the JS or Reason construct of interest

Cheers!

**Comment by chenglou** [comment]
Thanks for the feedback! Actually, those are indeed talking about the same block, and both referring to the Reason side. The first block:

```reason
let myFun = (x, y) => {
  let doubleX = x + x;
  let doubleY = y + y;
  doubleX + doubleY
};
```

Is actually a real Reason block returned from function. Same applies for if-else, etc. There's no real multi-line functions in OCaml/Reason (and no such need).

Is that clearer? How should this be reworded?

**Comment by chenglou** [comment]
Closing for now =)
