### ISSUE TITLE
Link navigates to https://reasonml.github.io/https://reasonml.github.io/reason-react/docs/en/installation.html

### ISSUE THREAD

**Issue by Aprillion** [facebook/reason#1568]
On page https://reasonml.github.io/ when I clicked on `<a href="https://reasonml.github.io/reason-react/docs/en/installation.html">ReasonReact</a>` link, it navigated to `https://reasonml.github.io/https://reasonml.github.io/reason-react/docs/en/installation.html` 

Happens on Win 10 Firefox 57.0b12 as well as Chrome 61 and 62 and on Edge.

Does not happen when I use the context menu to open the link on a new tab, only when I left-click the element => some random JS event handler.

**Comment by chenglou** [comment]
Fixed, thanks.

**Comment by Aprillion** [comment]
hm, now the url is ok after click, but the page content remains on the homepage, does not switch to ReasonReact page content :(

it works after refresh of the ReasonReact page, I can even go back&forward to switch between the 2 pages

but after refreshing again the home pages, it will again NOT show the other page, only changes url

(reproducible in privacy mode)

**Comment by chenglou** [comment]
Thanks for reporting back. I'll look into it. cc @rickyvetter

**Comment by bassjacob** [comment]
I can verify this on Linux on Firefox as well

**Comment by bassjacob** [comment]
```A page wasn't found for "//reasonml.github.io/reason-react/docs/en/installation.html"  loader.js:287:8
A page wasn't found for "/404.html" loader.js:287:8``` in the console when it occurs the first time

**Comment by jaredly** [comment]
I don't think this is there anymore
