### ISSUE TITLE
Reference to x::x instead of ~x in label docs

### ISSUE THREAD

**Issue by faassen** [facebook/reason#1569]
Readings docs at airport so will be succinct.

In this doc there are still a few stray references to "::".
 https://reasonml.github.io/guide/language/function

**Comment by faassen** [comment]
This is especially confusing in the note about unit () and currying. Since the function call syntax changed I don't think the explanation on why you always have to use () in the definition of a labeled function makes sense anymore.

**Comment by faassen** [comment]
The comment explaining why currying labels to explain why () must be passed comes before the section that introduces currying. That doesn't help to clarify the explanation.

**Comment by chenglou** [comment]
Fixed, thanks =)
