### ISSUE TITLE
[proposal] `(. )` checked application

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#1574]
```re
[@bs] f (a,b,c)
-->
f (. a, b,c) 

[@bs]
let f = (b,c) => {b + c }
-->
let f = (. b, c) => {  b + c}
```

**Comment by chenglou** [comment]
I think this makes sense now, under the new application syntax

**Comment by bobzhang** [comment]
@chenglou  `f (.)`

**Comment by chenglou** [comment]
cc @IwanKaramazow 

I'm ok with this I think. Though it might not be the time to onboard newcomers and introduce two application syntax yet. Not sure

**Comment by IwanKaramazow** [comment]
Ok, working on it

**Comment by bobzhang** [comment]
could this be prioritized? we will add a few libs, having a native syntax for uncurried callback will help people consume such libs

**Comment by IwanKaramazow** [comment]
Yes, I'll see what I can do this week.

**Comment by chenglou** [comment]
I believe the snippet should have been:

```reason
let f = [@bs] ((a, b) => a + b);
```

**Comment by ubsan** [comment]
Would `let f = (. a, b) => a + b;` have type `(int * int) -> int`? or would it be `int -> int -> int`?

**Comment by chenglou** [comment]
Nono, it has nothing to do with tuples. It's a BuckleScript-specific optimizations that annotates the type with some info that the BS compiler understands.

If you wanted tuple you can do it today (two layers of parens)

**Comment by ubsan** [comment]
ah, okay. So it's typed the same way as a normal function, but with some annotations?
