### ISSUE TITLE
Use git diff to output diffs for tests

### ISSUE THREAD

**Issue by zploskey** [facebook/reason#1575]
Right now in order to compare expected and actual test results we use `icdiff`, if available, and fall back to normal `diff`. In my experience, having `icdiff` installed makes running the test suite take about twice as long.

The `git diff` tool is fast and produces nice colored diffs. It works very well even for files not checked in to version control as long as you pass the `--no-index` flag. How would folks feel about using git's diff by default if git is available?

**Comment by chenglou** [comment]
icdiff is side-by-side though, looks really nice lol.

But yeah, if git colored diff looks nice then we can do it

**Comment by zploskey** [comment]
I think it would be nice to at least prefer `git diff` over `diff -u` when git is available, as I expect it almost always would be. I'm not very familiar with `icdiff` but my only problem with it was how slow it was.

**Comment by jordwalke** [comment]
I wish git diff did side by side though :(

**Comment by zploskey** [comment]
GNU diff (diffutils) has `-y, --side-by-side`: `output in two columns`, sometimes called by the separate executable `sdiff`. The source code available on Apple's open source website seems to indicate that the version of diffutils they ship includes this option, despite the fact that it's really old. We could play around with using that. Seems like they stayed on the GPL2 version of diffutils. I don't think OS X's diff supports color, but it's there on Linux.
