### ISSUE TITLE
refmt3 with unary -. in labelled arguments

### ISSUE THREAD

**Issue by bloodyowl** [facebook/reason#1580]
the following code works,

```reason
ReasonJs.Canvas2d.translate(~x=(-. actualSize /. 2.0), ~y=(-. actualSize /. 2.0), context);
```

but refmt reformats as

```reason
ReasonJs.Canvas2d.translate(~x=-. actualSize /. 2.0, ~y=-. actualSize /. 2.0, context);
```

which throws a syntax error

**Comment by anmonteiro** [comment]
I did some investigation on this one. It doesn't look to be specific to labeled arguments, the following example also throws a syntax error:

```
let x =-1;
```
