### ISSUE TITLE
Incorrect type generated by removing Js.t from object definition

### ISSUE THREAD

**Issue by TheSpyder** [facebook/reason#1599]
In v2, I created a simple window type:

```type window = Js.t {. <stuff here> };```

which the 2To3 upgrade translated to:

```type window = {. <stuff here> };```

But that then fails to compile when I do `window##stuff#=` on the next line (following the techniques in [how to consume JS properties and methods](https://bucklescript.github.io/bucklescript/Manual.html#_how_to_consume_js_property_and_methods)):

```
  This is:
    window
  But somewhere wanted:
    Js.t('a)
```

I eventually figured out it needs to be `type window = Js.t({. <stuff here> });` but if I refmt that it puts it back to the one that fails.

Looking at the ML output, the difference is:
Correct `type window = < stuff here >`
Incorrect `type window = < stuff here  > Js.t`

I don't want to include my real code, I can build a concrete replication case if necessary. But I figured the difference in types is fairly clear.

**Comment by chenglou** [comment]
Yeah, can you provide a small repro please? This is intentional. `Js.t({. a: int })` not sugars to `{. "a": int}`. Note the quotes. Type equivalent of the bs.obj value.

**Comment by TheSpyder** [comment]
It's probably the annotation which can't be applied if I use quotes. It was easier to create a small repro than I thought, sorry about that!

What I'm trying to do is equivalent to JS `window.myProperty = 3;` as the below code produces.

This works:
```
type window = Js.t({. [@bs.set {no_get: no_get}] myProperty : int});
[@bs.val] external window : window = "window";
window##myProperty#=3;
```

But refmt on that produces it without quotes:
```
type window = {. [@bs.set {no_get: no_get}] myProperty : int};
[@bs.val] external window : window = "window";
window##myProperty#=3;
```

And the concrete correct/incorrect ML when I `refmt --print ml`:
```
type window = < myProperty[@bs.set { no_get }] :int  > Js.t
type window = < myProperty[@bs.set { no_get }] :int  >
```

**Comment by chenglou** [comment]
Fixed

**Comment by TheSpyder** [comment]
Apologies for taking so long to get back to this - I only recently upgraded from 3.0.0, and I don't use bucklescript by default. This is now even more broken than before :)

The input `type window = Js.t({. [@bs.set {no_get: no_get}] myProperty : int});`
now becomes `type window = {. [@bs.set {no_get: no_get}] "myProperty": int};`

Which is a _syntax error_ (the quotes aren't valid around the property key) in addition to still being a type error on `window##myProperty#=3;` (same error I logged this issue with).

**Comment by TheSpyder** [comment]
Oh there was a bucklescript upgrade required as well. That would've been nice to know 🤔
