### ISSUE TITLE
Multiline Js.t shorthand still puts multiple keys on a single line

### ISSUE THREAD

**Issue by TheSpyder** [facebook/reason#1600]
When I have a short object type definition, it's suitable for a single line:

`type shortThing = {. "firstDef": (string, bool) => string, "secondDef": int};`

However when it gets a bit longer refmt switches to partial multiline. I'd prefer if as soon as it doesn't fit on one line it switched completely to multiline mode.

```
type longThing = {
  .
  "firstDef": (Js.boolean, Js.boolean, string) => string, "secondDef": string => unit
};
```

So in this case, `secondDef` should be on a new line (which it is once the length hits the line limit again).

I'd be willing for any definition with multiple "keys" to become multiline if that's what it takes to do this. But I'm guessing this partial multiline behaviour is a remnant of what happened with the old syntax:
```
type longThing =
  Js.t {. firstDef : Js.boolean => Js.boolean => string => string, secondDef : string => unit};
```

**Comment by chenglou** [comment]
Fixed in master
