### ISSUE TITLE
Comment inside array function parameter introduces extra indenting

### ISSUE THREAD

**Issue by TheSpyder** [facebook/reason#1602]
Probably related to general "comments in AST" issues. Old syntax:
```
let myVariable = myFunction [
  /* comment here */
  "strings long enough to make it line wrap",
  "strings long enough to make it line wrap",
  "strings long enough to make it line wrap"
]
```

After conversion, the intending is messed up and unnecessary:
```
let myVariable =
  myFunction
    /* comment here */
    ([
      "strings long enough to make it line wrap",
      "strings long enough to make it line wrap",
      "strings long enough to make it line wrap"
    ]);
```

In fact if I try to put the comment back inside the array refmt keeps producing the same result. Moving the comment above the function call returns what I expect (but the comment relates to the array contents, not really the function).

Also note, comments that aren't the first thing in the array don't have this problem.

**Comment by chenglou** [comment]
Fixed
