### ISSUE TITLE
refmt reformat bug when jsx component is used as argument value

### ISSUE THREAD

**Issue by remitbri** [facebook/reason#1607]
In the "old days" (well, until two weeks ago), I had this record (edited for this bugfile)
```re
{
  renderCell: fun _ item =>
    CellIcon.renderCell
      icon::<SomeSprite width=32 height=32 x=160 y=0 />
      ()
}
```

…which the Reason3 migration script transformed to 
```re
{
  renderCell: (_, item) =>
    CellIcon.renderCell(
      ~icon=(<SomeSprite width=32 height=32 x=160 y=0 />),
      ()
    )
},
```

and everything was fine.
Today: I work on the file with this record, saves, refmt acts and now I have

```re
{
  renderCell: (_, item) =>
    CellIcon.renderCell(
      ~icon=<SomeSprite width=32 height=32 x=160 y=0 />,
      ()
    )
},
```

…which gives me a `Error: 819: <UNKNOWN SYNTAX ERROR>`
What changed?  The parentheses around the SomeSprite jsx component.

**Comment by bloodyowl** [comment]
correction: the migration script didn't transform this correctly, I had to alter the concerned files afterwards.

in the mean time, `~icon({ <Jsx /> })` seems to do the week as it's not reformatted.

**Comment by chenglou** [comment]
Fixed
