### ISSUE TITLE
(Less Hacky) OCaml 4.06.0 support

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#1608]
It almost works!  A constructor changed in part of the compiler internals - not sure what exactly this comes from - but this crude hack is enough to make Reason build under 4.06.0.

```diff
diff --git a/src/reason-parser/reason_lexer.mll b/src/reason-parser/reason_lexer.mll
index 8e057ca..4a83b40 100644
--- a/src/reason-parser/reason_lexer.mll
+++ b/src/reason-parser/reason_lexer.mll
@@ -315,8 +315,9 @@ let preprocessor = ref None
 (* Warn about Latin-1 characters used in idents *)
 
 let warn_latin1 lexbuf =
-  Location.prerr_warning (Location.curr lexbuf)
-    (Warnings.Deprecated "ISO-Latin1 characters in identifiers")
+  let loc = Location.curr lexbuf in
+  Location.prerr_warning loc
+    (Warnings.Deprecated ("ISO-Latin1 characters in identifiers", loc, loc))
 ;;
 
 (* Error report *)
```
I'm sure that there is a cleaner way to fix this.  I'm not sure, however, how to fix this and keep compatibility with previous OCaml versions without using something like cppo.

**Comment by jordwalke** [comment]
Thank you, @hcarty. I think the simplest solution is to just include the implementation of 4.06.0's `prerr_warning` at the top of the `reason_lexer.mll` file. Then it should work in all versions.
