### ISSUE TITLE
Installing Reason messes with currently installed OCaml

### ISSUE THREAD

**Issue by soapdog** [facebook/reason#1612]
The installation procedure described as the NPM one in the manual tells users to install reason using the following command:

```
$ npm install -g https://github.com/reasonml/reason-cli/archive/3.0.0-bin-darwin.tar.gz
```

What it doesn't tell is that it will install OCaml and friends using symlinks that might shadow your current intallation as show in the following capture from the installation procedure:

```
/usr/local/bin/ocamlmerlin -> /usr/local/lib/node_modules/reason-cli/.bin/ocamlmerlin
/usr/local/bin/ocamlmerlin-reason -> /usr/local/lib/node_modules/reason-cli/.bin/ocamlmerlin-reason
/usr/local/bin/ocamlrun -> /usr/local/lib/node_modules/reason-cli/.bin/ocamlrun
/usr/local/bin/ocamlc.opt -> /usr/local/lib/node_modules/reason-cli/.bin/ocamlc.opt
/usr/local/bin/ocamlc -> /usr/local/lib/node_modules/reason-cli/.bin/ocamlc
/usr/local/bin/ocamlopt.opt -> /usr/local/lib/node_modules/reason-cli/.bin/ocamlopt.opt
/usr/local/bin/rtop -> /usr/local/lib/node_modules/reason-cli/.bin/rtop
/usr/local/bin/ocamlopt -> /usr/local/lib/node_modules/reason-cli/.bin/ocamlopt
/usr/local/bin/ocaml -> /usr/local/lib/node_modules/reason-cli/.bin/ocaml
/usr/local/bin/refmttype -> /usr/local/lib/node_modules/reason-cli/.bin/refmttype
/usr/local/bin/reopt -> /usr/local/lib/node_modules/reason-cli/.bin/reopt
/usr/local/bin/rebuild -> /usr/local/lib/node_modules/reason-cli/.bin/rebuild
/usr/local/bin/reactjs_jsx_ppx -> /usr/local/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx
/usr/local/bin/reactjs_jsx_ppx_2 -> /usr/local/lib/node_modules/reason-cli/.bin/reactjs_jsx_ppx_2
/usr/local/bin/menhir -> /usr/local/lib/node_modules/reason-cli/.bin/menhir
/usr/local/bin/ocamlfind -> /usr/local/lib/node_modules/reason-cli/.bin/ocamlfind
/usr/local/bin/reason-cli-esy-sandbox -> /usr/local/lib/node_modules/reason-cli/.bin/reason-cli-esy-sandbox
/usr/local/bin/utop -> /usr/local/lib/node_modules/reason-cli/.bin/utop
/usr/local/bin/refmt -> /usr/local/lib/node_modules/reason-cli/.bin/refmt
```

As someone who already has most of the OCaml tools installed using different versions than the one supplied by the ReasonML installation, you can imagine how this wrecked my system.

ReasonML can install any tool it likes but should restrict global links to its own tools. I am trying to install ReasonML and not shadow my current OCaml installation.

**Comment by jordwalke** [comment]
@soapdog That's a good point.
In this case it didn't ruin your existing system, but it shadowed your existing system, correct? So if you uninstall `reason-cli`, will it restore it back to its original state (I seriously hope so).

Which binaries would you expect it to install? We want to include at least merlin, refmt, rtop, and utop - but what if you had those already available in your system?

**Comment by soapdog** [comment]
@jordwalke actually I had to unravel the installation by hand because the post-install.sh script exploded so no only Reason shadowed my OCaml (and friendly utilities) but it wasn't installed sucessful, so I couldn't use NPM to uninstall it. I had to go and remove each symlink by hand.

I am lucky because my OCaml was elsewhere symlinked there. If the actual files were there, then Reason install would have overwritten them.

I believe this is an oversight in the installation. Some of us enjoy using JS & OCaml and have both toolsets installed. Ideally, Reason would install its needed tools to its own folder.

Installing ```refmt```  and ```rtop``` is an awesome idea but I already have ```merlin``` and ```utop```. I am on a different OCaml switch, I am using 4.05 and I believe ReasonML requires some pretty specific version to work, right? If there are no hard version requirements for ```merlin``` and ```utop```, then the installation could just check if they are already present in path.

**Comment by jordwalke** [comment]
The install should never explode. That is a different issue btw. Do you happen to have a record of what went wrong in the install? (An error log etc?) Whatever we shadow would be trivially removable (by uninstalling the package), and if that's not the case that is a separate bug.
Which binaries to shadow  is a different question, and I'm open to *not* including `ocamlopt` etc. I included many of these because some people requested them. @bsansouci 

`reason-cli` should, however give you everything you need to develop like `ocamlmerlin`, so that might still present problems for you? In that case, I think we need to find a way for people to use exactly one package manager to install things globally. Two competing package managers on one host each competing for global namespace is never going to end well. You mentioned you use `opam`, which is cool. I think we need a workflow that allows people to not have to mix package managers in the first place. If it's not this problem you discovered, it will be some other problem.

**Comment by soapdog** [comment]
I will try to get you a recipe. I am using OpenSuse Tumbleweed (which is their rolling release version). I installed OCaml using opam, so most of my stuff was safe in my home folder. One of the issues was that in my ```$PATH``` definition, ```/usr/local/bin``` appeared earlier than my .opam folder, so when the Reason installation broke leaving dangling symlinks, I couldn't call my OCaml stuff so my own builds for unrelated programs started breaking. It took me a while to realize what was happening.

Later tonight, I will power that machine back and try to figure out what went wrong with the installation script. I know it failed in a post-install.sh script, so it was not some JS code from NPM failing. One way to fail is to execute the NPM global install not having the correct permissions to write to global folders, this will explode and leave dangling symlinks.

**Comment by jordwalke** [comment]
Npm is known to fail with `-g` when not using `sudo`, but I've never seen it leave dangling binary links in that case.

BTW: This guide is great for npm.
https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
I recommend every npm user do this. That prevents npm from installing binary links in /usr/local/bin and it also lets you decide the priority of shadowing between npm and opam (whichever comes later in your bashrc wins).

**Comment by anmonteiro** [comment]
I'm gonna close this one out since reason-cli stopped being maintained and shouldn't be recommended anymore.
