### ISSUE TITLE
Prefix negative not accepted in named argument expression

### ISSUE THREAD

**Issue by ryanartecona** [facebook/reason#1618]
If I write this:

```reason
foo(~x=(-. y));
```

Refmt gives me back this, removing the parens around the negation:

```reason
foo(~x=-. y);
```

But if I re-run refmt, it throws `Error: 819: <UNKNOWN SYNTAX ERROR>`.

**Comment by anmonteiro** [comment]
Isn't this a duplicate of #1580?

**Comment by ryanartecona** [comment]
@anmonteiro Yup, looks like it. I'll close this out. I guess a maintainer should add the labels on this one to #1580, since this one looks triaged but that one doesn't?
