### ISSUE TITLE
[refmt] Keep existing spacing between statements

### ISSUE THREAD

**Issue by kyldvs** [facebook/reason#1622]
Input

```
let x = 1;
let y = 2;

let z = 3;

module A = {
  let x = 1;
  let y = 2;


  let z = 3;
};
```

Desired output

```
let x = 1;
let y = 2;

let z = 3;

module A = {
  let x = 1;
  let y = 2;

  let z = 3;
};
```

Actual output

```
let x = 1;

let y = 2;

let z = 3;

module A = {
  let x = 1;
  let y = 2;
  let z = 3;
};
```

Similar prettier example for reference: https://goo.gl/jVGeah

**Comment by jordwalke** [comment]
@IwanKaramazow had some ideas about how to do this by looking at the binding original locations. I suggested maybe using `ppx` attributes to encode them but I realized that's probably not the best idea and his original approach is better.

**Comment by IwanKaramazow** [comment]
I'll make this a priority, with a bit of luck I can land this next week.

**Comment by jaredly** [comment]
This is done!
