### ISSUE TITLE
Add a conversion function to and from Js objects and records

### ISSUE THREAD

**Issue by Risto-Stevcev** [facebook/reason#1632]
The motivation is that when a Js library returns an object, keeping it immutable makes it easier to reason about state in the application. And if a library requires an object to be able to convert the record back in to a Js object for the FFI

**Comment by kennetpostigo** [comment]
@Risto-Stevcev I think this should be filled in the bucklescript repo

**Comment by Risto-Stevcev** [comment]
That was my initial thought but it says not to file suggestions there, only bugs, so i don't know

**Comment by bobzhang** [comment]
@Risto-Stevcev this is a granted feature request: https://github.com/BuckleScript/bucklescript/issues/1213 good news is that it is available for next release

**Comment by chenglou** [comment]
Yep, soon
