### ISSUE TITLE
Multiple type equations in a module type in a function arg aren't printed properly

### ISSUE THREAD

**Issue by ryanartecona** [facebook/reason#1636]
The following snippet parses & compiles fine.

```reason
module type M = {type x; type y; let x: x;};
type x;
type y;

let f = ((module M): (module M with type x = x and type y = y)) => M.x;
```

But when I run it through refmt, I get the following, with the `...and type...` bit losing its separating space.

```reason
module type M = {type x; type y; let x: x;};

type x;

type y;

let f = ((module M): (module M with type x = x andtype y = y)) => M.x;
```

Afterward, it can no longer be parsed because of the `andtype`.

This seems to only be a problem when the module type is in a function argument position, as the following survives a refmt.

```reason
module type M = {type x; type y; let x: x;};

module N: M with type x = int and type y = int = {
  type x = int;
  type y = int;
  let x = 0;
};
```

**Comment by chenglou** [comment]
Thanks for reporting it!

**Comment by ryanartecona** [comment]
Sure thing!
