### ISSUE TITLE
Issues with `NuclideReason` plugin.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#164]
- [ ] If I open a file, close it and open another one, I still get errors from the first one.
- [x] Paths in symlinks should be made relative  (because `CommonML` doesn't form them as such - fix `CommonML`).
- [x] Paths in merlin should be made relative (because `CommonML` doesn't form them as such - fix `CommonML`).
- [x] Cannot complete `Js` for js_of_ocaml for some reason (only @yunxing) experienced this.
- [ ] pop up window of type error not positioned correctly,  blocking my view of the source code (known issue - will be resolved when Nuclide errors use datatips).
- [x] local type information is supported in Atom (should work with Emacs).
- [x] The`.js` ocaml base `MerlinService` just swallows errors (`MerlinProcess.js` should listen to `stderr` instead of just creating a `stdin` reader).
- [x] Diagnostics not showing up all of a sudden.

cc @chenglou

**Comment by chenglou** [comment]
Long done.
