### ISSUE TITLE
Limitations of the int numeric type

### ISSUE THREAD

**Issue by jkleiser** [facebook/reason#1646]
I just discovered that the int type is rather limited compared to the JavaScript Number integers. I tried the 'fact' function in https://reasonml.github.io/try/?reason=DYUwLgBATiDGEDMCGtIAoB2BKCBeAUAM4DuAlmLABYSY4De+APhAIx4B8rTEA+hxBggAqRCjCYAtCyz4AvgG58AKUIA6YAHsA5mmSo0LAExYsileu26xBgMwmzazTr3iWAFnvLHllwYCs9kA, and noticed that fact(12) seemed OK, but fact(13) and especially fact(14) were not OK.
I think it may surprise a few developers porting JavaScript code to Reason when they're finding that the Reason int is only 32 bit, and since there are no warnings (int operations are modulo 2^32), bugs may not be discovered easily.
In JavaScript, Number.MAX_SAFE_INTEGER is 9007199254740991 (2^53 - 1) in most modern browsers.

**Comment by zploskey** [comment]
There is Int64 in the standard library.

**Comment by jaredly** [comment]
Let's move this over to the bucklescript repo https://github.com/BuckleScript/bucklescript/issues/2887
