### ISSUE TITLE
single-line comment triggers "assert false" in lexer

### ISSUE THREAD

**Issue by glennsl** [facebook/reason#1647]
This snippet

```
// TODO
```

will cause refmt to emit this error:

```
refmt: internal error, uncaught exception:
       File "src/reason_lexer.mll", line 661, characters 6-12: Assertion failed
```

which is perhaps not the most friendly. The error points to the following line (which has since moved):

https://github.com/facebook/reason/blob/ebc7a8a69fcd6697b63ef55299747629d23a8dd2/src/reason-parser/reason_lexer.mll#L661

**Comment by chenglou** [comment]
Merging #1648 into this

**Comment by andreypopp** [comment]
Just triggered that too but I wasn't trying to add a single line comment but rather to use `(//)` operator. Just a data point.

**Comment by jordwalke** [comment]
I think @let-def has a "fix" for this :D :D :D

**Comment by chenglou** [comment]
Fixed for now; it throws a syntax error. But as ^, we'll support line comment soon!
