### ISSUE TITLE
`// foo` throws an exception in the lexer

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1648]
This should definitely fail gracefully.

Repro:

```reason
// foo
```

```sh
refmt: internal error, uncaught exception:
       File "src/reason-parser/reason_lexer.mll", line 700, characters 6-12: Assertion failed
       Raised at file "src/reason-parser/reason_toolchain.ml", line 89, characters 6-15
       Called from file "src/reason-parser/reason_toolchain.ml", line 296, characters 14-57
       Called from file "src/refmt/reason_implementation_printer.ml", line 35, characters 21-32
       Called from file "src/refmt/refmt_impl.ml", line 79, characters 6-51
       Called from file "src/refmt/refmt_impl.ml", line 96, characters 16-35
       Re-raised at file "parsing/location.ml", line 450, characters 12-23
       Re-raised at file "parsing/location.ml", line 450, characters 12-23
       Re-raised at file "parsing/location.ml", line 450, characters 12-23
       Re-raised at file "parsing/location.ml", line 450, characters 12-23
       Re-raised at file "parsing/location.ml", line 450, characters 12-23
       Re-raised at file "parsing/location.ml", line 450, characters 12-23
       Called from file "parsing/location.ml" (inlined), line 454, characters 31-61
       Called from file "src/refmt/refmt_impl.ml", line 101, characters 10-60
       Called from file "src/reason-parser/vendor/cmdliner/cmdliner.ml", line 1303, characters 27-34
       Called from file "src/reason-parser/vendor/cmdliner/cmdliner.ml", line 1350, characters 17-26
       Called from file "src/reason-parser/vendor/cmdliner/cmdliner.ml", line 1375, characters 8-50
```

Ideally we should say "Sorry, comments starting with // aren't supported yet. Please use /* and */"

If it doesn't take too long, we should just add line comment. Please please please.

@jordwalke

**Comment by webern** [comment]
Please add line comments.  Also, why is this closed? You shouldn't crash on this even if it's a syntax error.

**Comment by hcarty** [comment]
@webern Like comments are supported, at least by 3.4.0 and maybe earlier versions.

**Comment by webern** [comment]
OK, I did get this same exception from line comments. If this is the right tool then the version is:

bsb -version
4.0.18

**Comment by chenglou** [comment]
Next version of bs-platform will work

**Comment by webern** [comment]
Repros with the comments in this file.
[Styles.re.zip](https://github.com/facebook/reason/files/2974895/Styles.re.zip)

```
yarn build
yarn run v1.13.0
warning package.json: License should be a valid SPDX license expression
$ bsb -make-world
ninja: no work to do.
ninja: no work to do.
[1/2] Building src/Styles.mlast
refmt: internal error, uncaught exception:
       File "reason_lexer.mll", line 725, characters 6-12: Assertion failed

File "/Users/mjb/repos/mjb/ui/js/src/Styles.re", line 1:
Error: Error while running external preprocessor
Command line: /Users/mjb/repos/mjb/ui/js/node_modules/bs-platform/lib/refmt.exe --print binary '/Users/mjb/repos/mjb/ui/js/src/Styles.re' > /var/folders/rm/wb3nkcw91sl3174x90rw5n9r0000gn/T/ocamlpp598a30

ninja: error: rebuilding 'build.ninja': subcommand failed
```

**Comment by Schmavery** [comment]
fwiw I recently ran into an issue with the lexer having this issue when a single line comment is on the last line in the file. As a temporary work around, you could add something after the comments like I did

**Comment by IwanKaramazow** [comment]
@Schmavery do you still have the code to reproduce?
@webern what version of bsb are you using?

**Comment by webern** [comment]
@IwanKaramazow 4.0.18

**Comment by Schmavery** [comment]
@IwanKaramazow 
That was on bs-platform 4.0.18 (and I just reproed on bs-platform 5.0.0-dev.5) and get this:
```reason
// let _ = 1;
```
throws 
```
refmt: internal error, uncaught exception:
       File "reason_lexer.mll", line 725, characters 6-12: Assertion failed
```

If I add a newline (or anything else that's not a single-line comment) after the comment, reformat works again. FWIW that's using refmt with the `in-place` flag, but my editor integration (vscode reason-language-server) also seems unable to reformat it.

**Comment by cristianoc** [comment]
@Schmavery 
https://github.com/facebook/reason/issues/2350

**Comment by Schmavery** [comment]
Great! (The only reason I mentioned anything in this issue is that I noticed @webern 's example had a single-line comment on the last line, so this probably fixes their problem as well :)
