### ISSUE TITLE
Attributes on record label declaration

### ISSUE THREAD

**Issue by emillon** [facebook/reason#1653]
Hi,

I don't think it's currently possible to attach attributes to label declarations.
The ocaml syntax to do this is:

```ocaml
type t = { x : int [@attr "payload"] }
```

And the corresponding place in the AST is `pld_attributes`.

I'm not sure what happens since `refmt --parse=ml` outputs just `type t = {x: int};`, but on the other hand there is the following rule in the parser:

```ocaml
label_declaration:
  | item_attributes mutable_flag as_loc(LIDENT) COLON poly_type
    { let loc = mklocation $symbolstartpos $endpos in
      (Type.field $3 $5 ~mut:$2 ~loc, $1)
    }
```

So I'd expect something like `type t = { [@attr "payload"] x : int }` to work.

(note that `type t = { x : [@attr "payload"] int }` exists but is different, it attaches the attribute to the type itself)

Does this syntax exist? Or are there any plans to support it? Thanks!

**Comment by zploskey** [comment]
I've been attempting to enable this as part of solving #1559, since docstrings are also parsed as attributes. The part of the parser you are looking for is `lbl_expr:` which is used in `record_expr:`. It currently does not have `item_attributes` and adding it introduces a shift-reduce conflict.

**Comment by jordwalke** [comment]
@let-def That definition of `label_declaration` looks correct to me. Do you know what's going on with this one?

**Comment by let-def** [comment]
The pretty-printer is just dropping attributes on label. That fixes it (I will open a PR):
```
diff --git a/src/reason-parser/reason_pprint_ast.ml b/src/reason-parser/reason_pprint_ast.ml
index de1a04d..82b8980 100644
--- a/src/reason-parser/reason_pprint_ast.ml
+++ b/src/reason-parser/reason_pprint_ast.ml
@@ -2978,10 +2978,12 @@ class printer  ()= object(self:'self)
     let recordRow pld =
       let hasPunning = recordRowIsPunned pld in
       let name = if hasPunning then
-          SourceMap (pld.pld_name.loc, makeList [atom pld.pld_name.txt;])
+          [atom pld.pld_name.txt]
         else
-          SourceMap (pld.pld_name.loc, makeList [atom pld.pld_name.txt; atom ":"])
+          [atom pld.pld_name.txt; atom ":"]
       in
+      let name = SourceMap (pld.pld_name.loc, makeList name) in
+      let name = self#attach_std_attrs pld.pld_attributes name in
       let withMutable =
         match pld.pld_mutable with
         | Immutable -> name
```
