### ISSUE TITLE
[refmt] change default print-width to 80 columns

### ISSUE THREAD

**Issue by kennetpostigo** [facebook/reason#1662]
Currently the default is 100 columns, I was hoping that we could copy prettier default print-width, It reads nicer(opinion) and when embedding code into other sites(medium, etc.) the code reads perfectly. I know we can pass refmt this option with `-w` in the CLI, but most editors don't give option for this.

Here is prettier rationale for 80 columns: https://prettier.io/docs/en/options.html#print-width

**Comment by jaredly** [comment]
I think we're at 80 by default now
