### ISSUE TITLE
Extensible variant constructors should accept attribute after the bar

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1672]
Related: https://github.com/facebook/reason/pull/1670#issuecomment-348024786

This should parse:

```reason
type water = ..;

type water +=
  pri
  |  [@foo] MineralWater
  | SpringWater;
```

Right now only this works:

```reason
type water = ..;

type water +=
  pri
  [@foo] | MineralWater
  | SpringWater;
```

We should make the former parse, to be consistent with variant, poly variant, GADT, etc.

**Comment by chenglou** [comment]
@jordwalke @IwanKaramazow would there be any ambiguity here?

**Comment by IwanKaramazow** [comment]
No conflicts/ambiguities, PR is ready.
