### ISSUE TITLE
Invalid transpilation when using exponents

### ISSUE THREAD

**Issue by logason** [facebook/reason#1676]
I noticed some weird behaviour when using exponents in reason.

If I write the following code snippet in ocaml in the reasonml playground
```
let foo = (100. /. 2.) ** 2. +. (200. /. 2.) ** 2.;
```
it's transpiled to this reason snippet
```
let foo = 100. /. 2. ** 2. +. 200. /. 2. ** 2.;
```

That causes this discrepancy in the compiled javascript output:
```
var foo = 100 / Math.pow(2, 2) + 200 / Math.pow(2, 2);
```
instead of
```
var foo = Math.pow(100 / 2, 2) + Math.pow(200 / 2, 2);
```

The reason formatter in vscode also strips away parentheses when it shouldn't
```
let foo = (100. /. 2.) ** 2. +. (200. /. 2.) ** 2.;
```
is formatted to 
```
let foo = 100. /. 2. ** 2. +. 200. /. 2. ** 2.;
```
causing the same discrepancy as described above.

Try removing and re-adding the semicolon in the reason snippet here and notice the difference in the JS output: https://reasonml.github.io/try/?ocaml=DYUwLgBAZg9jEF4IAoCMAGdA6CB6HATFgJQQBUZEREA1DsgZjvlSeZUQNxA

**Comment by hcarty** [comment]
Yikes - that's a nasty correctness bug in the formatter!

**Comment by chenglou** [comment]
Regression from V3. Fixed. Will ship in the next release. Thanks!
