### ISSUE TITLE
Any chance this will move over to the MIT license?

### ISSUE THREAD

**Issue by kottin** [facebook/reason#1684]
I know facebook has moved other projects over to MIT due to concerns from the developer community over the BSD license used by facebook. Are there any plans to migrate this project as well? Would love to start using this but as it stands its off limits due to the license.

**Comment by OlegLustenko** [comment]
interesting what the problem do you have with BSD Licence.
[Go lang](https://github.com/golang/go) also has BSD-3-Clause Licence and there are no problems with development on go

**Comment by kottin** [comment]
Its not the BSD license itself, its [this little guy](https://github.com/facebook/reason/blob/master/PATENTS.txt) that creates the issue with some legal folks.

**Comment by jordwalke** [comment]
Done in [this commit](https://github.com/facebook/reason/commit/e8fb73ec6ff7c3136715a3c628769e3d5906c4f0). Thanks for the feedback.

**Comment by mmallis87** [comment]
@jordwalke if you rename LICENSE.txt file to LICENSE, Github will recognize the license as MIT and show a nice tab next to commits, branches, releases and contributors 😄

**Comment by IwanKaramazow** [comment]
@mmallis87 https://help.github.com/articles/licensing-a-repository/#determining-the-location-of-your-license

is this still the case, according to the link above both are valid?
