### ISSUE TITLE
Comment parsing failure.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#1687]
This is really strange. Since v3, Docblock comment parsing fails and non-docblock comment parsing succeeds!

```reason
This.fails(
  /**
   */
  ~w=x,
  ~h=y,
  "hi",
  "bye"
)

This.succeeds(
  /*
   */
  ~w=x,
  ~h=y,
  "hi",
  "bye"
)
```

Cc @let-def - what changed with how we parse docblock comments?

**Comment by let-def** [comment]
docblock are parsed like attributes, it is really just sugar for `[@ocaml.doc "bla"]`, so they can only appear in attribute position.

**Comment by jordwalke** [comment]
I can't believe I missed that you landed that! Awesome! Best bug ever.
