### ISSUE TITLE
Adding // to Try reason blows up the editor

### ISSUE THREAD

**Issue by xixixao** [facebook/reason#1690]
Add // at a beginning of a line, hit enter

No matter what else you have in the editor it blows up:
https://reasonml.github.io/try/?reason=C4TwDgpgBMBOHQLxQDIQIYDMoB8oDkB7AEwgAoBLAO2ABoZ4J64EBKAbgCgB6bzoA

**Comment by bsansouci** [comment]
Comments with // are not supported yet. You can use /* */
Could you comment on https://github.com/facebook/reason/issues/80 if you want sigle line comments

**Comment by cristianoc** [comment]
The crash is fixed in https://github.com/facebook/reason/pull/1747.
More work is needed to add support for end-of-line comments.
