### ISSUE TITLE
Support for JavaScript's immutable methods on Array

### ISSUE THREAD

**Issue by TrakBit** [facebook/reason#1701]
Support for JavaScript's immutable Array methods like concat, filter, slice, map in Reason's Array & List

**Comment by chenglou** [comment]
Hello! We do on the BuckleScript side, with even the JS API: https://bucklescript.github.io/docs/en/stdlib-overview.html

The other methods are already supported even on the native side, when logical.

Thanks for the report! Closing

**Comment by TrakBit** [comment]
Thanks for the feedback. So what would be the recommended API one should use in Reason, JS Array Api or OCaml Array Api ?

**Comment by chenglou** [comment]
Whichever one you feel suits you better. No preference for now
