### ISSUE TITLE
Emit undocumented infix operators as operators

### ISSUE THREAD

**Issue by ghuysmans** [facebook/reason#1705]
[js_of_ocaml](ocsigen/js_of_ocaml) uses `##` and `##.` respectively for JavaScript methods and properties. Those are accepted by _ocamlc_'s parser as (undocumented) infix operators and represented as functions applied to two arguments (their operands):
```
$ cat infix.ml 
let _ = a##b
$ ocamlc -dsource -dparsetree infix.ml
[
  structure_item (infix.ml[1,0+0]..[1,0+12])
    Pstr_value Nonrec
    [
      <def>
        pattern (infix.ml[1,0+4]..[1,0+5])
          Ppat_any
        expression (infix.ml[1,0+8]..[1,0+12])
          Pexp_apply
          expression (infix.ml[1,0+9]..[1,0+11])
            Pexp_ident "##" (infix.ml[1,0+9]..[1,0+11])
          [
            <arg>
            Nolabel
              expression (infix.ml[1,0+8]..[1,0+9])
                Pexp_ident "a" (infix.ml[1,0+8]..[1,0+9])
            <arg>
            Nolabel
              expression (infix.ml[1,0+11]..[1,0+12])
                Pexp_ident "b" (infix.ml[1,0+11]..[1,0+12])
          ]
    ]
]

let _ = ## a b 
File "infix.ml", line 1, characters 9-11:
Error: '##' is not a valid value identifier.
```

However, the source code corresponding to this AST (copied from `ocamlc -dsource`'s output, just above the error message) isn't syntactically valid anymore:
```
$ cat prefix.ml 
let _ = ## a b
$ ocamlc -dparsetree prefix.ml
File "prefix.ml", line 1, characters 8-10:
Error: Syntax error
```

Could we pretty-print "operators" starting with `#` the same way as we do for `+`, `-`...?

/cc @vasilisp

**Comment by vasilisp** [comment]
CC @let-def :).

**Comment by ghuysmans** [comment]
It seems it only affects the OCaml backend:
```
$ cat infix.re
let _ = a##b;
$ refmt -p ml infix.re
let _ = ## a b
```

**Comment by Octachron** [comment]
This was a bug in the OCaml ast pretty printer that has been fixed in 4.06, note also that extension-only  operators like `##` are documented in the language extension part of the reference manual : http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec269 .

**Comment by ghuysmans** [comment]
Thank you!

**Comment by jaredly** [comment]
Going to call this fixed then
