### ISSUE TITLE
JS String Enum Conversion

### ISSUE THREAD

**Issue by gniquil** [facebook/reason#1713]
The example shown in the bucklescript docs:

```
[@bs.deriving jsConverter]
type fruit = [
  | `Apple
  | [@bs.as "miniCoconut"] `Kiwi
  | `Watermelon
];
```

gets reformatted to (something like the following)

```
[@bs.deriving jsConverter]
type fruit = [
  | `Apple
  [@bs.as "miniCoconut"] | `Kiwi
  | `Watermelon
];
```

This is probably not expected. The `[@bs.as ...]` should probably go after `|` as was shown in the docs.

**Comment by chenglou** [comment]
Hey! This is fixed in the 3.0.4. Make sure you've upgraded =)
