### ISSUE TITLE
refmt broken when annotating uncurried function

### ISSUE THREAD

**Issue by gniquil** [facebook/reason#1722]
Here's an example:

![image](https://user-images.githubusercontent.com/149100/34392563-b90b71f8-eb01-11e7-8745-bf9f840a410f.png)

I'd like to inline function f, g, h,

So when I try this:

![image](https://user-images.githubusercontent.com/149100/34392577-d114e270-eb01-11e7-932c-5b305120af7c.png)

refmt changes the code to the following (which results in compile error):

![image](https://user-images.githubusercontent.com/149100/34392585-e746f25e-eb01-11e7-9630-33bb0bbaba50.png)

Turning refmt off, the inlined code did work correctly.

**Comment by mhallin** [comment]
+1 on this, I've got it down to this small case:

```reasonml
example([@bs] (x => x));
```

Which `refmt`s into

```reasonml
example( => [@bs] (x => x));
```

When using `Reason 3.0.4 @ 731e605`

**Comment by kucerm2** [comment]
Same error
```reason
 None |> Js.Option.map([@bs] (x => x + 1));
```
`refmt` changes the code to the following:
```reason
None |> Js.Option.map( => [@bs] (x => x + 1));
```

**Comment by jordwalke** [comment]
Fixed in master: https://github.com/facebook/reason/pull/1744

```
echo ' None |> Js.Option.map([@bs] (x => x + 1));' | esy x refmt
None |> Js.Option.map([@bs] x => x + 1);
```

**Comment by jordwalke** [comment]
Trying to cut a release tonight, closing this out.
