### ISSUE TITLE
Refmt "squishes" different functions together for nested modules

### ISSUE THREAD

**Issue by Risto-Stevcev** [facebook/reason#1723]
For example, if I parse this using `refmt --print re --parse re Foo.re`:

```reason
let foo = (x) => x ++ "!";
let bar = 123;


let norf = "worble";
```
it becomes:
```reason
let foo = (x) => x ++ "!";

let bar = 123;

let norf = "worble";
```

It will separate declarations with a newline so that it's easy to read. But for inner modules it will "squish" them together like this:
```reason
let foo = (x) => x ++ "!";

module Wizz = {
  let bar = 123;


  let norf = "worble";
};
```
becomes
```reason
let foo = (x) => x ++ "!";

module Wizz = {
  let bar = 123;
  let norf = "worble";
};
```

For this really simple example it's not a big deal, but for larger modules it makes the code substantially less readable. My suggestion is to have refmt continue to separate declarations with a newline

The nicest solution would be to have a flag, which when turned on refmt won't change how you separate declarations with newlines -- it keeps the structure you gave it. It would still re-format lines that are too long, but the flag would make refmt ignore how you separated declarations with newlines

**Comment by Risto-Stevcev** [comment]
See also #1863

**Comment by jaredly** [comment]
refmt will now respect whitespace separations between toplevel definitions :D
