### ISSUE TITLE
`try (foo().bar)` formats away the parens

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1727]
```reason
try (foo().bar) {
| Not_found => []
}
```

Formats to

```reason
try foo().bar {
| Not_found => []
};
```

Which is invalid.

Relevant: #1718

**Comment by jordwalke** [comment]
Does Fred's PR fix this? If so we should get it merged ASAP.

**Comment by chenglou** [comment]
We should only fix the printer, not make the parser only parse parenthesized version. It'd break existing code everywhere

**Comment by jordwalke** [comment]
I understand. I’m curious if Fred’s other diff fixes this printing issue. (I think he modified the printer too)

**Comment by jaredly** [comment]
Fixed https://reason.surge.sh/?syntax=Reason&code=DYUwLgBAHhC8BQEJgE4E8IAoBmB7XmAlAHQBGAhioRAN6IQA+EAcrmAPp4CuAdgCZwAfBADaAXXoBfANzwgA&canvas=200
