### ISSUE TITLE
refmt busted on class types, thereby can't compile reason code

### ISSUE THREAD

**Issue by fxfactorial** [facebook/reason#1746]
On refmt version `Reason 3.0.4 @ 731e605` and I gave it this OCaml code: 

```ocaml
class type ['provider_impl] _module = object

end

type t

class type bzz = object
  inherit [t] _module
end
```

Which gave me: 

```reasonml
class type _module ('provider_impl) = {};

type t;

class type bzz = {
  inherit (t) _module
};
```

And this does not compile with bsb raising a syntaxerror and refmt in emacs raising a syntax error.

**Comment by jordwalke** [comment]
Thanks for finding this one. This is an important one to fix for compatibility. As an temporary workaround, are you able to define the inherited class type in another `.ml` file?

**Comment by jordwalke** [comment]
Okay, took a look and it looks like we're printing the class type wrong:

This is the correct syntax:

```
class type _module ('provider_impl) = {};
type t;
class type bzz = {
  inherit _module(t)
};
```

**Comment by jordwalke** [comment]
Props to @barkmadley for fixing this! It will go out in the next release. I hope to wrap up intelligent trailing comma printing today which will go in the same release.

**Comment by barkmadley** [comment]
Oooh... Missing trailing commas is the one complaint I have about the current refmt output. Looking forward to that.
