### ISSUE TITLE
refmt globstar doesn't include base directory

### ISSUE THREAD

**Issue by will-wow** [facebook/reason#1748]
**Version:** 3.0.4

## Expected

 Passing refmt a globstar, like in `refmt --in-place src/**/*.re`, on a project that looks like:

```text
src
  one.re
  subdirectory
    two.re
```

Should format both `one.re` and `two.re`.

Running it on a project without sub-directories should work.

## Actual

Running `refmt --in-place src/**/*.re` on a project with out sub-directories in `src` throws this error:

```bash
$ refmt --in-place src/**/*.re
refmt: FILENAMES... arguments: no `src/**/*.re' file
```

Running it on a project with some files in sub-directories only formats the `.re` files in the directories.

Alternatively, `refmt --in-place src/*.re` only formats the files not in sub-directories, as expected.

It seems like the globstar `/**/` is being treated as meaning "at least one directory" instead of "zero or more directories" as expected.

I poked around the refmt code a bit, but I'm not sure where the file glob is actually getting parsed. If someone could point me to it, I could try to make a PR.

**Comment by chenglou** [comment]
Doesn't the globstar expansion happen before the command is invoked?

**Comment by jaredly** [comment]
yeah the globstar is a feature of your shell, not of refmt.
