### ISSUE TITLE
switch usage gets syntax error

### ISSUE THREAD

**Issue by fxfactorial** [facebook/reason#1749]
I'm noticing that there are many places where switch runs into syntax error trouble. 

Example:

```
let promise_to_result = (~errorMessage=?, f) =>
  Js.Promise.(
    Js.Result.(
      f
      |> then_(good => Ok(good) |> resolve)
      |> catch(bad =>
           (
             switch errorMessage {
             | Some(s) => Error(s)
             | None => Error(Js.Json.stringifyAny(bad))
             }
           )
           |> resolve
         )
    )
  );
```

is fine while:

```
let promise_to_result = (~errorMessage=?, f) =>
  Js.Promise.(
    Js.Result.(
      f
      |> then_(good => Ok(good) |> resolve)
      |> catch(bad =>
           (
             switch errorMessage {
             | Some(s) => Error(s)
             | None => Error((switch Js.Json.stringifyAny(bad) {
                 | _ => assert false
               }))
             }
           )
           |> resolve
         )
    )
  );
```

is a syntax error. on: `Reason 3.0.4 @ 731e605`

**Comment by fxfactorial** [comment]
Apparently all that was needed was an extra `()` around the expression that is being switched on.

**Comment by jordwalke** [comment]
Yeah, and we're going to start printing the parens around even the simplest argument to switch `switch(x)` just to reinforce that parens are needed.

**Comment by ubsan** [comment]
I still dislike that - it's entirely unnecessary, because {} are required. I think we should do the same for if-else as well, tbh.

**Comment by ubsan** [comment]
(i.e., we could do the same thing OCaml and Rust do - parse until the `{` as one expression)
