### ISSUE TITLE
Compilation of code with jbuilder/ppx that uses a newtype in a function fails

### ISSUE THREAD

**Issue by reynir** [facebook/reason#1756]
Compilation of code with jbuilder/ppx that uses a newtype in a function fails with `Error: Unbound type constructor a`

Minimal failing test case: https://gist.github.com/reynir/0ca3a1254bd47133dd308d5e2895923e

**Comment by reynir** [comment]
I don't believe the issue is with jbuilder or the ppx. If you convert the code to OCaml it Just Works™.

**Comment by reynir** [comment]
Also, the ppx in the example is an empty ppx so nothing is done.

**Comment by jaredly** [comment]
hmm what version of reason are you on?

**Comment by jaredly** [comment]
The latest version of reason isn't on opam yet, that might be the discrepancy. I'll reopen until we figure it out

**Comment by hcarty** [comment]
@jaredly Reason 3.2.0 is on opam now thanks to @pjhenning

**Comment by reynir** [comment]
It still fails on Reason 3.2.0.

**Comment by anmonteiro** [comment]
Can't repro anymore. Feel free to reopen if still a bug.
