### ISSUE TITLE
Refmt collapses line breaks inside [%raw ""], making it less readable

### ISSUE THREAD

**Issue by rafayepes** [facebook/reason#1757]
Input:
```
let foo = [%raw "function () {

}"];
```

Output: 
```
let foo = [%raw "function () {\n\n}"];
```

https://reasonml.github.io/en/try.html?reason=DYUwLgBAZg9jEF4IG0CkAnAhgdwgIigFcA7AYzAEsZiIAKASggG8AoASBYF88BdAbhYtQkWPCRosuAiXJUaDZu1LUAzjFAA6YDADmtADp4ARpnSH6A7vyA

TBH probably not a big deal since this should be used sparingly, but I had to use it (at least temporarily) for a big chunk and it got collapsed to 1 line full of "\n       ".

**Comment by ubsan** [comment]
@rafayepes Have you tried multiline string literals? `{|hello world|}` should work.

**Comment by rafayepes** [comment]
@ubsan that did work indeed! Thanks :)
