### ISSUE TITLE
Non-compilable refmt output

### ISSUE THREAD

**Issue by RobertPaul01** [facebook/reason#1760]
### Version: 
Reason 3.0.4 @ 731e605

When running this compilable code snippet through refmt:
```
module Document = {
  [@bs.val]
  external getElementById : string => Dom.element = "document.getElementById";
};

let input = Document.getElementById("input");

[@bs.set]
external set_onchange : (Dom.element, [@bs.this] (Dom.event => unit)) => unit =
  "onchange";

set_onchange(input, [@bs.this] (e => Js.log(e)));
```
The last line will turn into:

```
set_onchange(input,  => [@bs.this] (e => Js.log(e)));
```

Causing a syntax error.

**Comment by jordwalke** [comment]
This is fixed in master (thanks to @IwanKaramazow ) and will be in the upcoming release. Thank you for reporting - closing as a duplicate.
