### ISSUE TITLE
polymorphic variant subtyping is broken? 

### ISSUE THREAD

**Issue by fxfactorial** [facebook/reason#1765]
Given this

```ocaml
type blockTag = [`latest | `earliest | `pending ]

type orQuantity = [`quantity of int | blockTag]
```

refmt: `Reason 3.0.4 @ 731e605`

gives: 

```
type blockTag = [ | `latest | `earliest | `pending];

type orQuantity = [ | `quantity(int) blockTag];
```

and this does not compile. 

In addition, if you do change ```type orQuantity = [ | `quantity(int) blockTag];``` to ```type orQuantity = [ | `quantity(int) | blockTag];```, then refmt will still change it back to wrong syntax.

**Comment by jordwalke** [comment]
Thanks for the report. Should be another easy fix.

@barkmadley if you're interested in this one, please feel free otherwise I'll get to it after trailing comments. It will go out in the same release as the other fixes.

**Comment by barkmadley** [comment]
I must have missed the magic github incantation. This issue is now fixed in master.

**Comment by jordwalke** [comment]
You mean you didn't receive a notification about your PR being merged?
