### ISSUE TITLE
Rtop: show directive fails on remapped operators

### ISSUE THREAD

**Issue by Octachron** [facebook/reason#1766]
Using `#show` on remapped operators prints the signature of the corresponding OCaml operator, not the remapped Reason operator. For instance, `#show (^)` prints the signature of `(++)`:

```OCaml
#show (^)
```
>  let ( ^ ): (string, string) => string;

whereas
```OCaml
(^); 
```
> - : (ref('a)) => 'a = <fun>

and requesting the signature of `(++)` itself fails:

```OCaml
#show (++)
```
> Unknown element.

**Comment by jordwalke** [comment]
Thanks for reporting.
