### ISSUE TITLE
[refmt] Formatting of trailing comments in for-loops is not idempotent

### ISSUE THREAD

**Issue by kyldvs** [facebook/reason#1768]
(what happens to the comment is also probably a bug)

Start here: [(try reason link)](https://reasonml.github.io/en/try.html?reason=GYewTgBAFAlhMDsIAYIBcQQIwEoIG8AoCCAegCoIBjEAW1oFME0JzTiIAHMRNAfQQMA7gBtEDKDgDcHCtTqNmrdiW68BwsYMmzKNekxZtCAXxmFJUoA)

```
for (i in 0 to 1) {
  /* comment */
  print_newline();
  /* comment */
  print_newline()
  /* comment */
};

();
```

After first refmt:

```
for (i in 0 to 1)
  {
    /* comment */
    print_newline();
    /* comment */
    print_newline()
  };
  /* comment */

();
```

After second refmt:

```
for (i in 0 to 1) {
  /* comment */
  print_newline();
  /* comment */
  print_newline()
};

/* comment */
();
```

**Comment by jordwalke** [comment]
Remaining (more rare) issue tracked here: https://github.com/facebook/reason/issues/1781
