### ISSUE TITLE
Compiler crashes instead of producing warning about non-exhaustive pattern-match

### ISSUE THREAD

**Issue by radekm** [facebook/reason#1796]
Following code

```reason
let coordinates = (23, 42);
let (24, y) = coordinates;
```

produces

```
Fatal error: exception File "lam_coercion.ml", line 213, characters 9-15: Assertion failed
```

I expect that the code should compile with warning but its execution results in exception.

**Comment by cristianoc** [comment]
Interestingly, this only happens if the non-exhaustive match is the last line of code.

**Comment by radekm** [comment]
Maybe the problem is in BuckleScript https://github.com/BuckleScript/bucklescript/issues/2474

**Comment by jordwalke** [comment]
I'm pretty sure this is not an issue in the Reason implementation, and I see you've created an issue for BuckleScript, so I'll close this one. Thanks for reporting.
