### ISSUE TITLE
Error: EACCES: permission denied (Ubuntu 16.04 x86_64)

### ISSUE THREAD

**Issue by raould** [facebook/reason#1810]
(of course w/out sudo the "-g" npm can't write to the global npm package directory.)
```
$ sudo npm install -g bs-platform
...
fs.js:784
  return binding.rename(pathModule.toNamespacedPath(oldPath),
                 ^

Error: EACCES: permission denied, rename '/usr/lib/node_modules/bs-platform/vendor/ninja-build/ninja.linux64' -> '/usr/lib/nfs.js:784
  return binding.rename(pathModule.toNamespacedPath(oldPath),
                 ^

Error: EACCES: permission denied, rename '/usr/lib/node_modules/bs-platform/vendor/ninja-build/ninja.linux64' -> '/usr/lib/node_modules/bs-platform/lib/ninja.exe'
ode_modules/bs-platform/lib/ninja.exe'
```
[2018-02-08T07_39_25_312Z-debug.log](https://github.com/facebook/reason/files/1706124/2018-02-08T07_39_25_312Z-debug.log)

**Comment by rajatdhoot123** [comment]
Same Its not working with global install till then you can install locally.

step to install locally 

--> npm install bs-platform

then to run locally :   ./node_modules/.bin/bsb -init my-first-app -theme basic-reason

this command will create my-first-app inside your installation folder then 

cd my-first-app 

then use npm start 

It will compile and create the file 

then   node src/demo.bs.js
you get the output on console like :   Hello, BuckleScript and Reason!

**Comment by jaredly** [comment]
This probably belongs on the bs-platform repo. Alternatively, you could ask for help on [the forum](https://reasonml.chat/).

**Comment by bsansouci** [comment]
The answer is https://docs.npmjs.com/getting-started/fixing-npm-permissions. Idk if there's anything we can do...
