### ISSUE TITLE
OCaml version mismatch when installed via opam

### ISSUE THREAD

**Issue by dfalling** [facebook/reason#1816]
I'm trying to get the following working together: Reason ML, NVIM, ALE, Merlin.

Merlin had issues because its install (via `opam`) wasn't the same version as the `reason-cli`.  I uninstalled the npm reason package and did a `opam install reason` instead.  My application still seems to run properly, but now I'm getting warnings from ALE and Merlin that the OCaml versions don't match:
```
src/index.re|1 warning| ~/Code/reason-react/lib/bs/src/app.cmi is not a compiled interface for this version of OCaml. It seems to be for an older version of OCaml.
```

Is there another approach I should take to get Merlin working for Vim and Reason?

Thanks!

**Comment by jordwalke** [comment]
We do not recommend using both `opam` and `npm` (`reason-cli`) simultaneously. If you're using opam I assume you're building a native app?

**Comment by jordwalke** [comment]
@dfalling Can you describe your project? Reason works with opam, and merlin. Or it works with npm and merlin. It depends on the kind of project you are building though. Is it a webapp or a native app? What are your dependencies?

**Comment by dfalling** [comment]
@jordwalke right now there's not much to my project- I used reason-scripts to setup a React app and haven't felt the need to eject yet.  I'm using [ALE](https://github.com/w0rp/ale) for error display in VIM and [their docs](https://github.com/w0rp/ale/blob/b789b9eaadb40f8560843b31c79f7e508a57f23c/doc/ale-reasonml.txt) pointed me towards [setting up Merlin via opam](https://github.com/ocaml/merlin/wiki/vim-from-scratch) to get vim working.  This did fix my setup except for that version mismatch I pasted.

**Comment by outkine** [comment]
I've looked through the merlin source and it doesn't look like there's a way to disable that error. The only option is to install the right base switch version - you can check what version bsb is using in `bsb-native/vendor/ocaml/lib/ocaml/VERSION`.

The most annoying part of the error for me is that ALE moves the cursor back one character whenever merlin produces that warning. It may be worth filing an issue about that.

**Comment by dfalling** [comment]
Whoops, totally forgot about this ticket.  So my current working solution is ALE with `ale_reasonml_refmt_executable` set to use `bsrefmt`.  This requires installing `npm i -g bs-platform` sadly, so I have to make sure any time I update the `bs-platform` in my project, I also bump it globally.  Fortunately I only have one Reason project so I don't have any conflicts.

Any objections to my closing this ticket since I've found a workaround?

**Comment by outkine** [comment]
Nope, that makes sense :+1:
