### ISSUE TITLE
`[@bs]` attribute not parsed correctly in a certain case

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1823]
Sorry for the vague title. Here's a repro:

```reason
[@bs]foo([@bs] {val a = 1})
```

Previously, this becomes:

```ocaml
let _ = foo ((object (this) val a = 1 end)[@bs ])[@@bs ]
```

Now it is incorrectly:

```ocaml
let _ = foo (object (this) val a = 1 end)[@@bs ]
```

Not too important; super low pri as probably no one uses it (except one case in ReasonReact. I can circumvent this easily)

**Comment by idkjs** [comment]
Same problem? Seems like if you copy paste the [Try It json example](https://reasonml.github.io/en/try.html?reason=DYUwLgBADiBODOB7AdhAvBA3gImQQwFsRsAuLbAMwEsExSJsAhRAI2wBoHg946zsAWgAsCVMEOwBfTtjwBzYmQDMAJkkBuAFCbQkAFZJUGGAhQQAPgD4IAKXgA6Oynu9YVZHKoUAngEFk3hbWdvYA8lBgVM4KYACiAB6oVrYOTsj2UHgIIAnIWjrgEPhE6JoQEAYoZUEpjob2ACYgAMaITaEsei1g1ckh4ZHOeMgNACpCIMgAFADaAAIs8AC6EFNTUACU6MEOACJUzWD2MesyxcQbl707YRFR6cNjE9PziytrlchbaDdpjS1tEAdLqHKafS4ba61Ab3Y7gXL5XQQai0AByhBApXKIX2hzhYCm5xkKN42Eh5T6DhhQxG40mswWy1WYMM31+9SarSaAGUwG4PCyUBCof07tF4YlEYVuLx0SU0NUcQcjiciVweHRyTVRYMHrTngy3szwdtan9OYDefy5IKvlcKTdqekYgjtCFgIgbZg9OYABIgYAezgAEhJYDlmODMvDGPMekkGy0QA)  into vs-code, merlin reformats it to something else on save and then will not compile it. 

Specifically, its turning this 
```
  |> Js.Option.andThen([@bs] ((p) => Js.Dict.get(p, "name")))
  |> Js.Option.andThen([@bs] ((json) => Js.Json.decodeObject(json)))
```
 into this 
```
  |> Js.Option.andThen( => [@bs] (p => Js.Dict.get(p, "name")))
  |> Js.Option.andThen( => [@bs] (json => Js.Json.decodeObject(json)))
```
throws
`[bucklescript] 868: <UNKNOWN SYNTAX ERROR>` on the arrows. If u fix and save, it reformats back to bad code.

**Comment by chenglou** [comment]
Not the same issue. That's the old playground. I'll update it later, thanks.

**Comment by chenglou** [comment]
Fixed now. @IwanKaramazow let's make this issue's fix the last diff for the vendored refmt.js in BS

**Comment by cristianoc** [comment]
Another repro.
This `let k = [@bs] foo ([@bs] foo(3));` is formatted to `let k = foo(. foo(3));`.

**Comment by cristianoc** [comment]
This is coming from https://github.com/facebook/reason/pull/1803.
There's already a special case for callbacks:
```
    (* lifts the uncurried attr to the "top" expression, if the first arg isn't a callback
     * example:
     * f(. a, b, c) -> [@bs] f(a, b, c)  (attr sits on the "f" expr)
     * f((.) => 42, 1000) -> f([@bs] () => 42, 1000) (attr needs to stay on the callback) *)
```
And the examples in this thread also indicate special cases for objects and application.
I was playing with adding special cases, but I could not find a way to parse both the following correctly:
```
let a = [@bs] foo ([@bs] foo(3));

let a = foo(. foo(. 3));
```

@IwanKaramazow do you think there's a way to patch nexted uncurrying, or is it simpler to just not to support `add(. 2, . 3);`.

**Comment by IwanKaramazow** [comment]
@cristianoc Just submitted a PR that allow nested uncurrying. Made a whole bunch of wrong assumptions before.

```reason
let a = foo(. foo(. 3));

/* in */
add(. 2, . 3)
/* out */
(add(. 2))(. 3)

[@bs]foo([@bs] {val a = 1})
=>
foo(. [@bs] {val a = 1})
```

If you have any additional edge cases in mind, I can add them to the PR.
