### ISSUE TITLE
Js member access doesn't work in  https://reasonml.github.io/en/try.html

### ISSUE THREAD

**Issue by viebel** [facebook/reason#1825]
The following code snippet is causing a syntax error:

```
let bucklescript = {
  "info": "Bob"
};

let name = bucklescript##info;
```

![image](https://user-images.githubusercontent.com/955710/36300485-37ad28f0-130a-11e8-9b8b-e73ea67ba100.png)

**Comment by chenglou** [comment]
Yeah... this is a problem with the ocaml printer. Change `## bucklescript info` to `bucklescript##info` and it'll work. But then, editing reason code turns it back to the wrong printed ocaml code (which feed into the compiler)

**Comment by viebel** [comment]
So the bug is in the code that converts `reason` code to `ocaml` code?

**Comment by chenglou** [comment]
Yeah it's in the ocaml printer. It should be solved when we upgrade bucklescript's ocaml in a few months

**Comment by viebel** [comment]
OK OK

**Comment by chenglou** [comment]
Thanks for filing it though. Maybe we should put a note in that try page...

**Comment by viebel** [comment]
Good idea!

**Comment by ncthbrt** [comment]
Would second adding a not. Caught me off guard

**Comment by chenglou** [comment]
Done. Sorry about that
