### ISSUE TITLE
object duplication syntax prints (and/or parses) incorrectly

### ISSUE THREAD

**Issue by glennsl** [facebook/reason#1842]
Original OCaml:

```ml
let x = object (this) method push hd = {<v = hd :: v>} end
```
refmts to:

```reason
let x = {pub push = hd => {<v: [hd, ...v]>}};
```

which is not valid syntax because apaprently there should be a space between `<` and `v`. This is valid:

```reason
let x = {pub push = hd => {< v: [hd, ...v]>}};
```

Playground link: https://reasonml.github.io/en/try.html?ocaml=DYUwLgBAHhC8EHsBGArEBjSAKMALAlgM4CUEAtuLggCYQAOArobhLrfAN4A8AbnK7QBcgiDwB8AXwggAdtSA

**Comment by IwanKaramazow** [comment]
What version of refmt are you using?

**Comment by glennsl** [comment]
Whatever is in the playground, which seems pretty fresh since it does the new uncurrying syntax.

**Comment by jaredly** [comment]
This is the same as #1992
