### ISSUE TITLE
How to stringify a record?

### ISSUE THREAD

**Issue by Jianru-Lin** [facebook/reason#1850]
Hello, I'm trying to rewrite my old project in reason. And I feel great. However, when I need to print some records for debugging, I didn't find any function work. May I ask is there any functions that can convert any record to string? For example:

```
type person = {
  age: int,
  name: string,
};

let someone = {age: 9, name: "jerry"};

// convert a record to string
let someone_str = record_to_string(someone); // "{age: 9, name: \"jerry\"}"
```

Thank you! :D

**Comment by cullophid** [comment]
Currently there is no simple way. The best option is to use bs-json to convert it to json.

**Comment by Jianru-Lin** [comment]
@cullophid Thank you! I'll try. 😄
