### ISSUE TITLE
underscore as single arg name is a SYNTAX ERROR

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#1853]
I get `Error: 1575: <UNKNOWN SYNTAX ERROR>` with:

```
let a = _ => 0;
```

You might think this is dumb but in ReasonReact we have:
```
<div onClick=(_ => self.send(Click)) />
```

all the time because the argument is the JS event which we don't always need.

**Comment by chenglou** [comment]
cc @jordwalke another thing from the workshop
