### ISSUE TITLE
_ in variant with multi-arg is a syntax error

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#1856]
I accidentally wrote (notice the `_` at the end):

```reason
{ pmod_desc: Pmod_constraint({...inner_pmod_desc, pmod_desc: Pmod_structure(newList)}, _) }
```

This was a syntax error.

**Comment by jordwalke** [comment]
What would you expect the meaning of this to be?
We do not support `_` for constructors because `_` technically means partial application in functions.

**Comment by bsansouci** [comment]
I just meant that I get `SYNTAX ERROR`, it'd be nice to have a better error than that :)

**Comment by jordwalke** [comment]
Got it!
