### ISSUE TITLE
3.10 not available on Opam

### ISSUE THREAD

**Issue by dc-mak** [facebook/reason#1864]
https://opam.ocaml.org/packages/reason

**Comment by gandulio** [comment]
I'm going to try and make a PR for this, might take a couple days though cause I'm not very familiar with OPAM publishing practices.

**Comment by jordwalke** [comment]
any progress?

**Comment by ncihnegn** [comment]
Release an archive first, please.

**Comment by kMeillet** [comment]
Any news ? Windows user really need this.

**Comment by ncihnegn** [comment]
Why there is not even a 3.10 tag?

**Comment by hcarty** [comment]
The soon-to-be-released [dune-release](https://github.com/samoht/dune-release) may be helpful since Reason already uses dune/jbuilder as its build system.  `dune-release` automates most or all of the steps to release a package on opam.

**Comment by jordwalke** [comment]
It's not about releasing the tag, but about fixing up our release scripts (from `make release` to work with Opam now that we've factored out rtop into their own packages etc).

**Comment by mrkaspa** [comment]
Any progress?

**Comment by pjhenning** [comment]
I don't know about the why for that but in the mean time you can get an equivalent download to a release for the latest version here: https://registry.npmjs.org/@esy-ocaml/reason/-/reason-3.2.0.tgz

**Comment by IwanKaramazow** [comment]
3.1 is available on opam now
