### ISSUE TITLE
Stuck at converting JS objects to Reason Records possibly holds option(al) values

### ISSUE THREAD

**Issue by ryuheechul** [facebook/reason#1872]
I encountered an issue where I wanted to use `[@bs.deriving jsConverter]` to accept JS Objects and convert into Reason Records possibly holds option(al) values

I wrote the gist the attempts for the issue below
https://gist.github.com/ryuheechul/573ea3c203d8fb736ed82480cb8dafbc

And of course I can solve this for now by make a function works better than generated by `jsConverter` but I think it's very verbose and repetitive.

So I think what I wanted to know is how to deal with this situation if there is any good ways you know or opinions about this from folks.

Thanks!

**Comment by jaredly** [comment]
This issue list is unlikely to get you the kind of help & discussion you're looking for -- the discourse server over at https://reasonml.chat/ is the perfect place for this question :)
