### ISSUE TITLE
Documentation error? on "Pattern Matching" page

### ISSUE THREAD

**Issue by fremontmj** [facebook/reason#1878]
This example:
`let (Left v | Right v) = i;`

gives an error on compilation.  (I set it up this way):
```
type leftOrRight = 
| Left(int)
| Right(int);

let i = Left(1);
let (Left v | Right v) = i;
```

This works:
`let Left(v) | Right(v) = i;`

**Comment by chenglou** [comment]
Thanks! Fixed in https://github.com/reasonml/reasonml.github.io/commit/b66547a24486bfcac315b651addd2501f5d3ff40
