### ISSUE TITLE
MLRE/Reason-Tools conversion bug

### ISSUE THREAD

**Issue by idkjs** [facebook/reason#1879]
See: [example in reason-tools](https://reasonml.github.io/reason-tools/popup.html#TGlzdC5tYXAgfmY6YmFzaWNfY29sb3JfdG9faW50IFtCbHVlO1JlZF07Ow==)

Source is Ocaml [Variants](https://realworldocaml.org/v1/en/html/variants.html)

Link doesn't see to be working so...

So if you paste in `List.map ~f:basic_color_to_int [Blue;Red];;`
You get `List.map(~f=basic_color_to_int, [Blue, Red]);`
Working code should be: `List.map(basic_color_to_int, [Blue, Red]);`

**Comment by Schmavery** [comment]
I think this is because RWO expects you to be using Core, and Core shadows the stdlib List.map function with a version that has labelled arguments.
https://ocaml.janestreet.com/ocaml-core/109.22.00/doc/core/List.html

So this is a correct conversion, but just won't run unless you're using Core
