### ISSUE TITLE
Object property type not being enforced

### ISSUE THREAD

**Issue by harsh-vardhhan** [facebook/reason#1886]
```
type person = {
    name: string,
    age: int
};

let person = {
    "John"
};
```

person of type string is being allowed despite being typed as an object, why is that ?

**Comment by Schmavery** [comment]
@hcarty beat me to it, but one bonus thing to note is that you often won't need to use these sort of annotations once you start actually using the variable. You can see that the compiler will infer the type of `person` and throw an error if you try to access one of the record's fields:

```
let foo = person.name;  >> Line 5, 10: This expression has type string but an expression was expected of type person
```

So you know the typechecker's got your back even when you're not annotating your variables 😄
