### ISSUE TITLE
refmt of array access with partial function application product incorrect syntax

### ISSUE THREAD

**Issue by alextes** [facebook/reason#1889]
In formatting:
```re
let () =
  Node.Fs.readFileAsUtf8Sync("src/input-1")
  |> Js.String.split("\n")
  |> Array.get(_, 0)
  |> Js.log;
```

refmt produced:
```re
let () =
  Node.Fs.readFileAsUtf8Sync("src/input-1")
  |> Js.String.split("\n")
  |> _[0]
  |> Js.log;
```

Syntax error is: `Error: 1491: <UNKNOWN SYNTAX ERROR>`. From the highlighting I'm not sure how far the error is falling from the actual syntax problem.

@IwanKaramazow mentioned a relation to #1804 .

**Comment by IwanKaramazow** [comment]
I'll fix it, looking at it now.
