### ISSUE TITLE
Missing space when refmt-ing array with dereferenced value

### ISSUE THREAD

**Issue by emnh** [facebook/reason#1895]
Running refmt on the following removes the spaces in the array constructor and then confuses the compiler who now probably thinks that ^|] is an operator instead of two separate ones:
```reasonml
let a = ref(0);
let b = [| a^ |];
```

**Comment by Skovy** [comment]
I ran into this issue as well. I instead used parenthesis to avoid the syntax error, but `refmt` similarliy strips the `()` which results in a compile syntax error.

```reason
/* before */
[|(row^)|]
/* after remft */
[|row^|]
```
