### ISSUE TITLE
Automatic add dependencies to bsconfig

### ISSUE THREAD

**Issue by bifunctor** [facebook/reason#1896]
Hi all 
It would be nice, when install a dependency that it will add to bsconfig automatically.  

For example, install axios via   

`yarn add bs-axios`

then it should add to bsconfig automatically, instead manually.

```
{
  "name": "httpclient",
  "version": "0.1.0",
  "sources": {
    "dir" : "src",
    "subdirs" : true
  },
  "package-specs": {
    "module": "es6",
    "in-source": true
  },
  "suffix": ".bs.js",
  "bs-dependencies": [
      "bs-axios"
  ],
  "warnings": {
    "error" : "+101"
  },
  "namespace": true,
  "refmt": 3
}
```
Thanks

**Comment by jaredly** [comment]
This is a great idea! Unfortunately I don't think this repo is the best place for it.
I think the two options for implementation are
1) modify yarn to know about bsconfig (imo unlikely)
2) make a tool that synchronizes bsconfig & package.json
3) make a reason-specific package manager (this might be coming down the pipe in several months)
