### ISSUE TITLE
Dollars in keys

### ISSUE THREAD

**Issue by radekmie** [facebook/reason#1898]
I've tried to migrate one of mine MongoDB related projects to ReasonML and failed pretty soon, as this code:

```ocaml
let a = {"$a": 1}
```

Results in:

```ocaml
let a = [%bs.obj { ($a) = 1 }]
```

And therfore an error:

```
We've found a bug for you!
OCaml preview 1:22

Syntax error: ')' expected


We've found a bug for you!
OCaml preview 1:20

This '(' might be unmatched
```

Or even _better_, when ReasonReact JSX is turned on:

```
Line 1, 21: Syntax error: ')' expected
```

Same goes with keys where `$` is not at the beginning.

**Comment by wegry** [comment]
I think `[@bs.deriving abstract]` has you covered here.
```
[@bs.deriving abstract]
type a = {[@bs.as "$a"] dollarA: int};

a(~dollarA=5) |. Js.log;
```
is compiled to 

```
// Generated by BUCKLESCRIPT VERSION 3.0.1, PLEASE EDIT WITH CARE
'use strict';


console.log({
      $a: 5
    });

/*  Not a pure module */
```

**Comment by radekmie** [comment]
Thanks @wegry! It looks... Well, at least it works :smile:

**Comment by chenglou** [comment]
Yeah, that's the new idiom. Thanks @wegry
