### ISSUE TITLE
Pattern matching examples uses deprecated code : throws warning

### ISSUE THREAD

**Issue by erdahuja** [facebook/reason#1899]
```
let optionBoolToJsBoolean = (opt) =>
  switch (opt) {
  | Some(true) => Js.true_
  | Some(false)
  | None => Js.false_
  };
```

Warnings :

```
Warning number 3
OCaml preview 3:43-50

deprecated: Js.true_
Use true directly


Warning number 3
OCaml preview 4:50-58

deprecated: Js.false_
Use false directly
```

**Comment by chenglou** [comment]
This will be fixed this weekend. Playground uses BuckleScript master

**Comment by erdahuja** [comment]
@chenglou How can i help in fixing this. I want to contribute in this project.

**Comment by chenglou** [comment]
This is in another repo; though this particular error has now been fixed by https://github.com/reasonml/reasonml.github.io/commit/5ed3c2a149dbbef59420ee6af060ed4c4b6204de.

Thanks for raising the issue!
