### ISSUE TITLE
Error message when passing "for_" as prop

### ISSUE THREAD

**Issue by malisbad** [facebook/reason#1901]
Error message when passing in the `for` prop to a `label` node produces the following error message:

`For is a reserved keyword, it cannot be used as an identifier. Try 'for_' instead`

According to the source, and by example [here](https://reasonml.github.io/en/try.html?rrjsx=true&reason=LYewJgrgNgpgBAcQE4xgFwJYDsDmcC8cA3gFBxxoCeADvAM5oCGa8hp55Mw1VAXHAyTYcZOAF8A3KKq04jAMaYQWKaNho48kN2UwsGwgCUYjOsuMK0AOhSR5MJAGFt1XfoAUAIjQALYZ4BKVXJ1OGBGAGtWOHcAfXk-KDAULACCAD5iUXIrXK0dLD00ABpsuGwMTEYoAGUmFn53NPxMoi4eSn5PTzFSjjhbCHskRtjLDGV+ceViuFiGZhh+BZZmzIszLAtFKwA5EABVajBFvo4UsAd+eZgoADMMrP7yAB4wDAA3TShTOl3GYAwfCeO4YW5gTzpMr9F7YagQDTyH50P4AoGeDB0AC0CRg8giSEY7xAnnKYGBMAAHgDqLBHD48REAEYgSmk2IydG4-EstlwLBoinU7h0hk81mkgD0UOeHBePyZtzgPjQwCgADEQEghTTRYzeZCiBtzCYdoJhAAVEAAUVggI8ngAErcoCAAISBMQvSUK26ZaFwb3vD4yji9USSEiRkjbNAAEQA8gBZYw2PSXJBW21cIoAdUqPgAkmB3C9kKhMLg4NLZp5qCgPmCAO6BCRAA) it should be suggested as `htmlFor`.

Discussion about a user's issue located [here](https://reasonml.chat/t/how-to-use-label/467/2)

**Comment by anmonteiro** [comment]
The syntax error is correct, IMO, and `htmlFor` is library specific.
