### ISSUE TITLE
`[%raw (a) => 1]` turns into `fun%raw a => 1` then errors

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1902]
Repro:

- Format `[%raw (a) => 1]`
- See `fun%raw a => 1`
- Format `fun%raw a => 1`
- See error

3 issues here:

- `fun%raw` is kinda weird since we don't use `fun` anywhere anymore (and since the only usage of `fun` is for function cases, which might be misleading)
- `[%raw a => 1]` without parens around `(a)` is a syntax error
- `fun%raw a => 1` fails to reformat

**Comment by IwanKaramazow** [comment]
I can look at this
