### ISSUE TITLE
[GoodFirstTask] Fix formatting of GADTs

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#1905]
I was experimenting with some new Reason React JSX representations and I noticed that in one of the recent syntax refactorings, formatting of GADTs became very ugly:

```

type jsx('nature) =
  | Empty: jsx(empty)
  | Cons(elem(('s1, 'a1), 'sub1), jsx('tl)): jsx(
                                                   (('s1, 'a1) => 'sub1, 'tl),
                                                 );
```

This is a good first task if anyone is interested in learning the code base.

**Comment by mrandri19** [comment]
I'll have a look at this
