### ISSUE TITLE
feature request: generate source maps for js builds

### ISSUE THREAD

**Issue by kevinbarabash** [facebook/reason#1908]
I have some jest tests that I'm running coverage on and it can be hard to match lines from report from the compiled .bs.js files with the corresponding lines the in the source .re files.  Source maps could also be helpful when debugging compiled code in the browser.

**Comment by kevinbarabash** [comment]
https://github.com/BuckleScript/bucklescript/issues/1699 is probably a necessary first step.

**Comment by jaredly** [comment]
The implementation of this would be wholly in the bucklescript project, so I'm going to go ahead and close this. Reason's parser preserves file locations when handing the AST over to bucklescript, so I don't think any changes over here are needed.
