### ISSUE TITLE
JSX syntax doesn't support functors

### ISSUE THREAD

**Issue by OhadRau** [facebook/reason#1924]
Functors are a pretty powerful feature that could be used in conjunction with JSX/ReasonReact in order to make building UIs easier. As an example, let's say you have a ImageGallery component that can display a gallery of different image components. Using functors, you could define:

```reason
module ImageGallery(I: Image) = {
  let component = ReasonReact.statelessComponent("ImageGallery");
  let make = (~imgs=[||], _children) => {
    ...component,
    render: self =>
      <div>
        (ReasonReact.arrayToElement(Array.map(img => <I img/>, imgs)))
      </div>,
  };
};
```

Then in turn you would create the Image type and various implementations. For example, we could have `SquareImage : Image` and `CircularImage : Image` as two different implementations. Instead of having to create an element for each `Image` and then creating a wrapper `ImageGallery` around that, you could instead simply give it the list of images to load and then change the type of child used in the `ImageGallery` like so:

```reason
let images = [| loadImage("img/test.png"), loadImage("img/example.jpeg") |]

ReactDOMRe.renderToElementWithId(<ImageGallery(SquareImage) images />, "preview");
```

As it stands, the only way to do this with the current ReasonML JSX extension is by creating a temporary module:

```reason
let images = [| loadImage("img/test.png"), loadImage("img/example.jpeg") |]

module SquareImageGallery = ImageGallery(SquareImage);
ReactDOMRe.renderToElementWithId(<SquareImageGallery images />, "preview");
```

Though this is only a minor inconvenience, it seems like it should be an easy addition. I'm happy to implement this and then open a PR if this is something that others think would fit in well, but I was wondering whether there's a reason that this wasn't already a feature. Any thoughts?

**Comment by cristianoc** [comment]
Looks like a pretty natural extension. One thing to check I guess is whether there are any parsing issues. Also, what it would look like when there are separate open and close tags.

**Comment by cristianoc** [comment]
It could look like this:
```reason
<ImageGallery(SquareImage) images> <div /> </ImageGallery(SquareImage)>
```
which matches the usual rule that open and close tags are identical, though it might be a bit confusing and suggest that the application happens twice even though there is only one application.

Or it could even look like this:
```reason
<ImageGallery SquareImage images> <div /> </ImageGallery>
```
where the capital letter in `SquareImage` essentially represent a "module prop". Issues with this I imagine are when people use a capital letter for a prop by mistake, and end up seeing obscure error messages about functors.

**Comment by OhadRau** [comment]
As another thought, it may be possible (and even easier) to allow:

```reason
<ImageGallery(SquareImage) images> <div /> </ImageGallery>
```

This way, it's clear that application happens only once and I don't need to alter the lexer to accept new ending forms (since there are many special cases that have to get handled).

**Comment by OhadRau** [comment]
Ok, so I've found part of the reason why this wasn't previously included. For certain reasons that aren't super clear, OCaml doesn't let you have functor application in any arbitrary situation. One of these situations is selection from the functor's result: `F(X).x` isn't supported. There is an easy fix here, which would involve using `let module` to define the temporary module:

```reason
ReasonReact.element({
  let module ImageGallerySquareImage = ImageGallery(SquareImage);
  ImageGallerySquareImage.make(images, [||])
});
```

The issue with this is generating unique names. One way I've done this in the past is by creating unparseable names in the AST (e.g. `ImageGallery$(SquareImage)` could be the identifier) but as far as I know this won't work because the Reason pipeline involves parsing multiple times (am I wrong in this assumption?). Either way, I was wondering whether there's a more "idiomatic" way to do unique name generation in Reason.
