### ISSUE TITLE
[refmt] Refmt inserts empty lines between assignments

### ISSUE THREAD

**Issue by kutyel** [facebook/reason#1926]
Hi!

Normally in my JavaScript I tend to group various statements together and leave spaces between blocks of code to make clearer the separation between variable assignments and the rest of the code, for example. Right now when I do so, refmt inserts black lines in between, like so:

```ocaml
let conns = ref(0);
/* <-- this is the empty line I'm trying to get rid of */
let store = ref(initialState(X));
```

Since the new change to refmt it seems it preserves the empty lines placed by the developer, but it keeps adding the ones we did not put, I would be happy to help fixing this issue if someone points me in the right direction 😉(cc: @IwanKaramazow)

**Comment by IwanKaramazow** [comment]
Hi @kutyel.
If I understand everything correctly, you want:
```reason
let conns = ref(0);
let store = ref(initialState(X));
```
to be formatted as
```reason
let conns = ref(0);
let store = ref(initialState(X));
```

The current refmt in master will do that for you. It detects that there is no whitespace between the two lines, and formats it as is. You're probably using reason-cli?
@jordwalke @chenglou can we cut a new release/upgrade bucklescript asap?

**Comment by kutyel** [comment]
That's right, yes I was using reason-cli@3 😉

**Comment by chenglou** [comment]
Yep, can be closed now!
