### ISSUE TITLE
refmt errors on parentheses-less args of functions within ppx-attrs

### ISSUE THREAD

**Issue by andreypopp** [facebook/reason#1937]
This code:
```
[@test.call (string) => string]
let processCommandItem = 12;
```
reformats into:
```
[@test.call string => string]
let processCommandItem = 12;
```
which makes `refmt` throw on a further invocation with:
```
File "./failure.refmt.re", line 1, characters 19-21:
Error: 2282: syntax error, consider adding a `;' before
```

Looks like `[@test.call string => string]` isn't being accepted due to missing `(` and `)` around the arg.

Version used: https://github.com/facebook/reason/commit/0401064b696d0e9384b7824fbd0c7d6638cb553c

This looks like a regression as it worked with the previous release (reason-cli@3.1.0).

**Comment by andreypopp** [comment]
I'm wrong, the refmt from reason-cli@3.1.0 also throws in this case.

**Comment by IwanKaramazow** [comment]
I'll fix the parser.
How would you want to see this formatted? With or without parens on the single arg?
```
/* with parens */
[@test.call (string) => string]
let processCommandItem = 12;

/* without parens */
[@test.call string => string]
let processCommandItem = 12;
```

**Comment by andreypopp** [comment]
I'm not sure, maybe without parens to be consistent with regular functions:
```
% echo 'let x = (x) => x;' | esy refmt
let x = x => x;
```
