### ISSUE TITLE
refmt moves comments in presence of extension point syntax

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#1938]
Given the following code:
```reason
let () = {
  /* Clean things up later */
  %defer
  cleanup();
  something_else()
};
```
`refmt` from 0401064b will move the comment to after `cleanup();`:
```reason
let () = {
  %defer
  cleanup();
  /* Clean things up later */
  something_else();
};
```

**Comment by Lupus** [comment]
Hey @hcarty can you please share the link to PPX repo for %defer if it's available publicly?

**Comment by hcarty** [comment]
@Lupus Sure!  https://github.com/hcarty/ppx_defer or http://opam.ocaml.org/packages/ppx_defer/ on opam.
