### ISSUE TITLE
Equivalent of putAlanguageHere-koans

### ISSUE THREAD

**Issue by tclain** [facebook/reason#1948]
Hi guys,

first of all, thank you for your work, that's awesome !

I was wondering, if you'd be interested in this kind of initiative for reasonml:
https://github.com/lazerwalker/clojurescript-koans

This exists in  lot of language, and AFAIK, it seems very useful for beginners to approach a new  language.

I've seen some repos with this initiative as a static project for reason (at least two):
https://github.com/gabrielperales/reasonml-koans for instance.

In the reason ml organization , I see an empty repo : https://github.com/reasonml/reason-koans

I would really like to make it happen in  web version (written in reasonml of course, .... so meta) accessible to anyone without the need of installing something.

Would it be interesting for you guys ? Are you working on something similar ? If not, can I help ? Would you some ideas of the language features that could be demonstrated ? I was thinking of following the order of the official doc.

Thank you for your answers !

**Comment by jaredly** [comment]
An issue on here probably won't get the discussion you're looking for -- I think the reason discourse server (https://reasonml.chat) is what you're looking for! There people can more easily find & discuss your suggestion.
Thanks for bringing this up, I think it's a great idea!
