### ISSUE TITLE
Fix the rest of the spread syntax errors

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1952]
Thanks to #1925, we now have pretty good wrong list spread errors. These are still remaining:

- list spread pattern
- record spread `{a, ...r}`
- record spread pattern `{a, ...r}`
- array spread
- array spread pattern

As an aside, I'm convinced that #1925's way of fixing it is right (cc @cristianoc @IwanKaramazow). Because if we ever need to support those currently unsupported spread patterns, it'll be easy to unlock that. Simpler code for current maintenance too, so win-win.

**Comment by IwanKaramazow** [comment]
I'll take care of it.
