### ISSUE TITLE
Remove rebuild

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1953]
It's about time

**Comment by anmonteiro** [comment]
I may be too late to the party, but one useful usage of `rebuild` that I've taken advantage of in the past was to build unikernels in Reason.

I didn't really use `reuild` itself, but pasted the contents of the `myocamlbuild.ml` file in the auto-generated unikernel file with the same name.

**Comment by hcarty** [comment]
@anmonteiro Does dune support unikernel builds yet?

**Comment by anmonteiro** [comment]
@hcarty It's been a year since I last tried; I haven't kept up with Dune, so can't answer that one.

**Comment by hcarty** [comment]
I think the mirage folks have put a fair amount of testing and effort into it. Dune also has Reason support out of the box so it may provide a simpler build environment overall.
