### ISSUE TITLE
refmt assertion error

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1954]
```reason
module rec A = {
  type t;
}
and B = {
  type t;
};
```

**Comment by IwanKaramazow** [comment]
The Ocaml manual dictates that a recursive module needs a constraint:
```
 module rec module-name :  module-type =  module-expr   { and module-name :  module-type =  module-expr } 
```
The snippet you posted, is something that parses in Reason, but the resulting AST isn't something that the compiler accepts. Do we throw an error in the Reason parser if you forget to put a constraint?

**Comment by chenglou** [comment]
Whichever ehhh, simplifies our parser?

**Comment by anmonteiro** [comment]
in master:

```bash
$ ./_build/install/default/bin/refmt 
module rec A = {
  type t;
}
and B = {
  type t;
};

module rec A = {
  type t;
}
and B = {
  type t;
};
```
