### ISSUE TITLE
refmt removes necessary parenthesis

### ISSUE THREAD

**Issue by vkammerer** [facebook/reason#1957]
I was reading through http://reasonmlhub.com/exploring-reasonml/ch_functions.html (the section "Compatibility of function types with labeled parameters"), and trying to reproduce the examples locally when I encountered what seems to be a bug with refmt's handling of parenthesis.

The following correct code:
```
let myFunction = (aFun: ((~x: int, ~y: int) => int)) => aFun(5, 2);
```
is formatted by refmt to the following incorrect code (which doesn't compile)
```
let myFunction = (aFun: (~x: int, ~y: int) => int) => aFun(5, 2);
```

I created an example in the playground to reproduce the bug.
Steps:
- go to https://reasonml.github.io/en/try.html?rrjsx=true&reason=DYUwLgBAhgJjEF4IAoB+APANBVBPAlIgHwToQDUEuA3AFCiQDGUwwAggGICuAdgOoBLMAAsArGx4wATIhRRuPAFwo06ZQJ5hsedZsIISGsPn0l5vZKOxT8dWgCkAzgDpgAewDmyZq069BIuKSUsiwMCZ0QA
- as you can see, reason compiles correctly and the browser console logs the expected output.
- click on "refmt" and see how parenthesis are removed from the function's definition
- Trigger recompilation by adding a line break at the end
- reason cannot compile the code anymore and logs an error

**Comment by anmonteiro** [comment]
I don't think it's a problem with the printer. It seems to me that the parens are in fact unnecessary. Rather, I think we should be able to parse the paren-less version.
