### ISSUE TITLE
Extra line between recursive bindings

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#1958]
```reason
let anotherRegularLetBinding = "hi"

and yetAnotherBinding = "bye";
```

refmt this removes the line. I guess this is desired right? We can still be a bit opinionated for whitespace when it makes sense. If so, I'll close the issue.

cc @IwanKaramazow @jordwalke

**Comment by IwanKaramazow** [comment]
It's not yet implemented for recursive let bindings, probably should add it.

**Comment by chenglou** [comment]
Should we? No opinion, except unless this makes the logic even harder

**Comment by IwanKaramazow** [comment]
Not hard, just need to implement it.
