### ISSUE TITLE
[Suggestion] JSX semicolon - more helpful Syntax Error

### ISSUE THREAD

**Issue by mudrz** [facebook/reason#1967]
For some syntax errors I get a message `[merlin] A syntax error occurred. Help to improve this message:`.

For example when I put an extra `;` at the end of `</div>;` :

```reason
let make = (_children) => {
  ...component,
  render: _self => <div> 5 </div>;
};
```

<img width="1116" alt="screen shot 2018-05-28 at 7 37 11" src="https://user-images.githubusercontent.com/9587050/40597949-78b0a5ba-624d-11e8-95a6-9b2cf78d33ab.png">

Perhaps a more specific error message can be shown
(moved from https://github.com/reasonml-editor/vscode-reasonml/issues/217)

**Comment by anmonteiro** [comment]
I don't think this is a bug. the record syntax doesn't allow semicolons at the end of key-value pairs.

To help you visualize, here's your example with an extra braced expression:

```
let make = _children => {
  let componentDefinition = {
    ...component,
    render: _self => <div> 5 </div>
  };
  componentDefinition;
};
```

It does, allow, however, a trailing comma.

**Comment by anmonteiro** [comment]
Agreed on the better error message though!

**Comment by mudrz** [comment]
I also agree that it's not a bug (5 inside a <div/> is also incorrect reason jsx syntax), but I got such errors after copy-pasting from existing code and I didn't understand what is the issue

**Comment by anmonteiro** [comment]
@mudrz I just submitted https://github.com/facebook/reason/pull/1968 to address this issue!

**Comment by mudrz** [comment]
That was quick, thanks :)
