### ISSUE TITLE
Fast pipe and local open

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/reason#1983]
Compiler yells when I fast-pipe into local open.

Repro: https://reasonml.github.io/en/try.html?rrjsx=true&reason=LYewJgrgNgpgBAMTgXjgbwFBzrALnAMxTgAoAPALjgEsA7XAGjgE8qBnXAJzoHMBKFAD5SfANwYAvuIwB6AFRwAmjAAOcOTIwBGOAB9hCAHQkCJAPpMARFst8xGWQuVqNGIyR27DhEtdv3HOAA5EBV4V09vd1M-O3EgA

**Comment by ubsan** [comment]
It seems like it should be a compiler error if one does `x |. <expr>` where `<expr>` is not a (possibly parenthesized) function-call-expression.

**Comment by chenglou** [comment]
cc @bobzhang

**Comment by bobzhang** [comment]
feel free to close it, moved to bucklescript repo
