### ISSUE TITLE
Fix parsing of function object update.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#1992]
The following errors:

`echo 'let z = {<state: 0, x: y>} ' | refmt`

But if you include a space in between `<` and `state_` it does not. @IwanKaramazow Is this due to some of our recent JSX lexer hacks?

**Comment by IwanKaramazow** [comment]
Unfortunately it is, I'm afraid. Will fix.

**Comment by jaredly** [comment]
interestingly, refmt will transform `let z = {< state: 2 >}` to `let z = {<state: 2>}` which is then a syntax error
