### ISSUE TITLE
Automatic interface source detection for refmt

### ISSUE THREAD

**Issue by lpil** [facebook/reason#2000]
The Neoformat editor plugin is currently unable to format interface files with refmt. This is because the shell command used to invoke a formatter is defined statically per language, so the `--interface` flag is never set, causing all Reason files to be treated as implementation files. Refmt is run either on STDIN or on a tmp file, so the file extension is not present to determine the file type from.

I believe we could solve this problem while also improving the ergonomics of the refmt by introducing automatic interface detection by attempting to use the interface parser in the event that the implementation parser fails.

Here is some pseudocode:

```reason
switch (parseRE(source)) {
| Ok(ast) => prettyPrint(ast)
| Err(error) =>
  switch (parseREI) {
  | Ok(ast) => prettyPrint(ast)
  | Err(_) => fail(error)
  }
};
```

The only disadvantage I see here is having to parse the source twice in the event it has a syntax error, though I don't think this would be an issue to anyone.

I'd be willing to attempt to implement this feature with a little guidance :)

Related issue: https://github.com/sbdchd/neoformat/issues/153

**Comment by Schmavery** [comment]
Why not treat .rei as a different language from .re?

**Comment by lpil** [comment]
In vim interface files and implementation files are the same language.

It's technically possible, but it would be deviating from the standard and would require significant work to be  done in https://github.com/reasonml-editor/vim-reason-plus and any other Reason vim plugins.

Making refmt more permissive is much less work, and also makes the user interface a little friendlier :)

**Comment by chenglou** [comment]
We've considered this before, but given that `refmt` is used programmatically, we wanted to avoid folks accidentally using this behavior and slow down the parser twice

**Comment by lpil** [comment]
Could this behavour be opt-in via the CLI? Then it would not impact exist users.

**Comment by jaredly** [comment]
an `--auto-detect-interface` flag sounds reasonable

**Comment by lpil** [comment]
I've resolved my original issue client side. https://github.com/sbdchd/neoformat/pull/177

Once that PR is merged this will no longer be an issue for me. I'll leave the issue open in case this CLI API enhancement is still desired :)
