### ISSUE TITLE
New default error messages from the table are not good

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#2003]
```
File "", line 1, characters 11-12:
Error: 3630: <YOUR SYNTAX ERROR MESSAGE HERE>
```

We'll need to fix this before the next version. It looks like we don't know how parsers work lol

**Comment by jordwalke** [comment]
Is this in the current release on npm? Or is it a new problem since the last release?

**Comment by chenglou** [comment]
New problem; we've checked in the message table again (which is prolly a good thing)
