### ISSUE TITLE
Problem with generic Js.Promise.error

### ISSUE THREAD

**Issue by italonascimento** [facebook/reason#2006]
I'm making an http request which returns a promise.

When the request returns an error, though, I'm unable to access the response `body` field, as `Promise.error` is a generic type.

If I log the error using `Js.log` I'm able to verify that the object contains a `body` field, but I can't access it.

```reason
Js.Promise.(
  Request.get(url)
  |> catch(err => Js.log(err))
)
/*
{
  ...
  body: '{...}'
}
*/
```

What can I do in such situation?

**Comment by jaredly** [comment]
Looks like you're getting some help in discord, so I'll close this. Also note that the forum (https://reasonml.chat) can be quite helpful for questions like this.

**Comment by italonascimento** [comment]
gabrielrubens was really helpful on discord! I should have asked it there first, instead of opening the issue.
I'll surely take a look at the forum as well the next time. Thanks @jaredly  :)
