### ISSUE TITLE
Can the requirement to put a semicolon after an if/else block be relaxed?

### ISSUE THREAD

**Issue by bordoley** [facebook/reason#2011]
I'm not familiar enough with the grammar  to know if this is possible or not, but if possible it would be really nice if the following code compiled:

```
let test = b => {
  if (b) {
    ignore();
  }
  ignore();
};
```
Notice, the missing semicolon after the if block. I realize this is somewhat of a dubious request, but its a frequent source of hard to find compile bugs (out of habit) and I imagine hits newcomers to reason from JS/Java/C#/etc. quite often.

I'd suggest only relaxing this constraint at compile time, but adding the semicolon back in when printing. If this is not possible due to grammar restrictions, feel free to close.

**Comment by IwanKaramazow** [comment]
It’s on my todo list. This is a small case where the semi colon recovery fails, we can solve it at the grammar level

**Comment by bordoley** [comment]
well that was fast. thanks!

**Comment by chenglou** [comment]
Iwan's getting pretty good at this now lol
