### ISSUE TITLE
refmt prints invalid Reason code for annotated polymorphic variant values when parsing OCaml syntax

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#2017]
```
$ echo 'let x : t = `Poly' | refmt --parse=ml
let x:  .t = (`Poly: t);
```
The type constraint is duplicated and gets a leading `.` on the lhs of the `=`, leading to invalid syntax.
Reason 3.2.0 installed via opam.

**Comment by IwanKaramazow** [comment]
Hmm, this a serious bug. I'm fixing it, unacceptable.
