### ISSUE TITLE
Anonymous function arguments formatted oddly by refmt

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#2030]
With refmt 3.2.0:
```reason
Parent.Service.make_blocking(path, (request, _body) =>
  callback(dbd, request)
);
```
It would be nice to have the anonymous function all together, or maybe add a line break before the function if the line wraps.  Something along the lines of:
```reason
Parent.Service.make_blocking(
  path,
  (request, _body) => callback(dbd, request)
);
```

**Comment by anmonteiro** [comment]
I think this is deliberate. See how e.g. Prettier formats the same code:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAFAhgJwTAdAZTkwDcBLMOXAW3QGs4B9AIwBsIxbSoBzACgB0oAAiEAHdDAAWAGkEje2AI4BXOAGcY0ocwgATAJ4BKIQF4AfELDoWLJug69dTXVqWqNhwYYDcIaSAhRGFJoNWRQLEwIAHcMbCgwlHRiCFJdPxAmTHt6GHxxMC5uZBhMVX8uNSIYVGzuGmQAM2sq-wArNQAPACFsjjg89Co4ABkuOCaWuH9xTCrMZEz0Jn02KAzRTC4YAHU0qWQAdgAGGaiqnezRRc31ImIJ-zdSbFr0evRJllaQKqpSEplaa-IosOAARWUEHgXx+MGWe10ByQACZ-KV0KQWEUAMIQKgNFBQaCPEDKKoAFWWiWa3zgAF96UA

**Comment by jaredly** [comment]
my preference would be
```
Parent.Service.make_blocking(path, (request, _body) => {
  callback(dbd, request)
});
```
fwiw

**Comment by IwanKaramazow** [comment]
The callback is currently a special "printing pattern", that results in that kind of code. The idea is to make it visually very clear that you're dealing with a callback as the last argument.
We could optimize it even further though for certain cases, if someone has ideas?

**Comment by hcarty** [comment]
Ah, I see.  Thanks all!  Since this is deliberate, unless there another reason to keep the issue open then I'm ok with closing this.

**Comment by IwanKaramazow** [comment]
Ok, feel free to ping me if you have any problems with this.
