### ISSUE TITLE
Bigarray syntax does not refmt cleanly

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#2038]
The following fails with a syntax error:
```
echo "a.{1, 2}" | refmt --parse=ml | refmt
```
with an intermediate output of `a.{1 2};`.

**Comment by hcarty** [comment]
Unfortunately the work-around of calling the `Bigarray.Array*.get` function(s) directly doesn't work properly either as (for example) `Bigarray.Array2.get(a, 1, 2)` is refmt'd to `a.{1 2}`.

**Comment by IwanKaramazow** [comment]
I'm looking at it as a type.

**Comment by hcarty** [comment]
Thank you!
