### ISSUE TITLE
the value of_list can't be found in array

### ISSUE THREAD

**Issue by jenyckee** [facebook/reason#2046]
I'm trying to convert a list to an array but get the following error: 

`The value of_list can't be found in Array   `

**Comment by bsansouci** [comment]
Hey, this function should be part of `Pervasives` the stdlib. Did you `open` anything that could shadow the module `Array` like `open Belt;`?

**Comment by IwanKaramazow** [comment]
Can you show us the full code?

**Comment by IwanKaramazow** [comment]
@jenyckee feel free to ping me on Discord if you still have the problem. Gonna close this one in the mean time.

**Comment by wegry** [comment]
@jenyckee @bsansouci maybe you mean https://bucklescript.github.io/bucklescript/api/Belt_Array.html?

**Comment by IwanKaramazow** [comment]
@jenyckee the correct solution with Belt is
```
let a = Belt.List.toArray([1, 2, 3]);
Js.log(a);
```
https://reasonml.github.io/try?rrjsx=true&reason=DYUwLgBAhhC8ECETDAOgDIEsDOawHsBBAJ2KgE8AKAbQEYAaCAJkYGYBdASgG4AoXgFLZUwfAHNKUHryA

See https://bucklescript.github.io/bucklescript/api/Belt_List.html for documentation
