### ISSUE TITLE
Support `type asd = ~a:bool=? => int;`

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#2056]
Right now you need to wrap in parens: `type asd = (~a:bool=?) => int;`

Dunno what conflict this has

**Comment by jaredly** [comment]
tbh I like requiring parens there. `type asd = ~a:bool=? => int;` is hard for me to visually parse

**Comment by chenglou** [comment]
We can still format to the latter; just that this currently throws a parser error and it's hard to figure out why

**Comment by jaredly** [comment]
lol most parser errors are hard to figure out why atm

**Comment by chenglou** [comment]
Merged the diff; I understand that we don't want to support this, and tbh I won't document this. It's just one of the several places where we relax the parser (e.g. for semicolon and switch braces too) for now. If we can't have great error messages here, might as well have good recovery first. We can remove this feature later.

**Comment by jordwalke** [comment]
We should make notes in the parser which rules are not important to keep around, so that one day when a conflict comes up with a more important feature, we know we can easily delete it.
