### ISSUE TITLE
Bug with named parameters in 3.3.0

### ISSUE THREAD

**Issue by andreypopp** [facebook/reason#2070]
Named parameters reformatted incorrectly:
```
% echo 'f(~commit=!build)' | esy refmt
f(~commit=~!build);
```

**Comment by anmonteiro** [comment]
This is most likely my fault, and introduced in #1945 

I’ll have a look soon; this is now highest on my list

**Comment by anmonteiro** [comment]
@andreypopp fix submitted in https://github.com/facebook/reason/pull/2071
