### ISSUE TITLE
Rename reason

### ISSUE THREAD

**Issue by ondrejsevcik** [facebook/reason#2101]
Hello, I have a few complaints regarding `Reason` language name. 

It's generally known that naming things is hard, but if you create a new programming language that's supposed to be popular one day, you don't name it with one of the most popular words in English. It makes searching for any kind of topic impossible, whether it's Google, StackOverflow or any other search engine.

It also seems that there are two official names used interchangeably  `Reason` and `ReasonML`. Even this repo is called reason, but the website is reasonml.github.io. What is the official name?

Maybe it's not a bad idea to start thinking about the new name before reason popularity explodes (it's also possible that it's too late). 

Anyway, although I don't like the name, I really like the idea of Reason and all the effort you put into it. Huge thanks for that!

**Comment by schinns** [comment]
Those are some good points. Although, I am not convinced Reason's name will cause so much confusion and difficulty in indexing topics. Words like _go_ and _rust_ are as common words as _reason_, yet I don't know that Go And Rust communities are suffering from this issue. 

I agree with you that some of these can be an issue, but I don't know that it's worthwhile changing Reason's name at this point.

**Comment by ubsan** [comment]
@schinns I think the thing people in the go and rust communities do is postfix with "lang"; "ML" can serve much the same purpose for Reason. Perhaps, switching most of the branding over to "ReasonML" would be good?

**Comment by jordwalke** [comment]
Thank you for the feedback. We don't have plans to rename, but we will follow the pattern that we have used in the React community. We talk about "React", landing pages just say "React", but when we want SEO we use ReactJS.
Feel free to continue to discuss here even after the issue is closed.
