### ISSUE TITLE
Replacing |. with -> gives compile error when using underscore

### ISSUE THREAD

**Issue by jdeisenberg** [facebook/reason#2117]
With `bsb -version` 4.0.3, this code works:
```
let doStuff = (a: int, b: int, c: int): int => {
  a + 2 * b + 3 * c;
};

let test1 = 5 |. doStuff(3, _, 7);
Js.log2("Test1:", test1);
```
but this gives a compile error:
```
let test2 = 5 -> doStuff(3, _, 7);
Js.log2("Test2:", test2);
```
The error is:
```
  We've found a bug for you!
  /home/david/testor/src/Demo.re 9:13-24
  
   7 │ Js.log2("Test1:", test1);
   8 │ 
   9 │ let test2 = 5 -> doStuff(3, _, 7);
  10 │ Js.log2("Test2:", test2);
  11 │ 
  
  This function has type (int, int) => int
  It only accepts 2 arguments; here, it's called with more.
```
(The `5 -> doStuff` is highlighted)

Note: Even when the `_` is in the first position, the same error occurs. Getting rid of the underscore fixes the problem.

**Comment by IwanKaramazow** [comment]
@jdeisenberg thanks for the bug report, I'm investigating.

Hmm
```
let test1 = 5 |. doStuff(3, _, 7);
let test2 = 5->doStuff(3, _, 7);
```
is parsed as
```
let test1 = 5 |. (__x => doStuff(3, __x, 7));
let test2  = (__x) => (5 |. doStuff)(3, __x);
```
@anmonteiro this is a side-effect of `5->doStuff(3, _, 7);` being parsed as `(5->doStuff)(3, _, 7);`.
What do you think? Do we modify `process_underscore_application`?
