### ISSUE TITLE
Refmt printer error when running on a large codebase

### ISSUE THREAD

**Issue by thangngoc89** [facebook/reason#2118]
I ran refmt over my repo and here are some bugs I found (which totally prevent me from using refmt@3.3.2)

1. 

```
          <span className="EditorNav__button--saveIndicator ">
            (
                (switch (saveStatus) {
                | Pristine => ""
                | Saved => "Saved"
                | Saving => "Saving"
                | Unsaved => "Unsaved"
                })
              ->str
            )
          </span>
```

Get formatted into this

```
<span className="EditorNav__button--saveIndicator ">
            switch (saveStatus) {
            | Pristine => ""
            | Saved => "Saved"
            | Saving => "Saving"
            | Unsaved => "Unsaved"
            }
            ->str
          </span>
```

2. 

```
blocks
  ->(blocks => {"blocks": blocks})
```

to 

```
blocks
  ->blocks => {"blocks": blocks}
```

3. 

```
<title> ((state.title == "" ? "untitled" : state.title)->str) </title>
```

to 

```
<title> state.title == "" ? "untitled" : state.title->str </title>
```

4. 

Refmt doesn't understand this (the self.send part)

```
ReasonReact.Router.watchUrl(url =>
        Route.urlToRoute(url)->ChangeView->self.send
      );
```

Changed it into this as a work around

```
ReasonReact.Router.watchUrl(url =>
        Route.urlToRoute(url)->ChangeView->send
      );
```

**Comment by IwanKaramazow** [comment]
Thanks for the bug report, there's already a PR open with fixes, we're working on it.

**Comment by cknitt** [comment]
I ran into similar issues, e.g.

```reason
let twitterUrl = Social.profiles |. Map.String.getExn("twitter") |. (p => p.Social.url);
```

becomes

```reason
let twitterUrl = Social.profiles->(Map.String.getExn("twitter"))->p => p.Social.url;
```

Also, there are many cases where superfluous `()` are added, e.g.

```reason
locale->(Js.String.substring(~from=0, ~to_=2))
```

or

```reason
db
->(version(1))
->(stores(Js.Dict.fromList([("installation", ""), ("settings", ""), ("incidents", "incidentId")])))
```

or

```reason
        LicenseList.licenses
        ->(
            mapListToReactElements(item =>
              <div key=item.name>
                /* ... */
              </div>
            )
          )
```

**Comment by anmonteiro** [comment]
@cknitt My open PR (#2111) fixes your issues.

Furthermore, the parens are not superfluous. `->` has different precedence from `|.`.

So these are different:

```reason
locale->(Js.String.substring(~from=0, ~to_=2))


/* these are the same */ 
locale->Js.String.substring(~from=0, ~to_=2)
(locale->Js.String.substring)(~from=0, ~to_=2)

```

**Comment by jaredly** [comment]
Wait, so
`locale |. Js.String.substring(~from=0, ~to_=2)` (which is equivalent to `Js.String.substring(locale, ~from=0, ~to_=2)`
gets refmt'd to
`locale->(Js.String.substring(~from=0, ~to_=2))` (which is equivalent to `Js.String.substring(~from=0, ~to_=2, locale)`)?
That sounds like a bug.
I would expect `local |. Js.String.substring(~from=0, ~to_=2)` to be refmt'd to `locale->Js.String.substring(~from=0, ~to_=2)`.

**Comment by anmonteiro** [comment]
@jaredly sorry my example is misleading. it gets put as the first arg.

**Comment by cknitt** [comment]
My expectation would have been the same as @jaredly's.

I.e. I would have expected something like

```reason
a |. b(c) |. d;
```

to reformat to

```reason
a->b(c)->d;
```

but it reformats to

```reason
a->(b(c))->d;
```

which feels weird.

**Comment by IwanKaramazow** [comment]
The Reason fast pipe `->` is actually different than the `|.` infix operator from Bucklescript.
There's a range of things  `->` can do, that `|.` can't. For example precedence like `foo->bar##baz`.
You can think of `->` as an "access"-thing like the `.` in`foo.bar` or `##` in `foo##baz`.
If you write `a.b.c[0]`, everyone reads `(((a).b).c)[0]`.
`->` behaves exactly the same, `a->b->c[0]` is `((a->b)->c)[0]`.
`a->b(c)` is parsed as `(a->b)(c)`, after the bs ppx transform it'll be `(b(a))(c)`. Since Ocaml is a curried language this is actually the same as `b(a, c)`.
Because of the differences between `|.` as infix operator and `->` being "access"-like (think `.`), we can't just drop the parens when converting `|.` in `->`.  Reason operates on the ast level, we can't make any assumptions other than the ast we just parsed.
However, if you're compiling Reason with Bucklescript, you can drop the parens yourself safely. We don't have the same luxury on native.

**Comment by cknitt** [comment]
@IwanKaramazow Thanks for the explanation. I wasn't aware I could remove the superfluous `()` manually (and refmt would keep it that way). That is of course fine with me! Maybe this information could be added to the release notes / instructions for the migration script.

**Comment by IwanKaramazow** [comment]
All bugs have been fixed in master. Ping me if there are any new issues surfacing.
