### ISSUE TITLE
Refmt syntax error with fast-pipe into anonymous function

### ISSUE THREAD

**Issue by arnarthor** [facebook/reason#2127]
```ocaml
Belt.List.map([1, 2, 3], a => a + 1)->(sums => Js.log(sums));
```

Formats into 
```ocaml
Belt.List.map([1, 2, 3], a => a + 1)->sums => Js.log(sums);
```

Using this with the old fast-pipe syntax was fine before the update
```ocaml
Belt.List.map([1, 2, 3], a => a + 1) |. sums => Js.log(sums);
```

We used this pretty widely in our codebase without any problems

Which causes a syntax error.
/cc @IwanKaramazow

**Comment by anmonteiro** [comment]
This has been fixed in https://github.com/facebook/reason/pull/2111

**Comment by arnarthor** [comment]
Great, thanks! I tried looking through the issues but couldn't find any report.

**Comment by anmonteiro** [comment]
it was #2118 for reference
