### ISSUE TITLE
Explicit error for let after =>

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#2135]
It would be nice to have an explicit error for code like this contrived example:
```reason
let f = x =>
  /* This code is fine */
  switch (x) {
  | 0 => 1
  | 1 => 2
  | _ => assert(false)
  };
```
and then we come back later to refactor and accidentally introduce an error while editing:
```reason
let f = x =>
  /* Let's say we refactored and added this `let` */
  let y = x + 1;
  switch (y) {
  | 0 => 1
  | 1 => 2
  | _ => assert(false)
  };
```
This error can come up pretty easily since `refmt` eliminates curly braces around value definitions when they aren't syntactically necessary, as in the first example.

EDIT: Clarified some wording.

**Comment by anmonteiro** [comment]
related to #1813

**Comment by anmonteiro** [comment]
refmt preserves braces now. closing.
