### ISSUE TITLE
Signature of array accessor depends on whether the Belt module is open

### ISSUE THREAD

**Issue by cknitt** [facebook/reason#2139]
This came as a bit of a surprise:

```reason
let x = [|1|];

/* Compiles - accessor returns int */
x[0] + 1;

open Belt;

/* Compile error - accessor returns option(int) */
x[0] + 1;
```

**Comment by cknitt** [comment]
I am all for checked array access, too, and therefore actually prefer Belt's version. :wink: Still, this just caught me completely by surprise, as in most languages it would not be possible to override the `[]` operator in such a way.

But I guess this is just my lack of OCaml knowledge. 😕 It seems the `[]` array accessor is just sugar for `Array.get`, and that is overwritten by `Belt.Array.get`. Behavior is exactly the same in OCaml syntax (`x.(0)`). So I guess this is not something that will/can be changed in Reason.

**Comment by jaredly** [comment]
Yup, that certainly can be surprising :) but yeah, we're unlikely to change that behavior. If you want to find a nice place to point it out in the docs, that would be great! https://github.com/reasonml/reasonml.github.io
