### ISSUE TITLE
Formatting function with typed labelled argument twice gives syntax error.

### ISSUE THREAD

**Issue by cristianoc** [facebook/reason#2141]
Source:
```reason
let testCallNamedArgs = (foo: ((~a: int, ~b: int) => int), a, b) => foo(~a, ~b);
```

After one format:
```reason
let testCallNamedArgs = (foo: (~a: int, ~b: int) => int, a, b) =>
  foo(~a, ~b);
```
which then gives
```
Error: Syntax error: Labels are not allowed inside a tuple not expected.
```
Also, the prasing "not allowed" and "not expected" in the error message.

**Comment by jordwalke** [comment]
I think this issue is in the parser. It should accept the form:

```
let testCallNamedArgs = (foo: (~a: int, ~b: int) => int, a, b) =>
  foo(~a, ~b);
```
Without parens around the function type `(~a:int, ~b:int) => int`

**Comment by IwanKaramazow** [comment]
I encountered a similar issue in the past, I thought that the `ES6FUN` (lexer massage) doesn't get injected for types. Might be wrong though.

**Comment by IwanKaramazow** [comment]
@cristianoc sorry for the delay, master keeps the parens after formatting now. Will now work on the parser and drop the requirement of parens.
