### ISSUE TITLE
reason version on opam

### ISSUE THREAD

**Issue by drjdn** [facebook/reason#2154]
The current version of reason on opam is listed as 3.2.0.  When I install it via opam and look at the installed package list it also indicates that I'm running v3.2.0.  However, when I type:

```bash
# refmt --version
Reason 3.0.0 @ bee43b0
```
Indicating to me that the actual version being used by reason installed via opam is version 3.0.0.  Sorry if I'm misunderstanding how reason works but I'm assuming that dune, rtop etc. are using refmt directly.

Thanks,
Jason

**Comment by jordwalke** [comment]
Version 3.3 correctly updated the version. When we push 3.3.x to opam, it will be fixed. Thanks for reporting, it's a known temporary issue.
