### ISSUE TITLE
refmt generates a syntax error 

### ISSUE THREAD

**Issue by bloodyowl** [facebook/reason#2156]
```reason
<div>
(url
->a(b, _)
)
</div>
```

gets refmt'd to

```reason
<div> url->a(b, _) </div>;
```

which is a syntax error when you pipe to refmt (`bsrefmt file.re | bsrefmt`) for some reason:

```
File "", line 1, characters 16-17:
Error: 1349: <syntax error>(
```

**Comment by IwanKaramazow** [comment]
@bloodyowl this is fixed in master, sorry for the trouble. Ping me if you have any more questions.
