### ISSUE TITLE
feature request: binary pattern match shorthand 

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#2161]
moved from https://github.com/BuckleScript/bucklescript/issues/3020

e.g. `x matches {1 | 2 | 3}`

Here is the function I had written when I realized I would like a syntax shorthand like this:
```
let isIntegral: float=>bool = f => f |. modf |. fun
| (0.0, _) => true
| _ => false;
```

Which could be rewritten as:
```
let isIntegral: float=>bool = f => modf(f) matches { (0.0, _) };
```

**Comment by OvermindDL1** [comment]
Plus if you want to parse complex binaries then things like https://github.com/nojb/bitstring-ppx should probably be used and refined instead (it really needs an update, I wonder if there are any forks...).

**Comment by IwanKaramazow** [comment]
Closing this one for now, the added benefits don't outweigh the costs.
