### ISSUE TITLE
[refmt request] local open can be a bit agressive

### ISSUE THREAD

**Issue by texastoland** [facebook/reason#2164]
I'm currently working around it with `open!`.

Expected:

```
let (--) = Belt.Array.range;
let range2D = (~w, ~h) => {
  open Array.Infix;
  0 -- (h - 1) <#> (i => i * w + 1 -- (i + 1) * w);
};
```

Actual:

```
let (--) = Belt.Array.range;
let range2D = (~w, ~h) =>
  Array.Infix.(0 -- (h - 1) <#> (i => i * w + 1 -- (i + 1) * w));
```

**Comment by jordwalke** [comment]
See [my old PR](https://github.com/facebook/reason/pull/1826).

I think to add any more styling features like this we need to clean up stylistic attributes storage (as that PR demonstrates). Someone could rebase that part of the PR on top of master to get started.

**Comment by texastoland** [comment]
I assumed it must be a duplicate. Feel free to close. On an aside I find it fascinating that `refmt` simplifies code like solving an algebra problem. In practice it acts like a tutor. I wish there were also a "Prettier mode" where it promised to not change anything but punctuation. I didn't want to open an issue for it because I assume it's a philosophical decision and `refmt` should "just work".

**Comment by jordwalke** [comment]
I also would like two modes, but it's a tradeoff in having some consistency in the ecosystem. We should keep this issue open because I'm not sure there is another issue open (just my PR).
