### ISSUE TITLE
Bad type error location for jsx

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#2165]
The location of type errors are completely missing from this Reason example (I haven't tried a Reason React example - this is on the raw Reason syntax without bs-ppx)

```reason
module AdgroupStore = {
  let get = adgroupID => "THIS IS AN ADGROUP";
};

module PageStore = {
  let get = pageID => "THIS IS A PAGE";
};


let containerize = (~pageID, ~adgroupID, component) => {
  component(~page=PageStore.get(pageID), ~adgroup=AdgroupStore.get(adgroupID), ~children=[], ());
};

module MyComponent = {
  let createElement = (~page, ~adgroup, ~children, ()) => {
    ();
    ();
  };
  let createElement = containerize(createElement);
};


let renderThis = <MyComponent adgroupID="34" pageID="99"/>;

```

There's no location whatsoever on the type error for some reason.

**Comment by IwanKaramazow** [comment]
I'm looking into this together with https://github.com/facebook/reason/pull/2162.

**Comment by jordwalke** [comment]
It's even in the compiler errors.

**Comment by thangngoc89** [comment]
So this error is discovered first in Sketch. In parser reports the JSX position at `[ (0, -1), (0, -1) ]`

**Comment by IwanKaramazow** [comment]
There's a deeper problem, still investigating.
Fixing the `MyComponent` Pexp_ident location alone doesn't fix it in all cases.
