### ISSUE TITLE
[Doc] Readme refmt installation link

### ISSUE THREAD

**Issue by exced** [facebook/reason#2170]
Hi there,
It seems the refmt installation link is broken in the Readme

### Reproduction link
[https://github.com/facebook/reason/](https://github.com/facebook/reason)
[https://reasonml.github.io/docs/en/global-installation.html](https://reasonml.github.io/docs/en/global-installation.html)

### What is expected?
Refmt installation page opens

### What is actually happening?
Page not found

**Comment by chenglou** [comment]
@exced I'll assume you accidentally re-opened this!
