### ISSUE TITLE
Playground breaking with any ReasonReact usage

### ISSUE THREAD

**Issue by grsabreu** [facebook/reason#2179]
https://reasonml.github.io/try.html?rrjsx=true&reason=DYUwLgBATiDOEF4BQEIB4AmBLAbhA9AHwDcSSAUrAHTAD2A5gBQywCUpQA

![image](https://user-images.githubusercontent.com/1283200/45400020-c380b180-b620-11e8-9cd3-7a330c6b471a.png)

**Comment by chenglou** [comment]
Thanks
