### ISSUE TITLE
Documentation error in filter() type annotation

### ISSUE THREAD

**Issue by ashokkbhaskar** [facebook/reason#2196]
On the documentation page for "Fast Pipe," under heading "JS Method Chaining," `filter()` has this type annotation:

    [@bs.send] external filter : (array('a), 'a => 'b) => array('b) = "";

I believe this should be:

    [@bs.send] external filter : (array('a), 'a => bool) => array('a) = "";

**Comment by anmonteiro** [comment]
Moved to https://github.com/reasonml/reasonml.github.io/issues/590
