### ISSUE TITLE
Confusing error message for wrong named arg syntax

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#2202]
I got stuck on this for a couple of minutes wondering what the error meant:
```reason
drawWithRotation(
        img: Belt.Map.String.getExn(assetMap, kind),
        ~pos=(x, y),
        ~width=fruitSize,
        ~height=fruitSize + 20,
        ~rot=r,
        env,
      ),
```
The error is on the 2nd line (or below, line 79)
```
  We've found a bug for you!
  /Users/benjamin/Desktop/fruit-ninja/src/index.re 79:14-51

  77 ┆ ({x, y, r, kind}) =>
  78 ┆   drawWithRotation(
  79 ┆     img: Belt.Map.String.getExn(assetMap, kind),
  80 ┆     ~pos=(x, y),
  81 ┆     ~width=fruitSize,

  This type constructor's parameter, `Belt.Map.String.getExn`, can't be found. Is it a typo?
```

The highlighted portion is `Belt.Map.String.getExn(assetMap, kind)` which got me thinking the function didn't exist, but it was just the `img: `.

**Comment by IwanKaramazow** [comment]
This is a bit unfortunate, we can't really do anything about this. It's actually valid syntax from a refmt point of view.

```reason
function(foo: string, ~a=2, ~b=3);
```
In the above function application the first argument `foo` is an expression, that is an explicit `string`...
In theory `img` could have an explicit type that is constructed by the type `getExn(assetMap, kind)` which lives in the `Belt.Map.String` module...

The error message is actually quite accurate here, `Belt.Map.String.getExn` isn't a type constructor and there's a typo 😬I totally get the confusion though… I'm afraid that there isn't much we can do in this case. Feel free to reopen/ping me if you have other suggestions/a solution.
