### ISSUE TITLE
Consuming refmt printers from a native app

### ISSUE THREAD

**Issue by jchavarri** [facebook/reason#2214]
I'm trying to make use of the `reason` package in a native Reason app, so I can use refmt printers to produce valid output OCaml or Reason code by providing a syntax tree (I tried to do this in BuckleScript first, but I have not been able to because making ocaml-migrate-parsetree work with BuckleScript [doesn't seem to be trivial](https://reasonml.chat/t/ocaml-migrate-parsetree-for-bucklescript/1034/2)).

I've used https://github.com/esy-ocaml/hello-reason as a template, and I was trying to add `reason` as a lib to the dune config file:

```
(libraries reason lambda-term lwt))
```
but the compiler errors because it is not able to find the `Reason` module.

Is this something that could be done without vendoring the `refmt` folder in my project?

Thanks!

**Comment by IwanKaramazow** [comment]
Have you seen the https://github.com/facebook/reason#native-api section?

**Comment by jchavarri** [comment]
Ah, `Reason_toolchain`! I hadn't seen that section, thanks @IwanKaramazow  😄
