### ISSUE TITLE
Windows - AppVeyor: Fix (enable) tests on Windows

### ISSUE THREAD

**Issue by bryphe** [facebook/reason#2224]
There are several blockers to getting the tests running (next step after #2209 - which gets `reason` building on a Windows appveyor environment via `esy`!).

The first issue is that they are bash scripts, which are not traditionally friendly on Windows, since there is no bash environment by default - but we can leverage esy's environment via `esy b`.

Running the jsxPpxTests via `esy b ./miscTests/jsxPpxTest.sh` gives:
```
E:\reason-core [master +2 ~8 -0 !]> esy b ./miscTests/jsxPpxTest.sh
Testing reactjs @JSX ppx...
V2 behavior 1: error in output after the ppx ran. Here's the content:
'.' is not recognized as an internal or external command,
operable program or batch file.
File "miscTests/reactjs_jsx_ppx_tests/test1.re", line 1:
Error: Error while running external preprocessor
Command line: ./_build/install/default/bin/refmt --print binary "miscTests/reactjs_jsx_ppx_tests/test1.re" > C:\Users\bryph\AppData\Roaming\npm\node_modules\esy\node_modules\esy-bash\.cygwin\tmp\ocamlppb888c8
```

Need to track down where that error is coming from - it seems like a path issue.

Likewise, we see errors running the format tests:
```
Idempotent Test: ./class.re
refmt: FILENAMES... arguments: no
       `/cygdrive/e/reason-core/formatTest/oprintTests/actual_output/./class.re'
       file
Usage: refmt [OPTION]... [FILENAMES]...
Try `refmt --help' for more information.
refmt: FILENAMES... arguments: no
       `/cygdrive/e/reason-core/formatTest/oprintTests/intf_output/./class.re'
       file
Usage: refmt [OPTION]... [FILENAMES]...
```

I believe the issues in both cases are that the tools, like `refmt`, are built as __native windows executables__ - but because we are running the tests in a bash environment (which is cygwin, on Windows), we get some bash/cygwin-style paths sneaking in. We'd need to detect that we are on a Windows platform (ie, via `uname`), and convert the paths to Windows-style paths (via `cygpath -w`) prior to passing them into windows executables. Would need some more investigation though.

**Comment by anmonteiro** [comment]
We're now running tests on windows via Azure Pipelines.
