### ISSUE TITLE
Atom Reason Round Two.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#224]
Here's the next round of features:
- [x] Work without Nuclide. I already got the diagnostics to work with regular linter, but we need type hints support without Nuclide, and  a menu item/action/shortcut for code formatting. Should also rewrite MerlinService.js in Reason itself.
- [x] Formatting type hints (I think they should be 80 chars max if it's possible).
- [x] ~~Locate command that works with or without Hyperclick.~~ (Edit: chenglou was here. We agreed offline that dependency on hyperclick is fine).
- [x] Merlin proxy plugin for Atom. _The_ Atom plugin that is installed via Atom packages GUI. All this does is load the right version of the Atom Reason plugin by `require(execSync("opam config var share") + "/reason/AtomReason/main.js")`. What this does is bypasses the Atom plugin manager to guarantee that your editor plugin is always in sync with whatever version of Reason your global switch (or local project) uses.

**Comment by chenglou** [comment]
Long done
