### ISSUE TITLE
For loop confusing parsing error

### ISSUE THREAD

**Issue by ryyppy** [facebook/reason#2243]
Given following statement:

```ocaml
for (i in 0 to 10) {
  /* ... */
}
```

Does cause a SYNTAX ERROR. This is caused by the missing semicolon in the end of the curly braces scope. Ideally refmt should be clever enough to auto-insert the semicolon.

Not sure if this is hard to fix, but it took me quite a while to bisect the error.

**Comment by anmonteiro** [comment]
In the absence of a better repro case, reerror (#2480) fixes the reported minimal case.
