### ISSUE TITLE
refmt removes needed {}

### ISSUE THREAD

**Issue by j-m-hoffmann** [facebook/reason#2248]
The code is

`<div style=Styles.hintBox>`
`  {`
`    hints`
`    ->Belt.List.toArray`
`    ->Belt.Array.map(hint => <Hint hint />)`
`    ->ReasonReact.array`
`  }`
`</div>`

when i invoke refmt via reason-language-server in vim refmt gives me:

`<div style=Styles.hintBox>`
`  hints`
`  ->Belt.List.toArray`
`  ->Belt.Array.map(hint => <Hint hint />)`
`  ->ReasonReact.array`
`</div>`

and an error. Same in vscode. Does not happen in intellij. invoked refmt via cli, gave the wrong output as well.

**Comment by j-m-hoffmann** [comment]
running on linux, upgraded reason-cli from 3.3.2 to 3.3.3 and bs-platform to 4.0.6, same result.

**Comment by anmonteiro** [comment]
This is fixed in 3.3.7.

**Comment by j-m-hoffmann** [comment]
okay thanks. Do you have a rough when it will be released?

**Comment by j-m-hoffmann** [comment]
reason-language-server 1.2.1 does it correctly, upgraded from 1.1.1

**Comment by j-m-hoffmann** [comment]
or can i compile from source with ocaml 4.06.1?

**Comment by j-m-hoffmann** [comment]
@anmonteiro Thank you
