### ISSUE TITLE
reason oprinter broken for `not_`

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#2273]
moved from https://github.com/BuckleScript/bucklescript/issues/3094 (cc @wyze)

This was working correctly in bs-platform 4.0.5, but started running into this when I upgraded to 4.0.6.

**Source**

```ocaml
type ex;
[@bs.val] external expect: Dom.element => ex = "";
[@bs.get] external not_: ex => ex = "not";
```

**Command**

```shell
$ bsc -bs-re-out lib/bs/src/File.cmi > src/File.rei
```

**Output**

```ocaml
type ex;
[@bs.val] external expect: Dom.element => ex = "";
[@bs.get] external not__: ex => ex = "not";
```

**Error**

```shell
[2/3] Building src/JestDom.cmj

  We've found a bug for you!
  /Users/neil/Projects/personal/bs-jest-dom/src/JestDom.re

  The implementation src/JestDom.mlast
       does not match the interface src/jestDom.cmi:
       The value `not__' is required but not provided

error Command failed with exit code 2.
```

**Expected**

```ocaml
type ex;
[@bs.val] external expect: Dom.element => ex = "";
[@bs.get] external not_: ex => ex = "not";
```

**Comment by anmonteiro** [comment]
I can't repro this. Could you provide instructions on how to?

**Comment by bobzhang** [comment]
I will see if there is an easy way to reproduce it, note that oprinter for reason used by bucklescript is upstreamed from reason repo

**Comment by wezm** [comment]
We ran into this issue as well. The code is a test that uses [bs-enzyme](https://github.com/rhysforyou/bs-enzyme):

```reason
open! Expect;

let component =
  Enzyme.shallow(
    <CommitmentTypeSelect onChange availableDispatches dispatchContractSelection />,
  );

expect(Enzyme.Shallow.html(component)) |> not_ |> toContainString("Required");
```

When formatting with `refmt` the last line gets turned into the following which is wrong and does not compile:

```reason
expect(Enzyme.Shallow.html(component)) |> (!) |> toContainString("Required");
```

**Comment by IwanKaramazow** [comment]
@wezm what version of Bucklescript are you using?

**Comment by wezm** [comment]
@IwanKaramazow BuckleScript 3.1.5 (Using OCaml4.02.3+BS ) (bs-platform 4.0.6)

**Comment by IwanKaramazow** [comment]
@wezm do you get the same on bs-platform 4.0.7?

**Comment by bobzhang** [comment]
Seems to be fixed in next version, will double check

**Comment by wezm** [comment]
> do you get the same on bs-platform 4.0.7

Sorry I haven't been able to try this as our code needs some changes to be 4.0.7 compatible and I can't tackle that right now. Should be able to have a look later in the week.

**Comment by bobzhang** [comment]
I can confirm this is fixed in bucklescript trunk (upstreamed), thanks
