### ISSUE TITLE
[refmt] Block formatting in JSX

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/reason#2293]
Input:

```reason
<div>
  {
    let left = (limit - value->Js.String.length)->Int.toString;
    {j|$left characters left|j}->React.string;
  }
</div>
```

Output:

```reason
<div>
  {let left = (limit - value->Js.String.length)->Int.toString
   {j|$left characters left|j}->React.string}
</div>
```

**Comment by MoOx** [comment]
Note that the initial snippet was perfectly working with bs-platform 4.0.6

**Comment by IwanKaramazow** [comment]
I'm looking into the issue.

**Comment by IwanKaramazow** [comment]
@anmonteiro would you mind taking this one?
I came to the following solution, but I'm not sure if this is the right solution
![image](https://user-images.githubusercontent.com/10634678/50382026-e5fd7e80-0695-11e9-9fa2-8ef5aac59f6a.png)

**Comment by anmonteiro** [comment]
@IwanKaramazow I just tried it locally. That does indeed seem like the right fix here.

**Comment by bloodyowl** [comment]
is there any progress on this?

**Comment by osener** [comment]
Is there a workaround for this before that I can use we get a bs-platform release that includes the fix?

**Comment by IwanKaramazow** [comment]
PR with fix is up at https://github.com/facebook/reason/pull/2319.
Sorry for the delay!

**Comment by osener** [comment]
Fantastic, thank you @IwanKaramazow!
