### ISSUE TITLE
Invalid output with JSX: missing closing bracket

### ISSUE THREAD

**Issue by jchavarri** [facebook/reason#2297]
Valid input: `let t = <view style={Style.make()}> ...items </view>`

Invalid output: `let t = <view style={Style.make()> ...items </view>;` 

Note the missing closing bracket after `Style.make()`.

Tested in `v 3.3.7,  @ 43efc14`.
Tested as well with `reason-language-server` v 1.4.1, it produces the same invalid output.

**Comment by IwanKaramazow** [comment]
This has been fixed in https://github.com/facebook/reason/pull/2292/.

**Comment by jchavarri** [comment]
Thanks @IwanKaramazow !! 🙂
