### ISSUE TITLE
Underscore in labeled argument has to be replicated at call site

### ISSUE THREAD

**Issue by habibalamin** [facebook/reason#2299]
The Reason compiler emits an `unused variable` warning for labeled arguments, but in some cases, an API consumer is expecting the function to take a particular labeled argument, even though the function ignores it.

I think labeled arguments should be able to be prefixed with an underscore without breaking call sites.

```reason
let test = (~arg) => { /* ignore arg for whatever reason */ }
/* This should be allowed to be:
    let test = (~_arg) => { /* ignore _arg for whatever reason */ }
    without breaking the line below
*/

/* […] */

test(~arg="whatever")
```

**Comment by johnhaley81** [comment]
Just a note that you can do:

```reason
let test = (~arg as _arg) => ();
```

Which doesn't require any magic. :)

**Comment by habibalamin** [comment]
I will try this later. Thanks.

**Comment by habibalamin** [comment]
That works great, thanks.

For anyone else reading, you can also do this for _optional_ labeled arguments and just use an underscore on its own as the alias, and even do this for _multiple_ arguments (shadowing the singular underscore in a sense) without any further warnings from the compiler:

```reason
let test = (~abc as _=?, ~def as _=?, ()) => 1;
test(~abc=1) : (~def: '_a=?, unit) => int = <fun>
test(~abc=1, ()) : int = 1
```

You can see the difference between valid and invalid forms below:

```diff
-let test = (~abc=? as _, ~def=? as _, ()) => 1;
+let test = (~abc as _=?, ~def as _=?, ()) => 1;
```

**Comment by habibalamin** [comment]
This is a satisfactory ‘workaround’ for me, so I'm going to close this issue.
