### ISSUE TITLE
[NuclideReason] File highlight defaults to "Regular Expression (babel)" instead of reason

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#234]

**Comment by kassens** [comment]
Who has regex files anyway? Maybe we can just remove the `*.re` suffix from the regex syntax (assuming that's what's causing this)?

**Comment by chenglou** [comment]
> Should take 5mins

Man, software engineering...

It's most likely caused by [this](https://github.com/gandm/language-babel/blob/f133b69d61770ac8278131b0c5226823a5ca3dc0/grammars/Babel%20Regex.json#L5). And I don't think atom has a way of specifying priority. I've disabled language-babel for now.

**Comment by kassens** [comment]
Opened gandm/language-babel#194 to see if they actually need the `re` extension.

**Comment by chenglou** [comment]
Awesome, closing!
