### ISSUE TITLE
Reason reserved words are not translated in type names coming from OCaml

### ISSUE THREAD

**Issue by hcarty** [facebook/reason#2341]
If you have an OCaml module which uses a Reason reserved word as a type name there is no way to access that type name from within Reason code.  For example, the `pub` type here couldn't be referenced from Reason:
```ocaml
type pub = { x : int }
```
For values, this is handled by adding a trailing `_` to the value's name.  We should have the same transformation for types.  And probably record fields, method names and anything else which could conflict if they're not translated yet.

**Comment by hcarty** [comment]
A summary of cases which should be handled:
```ocaml
(* Type names (supported with PR#2342) *)
module T = struct
  type pub = unit
end

(* Value names (already supported) *)
module V = struct
  let pub = ()
end

(* Record fields *)
module R = struct
  type r = { pub : int }
end

(* Class names *)
module C = struct
  class pub = object end
end

(* Object methods *)
module O = struct
  let o = object method pub = () end
end
```

**Comment by jordwalke** [comment]
Reopening because not every case is handled yet.

**Comment by hcarty** [comment]
Thank you @anmonteiro!
