### ISSUE TITLE
[refmt] Lexer fails on line comment, if it's the last line without a newline.

### ISSUE THREAD

**Issue by cristianoc** [facebook/reason#2350]
e.g. if this line is the entire file
```reason
// 34
```

```
refmt: internal error, uncaught exception:
       File "src/reason-parser/reason_lexer.mll", line 725, characters 6-12: Assertion failed
```

**Comment by IwanKaramazow** [comment]
What version/commit are you running?
I can't seem to reproduce this on master…

**Comment by IwanKaramazow** [comment]
Seems that the code doesn't explicitly handle EOF, submitted a PR that does exactly that in https://github.com/facebook/reason/pull/2353/files
