### ISSUE TITLE
Obscure "syntax error" when record key is reserved

### ISSUE THREAD

**Issue by iddan** [facebook/reason#2362]
When key is reserved an obscure syntax error is emitted.
Example:
https://reasonml.github.io/en/try?rrjsx=true&reason=C4TwDgpgBAhlC8UDeAoKUCQB7ARgKwgGNgAuKAZ2ACcUBfAbiA

**Comment by anmonteiro** [comment]
I suspect the playground is a bit outdated. I have personally worked on making this class of errors better. Here's how it looks in master:

```shell
$ ./_build/install/default/bin/refmt          
type a = {
        object: str
};
File "", line 2, characters 3-9:
Error: 766: object is a reserved keyword, it cannot be used as an identifier. Try `object_` or `_object` instead

```
