### ISSUE TITLE
refmt does not return error code

### ISSUE THREAD

**Issue by robz** [facebook/reason#2381]
src/README.md states:

> To add a Menhir error message, you first need to know the error code. To find the error code, you can run the following commands from the Reason project root:
> 
> ```
> make
> ./_build/install/default/bin/refmt --parse re foo.re

But after cloning this repo, running `esy install`, and then running  `refmt` on a file with an error does not return an error code:

```
$ _esy/default/build/install/default/bin/refmt --parse re ../hello-reason/bin/Hello.re
File "../hello-reason/bin/Hello.re", line 5, characters 12-14:
Error: File "../hello-reason/bin/Hello.re", line 5, characters 12-14:
       Error: Syntax error
$ _esy/default/build/install/default/bin/refmt --version
Reason 3.4.1 @ ea3fc2c
```

where "../hello-reason/bin/Hello.re" is

```
/* test comma syntax error */
let f = (x: option(int)) =>
  switch (x) {
  | None => 0,
  | Some(_) => 1
  };
```

An older version 3.3.3 returns this error code:

```
$ refmt --parse re ../hello-reason/bin/Hello.re
File "../hello-reason/bin/Hello.re", line 4, characters 13-14:
Error: 3773: <syntax error>
$ refmt --version
Reason 3.3.3 @ fefe5e4d
```

**Comment by jordwalke** [comment]
Great find, @robz.

@anmonteiro Do you think your new error catching fix has addressed this?

**Comment by anmonteiro** [comment]
This is not relevant anymore, as we're not using Menhir error codes since #2480
