### ISSUE TITLE
Fatal Error with bs 5.0.3 candidate

### ISSUE THREAD

**Issue by diligiant** [facebook/reason#2383]
The snippet below triggers `Fatal error: exception File "ast_external_process.ml", line 135, characters 13-19: Assertion failed` instead of an error message. Tested with [#740f0bf](https://github.com/BuckleScript/bucklescript/tree/740f0bfc98d310a10863b3fc0f8a5db211bf5e69)

```
module MiniHelmetJsCompat = {
  [@bs.module "react-helmet"][@react.component]
  external make: (~title: string=?) => React.element = "default";
};

[@react.component]
let make = (~title: string=?) => { <MiniHelmetJsCompat title /> };
```
Cc @bobzhang

**Comment by anmonteiro** [comment]
@rickyvetter isn't this fixed in the JSX PPX?

**Comment by diligiant** [comment]
@anmonteiro no, it's not. That's why @bobzhang asked me to open an issue here.

**Comment by anmonteiro** [comment]
So, I tried running this on master and:

1. there's no error
2. ast_external_process.ml seems to be a BuckleScript file: https://github.com/BuckleScript/bucklescript/blob/master/jscomp/syntax/ast_external_process.ml

**Comment by diligiant** [comment]
@anmonteiro You're right ; I've pulled latest commits (from early morning) and I now have the expected error message. 
[I know that's in bs but @bobzhang wanted me to report it here]
