### ISSUE TITLE
External keyword not working and only giving syntax error

### ISSUE THREAD

**Issue by MarcCoquand** [facebook/reason#2412]
When trying to use external keyword in a file like the following:
```
type request = {
    body: string,
    path: string,
    headers : Js.Dict.t(string),
    statusCode: int,
    method: string
    }


type response = {
    bodyString: option(string),
    bodyBuffer: option(Node.Buffer.t),
    headers: Js.Dict.t(string),
    statusCode: int,
    encoding: string,
    statusMessage: string
}

type application = request => response

[@bs.module "./rawCreateServer.js"] [@bs.val] external rawCreateServer : int => application => unit = "rawCreateServer"

```

you get a syntax error on the word external without any direction whatsoever. You can circumvent this for now by creating a new file and adding
```
[@bs.module "./rawCreateServer.js"] [@bs.val] external rawCreateServer : 'a => 'b => unit = "rawCreateServer"
```
and afterwards in the original file add the typings you want
```
type request = {
    body: string,
    path: string,
    headers : Js.Dict.t(string),
    statusCode: int,
    method: string
    }


type response = {
    bodyString: option(string),
    bodyBuffer: option(Node.Buffer.t),
    headers: Js.Dict.t(string),
    statusCode: int,
    encoding: string,
    statusMessage: string
}

let startServer = (port: int, app: application): unit =>
    UnsafeRaw.rawCreateServer(port,app)
```
but this does not feel correct at all.

**Comment by Schmavery** [comment]
As a starting point it seems to work better for me when I have semicolons at the end of the statements.
It also seems like method might be a keyword? When I replace it with `method_` [it seems to parse better](https://reasonml.github.io/try?rrjsx=true&reason=C4TwDgpgBAThCOBXCBnYUC8UDeAoKBUARgPYAmIAXFGjAJYB2A5gDT6FgCGwAFtbY1bsCPCJzIQYKKNQBSKAHQAROgGNgC4AAoBzAJRtCNYN0QoAwuQjVGwQ4QC2EXuQD6-YPWbCoAXwDcuEGgkLCoYCQMKNBYeEakFADKnoLUJGDAdJE6Kfr2BAkgAEKIAGalkmkZWQxaAHJWCiXlkpoGPqLikihyiirqmjleTO1GaKYWVjYMdj4QDKrkqcbD+cYTALKoKJxM1iuCuAHB4NCcYGAANmrcNZhhSKjoGAB8YSgRURCBuADaAAJERQOciIS7QABECgA9DBOAB3cxwbgQRKSABurQAVigIQBdKAAoEKdGcS4EiAAD2AkgYZNgCKRYhpaJgmJgMigtkwb3OVxumUiPKgiAYdGeUAhcMRyJZGMkEP8QA)
```reason
type request = {
    body: string,
    path: string,
    headers : Js.Dict.t(string),
    statusCode: int,
    method_: string
    };


type response = {
    bodyString: option(string),
    bodyBuffer: option(Node.Buffer.t),
    headers: Js.Dict.t(string),
    statusCode: int,
    encoding: string,
    statusMessage: string
};

type application = request => response;

[@bs.module "./rawCreateServer.js"] [@bs.val] external rawCreateServer : int => application => unit = "rawCreateServer";
```

**Comment by MarcCoquand** [comment]
Indeed, when manually adding ; the error seemed to resolve itself.

**Comment by jordwalke** [comment]
Note that the leniency in omitting semicolons is considered a *dev time* feature, that is not part of the official Reason concrete syntax. If you refmt your file in cases where we accept an omitted semicolon, the semicolons will be inserted for you. But in this case, we needed to do a better job of that dev-time assistance when it comes to the `external` keyword (thanks for the diff @anmonteiro - will merge it!)
