### ISSUE TITLE
Make ` = ""` optional in reason syntax

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#2422]
```reason
[@bs.obj]
external bsObjMake: (~comment: string=?, ~platform: string, unit) => _ = "";
```
it would be nice to just have
```reason
[@bs.obj]
external bsObjMake: (~comment: string=?, ~platform: string, unit) => _  ;
```

**Comment by baransu** [comment]
Would it behave the same for all external? With [@bs.obj] it makes sense to omit = „” but with other cases like actual bindings I have strong feelings about not using = „” at all. It’s one of the common bug sources in my team. Someone changes external fn name and runtime errors pops up :/

**Comment by bobzhang** [comment]
@baransu I agree with you that not using `= ""` in most cases except `bs.obj`. And we are going to warn users when seeing `=""`. For bs.obj, it has to be an empty string

**Comment by jordwalke** [comment]
I could also see this being useful if someone made a ppx plugin for automatically creating c bindings or bindings to other languages. Good first task as it's pretty easy.

**Comment by gabrielrumiranda** [comment]
can I take this ?
