### ISSUE TITLE
Why swift is Fruit flavoured OCaml

### ISSUE THREAD

**Issue by shineli-da** [facebook/reason#2441]
The official doc says: 
Swift. Fruit-flavored OCaml! https://reasonml.github.io/docs/en/what-and-why

I want to know why before I can quote it.

**Comment by hcarty** [comment]
I didn't write the words, but I'd guess that it's because Swift was developed at Apple (named after a fruit) and is stylistically similar to Reason/OCaml in many ways.

**Comment by ubsan** [comment]
I don't know why that would be -- Swift is a language which is not very similar to OCaml at all, even if it has some OCaml flavoring with the type inference and discriminated unions

**Comment by yawaramin** [comment]
@ubsan I guess we consider it a spiritual descendent of OCaml, by way of Scala.

I think this issue can be closed, @shineli-da ?

**Comment by shineli-da** [comment]
Yeah sure. Thank you all.

**Comment by jordwalke** [comment]
Or maybe it's Camel flavored fruit?
