### ISSUE TITLE
Fragment inside of JSX prop reformatted to invalid code

### ISSUE THREAD

**Issue by cknitt** [facebook/reason#2448]
`refmt` formats

```reason
<A someProp={ <> {React.string("Hello")} </> } />;
```

to

```reason
<A someProp=<> {React.string("Hello")} </> />;
```

which is invalid code (cannot be parsed anymore).

The problem only occurs for fragments, the following is formatted just fine:

```reason
<A someProp={ <div> {React.string("Hello")} </div> } />;
```

**Comment by cknitt** [comment]
(Tested in both 3.4.2 and 3.5.0.)

**Comment by baransu** [comment]
The current workaround is using `<React.Fragment/>` which if formatted properly.

**Comment by cknitt** [comment]
Yes, thanks, that would work. Or assign the fragment to a variable beforehand and pass that variable as the prop.

But this should really be fixed in the printer.

**Comment by anmonteiro** [comment]
Fixed in https://github.com/facebook/reason/pull/2463
