### ISSUE TITLE
Support new monadic let* and applicative let+ (ocaml 4.08)

### ISSUE THREAD

**Issue by entropitor** [facebook/reason#2455]
A syntax has landed on OCaml, I think this should be supported in ReasonML as well!

https://jobjo.github.io/2019/04/24/ocaml-has-some-new-shiny-syntax.html
https://github.com/ocaml/ocaml/pull/1947
https://ocaml.org/releases/4.08.0.html

I cannot seem to find any issues related to this already

**Comment by Lupus** [comment]
#1321 morphed into support for "let+" after long discussion about Reason-specific syntax for async/await as seen in JS.
