### ISSUE TITLE
Editors: Quickly convert portions of text between syntaxes

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#247]
I think this might be extremely helpful for onboarding the OCaml folks: you start inside a .re file, write some Reason code, and then upon syntax confusion write your code OCaml, select, format into reason, then continue. It'll also be a great stop gap measure for when people fail to understand some errors, e.g. #244, #245, etc.

Otherwise I personally do `echo "someCode" | reasonfmt -parse ml...` etc., which is tedious.

Should be easy to implement; just passing two more flags to our existing formatter.

**Comment by jordwalke** [comment]
Here's some specifics:

If you're in a `.re` file, you could have two commands:
- Convert selected text from `.ml` to `.re` syntax inline, and replace.
- Convert selected `.re` into `.ml` in a scratch buffer so I can see what this Reason means.

- [ ] Implement this for Atom
- [ ] Implement this for Vim
- [ ] Implement this for Emacs

**Comment by chenglou** [comment]
Alright alright, [reason-tools] and the recent changes to `refmt` make this kinda obsolete. Plus we already have quite a bit of editor integration. Closing!
