### ISSUE TITLE
regression of handling keywords like method when we upgrade

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#2494]
https://github.com/BuckleScript/bucklescript/issues/3969

```reason
type method = string;

type request = {method};
```

gives

```
  This type constructor's parameter, `method`, can't be found. Is it a typo?

  Hint: Did you mean method_?
```

And

```reason
type method_ = string;

type request = {method_};
```

gives

```
  This type constructor's parameter, `method_`, can't be found. Is it a typo?

  Hint: Did you mean method__?
```

**Comment by bobzhang** [comment]
would anyone have a look at this issue

**Comment by anmonteiro** [comment]
I haven't looked but #2380 has been waiting for a review forever.

**Comment by anmonteiro** [comment]
Confirmed #2380 fixes this issue

**Comment by anmonteiro** [comment]
This is now in master. There are a lot of AST nodes in OCaml, and I think I got the most of them in #2380. If you find more discrepancies please let us know by opening a new issue!
