### ISSUE TITLE
Raise minimum OCaml AST support

### ISSUE THREAD

**Issue by ryyppy** [facebook/reason#2496]
As far as I understand Migrate-Parse-Tree, Reason is currently running on the OCaml base version 4.04. The BuckleScript v7 release (also other tools like genType) will drop 4.02 support and there is no plan to support 4.04 whatsoever.

We are in the process of making `refmt` an integrated part of the BuckleScript Playground JS Bundle, so we strive to make the bundle as small and efficient as possible.

In our code review, @bobzhang stated: `Is reason developed against 404? Maybe a good time to bump into 406 as well` ([see](https://github.com/BuckleScript/bucklescript/pull/3976#discussion_r348672666)). Now this got me curious. 

Are there many Reason consumers dependent on the 404 format? If not, would there be a chance to raise the minimum version to 4.06? As far as I understand MPT, this would  speed up the convertion speed and reduce the executable / js bundle size if I am not mistaken?

If this is a silly request, feel free to close it. I couldn't find any information on Reason's OCaml support plans (except one very old discussion from 2017) and I am trying to get up to date context.

4.02 will definitely be obsolete, I guess this will make things easier in the Reason codebase as well?

**Comment by anmonteiro** [comment]
related: #2036

**Comment by anmonteiro** [comment]
Done in #2487
