### ISSUE TITLE
Comprehensive coverage of attributes and attribute payloads.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#25]
This is a fairly large task, but I'm currently updating the printer to include a lot of the attribute printing features. After that is done, it will be much easier to finish the remaining work which entails going through the history of `parser.mly` for the last year and making sure that we have every new feature that has snuck into upstream.

Among other known features/gaps:
- Add signatures to `payload:` parsing of attributes.
- Test cases for all the ways which attributes can be applied.

Then, as a follow up, we can do some really good things with attributes.
1. Store the comments as documentation within the AST directly inside of attributes. This is good because some tools are under development that will autogenerate documentation based on these without having to use ocamldoc.
2. We can then build awesome async support using lwt_ppx.

**Comment by jaredly** [comment]
I think we're good on this
