### ISSUE TITLE
[refmt bug] renames quoted object fields, inconsistently since bs-platform 7.0.0.

### ISSUE THREAD

**Issue by cristianoc** [facebook/reason#2505]
In bs-platform `"7.0.0` this gives a type error.

```reason
type marshalFields = {
  .
  "switch__": string,
};

let testMarshalFields: marshalFields = {
  "switch__": "switch",
};
```

reformats to `ocaml`:

```ml
type marshalFields = < switch: string   >  Js.t
let testMarshalFields = ([%bs.obj { switch_ = "switch" }] : marshalFields)
```

This is what it used to reformat to with bs-platform `7.0.0-dev.2`:
```ml
type marshalFields = < switch__: string   >  Js.t
let testMarshalFields = ([%bs.obj { switch__ = "switch" }] : marshalFields)
```

**Comment by bobzhang** [comment]
Any chance that we can get a quick fix? doing a minor release soon, if so we can get it in, thanks

**Comment by cristianoc** [comment]
For reference, here are some tests I had to change until this is resolved:
https://github.com/cristianoc/genType/pull/316/commits/15109ad6351371585d02700f08411c04fb34f07f
