### ISSUE TITLE
Use a consistent versioning scheme

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#251]
Give that we want to change syntax frequently without providing backward compatibility, I'm wondering if we should stick to [semver](http://semver.org/) or a customized version scheme.

The problem with semver is that since we frequently break syntax backward compatibility, based on semver's description every time we upgrade syntax, we need to bump up Major version --  we could do that, but it looks like we will be upgrading Major version too fast.

Here are my thoughts about a possible versioning scheme :
1. PATCH version: when we make bug fixes to our toolings and syntax in a backward compatible way
2. MINOR version: when we update syntax in a incompatible way
3. MAJOR version: when we make incompatible tooling changes

**Comment by chenglou** [comment]
Semver
