### ISSUE TITLE
regression for Ocaml keyword match when upgrading to bucklescript 7.0.1

### ISSUE THREAD

**Issue by mbirkegaard** [facebook/reason#2519]
This looks to be the same problem as in https://github.com/facebook/reason/issues/2494 that @anmonteiro fixed for most keywords in https://github.com/facebook/reason/pull/2380.

```
  type match = {id: string};
  type matches = array(match);
```
results in
```
This type constructor's parameter, `match__`, can't be found. Is it a typo?
```

**Comment by cristianoc** [comment]
Not broken in master.
