### ISSUE TITLE
Typing an integer greater than 2,147,483,647 causes Try Reason to crash

### ISSUE THREAD

**Issue by kiangtengl** [facebook/reason#2538]
Typing an int larger than int32.max causes the TryReason to crash (see screencast)

![Screen-Recording-2020-01-28-at-3 32 11-PM](https://user-images.githubusercontent.com/574734/73314977-afbcf780-41e3-11ea-988d-61e37b7e0c65.gif)

**Comment by anmonteiro** [comment]
Looks like a BuckleScript problem.
