### ISSUE TITLE
`{j|$variable|j}` interpolation not type safe.

### ISSUE THREAD

**Issue by erlandsona** [facebook/reason#2556]
I have an opaque type that `{j|url/$myOpaqueType/path|j}` is perfectly happy compiling. If I change my syntax to `"url/"++myOpaqueType++"/path"` it won't compile which is what I would expect from the interpolation syntax as well. 
I suppose I'm fine with safe coercions like `string_of_int` or `string_of_float` because those have an expected behavior but I certainly want the compiler to yell at me for using a custom type in an interpolation without first converting it to some string safe type first.

**Comment by anmonteiro** [comment]
This issue belongs in the BuckleScript repository. There's no interpolation syntax outside of BuckleScript.

**Comment by erlandsona** [comment]
Ah my B!
