### ISSUE TITLE
Obj.magic unexpected behaviour

### ISSUE THREAD

**Issue by prophet1906** [facebook/reason#2564]
For following code snippet:
```
let x = "1";
let y = 2;
let z = Obj.magic(x) + y;
Js.log(z);
```
Expected Output: 3
Actual Output: 12

Is it expected behavior? or I am missing something.

**Comment by bloodyowl** [comment]
That's logical, yeah. By using `Obj.magic` you tell the compiler that your string is an int, so it doesn't apply any treatment, leaving you with `"1" + 2`, which, in JS leaves you with `"12"`.

You can do the following to ensure type safety:

```reason
let z = Belt.Int.fromString(x)->Belt.Option.getWithDefault(0) + y;
```
