### ISSUE TITLE
Children spread + List.cons gets refmted into semantically different code

### ISSUE THREAD

**Issue by jchavarri** [facebook/reason#2591]
Input:

```reason
<head>
  ...{[title, ...other_elements]}
</head>
```

which would produce something like this (in `.ml` syntax):

```ocaml
let _ = ((head ~children:(title :: other_elements) ())[@JSX ])
```

gets transformed into:

```reason
<head>
  title
  other_elements
</head>
```

Which is a very different thing:

```ocaml
let _ = ((head ~children:[title; other_elements] ())[@JSX ])
```

**Comment by jfrolich** [comment]
Perhaps this syntax would be nice to have: `<tr>...{[<b/>,...doc]}</tr>` into `<a> <b /> ...doc </a>`

**Comment by jordwalke** [comment]
Looked into this. I found out where it's happening. `formatChildren` function needs to bail out on any list cons `::` which is not ending in a nil termination `[]`.
