### ISSUE TITLE
support, inherit on objects since 4.06

### ISSUE THREAD

**Issue by EduardoRFS** [facebook/reason#2606]
Since 4.06 OCaml supports inherit in objects, but there is no way to do that in Reason. This is really important as it makes functions + objects a full replacement of classes.

```ocaml
module type X  = sig type x = < x  > end
```

**Comment by anmonteiro** [comment]
supported since #2487 

see https://github.com/facebook/reason/blob/master/formatTest/unit_tests/input/object.re#L47-L72
