### ISSUE TITLE
Release on Opam

### ISSUE THREAD

**Issue by tmattio** [facebook/reason#2630]
Hi!

The latest version of Reason released on Opam is not compatible with OCaml 4.11. This is currently impacting several projects that use Reason, for instance:

- ocaml-lsp-server (https://github.com/ocaml/opam-repository/pull/17079)
- spin (https://github.com/tmattio/spin/issues/86)

Is there any plan to release the latest version of Reason on Opam?

Thanks a lot 🙂

**Comment by kit-ty-kate** [comment]
ping @anmonteiro

**Comment by anmonteiro** [comment]
Thanks for the reminder. I'll cut a release this weekend.

**Comment by kit-ty-kate** [comment]
@anmonteiro Could it also have https://github.com/facebook/reason/pull/2635 if possible?

**Comment by anmonteiro** [comment]
Unfortunately I can't cut releases. @jordwalke would have to do it. I'm gonna publish 3.6.2 which exists somewhere on NPM.

**Comment by anmonteiro** [comment]
https://github.com/ocaml/opam-repository/pull/17592

**Comment by kit-ty-kate** [comment]
I believe this particular issue can be closed now that the package is available in opam. Thanks a lot for that again!

**Comment by tmattio** [comment]
Thanks a lot @anmonteiro and @kit-ty-kate! Closing this now 🙂
