### ISSUE TITLE
[Documentation]

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#285]
Here's what we need to document (in the official docs page): (Please add anything you think of).
- [x] Recursive bindings, simultaneous bindings.
- [x] Imperative statements if/while/for.
- [x] Very basic syntactic features.
- [x] More advanced features (named arguments, modules, signatures).
- [x] All the very advanced features Objects.
- [ ] Describe likelihood of change for each of the three (the later are definitely more likely to change rapidly).
- [ ] How to upgrade versions.
- [x] How to build a sample project (CommonML is a good "playground" to try our Reason in).
- [x] Emacs/Vim setup.
- [ ] Using `rebuild` in existing projects.

**Comment by chenglou** [comment]
Done done done
