### ISSUE TITLE
Merlin to support both ML and RE simultaneously.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#287]
@def-lkb:
We're realizing that one important feature, which might be satisfied by your latest progress on Merlin, is the ability to have merlin that will operate on both regular ML (with the default "reader"), and on RE, with a custom `Reader`. With the way we started out, we just passed global `-pp` flags to Merlin. This works when you _only_ edit `.re` files, but when we edit `.ml` files, they will crash. Then we discussed adding the `READERS` to the `.merlin` file. This is a good start, because different projects might want different readers - but I believe it's not enough because it still might pass a `.ml` file to the Reason Reader, which it can't really handle (cannot do parsing recovery etc).

I think what we really want is the following specified in the merlin file:

```
READER reason .re .rei
```

This should accomplish three things:
1. Register the reader `reason`.
2. Associate the `reason` reader with file suffixes (`.re` for impl, and `.rei` for interfaces).
3. Allow `.re`, `.rei` to participate in `MerlinLocate` commands (so could take the place of the `SUFFIX` command).

To register _only_ the suffixes without a `Reader`, I suppose you could do:

```
READER default .re .rei
```

**Comment by jberdine** [comment]
Are there pointers to the nuclide/atom issues tracking this problem?  On the infer team we are hitting this and it's quite suboptimal.  Is using merlin with both reason and ocaml simultaneously expected to work, if we were to upgrade to some particular version?

**Comment by jordwalke** [comment]
I am editong both simultaneously in atom reason so I assume it works in other editors too. I think it was added in a recent version and Yunxing is upgrading Infer to that latest version as we speak so that it can use the new packaging workflow.

**Comment by freebroccolo** [comment]
I can confirm that it works in the vscode extension too. As long as you have a new enough `merlin` with `merlin-extend` support (might require building from `master`), it should "just work".

When a file is synchronized with merlin, commands of the following form are sent:

```javascript
{
  context: ["auto", "M.{ml, mli, re, rei}"],
  query: ["tell", "<start>", "<end>", "<content>"]
}
```

If `merlin-extend` support is available, and "auto" is used for the context (rather than "ml" or "mli"), merlin should detect whether it is an OCaml or Reason file and do the right thing.
