### ISSUE TITLE
Preserve end of line comments.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#313]
``` ocaml
let x = "myVar"; (* This is an end of line comment *)
let y = "something";
```

This may or may not be launch blocking. I would normally deprioritize this if we were only considering from scratch Reason projects (where can simply state that we don't yet support end of line comments), but for converting projects over it's pretty important to be able to support this.

I don't really even think it would be that difficult. I bet we can think of a hack to make it work and infer if the comment was originally at the end of a line. We may want the reason toolchain to always pass the original text document to the `Reason` pretty printer. That way it can make various judgement calls about comments or anything else.

**Comment by jmmk** [comment]
@jordwalke  seems like this is done?

**Comment by chenglou** [comment]
Done a while ago, thanks.
