### ISSUE TITLE
Support 4.03

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#32]
The newest OCaml compiler has a few changes in the AST that make the parser incompatible. I'll update this issue with things I observe, though there aren't many changes that are difficult to adapt to.
1. The `?` in optional named arguments, has been improved so that the question mark doesn't become a part of the name itself (which would then later be used to interpret it as optional) - instead, it is modeled using a variant type appropriately.

**Comment by vramana** [comment]
@jordwalke This should now be either be closed or title should be changed to Support 4.04

**Comment by dysinger** [comment]
Please support 4.04 so I don't have to switch to play with Mirage 3.x

**Comment by SanderSpies** [comment]
@dysinger It is being worked on: https://github.com/facebook/reason/pull/907

**Comment by jordwalke** [comment]
So happy!
