### ISSUE TITLE
comments do not seem to be rewrapped

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#328]
Executing `reasonfmt -print-width 70` on code that includes comments extending to e.g. 80 columns does not rewrap them to fit within 70 columns.  Likewise, `reasonfmt -print-width 100` does not produce code where comments reach all the way to 100 columns.

If comments are not rewrapped, then linters will continue to complain about them, and there will be an even greater overhead to commenting code.

If the concern is to preserve commented-out code, perhaps reasonfmt could try to parse each comment as code, and if successful then format the comment as code, and otherwise just line-wrap it to the specified margin.

**Comment by jordwalke** [comment]
Closing, replaced by this other task which would encompass [this one](https://github.com/facebook/reason/issues/2008)
