### ISSUE TITLE
Do something with BetterErrors

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#336]
We either go all-in on this by replacing commonML's reporter, or we kick this out of this repo. Otherwise it's just sitting here being useless.

**Comment by chenglou** [comment]
BetterErrors master streams and dropped dep on ANSITerminal. We're good to go for rebuild integration here.

**Comment by jordwalke** [comment]
Awesome! My proposal is:

We can keep `refmterr` as a program that you can pipe stuff to (with those crazy redirects of course), but also inside of `rebuild`, for any `.re`/`.rei` file that is compiled, we can process the build output through `refmterr` just for that one compilation command.

**Comment by chenglou** [comment]
Welp, I guess this is solved now with the npm reason?

**Comment by jordwalke** [comment]
Yeah we need the latest better errors to be ported to an NPM package that works with the NPM findlib support though. I only ported an old version

**Comment by chenglou** [comment]
That's already done: https://github.com/npm-ml/BetterErrors/tree/npm

Only need to integrate into reason now. Which was tricky because of [this](https://github.com/facebook/reason/blob/fe86599e38a4516756eaa67c7b9258563b90d83a/src/reason_error_reporter.ml#L3).

So the BetterErrors type printer depends on Reason...

**Comment by jordwalke** [comment]
Sorry, what are you referring to in [this](https://github.com/facebook/reason/blob/fe86599e38a4516756eaa67c7b9258563b90d83a/src/reason_error_reporter.ml#L3)?

**Comment by jordwalke** [comment]
> That's already done: https://github.com/npm-ml/BetterErrors/tree/npm

That doesn't have findlib support right? It's not clear how that `npm` release that you linked to is compiled and installed. There's no Makefile.
