### ISSUE TITLE
Do not force break for "small" if statements.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#375]
In cases like the following, forcing a break is really ugly.
```rust
let res =
   myFunction
     arg
     (if (x) {expr} else {expr2});
```

So let's change the `if` formatting to not force breaks if:
- There is only one sequence item inside of the `{}`
- There is no "else if".

This is a "great first task" for someone looking to help out.

**Comment by SanderSpies** [comment]
I'm "claiming" this issue.

**Comment by jordwalke** [comment]
It is actually quite challenging believe it or not. I have tried twice and failed.

**Comment by SanderSpies** [comment]
Ah, guess @cristianoc is doing this one! Then I pick up something else.

**Comment by cristianoc** [comment]
Sorry @SanderSpies I was trying to assign the task to you, then got my name by mistake.

**Comment by SanderSpies** [comment]
@cristianoc No worries - thanks for assigning.

**Comment by jordwalke** [comment]
You could take a look and document why it's challenging.

**Comment by SanderSpies** [comment]
@jordwalke Seems you already did that: https://github.com/mjambon/easy-format/issues/12. 

Is there btw. already a function to count sequences or more ideal a sequence "threshold" function?

**Comment by jordwalke** [comment]
I don't believe such a thing exists, but the challenge was mostly in the easy-format issue. Good find.

**Comment by SanderSpies** [comment]
Close please (fixed already(

**Comment by yunxing** [comment]
Closing this. 

@SanderSpies I made a small change on top of your diff so it would still break if the if statement can't fit into a single line.
