### ISSUE TITLE
Do not require `{}` around content to right of match case.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#376]
I believe @yunxing was pushing for this. I did some experiments and it turns out this save us a _ton_ of both horizontal space (because less indentation) and also vertical (because less indentation triggers fewer wrappings).

So we can just assume there's already an "implicit" wrapping `{}` around each match case to the right of `=>`. This works very well in the `switch` statements because we are already guarded by `|` tokens, so there shouldn't be any conflicts/downsides. It's also more familiar to people who have used `case/switch` statements in other languages.

**Comment by chenglou** [comment]
Done
