### ISSUE TITLE
Forgetting ; after braces

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#402]
This is beating to death but I keep doing this:

```rust
let a => {
  bla;
}
```

And forgetting the semicolon after the closing brace.

Another one:

```rust
print "hello"
if (a == 5) {
  1
}
```

**Comment by yunxing** [comment]
Should be fixed now.

**Comment by chenglou** [comment]
`Module item` will still trip people up I think.

**Comment by yunxing** [comment]
@chenglou I think we changed it to "invalid statement"?
