### ISSUE TITLE
Investigate Reason support for Codeboard

### ISSUE THREAD

**Issue by cristianoc** [facebook/reason#403]
[Codeboard](https://codeboard.io/) is a web-based IDE to teach programming in the classroom.
@haches @martinnordio

To add Reason support to Codeboard:
+ Backend support
Add a Docker container that installs Reason. This could be a modified version of the Infer container, as Infer already uses opam.
Use the stable Reason version specified in the README, which can be updated from time to time.
Currently:
`opam pin add -y reason git@github.com:facebook/reason.git#b105ecd2b6728e3f62f11f82a2947c8ca2b59fed`

+ Syntax highlighting in the Web IDE
Reusing swift syntax highlighting should already be pretty good.

+ Create project
A project consists of a list of `.re` files, and perhaps `.rei` files too, Whose Name Starts With a Capitalized Letter. Here's an example:
```
$ cat Message.re 
let message = "Hello"

$ cat Hello.re 
let () = print_string (Message.message ^ "\n")
```

+ Build
```
$ rebuild Hello.native
```
+ Run
```
$ ./Hello.native 
Hello
```
+ Clean project
```
rm -r _build
```

**Comment by bsansouci** [comment]
Can this be closed? :D

**Comment by cristianoc** [comment]
Yes, it's now supported.
