### ISSUE TITLE
[Printer] Group items in file according to convention.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#41]
Right now, when you print source files, they are always separated by spaces.
I'll propose a very simple convention that is better than this, though not perfect (team specific conventions would likely want to refine this).

If a comment is a "doc block" comment, it should have two total spaces above it. If it is a regular comment, it should have one space above it.

All other items in a structure/signature should be grouped together by their kind - so `let` bindings with `let` bindings, and `type` bindings with `type` bindings - `open` with `open` etc.

``` rust
open Foo;
open Bar;

type t = {x: int, y: int};
type t3 = (int, int);

let oneSpaceAboveThis = 100;
let anotherRegularLetBinding = "hi"
and yetAnotherBinding = "bye";

/**
 * let regular comment.
 */
let item = 0;


/**
 * docBlock comment.
 */
let anotherItem = 10;
```

**Comment by SanderSpies** [comment]
So, how do I get started on this?

**Comment by SanderSpies** [comment]
Does this relate to running: `refmt -parse re -print re Foo.re` and the result of this?

**Comment by wincent** [comment]
This would be a great help to readability if it were applied within block scopes.

At the moment I have some test assertions in a module, nested inside a block scope to prevent it from producing a bunch of unwanted exports, and `refmt` is producing a several hundred uninterrupted lines which is a little too dense; here's a sample:

```reason
/* Tests */
let _ = {
  /* ... dozens of lines here ... */
  /* Same replica id, ascending counters. */
  let a = createID replica::"replica" counter::5 ();
  let b = createID replica::"replica" counter::10 ();
  assert (compareIDs a b == (-1));
  /* Same replica id, descending counters. */
  let a = createID replica::"replica" counter::10 ();
  let b = createID replica::"replica" counter::5 ();
  assert (compareIDs a b == 1);
  /* Same replica id, equal counters. */
  let a = createID replica::"replica" counter::10 ();
  let b = createID replica::"replica" counter::10 ();
  assert (compareIDs a b == 0);
  /* Different replicas (descending), ascending counters. */
  let a = createID replica::"zzz" counter::5 ();
  let b = createID replica::"aaa" counter::10 ();
  assert (compareIDs a b == (-1));
  /* Different replicas (descending), descending counters. */
  let a = createID replica::"zzz" counter::10 ();
  let b = createID replica::"aaa" counter::5 ();
  assert (compareIDs a b == 1);
  /* Different replicas (descending), equal counters. */
  let a = createID replica::"zzz" counter::10 ();
  let b = createID replica::"aaa" counter::10 ();
  assert (compareIDs a b == 1);
  /* Different replicas (ascending), ascending counters. */
  let a = createID replica::"bar" counter::5 ();
  let b = createID replica::"foo" counter::10 ();
  assert (compareIDs a b == (-1));
  /* Different replicas (ascending), descending counters. */
  let a = createID replica::"bar" counter::10 ();
  let b = createID replica::"foo" counter::5 ();
  assert (compareIDs a b == 1);
  /* Different replicas (ascending), equal counters. */
  let a = createID replica::"bar" counter::10 ();
  let b = createID replica::"foo" counter::10 ();
  assert (compareIDs a b == (-1));
  /* doc is the simplest cursor. */
  assert (doc.init == []);
  assert (doc.last == Doc);
  /* ... hundreds of lines here ... */
};
```

**Comment by jordwalke** [comment]
@wincent Yes, the `/**` is the way to signal to the formatter, "I want an additional blank line above this item". However, even without having the user manually specify which blank links to insert, I think there's some pretty good defaults we could apply (group many subsequent let bindings or type definitions etc).

**Comment by chenglou** [comment]
Closed by @IwanKaramazow
