### ISSUE TITLE
[Atom] Display api docs for elements

### ISSUE THREAD

**Issue by kayceesrk** [facebook/reason#417]
It would be great to have the ability to view api documentation in the editor similar to [0]. @let-def tells me that merlin already has support for fetching documentation. Ideally, we want to have hyperlinked documentation generated for the current package sandbox through external (under-dev) tools such as `odoc / codoc`. 

[0] https://github.com/sharvil/api-docs

**Comment by SanderSpies** [comment]
This has been implemented within Atom.

**Comment by chenglou** [comment]
Yep
