### ISSUE TITLE
Not enough open lines between items

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#424]
Several related things that are suboptimal:
- items in modules and signatures defined not at file top-level should be separated by open lines just like top-level definitions do
- comments with open lines before and after them should be associated with the enclosing module / 'thing' if anything, and the formatting should at least preserve the open lines before and after
- let...and...and... should be formatted with intervening open lines the same way let...let...let... is

**Comment by jaredly** [comment]
we now allow blank lines!
