### ISSUE TITLE
Missing line breaks, formatted code exceeds margin

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#427]
Sometimes the formatter does not break enough lines, leading to code exceeding the margin.  E.g.:

```
let d_instrs sub_instrs::(sub_instrs: bool) (curr_instr: option Sil.instr) (node: t) => L.add_print_action (
  L.PTnode_instrs,
  Obj.repr (sub_instrs, curr_instr, node)
);
```

is 110 columns instead of staying within 100

**Comment by jberdine** [comment]
Perhaps a different issue, but with 1.4.0 the code:
```
let tenv_serializer: Serialization.serializer t = Serialization.create_serializer Serialization.tenv_key;
```
formats to itself and is 105 columns wide while the margin is 100.

**Comment by chenglou** [comment]
Fixed.
