### ISSUE TITLE
Consider embracing `fun` cases

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#430]
It might be better to uniformly embrace `fun` and `switch` expressions (and sum type definitions), but only if they are not the body of a `let` binding. That would avoid the nested match case problem, allow the following nice progression with `fun`:

```
let myFun = fun   a => a;
let myFun = fun | a => a;    /* You can add a bar before the argument */
let myFun = fun | a => a     /* You can add more forms by simply adding more bars */
                | b => b;    /* You can add more forms by simply adding more bars */
```

and be uniform with flow and ocaml type definitions, and would also uniformly allow `= fun` to be changed to `x = switch x` without churning the formatting. Apart from increasing the uniformity between `fun` and `switch`, it would allow code like:

```
IList.filter
  (
    fun
    | Sil.Aeq lhs rhs
    | Sil.Aneq lhs rhs => exp_contains lhs || exp_contains rhs
  )
  pi
```

to be formatted as

```
IList.filter
  fun {
  | Sil.Aeq lhs rhs
  | Sil.Aneq lhs rhs => exp_contains lhs || exp_contains rhs
  }
  pi
```

I make no claim that this is common, but the current reason version of this embraces the fun expression cases with parens, and the switch cases with braces, which strikes me as odd. Also, I expect that embracing fun cases instead of putting parens around the whole fun expression will help for things like function arguments to e.g. map.

There is the drawback that there is a distinction between expressions in general and the now-special ones that are the immediate body of a let binding. Maybe worth it though. Also, it isn't too far down the ML path before programmers need to think of let bindings as being special anyhow, due to their role as the only point where polymorphism is introduced by type inference.

Another option would be to embrace the cases of switch and fun only when they are the immediate subexpression of another switch or fun. I'm not sure I like that so much, but don't have a good reason why, other than I expect that code modifications like adding a let binding to the body of a case would cause the formatting to churn because the braces wouldn't be needed any longer.

**Comment by kennetpostigo** [comment]
Discussion seems to have died down here, not sure the if any "final" decision has been made or continued work to support fun cases is in the pipeline. Is this an issue that would be okay to close?

**Comment by jaredly** [comment]
our syntax is... now quite different. feel free to open a new issue if more discussion is needed.
