### ISSUE TITLE
Custom Reader for Merlin

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#45]
Frederic (Merlin author) and I have been collaborating on a protocol to allow custom parsers for Merlin. He committed a branch that has a custom "reader" (which means a custom syntax). We need to define one of these for Reason's syntax.

Here's the branch that has the Reader abstraction introduced:
https://github.com/the-lambda-church/merlin/tree/experimental-refactor

**Comment by chenglou** [comment]
Long done
