### ISSUE TITLE
rtop throws "Error: Reference to undefined global `Odoc_html'"

### ISSUE THREAD

**Issue by maacl** [facebook/reason#466]
I followed the installation instructions for OSX. The test works fine, but starting ```rtop``` throws:

    File "/Users/mac/.opam/4.02.3/bin/rtop_init.ml", line 1:
    Error: Reference to undefined global `Odoc_html'

**Comment by kayceesrk** [comment]
Thanks. A new stable version has been tagged. Run

```
opam pin add -y reason https://github.com/facebook/reason.git#0.0.6
```

to reinstall reason. `rtop` should work then.

**Comment by tsaiDavid** [comment]
@kayceesrk thanks! I'm going to give that a try, I had the same error. @maacl I'm using ZSH btw

**Comment by tsaiDavid** [comment]
@kayceesrk That got rtop working, but I'm getting this issue now:
https://github.com/facebook/reason/issues/471
