### ISSUE TITLE
Frontpage breaks on phone

### ISSUE THREAD

**Issue by rickyhan** [facebook/reason#469]
The bash picture is too wide for my Nexus 6P. Consider making it responsive.

**Comment by chenglou** [comment]
Don't have a Nexus 6P around, and it looks right on the Chrome simulator. Can you provide a screenshot please?

**Comment by yutongp** [comment]
I have a Nexus 6P. I don't experience wide bash picture with Chrome.

![13230816_1094810697245717_2074176577_o](https://cloud.githubusercontent.com/assets/915849/15341256/6b9f3f24-1c42-11e6-809d-d30ffe2554ad.png)

**Comment by chenglou** [comment]
Just grabbed a 6P too:
![13262512_1152698378108716_1386072281_o png](https://cloud.githubusercontent.com/assets/1909539/15341293/b09c608e-1c42-11e6-90ca-0a111881633f.jpeg)

@rickylqhan do you see the same thing?

**Comment by abacaj** [comment]
Nexus 5X here:

![screenshot_20160517-193011](https://cloud.githubusercontent.com/assets/7272343/15342757/dc7ec1c4-1c65-11e6-9484-a2140c303431.png)

**Comment by rickylqhan** [comment]
@chenglou I'm not sure if that's the full width? Should it stretch to fill the whole width? Here is a screenshot of what it should look like.

![screenshot_20160518-000321](https://cloud.githubusercontent.com/assets/1768528/15347124/8dfc4c70-1c8c-11e6-988e-c7feef4c1d76.png)

**Comment by kennetpostigo** [comment]
We have a new webiste now so this issue should be okay to close.
