### ISSUE TITLE
version for Windows please

### ISSUE THREAD

**Issue by aleksey-bykov** [facebook/reason#470]
subj

**Comment by Schmavery** [comment]
I had no problems installing it using [Bash on Ubuntu on Windows](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/).  Just available in [Insider Preview builds](https://blogs.windows.com/windowsexperience/2016/05/10/announcing-windows-10-insider-preview-build-14342/) right now but should be released pretty soon, I'd imagine.

**Comment by chenglou** [comment]
woohoo cc @jordwalke

**Comment by ForNeVeR** [comment]
I am still not sure if that Bash for Windows thing could be considered "production"-ready and for which scenarios exactly. Native Windows version still would be preferable.

We want the toolchain to be able to compile native Windows executables after all.

**Comment by XVilka** [comment]
Related https://github.com/ocaml/opam/issues/2191

**Comment by XVilka** [comment]
And this one - https://github.com/facebook/infer/issues/35 - is also from Facebook. Sadly OCaml ecosystem has poor Windows platform support.

**Comment by chenglou** [comment]
As a side note, we got some docker stuff checked in yesterday.

**Comment by braibant** [comment]
https://github.com/braibant/ocaml-windows-bootstrap contains a powershell script that should install cygwin and the dependencies required by OCaml, as well as some OCaml packages. It could be nice to update it to handle reason.

**Comment by XVilka** [comment]
Regarding opam support for Windows without need for Cygwin (and compiling OCaml as well, using opam) - there is a lot of activity in this branch https://github.com/dra27/opam/commits/windows

**Comment by kennetpostigo** [comment]
@jordwalke I think theres a windows support issue open in reason-cli, would it be okay to close this and move discussion over to that [issue](https://github.com/reasonml/reason-cli/issues/35)?

**Comment by chenglou** [comment]
refmt itself on js side now works on windows, though the installation path is indeed a bit different now. Closing!
