### ISSUE TITLE
Issue when resizing rtop (iTerm2 + ZSH)

### ISSUE THREAD

**Issue by tsaiDavid** [facebook/reason#471]
Hey all - I was finally able to get `rtop` to run, but am getting the following problem when resizing:

**During Resizing**
![http://i.giphy.com/3oEjHZCurIZ9gcRU5i.gif](http://i.giphy.com/3oEjHZCurIZ9gcRU5i.gif)

**On Return**
![http://i.giphy.com/xT4uQAZh39FyWC3C9O.gif](http://i.giphy.com/xT4uQAZh39FyWC3C9O.gif)

**Comment by jordwalke** [comment]
thanks for providing gifs! Does it clearing the terminal fix the issue? (Command + k)

**Comment by tsaiDavid** [comment]
@jordwalke - No problem and thanks for the hard work on this. I gave that a shot but that didn't work. I've quit iTerm as well. I haven't had trouble with other REPLs or things like `vi` with my current setup (theme, shell, etc)

**Comment by bsansouci** [comment]
Isn't this a problem with utop itself?
<img width="924" alt="screen shot 2016-05-17 at 18 01 38" src="https://cloud.githubusercontent.com/assets/4534692/15344178/6cd5c356-1c59-11e6-9e2c-4115f278700d.png">

**Comment by chenglou** [comment]
It is

**Comment by tsaiDavid** [comment]
Thanks for sharing your screenshot too - didn't realize it was related to `utop` - has anyone had success in actually getting it to work as intended?

**Comment by maacl** [comment]
I get the same. iTerm2, zsh on OSX.

**Comment by kennetpostigo** [comment]
If this is a problem in utop itself maybe this issue should be closed and an issue should be raised whereever utop repo is at?
