### ISSUE TITLE
Type inferred by Reason is rejected if given as annotation

### ISSUE THREAD

**Issue by lukenels** [facebook/reason#474]
```
let ap = fun a b =>
  switch (a, b) {
    | (Some f, Some x) => Some (f x)
    | _ => None
  };
```

The above snippet typechecks with the following type:

```
# #use "test.re";
let ap : option 'a => 'b => option 'a => option 'b = <fun>
```

If you turn around and annotate the code with that type, however, it fails as follows.

```
let (ap:  option 'a => 'b => option 'a => option 'b) = fun a b =>
  switch (a, b) {
    | (Some f, Some x) => Some (f x)
    | _ => None
  };
```

```
#use "test.re";
File "test.re", line 4, characters 26-36: Error: This expression has type option 'b but an expression was expected of type option 'a => option (option 'c)
```

This is likely due to a bug in the way nested function types are printed.

**Comment by yunxing** [comment]
Thanks for reporting! I think the correct type here should be : 
`# #use "test.re";
let ap : option ('a => 'b) => option 'a => option 'b = <fun>
`
Somehow we are not printing the parens correctly.

**Comment by jordwalke** [comment]
Thanks for reporting!
