### ISSUE TITLE
documentation code is hard to read (on Chrome + Ubuntu 14.04)

### ISSUE THREAD

**Issue by sairion** [facebook/reason#475]
![reason](https://cloud.githubusercontent.com/assets/484290/15349588/dbbf92aa-1d0e-11e6-99d0-f0f6aa3f5ff7.png)

Hello! Thanks for sharing your awesome work. However, I found the code in documentation is a bit hard to read. Specifically, due to `letter-spacing: -1px` typesetting, letter spacing is too narrow. I believe the style designed with assume that user to have Menlo (`font-family: Menlo, monospace`), but it falls back to default platform font, since I don't have one on my platform. Also whom I know uses Windows having hard time to read.

I use user stylesheet to preventing this problem but I think it can be improved! :)

**Comment by jordwalke** [comment]
Would you suggest a fallback/screenshot that you think would work for people without Menlo?

**Comment by sairion** [comment]
@jordwalke Github is using 

```css
font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
```

I think it would work for the most of users. Also, I think it would be better to remove `letter-spacing: -1px;`, at least for `code` and `pre` :)

**Comment by kennetpostigo** [comment]
This should be okay to close with the new site being used now.

**Comment by sairion** [comment]
Yeah, it seems ok now :)
