### ISSUE TITLE
Atom giving error when referencing other file

### ISSUE THREAD

**Issue by SanderSpies** [facebook/reason#477]
Probably related to underlying tooling (Merlin?) - but still an annoyance for me.

Foo.ml
```
let bar = fun a => a + 2;
```

B.ml
```
print_int (Foo.bar 1);
```
A red line appears underneath Foo, while `rebuild B.native` just works.

**Comment by chenglou** [comment]
Does the error still appear after a build?

**Comment by michelebelmonte** [comment]
I had a similar issue: it was fixed adding to the .merlin file the folder containing the files produced by rebuild. e.g.:
B ./_build

**Comment by chenglou** [comment]
cc @yunxing. I didn't know rebuild took care of .merlin?

**Comment by yunxing** [comment]
@chenglou @michelebelmonte `rebuild` doesn't generate .merlin files. I thought about doing that but I feel it is out of the scope of `rebuild` as a backward compatibility tool.

**Comment by chenglou** [comment]
Cool. Closing this then. Once our new build system comes out it'll auto-generate the merlin file. Meanwhile people will need to know how merlin works...

**Comment by jordwalke** [comment]
@yunxing Do you have any idea how to integrate `rebuild` and the Jenga rules? Is there a way to make `ocamlbuild` rules that simply defer to the Jenga build for some things? It could help us keep `rebuild` as the primary entrypoint. (Is this a bad idea?)

**Comment by yunxing** [comment]
@jordwalke Interesting idea. I think we should be able to integrate ocamlbuild with Jenga build rules as they are pretty flexible (we also need to support current behavior for ml projects conversion).
