### ISSUE TITLE
Missing link of rtop on tools section of GitHub pages

### ISSUE THREAD

**Issue by meisyal** [facebook/reason#482]
I saw there is a missing link of `rtop` on tools section of GitHub pages. Please, take a look [here](https://github.com/facebook/reason/blob/gh-pages/tools.html#L181). It is written as `[`rtop`](file:///Users/jwalke/githubdocs/Reason/index.html#reason-repl), a`. That link points to someone local files. This is just a minor issue.

**Comment by chenglou** [comment]
Thanks!

**Comment by meisyal** [comment]
You're welcome.
