### ISSUE TITLE
Navigate rtop completion list on Mac OS X?

### ISSUE THREAD

**Issue by jkleiser** [facebook/reason#494]
I read here https://opam.ocaml.org/blog/about-utop/, under "Real-time completion", that one can navigate the utop completion list by using the meta key and the left and right arrows. I have tried using the alt-arrow (and other) combinations, but this far I have not been able to move among the completion alternatives.
If I type e.g. "#ut", I would like to move to alternative #2 which is "utop_help". Is it possible to do this on Mac OS X?
I'm right now using Terminal 2.6.1 on Mac OS X 10.11.5.

**Comment by kayceesrk** [comment]
For me `ctrl-alt-arrow`, moves among the alternatives in the list.

**Comment by jkleiser** [comment]
For some reason `ctrl-alt-arrow` doesn't work for me. (I'll try on another Mac later.)

**Comment by jkleiser** [comment]
I tried the other Mac (OS X 10.10.5, Terminal 2.5.3), but I could not move among the completion alternatives (using `ctrl-alt-arrow`) there either.

**Comment by jkleiser** [comment]
With some help from bsansouci @ #reasonml, I found the solution. In Preferences->Profiles->Keyboard I removed the Key Action for `alt-left arrow` (\033b) and `alt-right arrow` (\033f), and also enabled "Use Option as Meta key". Then I was able to navigate the completion list. To then make use of the selected command, I did `alt-tab`.

**Comment by jordwalke** [comment]
I'd really like it if tab and shift tab would cycle through. I believe shift tab is an impossibility in terminals.

**Comment by kennetpostigo** [comment]
seems like a solution was found, is this okay to close?

**Comment by chenglou** [comment]
Yep, thanks.
