### ISSUE TITLE
Question: How to work with libraries?

### ISSUE THREAD

**Issue by zsck** [facebook/reason#495]
Hi there, I'm sorry I have a terribly silly question.

I've just started poking around with Reason and I want to get an HTTP server running. I've decided to try to use the cohttp and lwt libraries in tandem, however I  have no idea how to get rebuild to compile/recognize them.
I've got Atom set up with Nuclide and the Reason tools, and have been able to compile Reason programs that just use the builtin language. However, now that I've installed the libraries I want to use with

    opam install cohttp lwt

and written `main.re` containing

```
open! Cohttp;
open! Lwt;
open! Cohttp_lwt_unix;

print_string "Hello world!\n"
```

I get the following output from rebuild:

```
$ rebuild -mod cohttp -mod lwt main.native

+ /Users/zmullaly/.opam/4.02.3/bin/ocamlc.opt -c -pp refmt -o main.cmo -intf-suffix .rei -impl main.re
File "main.re", line 1, characters 6-9:
Error: Unbound module Lwt
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.

  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:

      true: -traverse
      <dir1> or <dir2>: traverse

Compilation unsuccessful after building 2 targets (1 cached) in 00:00:00.
```

And no .native file is produced.

Likewise, in Atom, I have the following errors:

```
Error: unbound module Cohttp
Error: unbound module Lwt
Error: unbound module Cohttp_lwt_unix
```

What am I supposed to be doing here to link with the libraries I downloaded?

**Comment by zsck** [comment]
**Update**

I figured out that I had to compile with

    rebuild -pkg cohttp -pkg lwt main.native

This gets the build to pass. However, I'm not sure what I can do about Atom not recognizing the installed modules.

**Comment by hcarty** [comment]
I suspect that you need to create a `.merlin` file in the root of your project/source directory with the content:
```
PKG cohttp lwt
```
to let merlin know what packages you're using in your code.

**Comment by yunxing** [comment]
@hcarty Thanks, that's correct. 

@zsck Our editor support relies on a `.merlin` file to detect installed modules (see https://github.com/the-lambda-church/merlin). We didn't document merlin much because we are planning to a project helper tool to hide the details of `.merlin` by auto generating it.

**Comment by yunxing** [comment]
Closing this as the question has been answered. Feel free to reopen if you have any other questions.

**Comment by IwanKaramazow** [comment]
Is it possible to include external libraries (like cohttp) with the CommonML example project?  (the jordwalke/ReasonExampleProject).
I tried to make it work, but haven't had much success with it.. However, I'm pretty new to the whole Ocaml/Reason language, so I have absolutely no idea if this is even possible.

Should I use rebuild as build tool when including libs like cohttp? Or is this possible with the CommonML example project too?

**Comment by bsansouci** [comment]
@IwanKaramazow I'd say just use rebuild with the -pkg cohttp option.
