### ISSUE TITLE
Question: Public chatroom for working with Reason?

### ISSUE THREAD

**Issue by zsck** [facebook/reason#496]
Is there any chance a public IRC channel or Slack channel could be set up for discussion about Reason? I understand it might be difficult for Facebook staff to handle it all the time, but I would really like to be able to ask Reason and OCaml-related questions in the context of Reason.

**Comment by bsansouci** [comment]
I just asked the Discord channel reactiflux and they don't want reason because it's totally different/unrelated. Maybe an irc channel on freenode?

**Comment by chenglou** [comment]
Man this has been debated to death and thanks for reminding us to get back on it. Slack unfortunately did not scale for reactiflux, thus the discord migration. I myself am on both, but I find discord still a bit of a heavy thing to buy into. Meanwhile we've joined #reason as a stop-gap solution before settling on discord/gitter. See you there!

**Comment by jordwalke** [comment]
Cool! For now, most of the discussion will likely revolve around the implementation of the toolchain. I might suggest creating two rooms: #reason and #reason-bike-shed
(I don't like IRC very much, but it makes sense to have an IRC channel while looking for another solution). As more of the dev-experience is unified, a good place for noobs to discuss will become very important so I'm glad you're thinking about this.

**Comment by chenglou** [comment]
bike-shed will mostly be about syntax right? If so I'll call it that, lol

**Comment by yunxing** [comment]
Closing this as we are mostly discussing on #reasonml now. Feel free to reopen if you have any other idea for a better public channel.
