### ISSUE TITLE
Example program doesn't work in reason project directory

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#500]
I'm finally able to reproduce the issue @xorgy mentioned in #468

Looks like the problem only show up when building `hello.native` in the reason repo.

![image](https://cloud.githubusercontent.com/assets/1017689/15419798/7c961fe6-1e1d-11e6-935b-13aec59eb78e.png)

**Comment by xorgy** [comment]
Probably a good idea to document that that doesn't work in the `README.md`.

**Comment by jordwalke** [comment]
So the problem is that our own project's tags get in the way?

**Comment by yunxing** [comment]
Yes, I probably a bug in rebuild. Haven't got a chance to look into it yet. Just opening the issue here for other people's reference.

**Comment by kennetpostigo** [comment]
After reading the issue referenced above does the work that adds `ocaml-migrate-parsetree` fix the problems going on here? if so, is this okay to close?

**Comment by chenglou** [comment]
Done done
