### ISSUE TITLE
rtop finishes parsing when not terminated with a `;` with no execution

### ISSUE THREAD

**Issue by simonjbeaumont** [facebook/reason#505]
```
Reason # let f = fun n => n;
let f : 'a => 'a = <fun>
Reason # f 1
Reason # f
Reason # f 1;
- : int = 1
```

**Comment by chenglou** [comment]
cc @jordwalke @yunxing this is a bit troublesome because it swallows errors.
<img width="571" alt="screenshot 2016-05-26 20 55 39" src="https://cloud.githubusercontent.com/assets/1909539/15597372/3953fb2e-2384-11e6-9c0b-8ee91d313944.png">

**Comment by jordwalke** [comment]
I don't think this was always the case.

**Comment by yunxing** [comment]
@simonjbeaumont Sorry just saw this. I think this could be related to some of the stuff that I added to support rtop -stdin and use file. 

Let me see what's a good solution here.

**Comment by yunxing** [comment]
This should have been fixed in trunk. Closing it.
