### ISSUE TITLE
Can't pattern-match a list as [a, ...as]

### ISSUE THREAD

**Issue by yawaramin** [facebook/reason#507]
On compiling the following:

```
let xs = [1, 2, 3];
let [a, ...as] = xs;
```

We get the compile error:

```
File "Hello.re", line 2, characters 11-13:
Error: 745: <SYNTAX ERROR>
```

If we change the pattern to `[b, ...bs]` the compile succeeds.

**Comment by yawaramin** [comment]
Whoops. `as` is a keyword.

**Comment by yunxing** [comment]
Good catch (I was confused also). 

I think in this case we should change the error message of error state 745. Reopening it.

**Comment by chenglou** [comment]
@yunxing ping me on your diff if you make one. I wanna see menhir error warning in action!

**Comment by yunxing** [comment]
@chenglou Sure. I'm planning to write a detailed doc about how to contribute to menhir error warning database in the weekend so other people can contribute to it leisurely.
