### ISSUE TITLE
refmt could use cmdliner

### ISSUE THREAD

**Issue by samoht** [facebook/reason#508]
Currently `refmt -h` is not very helpful/beautiful. It would be nice if all the CLI tools that you distribute could use cmdliner. You can see an example of what I mean if you run `opam --help`.

**Comment by yunxing** [comment]
@fxfactorial submitted #395 that will help us get there. 

`opam --help` is beautiful!

**Comment by tekknolagi** [comment]
Being worked on in https://github.com/facebook/reason/pull/995

**Comment by rgrinberg** [comment]
Isn't this done?

**Comment by tekknolagi** [comment]
Yes, yes it is. Thanks!

**Comment by tekknolagi** [comment]
Paging @yunxing

**Comment by jordwalke** [comment]
Yes, it's done!

**Comment by fxfactorial** [comment]
Oh nice, it was merged?

**Comment by jordwalke** [comment]
It was rebuilt a while ago and then merged, yes (we went with vendoring it). Thanks for kicking off the effort, @fxfactorial.
