### ISSUE TITLE
redoc generates repeated output

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#509]
@kayceesrk I'm not sure if this is a bug in redoc, or ocamldoc, but it seems that redoc is generating repeated output:

http://kcsrk.info/reason_stdlib_docs/Scanf.html

Compare that to the official docs:

http://caml.inria.fr/pub/docs/manual-ocaml/libref/Scanf.html

I noticed this while refactoring the style sheet.

**Comment by kayceesrk** [comment]
It is a known bug, which has been fixed in 4.03 [0].

[0] https://github.com/ocaml/ocaml/pull/348
