### ISSUE TITLE
rtop throws "Error: Reference to undefined global `Reason_util'"

### ISSUE THREAD

**Issue by Hobinx** [facebook/reason#510]
I followed the install instruction on OS X, and the installation test worked fine, but starting `rtop` throws:

```
Exception: "Assert_failure src/reason_util.ml:17:4".
File "/Users/###/.opam/4.02.3/bin/rtop_init.ml", line 1:
Error: Reference to undefined global `Reason_util'
```

**Comment by yunxing** [comment]
Hi @Hobinx, thanks for reporting!

Could you try to set the environment variable "OCAMLRUNPARAM" to "b" and try again?

**Comment by kayceesrk** [comment]
@Hobinx Do you happen to have a `~/.ocamlinit` file? Mine had `#camlp4o;;`, which caused this error. Reason is not compatible with camlp4, and commenting this out makes the error go away for me.

**Comment by Hobinx** [comment]
@kayceesrk Yeah, I have a `~/.ocamlinit` file, and I comment out  `#camlp4o`, but same error again when I started the `rtop`.

**Comment by Hobinx** [comment]
@yunxing I set the environment variable "OCAMLRUNPARAM" to "b" and run `rtop`, the same error message prints out. Looks like `rtop` is not loaded, the toplevel is just `utop`, because when I type `[1, 2, 3]` in it, it prints out the type `(int * int  * int) list`, rather than normal list in Reason's basic syntax.

**Comment by trevorriles** [comment]
@Hobinx I deleted the `~/.ocamlinit` file, and re-ran `opam init` and ``eval `opam config env``` and I could run `rtop`

**Comment by yunxing** [comment]
@trevorriles @Hobinx hmm looks like the issue is in ~/.ocamlinit file. Could you please share yours so I can reproduce it on my end?

**Comment by Hobinx** [comment]
@yunxing 
```
(* Added by OPAM. *)
let () =
  try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
  with Not_found -> ()
;;
#use "topfind";;
#thread;;


#camlp4o;; 
#require "core.top";;
#require "core.syntax";;
```

**Comment by Hobinx** [comment]
@trevorriles Yeah, you are right. I deleted the `.ocamlinit` file, and re-ran `opam init` and ``eval `opam config env` ``,  and problem solved.

**Comment by jordwalke** [comment]
Should we have a `.reasoninit` instead?

**Comment by yunxing** [comment]
@jordwalke that's what I'm thinking. Another way is to detect if #camlp4o is used in .ocamlinit and fail.
