### ISSUE TITLE
Allow for customized error messages in parser

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#518]
We currently only support a predefined set of error types in the parser as provided from compiler-libs (Expecting blah, Unclosed blah). 

However, somethings we want to provides a more specialized error message.

For example, when one types `| hd :: tl -> `, we would like to reminds him: " `::` is not supported in Reason, please use [hd, ...tl]" instead. 

To achieve this, we first need a constructor that can take an arbitrary string as error message.

**Comment by SanderSpies** [comment]
I guess that would mean exposing ` Location.errorf_prefixed`?

**Comment by yunxing** [comment]
@SanderSpies Good point! I think we should use `Location.raise_errorf` here.

**Comment by SanderSpies** [comment]
Alright I'll use that in my PR.
