### ISSUE TITLE
Publishing Reason packages.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#525]
We've made the conscious decision to first focus on upgrade flows for the syntax. We know we won't get it right on the first shot and because of the way `Reason` works, that's okay. But to make this a reality in practice, we need to make this world of rapid upgrades compatible with various package managers/build systems. Here is the current challenge:
- We need each package in your app to be able to depend on a different version of Reason because it might be that some of your packages had upgraded to a new version and others have not. If Reason is just an ordinary `opam` package, then there can only be one version of it per opam switch. If using npm, multiple versions can be supported simultaneously (and this is one of the only few cases where I find that feature useful - I would not suggest it in general).
- We need `rebuild` and `jengaboot` and every other build system to be able to select just the right path to `refmt` to supply to its `-pp` arguments.

How would we do this with `opam`? Would we create a separate package name for each version (such as `reason1`, `reason2`?

cc @samoht @yunxing

**Comment by yunxing** [comment]
Creating different packages by putting package version into the name should work here. It is just a big hack on top of opam. 

Another hacky solution is to download/compile a specific version of refmt on the fly when we need it. This is what we are doing in reup.sh

**Comment by nmn** [comment]
Is it possible to publish some sort of compiled version of the packages instead. Maybe just stick to OCAML itself. Am I right in thinking that Reason can be treated as a compile to OCaml language? Like Coffeescript to Javascript?

In that case it makes sense to convert source code to OCaml when publishing to OPAM. The source code on Github should remain in Reason of course.

**Comment by jordwalke** [comment]
We could use `.ml` as the published version, but that requires that someone produce a reliable, well tested printer for the `.ml` syntax which doesn't exist yet (understandably, because pretty printing `.ml` isn't in the critical developer path for ML, yet it is for `Reason`). Eventually, I imagine we will have a good `.ml` pretty printer, but it won't be for a while.

I see three solutions:
- Require the package manager to permit multiple versions of a package to exist as long as those packages are strictly build/development dependencies - not runtime. (Hard for OPAM, works with npm).
- Publish separate packages for each version of Reason (this seems easy to do and should work easily with the build system, but not sure if there's other things I'm not seeing).
- Have each published package generate a "compiled version" as you said, but not the `.ml` syntax, rather a raw binary dump of the already-parsed AST. Then we make a master `-pp` program which can load this raw AST into any `ocamlc` command, regardless of the version of Reason that parsed it.

**Comment by nmn** [comment]
I think the problem with the second solution is that in the early days as Reason updates quickly we probably don't want to force lib authors to keep re-publishing the same code just to track the version of Reason.

I like the third version, though I'm not sure what the real difference is between a raw AST or a .ml file which may not be pretty-printed. Both options seem equivalent. (Unless printing .ml code at all isn't quite possible yet)

**Comment by jordwalke** [comment]
I think I was not clear when explaining the second option. The second option is to publish separate Reason packages - one for every version of Reason. Package authors that *use* Reason don't have to do any extra work, they simply depend on `Reason2_2` instead of `Reason.2.2`. I'll clarify the comment.

**Comment by yunxing** [comment]
The problem with the third option is that the AST can also change between Reason versions if Reason switch to a different ocaml version.

**Comment by nmn** [comment]
@jordwalke That makes sense now. Sound good! I'm pretty new to OCaml, so don't really know the inner workings of OPAM.

**Comment by jordwalke** [comment]
@yunxing 
> The problem with the third option is that the AST can also change between Reason versions if Reason switch to a different ocaml version.

For any given OPAM switch there is always one OCaml version and you could version the combination of OCaml compiler + Reason version such as `Reason_v1_ocaml4_02_3`

**Comment by bobzhang** [comment]
@jordwalke hidden fact: ocaml accept raw ast directly, there is no need for a `-pp`

**Comment by jordwalke** [comment]
@bobzhang Really! That's convenient, because we wouldn't have to make a dummy `-pp` binary. How do you get it to work? Does it automatically detect the "magic number" used to encode marshaled structures?

**Comment by bobzhang** [comment]
Yes, it might bring some security issues though

**Comment by kennetpostigo** [comment]
Did the work that adds `ocaml-migrate-parsetree` help mitigate these issues? If so, would this be okay to close?

**Comment by jaredly** [comment]
esy is working toward this, and this issue is quite old
