### ISSUE TITLE
comment out code; refmt; uncomment code does not parse

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#537]
It is inconvenient that starting with code printed by refmt and commenting out some of it such that the rest still parses, applying refmt, and then uncommenting the code results in code that does not parse.

**Comment by jordwalke** [comment]
I've seen a couple cases where this would happen, but maybe you have a good tiny repro case.

**Comment by jberdine** [comment]
Here is one:
```
let exp_get_vars exp => {
  let rec exp_get_vars_ exp vars =>
    switch exp {
    | Lvar pvar => (fst vars, [pvar, ...snd vars])
    | Sizeof _ (Some l) _ => exp_get_vars_ l vars
    | Sizeof _ _ _ => vars
    };
  exp_get_vars_ exp ([], [])
};
```
Comment out the last case of the switch and refmt moves it out of the `}`.

**Comment by jordwalke** [comment]
Thanks, I considered that a separate bug in its own right.

**Comment by let-def** [comment]
It seems this occurrence is fixed. I tried to reproduce, the brace was not moved.

**Comment by kennetpostigo** [comment]
is this okay to close?
