### ISSUE TITLE
Not_found in refmt: two semicolons after a switch

### ISSUE THREAD

**Issue by Charlesetc** [facebook/reason#541]
refmt fails with Not_found error on this code:
```
let testcase => switch foobar {
  | 'a' => 1;
  | 'b' => 2;
  ;
}
```
Removing the extra semicolon fixes the problem.

This is the stack trace:
```
Fatal error: exception Not_found
Raised at file "src/reason_toolchain.ml", line 87, characters 10-13
Called from file "src/reason_toolchain.ml", line 233, characters 14-57
Called from file "src/refmt_impl.ml", line 12, characters 48-157
Called from file "src/refmt_impl.ml", line 153, characters 18-69
```

```
$ rebuild -version
ocamlbuild 4.02.3
$ opam list | ag reason
reason                  0.0.5 (pinned)
```
Might be related to #533

**Comment by yunxing** [comment]
Hi thanks for reporting! Should have been fixed on master now by #533 . Do you want to rebase to master and double check? Thanks.

**Comment by Charlesetc** [comment]
It did get better - it's now an "unkown syntax error". It does have line numbers etc

```
File "testcase.re", line 4, characters 2-3:
Error: 2483: <UNKNOWN SYNTAX ERROR>
```

**Comment by yunxing** [comment]
oh I intentionally put the msg there.

Some backgrounds: 

We use Menhir as a compiler to auto generate syntax error states. Each error message state comes with a state number (the one that you see after `Error`).

We then manually write corresponding error messages to represent each state in 'reason_parser.messages'. 

However, in some cases Menhir cannot recognize an error message state (`2483` in this case) in the database and throws `Not_found` exception. We need a generic error message to represent that kinds of states where its stateID cannot be found in `reason_parser.messages`  and I chose `<UNKNOWN SYNTAX ERROR>`.

**Comment by Charlesetc** [comment]
That makes total sense - thanks!
