### ISSUE TITLE
submit reason PR to github linguist

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#545]
https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language

I've started and dropped this a few times now. Part of me want to see Reason immediately recognized by github but part of me says we should meet the popularity criteria on that page first. I'll hold this off and wait for us to acquire some more credibility.

**Comment by jordwalke** [comment]
The Rust highlighting works for me in the mean time!

**Comment by chenglou** [comment]
Note for folks viewing this issue: if you put
```rust
/*
 * vim: set ft=rust:
 * vim: set ft=reason:
 */
```
At the top of your reason source file, the github heuristics will use [Rust](https://github.com/rust-lang/rust)'s language highlighting; Rust's syntax is similar than ours currently.

In the future, the ` * vim: set ft=reason:` line will act as a progressive enhancement if it ever becomes available.

**Comment by jordwalke** [comment]
@chenglou, Also if you have the `ft=rust` at the top, then you *need* the `ft=reason` after it in order for Vim to load Reason syntax instead of Rust, so it has two benefits.

**Comment by braibant** [comment]
Would it make sense to try to aggregate the github statistics accross OCaml and `reason`? I am confused by the classification of the latter as a separate language.

**Comment by jordwalke** [comment]
@braibant : I think that makes sense. It looks like it's possible to do this - `.ml` and `.mli` files are both considered OCaml files. The only thing I don't know how to do, is *append* to the existing OCaml linguist configuration by adding Reason syntax.

**Comment by braibant** [comment]
I would very much support that. @samoht is the one who apparently submitted the OCaml samples, so he might know what to do.

**Comment by lpil** [comment]
Any progress here? :)

**Comment by chenglou** [comment]
No answer here yet: https://github.com/github/linguist/pull/3336

**Comment by jordwalke** [comment]
For now, you can put this at the top of your file and it will highlight it reasonably well:

```
/*
 * vim: set ft=rust:
 * vim: set ft=reason:
 */
```

**Comment by Alhadis** [comment]
Hey guys. Sorry about the slow response from Linguist's side... I've posted a list of steps that need to be taken before we can get it merged. 👍 

@jordwalke There's a `.DS_Store` file that's been checked into the repository at [`editorSupport/VimReason/plugin/.DS_Store`](https://github.com/facebook/reason/blob/master/editorSupport/VimReason/plugin/.DS_Store)... you may wish to remove it. =)

**Comment by chenglou** [comment]
Removed DS_Store, thanks for spotting it =)

**Comment by Alhadis** [comment]
An automated process of mine did, actually. =) It recursively clears my system of Steve Jobs' toenails every hour or so, and I noticed it'd modified one of Linguist's submodules. Not the first time a `.DS_Store` file made its presence known like that, heh.

**Comment by lpil** [comment]
It seems the linguist PR had been merged. Can we close this?

**Comment by chenglou** [comment]
Yep! Thanks.
