### ISSUE TITLE
refmf configuration documentation

### ISSUE THREAD

**Issue by michelebelmonte** [facebook/reason#554]
A minor note: on the Reason Tools page (https://facebook.github.io/reason/tools.html), it is mentioned that in order to change refmf wrap line width, one has to select the Nuclide-Reason package. 

Is it possible the the package is atom-reason, instead? 
I can see a default refmf width property in the package, and I cannot find the Nuclide-Reason at all in the Manage View.

**Comment by SanderSpies** [comment]
Did you go to the Nuclide settings or Atom settings?

**Comment by michelebelmonte** [comment]
I checked, but nothing.
For example, under Nuclide, I can see nuclide-react-native and nuclide-remote-tags, but no nuclide-reason in between.

**Comment by SanderSpies** [comment]
First you have to install atom-reason-loader (as mentioned on https://facebook.github.io/reason/tools.html) to load all the necessary Reason plugins for Nuclide. Once you have installed it - you can go to settings -> packages -> atom-reason and change the refmt width property.

**Comment by michelebelmonte** [comment]
Hi Steve,
thanks for your help.
My initial point was not about the installation process of atom-reason-loader:
it worked straight out of the box.

My concern was about the fact that in the documentation page (https://facebook.github.io/reason/tools.html), it is mentioned that, in order to edit refmt default width, one has to modify the NuclideReason settings.
Maybe the page should mention atom-reason instead of NuclideReason.

In attach an image to clarify my point.
![refmt1](https://cloud.githubusercontent.com/assets/18641909/15653340/5de5368a-2684-11e6-9baf-28cf429bb03c.png)

**Comment by cristianoc** [comment]
Definitely a typo in the docs. Fixed in https://github.com/facebook/reason/commit/3a92cc563184bf5158648d67406276b94ce3152e.
