### ISSUE TITLE
Announcing reason on the ocaml mailing list

### ISSUE THREAD

**Issue by braibant** [facebook/reason#557]
Any reason, `reason` was not announced on the ocaml mailing list at this point? It seems to me that those changes might make it even harder for the existing ocaml community to understand and read code written with the `reason` syntax. It could a nice occasion be nice to benefit from an healthy discussion with the rest of the OCaml community (before iterating even more through syntax changes). 

(For instance, for me, #550 seems not that intuitive.)

**Comment by jordwalke** [comment]
No reason except lack of time, and wanting to have a better, easier to try out experience before broadcasting more widely (I'd like a js_of_ocaml top level to try immediately for example).
We didn't really expect Reason to get as much interest as it has already (1200+ stars in just a few days without much open source communication about it).

w.r.t. intuitiveness: While Reason *does* fix many of the pitfalls that experienced OCamlers report, the main goal was to fix pitfalls and friction that people totally *new* to the language typically experience. The choices we make to appeal to these different audiences will vary dramatically.
It's entirely possible that experienced OCamlers (who care primarily about collaborating with other OCamlers), won't find anything valuable in the new syntax, or even the upcoming build/namespace/share workflow. I think that's totally okay and those same people will likely enjoy the network effects of having more people care about their same underlying technology (at least I hope they would).
There are some tools in Reason that provide a nice small, very incremental path forward for the existing OCaml concrete syntax. Once you get all the syntax automatically formatted via Reason, you can *rapidly* evolve the syntax to be whatever you want it to be including a syntax that is mostly the same as the current OCaml syntax. It's not easy to accomplish such an automated formatter, but Reason has done so, or at least seeks to. Some have proposed that we can eventually use these same tools to help evolve the current OCaml syntax and I think that sounds great too.

**Comment by braibant** [comment]
I understand that there has been a lot of activity around `reason`, which probably comes from the fact that it was broadcasted quite widely on hacker news.  

I think that `reason` is a very nice, if not straightforward, idea at it's core: that is, it's possible to change the syntax of an existing language without changing its type-system, its semantics nor its runtime (which are for me the parts that define a language). With that idea, and the nice reformating tools, it's possible to have a tight update loop experimenting with the syntax; and I look forward to see a version of the reformating tools geared toward the existing OCaml syntax. (To be fair, I also look forward to see new work going on in other parts of the reason toolchain and ecosystem, and I am very excited about the idea of the `OCaml/reason` community growing and exchanging.)  

However, I think that part of the activity of `reason` comes from the fact that it builds on a mature language, with a mature (and still growing) set of libraries and community of users. One of the reasons I am pushing to announce reason on the OCaml mailing list is just to acknowledge that fact. 

The other reason I am pushing for taking into account the feedback of the existing OCaml community is that this community of users has built tools and systems and libraries, written books and resources. (And I expect new resources to be written for `reason`)  I think it would be *very* nice if those resources could be shared between people using the `reason` syntax, and people using the regular OCaml one. That is, I would really like the syntax of one flavor makes code, blogs or books being still understandable at first blush by the users of the other flavor (Otherwise, there is a risk of a split between the resources used by the two communities, and a risk of people having to make a choice between writing resources in one flavor or the other.)

**Comment by jordwalke** [comment]
These are all great points. I *will* make an announcement on the mailing list. I've merely got some non-reason related things to take care of for about one week, then I'll get back to preparing a note.

**Comment by chenglou** [comment]
Done!
