### ISSUE TITLE
poor formatting of comments between switch cases

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#559]
Consider:

```
let _ =
  switch x {
  | None
  | Some _ => ()
  };
```

If a comment is added between the cases:

```
let _ =
  switch x {
  | None
  /* between */
  | Some _ => ()
  };
```

then refmt is very heavy-handed:

```
let _ =
  switch x {
  | None
  | /* between */
    Some _ =>
    ()
  };
```

It would be good if the `|` and the pattern `Some _` weren't split up, and if the line breaking didn't change.

**Comment by tadeuzagallo** [comment]
I started looking into this but couldn't figure it out... This only happens with or patterns, the following is fine:
```swift
switch x {
  | None => ()
  /* between*/
  | Some _ =>  ()
}
```

I tried changing `interleaveComments` and rearranging the patterns in the `case_list` method in the printer, and also looked into how the `or_pattern` is parsed, I could change the line breaks, but couldn't move the comment to before the bar at any cost. I'd be happy to give it another try if anyone has some pointers.

**Comment by SanderSpies** [comment]
@tadeuzagallo I pretty much got to the same result. Did you try   listConfigIfCommentsInterleaved already? (Just discovered it, but no machine right now to try it).

**Comment by tadeuzagallo** [comment]
@SanderSpies I took a look at it, but all it does is allow you to change some configurations conditionally, but I couldn't find any config that produce the correct behaviour...

**Comment by tadeuzagallo** [comment]
Ok, I figured it out, I'll send a PR soon.

**Comment by chenglou** [comment]
Fixed!
