### ISSUE TITLE
indent-for-tab-command often reports errors

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#560]
Calling indent-for-tab-command in reason-mode often reports the error `indent-line-to: Wrong type argument: wholenump, -2` and fails to indent the line.

**Comment by yunxing** [comment]
Thanks, I've been seeing this as well and believe I have a reliable repo to it.

**Comment by yunxing** [comment]
This is the minimum case that I can reproduce: 
![image](https://cloud.githubusercontent.com/assets/1017689/16141353/93c6d112-340f-11e6-8c53-586618b81ab2.png)
