### ISSUE TITLE
Packages for ArchLinux AUR

### ISSUE THREAD

**Issue by clentfort** [facebook/reason#567]
This isn't really related to the core of reason but since there is no gitter/slack/irc or similar community (or I simply couldn't find it) I though I'd ask here:

I'm looking for some help in the creation of packages for the ArchLinux User Repository! My current PKGBUILDs can be found here: https://github.com/clentfort/reason-pkgbuilds I'd appreciate any help since I'm new to OCaml and new to the creation of AUR builds.

**Comment by yunxing** [comment]
@clentfort Thanks for the help! I haven't been working on AUR builds for a while. But if you run into any issues I can definitely help you to debug it. 

In the meanwhile, we do have a irc channel #reasonml. Feel free to ask any questions there or in this thread.

**Comment by kennetpostigo** [comment]
Is this okay to close? Discussion seems to have died down.
