### ISSUE TITLE
"switch x" vs "match x with"

### ISSUE THREAD

**Issue by spencerwi** [facebook/reason#568]
What's the motivating factor for changing `match x with` to `switch x`? I understand the reason for the braces, but it seems like changing to `switch` just makes Reason less compatible with OCaml, while also causing confusion with `switch-case` and losing some clear readability.

From a readability standpoint, I read the following:

```
match x with {
    Some y => y
    None => 0
}
```

as "match x with Some y and return y, or with None and return 0", where 

```
switch x {
    Some y => y
    None => 0
}
```

maybe reads as "switch x to Some y then y, or None then 0", which doesn't really convey the same thing to new developers. A move to `switch x` over `match x with` loses clear readability for the sake of keystrokes (incidentally, the opposite choice from the one taken with the braces/no-braces tradeoff).

Calling this `switch x` also confuses it with other languages' switch-case constructs, which _are_ less powerful than pattern-matching, which may lead users to believe that Reason's pattern-matching is similarly limited.

**Comment by jordwalke** [comment]
The later example is missing the "case bars". If you put those in the last example, and read them aloud as "case Some x", I wonder if that changes your mental flow when reading it.

> but it seems like changing to switch just makes Reason less compatible with OCaml

Reason is fully compatible with OCaml regardless of the particular syntax chosen for `switch`. I think you know this already, but I'm just clarifying for any readers out there who weren't aware.

> Calling this switch x also confuses it with other languages' switch-case constructs, which are less powerful than pattern-matching

This is now no longer true, with the introduction of Swift.

**Comment by spencerwi** [comment]
I just wrote my sample based on the current Reason documentation (http://facebook.github.io/reason/mlCompared.html#reason-and-ocaml-pattern-matching).

By "less compatible", I mean it's one more thing that I have to change if I'm migrating a codebase from OCaml to Reason. It's one more obstacle between having the same code "just work" for both OCaml and Reason, which, granted, it's a different syntax, but usually that syntax should have a good -- pardon the pun -- reason for being different.

And yes, sure, the brand-new, low-adoption language of Swift has misnamed their pattern-matching as "switch-case". But I'm talking about the majority of incumbent languages (Java, C, C#, Javascript, etc) that have a `switch-case` construct that's less powerful than pattern-matching. Far, _far_ more devs use Java/C/C#/Javascript than use Swift, and even then you have the problem where now it's a "well, which _kind_ of switch-case construct is this: the powerful one or the weak one?" instead of "oh, `match x with`...that sounds like pattern-matching. I can use destructuring here safely."

**Comment by yunxing** [comment]
Hi Spencer,

Good points about the two versions of switch-case -- powerful one and weak one. 

My understanding is that the `switch-case` in both family of languages (C/JAVA vs patterm matching) are serving the same purpose : you are changing the flow of a computation based on the value in runtime. If they are acting towards the same goal, they should have the same syntax. 

Regarding to the confusion of assuming between the powerful one and the weak one: Either assumption will be fine. If one assumes the `switch-case` in Reason is the weak one as in C, JAVA, the compiler will help him correct his assumption by pointing out cases that are not covered, thus "educating" him to build a new mental model using the strong one. If one assumes the `switch-case` in Reason is the powerful one, then he is also good and can use the same assumption in other languages (e.g., write more extensive switch-cases in C/JAVA).

**Comment by spencerwi** [comment]
Fair enough; I guess it's just an opinion question. At a certain point, I don't have to like Reason's syntax, and y'all don't have to change it based on my opinion.

It does leave me with a follow-up question: since I don't really care for most of Reason's syntactical changes, will there still be a way for me to use Reason's toolchain improvements with plain-old-OCaml? That's really the advantage I see with the effort around Reason.

**Comment by yunxing** [comment]
@spencerwi. Thanks, we really appreciate your opinion. Usually we look back at some certain proposals of syntax changes if there are big number of people demanding it. Sometimes we do also a internal vote to make a decision, but there is no formal process at this point.

Reason is not only about a syntax change. The goal is more about a more polished layer to boost up developer experience in a modern way. For example, we are working on to have more intuitive type error and syntax errors (thanks to [Menhir](http://gallium.inria.fr/~fpottier/menhir/) and [BetterErrors](https://github.com/chenglou/BetterErrors)). We will also leverage Jenga to provide an unified build system that would be much faster than existing one. 

Another vision that we have in the long run is to allow developers choose whatever syntax they want (Reason/OCaml) in their editor, but commit as only one language. If we can reach that point, people who prefer original OCaml syntax can also benefit from the efforts we are making here.

**Comment by yunxing** [comment]
Closing this for now and will back to this later if more people ask for it. Feel free to continue our discussion here.

**Comment by spencerwi** [comment]
Wow! That all sounds really exciting! It sounds exactly like what OCaml needs. Looking forward to seeing all this come to fruition -- I love OCaml, but its developer-workflow ergonomics are in need of exactly what you're building.
