### ISSUE TITLE
Rework ocamlfind packages

### ISSUE THREAD

**Issue by Engil** [facebook/reason#586]
Hello,

I am currently working on building a js_of_ocaml toplevel for Reason, and am facing a problem when using ocamlfind to retrieve Reason modules I need when compiling.

The main problem is that currently, `reason.lib` exposes too much modules and is unpractical when used in combination with js_of_ocaml (since for example `Reason_utop` doesn't play well with jsoo).

I think there is a need to split the several components of Reason inside smaller packages (for example, regrouping parsers and printers in separated packages).

I am not sure on how to separate nicely those packages, though. The only thing I need right now is moving `Reason_utop` away and exposing some more modules (`Reason_util` for example is exposing the function I need to parse a toplevel phrase, so having it exposed somehow would be nice.). So some feedback on what others needs would be nice before deciding anything. :)

(ping @bobzhang, who might be interested for Bucklescript/Reason)

**Comment by SanderSpies** [comment]
Related: #419.

**Comment by jaredly** [comment]
I think this is probably different at this point. feel free to reopen if it's still an issue
