### ISSUE TITLE
New syntax error under 0.0.6

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#592]
```rust
let now = fun () :time => {
  (0,0,0)
}
```

<img width="575" alt="screenshot 2016-06-15 15 01 52" src="https://cloud.githubusercontent.com/assets/1909539/16098890/238d9760-330a-11e6-8121-370ad673a747.png">

@yunxing

**Comment by yunxing** [comment]
@chenglou Are you still able to reproduce this? I can't reproduce it on my end.

```
~/p/ocaml $ cat try.re
let now = fun () :time => {
  (0, 0, 0)
}
~/p/ocaml $ refmt -parse re -print re try.re

let now () :time => (0, 0, 0);
```

**Comment by jordwalke** [comment]
I think @SanderSpies recently added support for this, correct?

**Comment by SanderSpies** [comment]
Correct, but also can't reproduce the issue with this code.

**Comment by jordwalke** [comment]
Cheng must have had an older version pinned (we likely haven't updated the readme to pin the newest version).

**Comment by yunxing** [comment]
@chenglou Are you still able to reproduce this issue now?

**Comment by chenglou** [comment]
Fixed, thanks.
