### ISSUE TITLE
Custom `-pp` just for `ocamldep` that makes recompilation more-incremental.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#595]
On the topic of ocamldep. Cheng found a bug in our use of ocamldep, that I imagine comes up quite frequently (It's not important, but basically we need to know that when someone refers to `Pack.Mod`, we're actually depending on `Mod`, because `Pack` might be the module alias namespace that *we ourselves* belong to, and that was opened via `-open`).

With our opinionated `jengaboot` rules for namespaceing (via module alias), we  are well positioned to avoid this particular pitfall and I think that we can include the solution in Reason out of the box. The solution I have in mind improves incremental recompilation as well.

- When we are in package `Pack`, we know what our dependencies' namespaces are (according to our opinionated jenga system, we read them from a `package.json/opam` file). We also know the name of the namespace that we are being compiled *into* (it's the name of the package!)
- Given that we're using opinionated JaneStreet style build rules, we know that `Dep1.X` is actually going to be compiled into a module artifact named `Dep1__X`.
- We can include a custom preprocessor named `-pp refmt-for-ocamldep`, which is the same as `-pp refmt`, but replaces `Dep1.X` with `Dep1__X` when we know that `Dep1` is one of our dependency package names, and replaces `Pack.X` to `Pack__X` when we know that `Pack` is the name of our own package.
- Not only does this solve that bug that we found in our use of `ocamldep`, but it will also allow *fine grained* dependencies to be detected *between* packages. This is really great because it means if I change a single file in a dependency package that I'm developing, recompilation will be *super* incremental. Currently, we just say "they changed something in a dependency `Dep1`, better recompile everything that depends on `Dep1`".

I know there's some discussion of improvements to module aliases coming, but this should work today in most cases (it's not perfect but neither is `ocamldep` right now).

**Comment by jberdine** [comment]
Just to confirm, you're already using '-no-alias-deps', right?

**Comment by jordwalke** [comment]
Yes.

**Comment by jordwalke** [comment]
Or do you mean as in argument to ocamldep

**Comment by jberdine** [comment]
Ok.  I didn't mean to ocamldep.

I'm not sure I understand.  Suppose there are two modules Dep.X and Dep.Y within "package" Dep.  Is it expected that the code of X can refer to Dep.Y?  I would have expected not, and that Y without Dep. would need to be used.  Why?  I'm not sure, but that's what my immediate expectation is.  Perhaps referring to Dep from a module that forms part of Dep is too close to a recursive reference to be comfortable.

To me this seems independent of being able to track dependencies to modules of packages, instead of to entire packages.

**Comment by chenglou** [comment]
@jordwalke we should update this with the `as-map` findings

**Comment by jordwalke** [comment]
Yes, as-map in 4.03 might do exactly what we want.

**Comment by jordwalke** [comment]
Closing because as-map likely does what we want and we may make Reason 4.03+ only.
