### ISSUE TITLE
[Atom-Reason] selectOccurences  (alt + d) seems to be broken

### ISSUE THREAD

**Issue by SanderSpies** [facebook/reason#599]
Selects too many items - also those out of the current scope. 

(previous comment was incorrect).

**Comment by SanderSpies** [comment]
For example, I have a .re file with the following contents:
```
let foo bar =>
   bar ^ "!"

let foo2 bar =>
   bar + 2
```

and navigate the cursor to the second bar and press `alt + d` all the bars are selected. Merlin however correctly only gives the first two bars. So something goes wrong within Atom.

**Comment by SanderSpies** [comment]
It just works fine - I was mixing up the highlighted and selected area because the selected area looks way too much like the non selected.

**Comment by chenglou** [comment]
Ahhh I had that problem too. We can tweak the Atom styles or something.
