### ISSUE TITLE
Array indexing and assignment syntax feels funny

### ISSUE THREAD

**Issue by bslatkin** [facebook/reason#605]
Here's a simple program:

```
let myArray = Array.of_list [1, 2, 3, 4];
Printf.printf "My array is %s\n" (Batteries.dump myArray);
myArray.(2) = 7;
Printf.printf "My array after is %s\n" (Batteries.dump myArray);
let z = myArray.(1);
Printf.printf "Number is %d" z;
```

Some things about this:
1. Is it possible to make the syntax be `myArray[2] = 7` instead of `myArray.(2) = y`?
2. Could `myArray[1]` be used to access a value instead of `myArray.(1)`?

This may be similar in spirit to #356 about the syntax for interacting with `ref`s.

Another thing to note here is the string access syntax uses `[x]` instead of `(x)` which makes this even more confusing. Would it be possible to use `[x]` in both cases?

**Comment by braibant** [comment]
In a nutshell, being able to use the same syntax for string access and array access requires to be able to discriminate on the type of the thing you access. OCaml (for which `reason` is a frontend) does not support this kind of ad-hoc polymorphism, and uses different functions (with different types) for string access and array access. Those different functions have different notations and all goes well. There are proposals in OCaml to add support for [modular implicits](http://arxiv.org/pdf/1512.01895.pdf) which would provide ad-hoc polymorphism and the way to use the same notation for accessors (among other nice things).

**Comment by kennetpostigo** [comment]
Discussion here seems to have died down, is there any work to make room these changes? If not, is this okay to close?

**Comment by hcarty** [comment]
This may be worth revisiting if modular implicits or something like https://github.com/ocaml/ocaml/pull/616 ever make it into the language.

**Comment by chenglou** [comment]
This is now fixed
