### ISSUE TITLE
`inherit` in mli file gets pretty printed wrong

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#606]
The title says it all.

OCaml code:

``` ocaml
class type
    something =
        object
        inherit Wrappee.t
    end
```

becomes

``` rust
class type something = {
  inherit new Wrappee.t
};
```

I'm guessing the `new` keyword isn't supposed to be there.

**Comment by bsansouci** [comment]
Seems like this is where the pretty printer goes rogue: https://github.com/facebook/reason/blob/ab6ba1cd01d800bd9cbfb4b5afd3928169e1964b/src/reason_pprint_ast.ml#L4518-L4519 :p

**Comment by jaredly** [comment]
fixed
