### ISSUE TITLE
Push reason to opam official repo

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#608]
Instead of asking people to pin all the packages, we need to push Reason to the official repo. This way projects in the official repo can just specify reason as a dependency in their opam files.

My understanding is that we have three to-dos:
- Add Merlin-extend as a official opam package
- Update Merlin opam package itself (should be done)
- Add Reason as a official opam package

**Comment by kennetpostigo** [comment]
I think this work has gone through to opam, is this okay to close?

**Comment by chenglou** [comment]
Yep!
