### ISSUE TITLE
Has trouble with user defined infix operator

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#609]
The operator in question is `let (->*) = fun a b => a + b;` and I get 4 "Invalid module item" on that line.
I'm not too sure if this is a parsing issue, or a known ocaml thing (the `*` is causing the problem).
If I switch to `*->` then I get no more error.
In comparison `->+` and `->-` both work.

For `let (->\) = fun a b => a \ b;` I get "invalidCharacter.orComment.orString" due to the `\`. Again, not too sure if that's supposed to happen or not. And `\->` works.

**Comment by SanderSpies** [comment]
Seems that Reason requires you to write a `\` before `*`. `let (->\*) = fun a b => a + b;` does work. Within OCaml it just works fine. It also removes the `\` when converting to OCaml.

**Comment by bsansouci** [comment]
@SanderSpies It seems to me like we don't want this behavior because an extra `\` really changes the look of an infix operator lol.

**Comment by SanderSpies** [comment]
@bsansouci Agreed - we should fix this.

**Comment by yunxing** [comment]
Agree, this is also making some converted ocaml programs become ugly since they have some operators that involve "*" and "/".

**Comment by anmonteiro** [comment]
Can't repro on current master.

**Comment by Lupus** [comment]
Looks like there are stil issues with operators with `/` inside. The following code snippet is formatted from OCaml and results in syntax error ([try link](https://reasonml.github.io/en/try?rrjsx=true&reason=DYUwLgBATg9grmEBnCBeAUBCAleikB0AFJlhAJIB2AZgJYAexpZEAEgIaUAmoUhJLFgHdaYABYB9ALbgxMLkQDazQViIADAOIBRACoAaaODhRKEgEa0A5kjBRalKxAA8AEgggpABzABPAJT6KqoaOgYQVlAg4CBQLq4AfBBIRABEkdFgqf4QAFRJDpDOAPRJtnElZXaBwYKheoZIcFLxZWlNUtl5BZSQRJU5hTWqWAC6-rUTLFMQ-gDc6EA)), until I escape (use `<\/>` operator instead):

```reason
let routes =
  Routes.(
    Infix.(
      Handlers.(
        with_method([
          (`GET, return_bigstring <$ empty),
          (`GET, greeter <$> s("greet") *> int </> str </> str),
          (`GET, sum <$> s("sum") *> int (</>) int),
        ])
      )
    )
  );
```

**Comment by Lupus** [comment]
What's even worse, refmt removes those escapings, making the code unparseable again :-/ @chenglou should I open a separate issue on this matter? Or may be you could reopen this one?
