### ISSUE TITLE
Lots of noise in .messages

### ISSUE THREAD

**Issue by SanderSpies** [facebook/reason#611]
This is bad for reviewing. 

For my local reviewing I'll probably use a search and replace regexp that removes all the state numbers with an empty string. This way I'll be able to actually see what changed, perhaps we could add something like this to the repo?

**Comment by yunxing** [comment]
Hmm, the states are there for debugging purpose so I'm not sure if we can just remove them. 

Two things I think we can do are:
- Treat .messages as a binary file in git, so it won't show up in git show / diff.
- Have a separate projected file that is generated by filtering out all the state numbers in the original .messages file as you mentioned. So people can just review that file instead.

**Comment by SanderSpies** [comment]
Yeah, the second item is exactly what we need.
