### ISSUE TITLE
JSON notation in Reason

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#634]
it would be nice that 

``` ocaml
{ x : [ { y : 3 } , {y : 3 } ] }
```

is legal syntax.

The only missing part is currently Reason use `[||]` for Array notation, with the BukleScript backend, we can literally compile it into JSON: https://github.com/bloomberg/bucklescript/blob/master/docs/OCaml-call-JS.md#ffi-to-js-plain-objects

This means we can get simple type provider for free

**Comment by chenglou** [comment]
Could you give an example of how we'd get type providers for free here?
Also, not sure that BuckleScript should tie itself to a particular Reason syntax (since the goal is that the syntax is local and customizable, etc.). But that's up to you of course =)

**Comment by bobzhang** [comment]
here json notation is static, not by parsing, so currently in bucklescript:

```ocaml
let u  = [%bs.obj  [|  { x = { y = [|1; 2; 3|] } } |]
```

`u` is inferred as (at compile time)

```ocaml
val u : [%bs.obj < x : < y : int array > > ]
```

since bucklescript also compile tuples as an array, you get heterogenous array (via tuple) and homogenous array (via array), which will cover most daily use cases.

So if Reason changes array syntax to JS's array notation, it would mean user could write JSON in reason, they get strongly typed data structure.

Only a little tweak to Reason's array syntax would make it much more friendly to JS developers

**Comment by chenglou** [comment]
Ok that makes sense. Once Reason gets to the point where the syntax becomes truly local, we'll be able to have such easily. Right now, all that's left is the debate of whether we should encourage list or array to be the ocaml default.

**Comment by jaredly** [comment]
we now have `{"obj": "val"}` syntax!
