### ISSUE TITLE
Create monolithic bytecode build of [Jengaboot] for distribution.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#640]
[`jengaboot`](https://github.com/chenglou/jengaboot) has two components. A statically compiled build system `jenga`, and then a dynamically loaded `jengaRoot` file. We want to distribute `jenga` to hosts without them having to compile it, in a cross platform manner. However, we can't just use the bytecode version of `jenga` because the bytecode `jenga` can't dynamically load `jengaRoot` (it's an unrelated issue, but still blocking us). So instead, we can "fuse" the `jengaRoot` into `jenga` to do a custom build of `jenga` that doesn't dynamically load whatever `jengaRoot` you have in the directory - instead it has it precompiled into `jenga`. Then we can distribute the bytecode version of that. This will work on `npm` or on `CI` servers without network access and without having `opam` available.

**Comment by chenglou** [comment]
Tracked in https://github.com/reasonml/rebel/pull/27

**Comment by chenglou** [comment]
gg jengaboot
