### ISSUE TITLE
change `let open Foo` to be `open Foo`.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#641]
I think the `let` is excessive, let's just use `open Foo` even when opening locally in scope.

**Comment by jordwalke** [comment]
It should be pretty easy, so tagging `Good First Task`.

You might as well support both `let open Foo` and `open Foo` but have the printer print the later. Then one day we can remove support for `let open Foo` altogether.

**Comment by chenglou** [comment]
More discussion on https://github.com/facebook/reason/issues/672#issuecomment-239038845

**Comment by jordwalke** [comment]
Also, we have another task for changing `let module X` to be `mod X`: https://github.com/facebook/reason/issues/26

It would go nicely with this task.
