### ISSUE TITLE
"Ternary" not parsed correctly

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#642]
I discovered the following example is not parsed correctly.

```
 something.contents = isUndefined (childHeight.contents) ? X : Y;
```

Is parsed as.
```
 (something.contents = isUndefined (childHeight.contents)) ? X : Y;
```

Which I suppose makes sense as a lexical interpretation of the statement, but it's not intuitive, and not what you would expect. It's also never a valid program (the result of an imperative assignment is `unit`, which could never be `true/false`).

**Comment by jordwalke** [comment]
Some things to test in type checked unit tests:

```
let x : unit = something.contents = func call ? A : B;
something.contents = func call ? A : B;
(something.contents = func call ? A : B) : unit;
```

**Comment by ak3n** [comment]
Should I open a new issue for `(something.contents = func call ? A : B) : unit;`? Because it's not accepted by parser right now.

**Comment by jordwalke** [comment]
Did you see this PR?
https://github.com/facebook/reason/pull/702


Also, type assertions `:` (in general) must be wrapped in parens. There are only a few places where we relax that requirement such as `let x : int = 2;` and tuples `(2: int, 5: int)`.

**Comment by chenglou** [comment]
This is done right?

**Comment by jordwalke** [comment]
Yes.
