### ISSUE TITLE
BuckleScript `##` and `#=` don't compile

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#652]
cc @yunxing @bobzhang @fxfactorial. (Related: #650) Repro:

```
## http createServer;
```

(Original OCaml code is `http##createServer` [here](https://github.com/bloomberg/bucklescript-addons/blob/cb493954288ae63bfb08726771ae79334e838628/examples/node-http-server/src/test_http_server.ml). Reason uses prefix notation).

`bsc -pp refmt -impl test.re` errors with:

```
File "test.re", line 1, characters 0-1:
Error: 0: <SYNTAX ERROR>
```

**Comment by Schmavery** [comment]
Do we maybe just need to recognize it as an identifier and make sure reason doesn't die on it? Then we can run the regular ## preprocessor on the .ml code?
This seems to be blocking the regular use of js bindings. When we wrote reason code with js_of_ocaml we had to use the workaround of writing the code that the preprocessor generates (which works fine but ## is more convenient).

**Comment by jordwalke** [comment]
@Schmavery : This sounds correct. It should be just a matter of looking at what OCaml's parser does and then recreating it in the Reason parser. Another Good First Task (tagging as such). Let me know if this begins to block you on something and we'll elevate the priority.

**Comment by bobzhang** [comment]
If Reason moves in the direction to avoid `#` operator in the concrete syntax, that would be cool (better `cpp` compatibility is a huge win)
For example, if we decide to use `..` for Js object method dispatching, we don't need go through ppx, the `##` rewrite rule(at least for BuckleScript) is pretty simple, so we can directly construct the AST node without ppx.

**Comment by chenglou** [comment]
Resolved already =)
