### ISSUE TITLE
/* let a = [%bs.obj {hi: a" [@bs]}]; */ fails to parse

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#660]
cc @yunxing

**Comment by jordwalke** [comment]
The string is not balanced inside of the comment, correct?

**Comment by chenglou** [comment]
Right. I keep forgetting ocaml tries to parse what's inside...

**Comment by yunxing** [comment]
@chenglou Interesting. I didn't ocaml tries to parse what's inside.

**Comment by chenglou** [comment]
Nested comments work

**Comment by jordwalke** [comment]
It's actually reason lexer that is doing this - forked from OCaml's.

**Comment by jaredly** [comment]
the PR was abandoned b/c it would break ocaml compat
