### ISSUE TITLE
What does "Const" mean in Reason?

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/reason#665]
I am trying to understand what this means:
```
let is_null_literal =
  fun
  | Const (Cint n) => IntLit.isnull n
  | _ => false;
```
Is this an in-built type/expression in Reason, or a user-defined type in the codebase I'm studying?

**Comment by yunxing** [comment]
Probably a user defined constructor that is imported by an "open" statement at the beginning of the program (I assume you are studying Infer, so this is where the type is defined: https://github.com/facebook/infer/blob/c147ab419712f8df7aaf0ff55d5211a970b5e39d/infer/src/IR/Exp.re). Once you have atom plugin installed, you can also try to set up [Merlin](https://github.com/the-lambda-church/merlin) and jump to the definition very easily.

**Comment by yunxing** [comment]
Feel free to comment here if you have other questions.

**Comment by jberdine** [comment]
> I am trying to understand what this means:
> ```
> let is_null_literal =
>   fun
>   | Const (Cint n) => IntLit.isnull n
>   | _ => false;
> ```
> Is this an in-built type/expression in Reason, or a user-defined type in the codebase I'm studying?

It's not builtin.  merlin-locate should jump to its definition, which is in https://phabricator.intern.facebook.com/diffusion/INFER/browse/master/infer/src/IR/Const.re

**Comment by jberdine** [comment]
> Probably a user defined constructor that is imported by an "open" statement at the beginning of the program

This is actually type-based resolution, not "open", FWIW.

**Comment by xennygrimmato** [comment]
Thanks, this is really really useful!
I have ocamlmerlin installed along with nuclide.
Are there any other useful packages that you suggest I can install to speed up development, or some shortcut-commands?

**Comment by jordwalke** [comment]
> This is actually type-based resolution, not "open", FWIW.

@jberdine What did you mean by this? When I think type based resolution, I think modular implicits. What were you referring to?

**Comment by jberdine** [comment]
See http://caml.inria.fr/mantis/view.php?id=5759 for some context.  Now that you ask, this feature seems to be pretty hard to find.  Basically, if the type-checker knows what type an expression must have, it can allow using fields and constructors from that type without module qualification.  In infer we compile with -principal to ensure that any such resolutions are done in a completely unambiguous way.  In practice, this means that often code can add a few type ascriptions to function parameters and then avoid a lot of module names in the body, without needing "open".  Only for constructors and fields, not module values though.

**Comment by jberdine** [comment]
Also see Alain's blog post:
https://www.lexifi.com/blog/type-based-selection-label-and-constructors
