### ISSUE TITLE
`npm` installation workflow (Master Task)

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#668]
We have some really good use cases for wanting to install `Reason` via `npm`.
- First and foremost, our Nuclide IDE project is built using `npm` packages, and we want to give first class support to `Reason` in Nuclide. By adding `npm` support to `Reason`, people will be able to install the entire toolchain right from inside the editor.
- CI deployments, where we need to copy over entire trees of source files before beginning to build. `npm` supports this pretty easily.
- Make it easier for `JS` developers to get started, since 99% of them already have `npm` installed, it eliminates one step.
- Remove the barrier to sharing of dependencies, since even official `npm` packages can depend on `git` URLs. This means that people can commit and share experiments in a lightweight manner without requiring review, and without any special commands (they are still installed via `npm install` like any other package).

You can get a sense for the new workflow here:

```
git clone https://github.com/reasonml/ExampleProject.git
cd ExampleProject
npm install
```

Then the project and all its dependencies are installed, including the OCaml compiler, and Reason. You'll see a `Test.exe` as a result. The executables are built on the architecture, by the source, so the first time you install a project it takes a few minutes for all the dependencies.
### Remaining Work
- [ ]  [Make editor plugins use `node_modules` for plugin source, `merlin`, and `reason`](https://github.com/facebook/reason/issues/648)
- [ ]  Create automatic adapter for `opam` packages so that we could:
  - Have a script that automates packaging up `opam` packages as `npm` dependencies.
  - Or eventually (not immediate goal), have the package manager resolve `opam` dependencies on the fly using the official opam repo.
  - (Much longer term), convert an `npm` package back to `opam`.
- [ ] [Include a lighter weight top level](https://github.com/facebook/reason/issues/667)

**Comment by jaredly** [comment]
bs-platform + reason-cli get this done :)
