### ISSUE TITLE
Problem in understanding a line from Facebook Infer's source code

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/reason#669]
Can someone help me understand what [this line](https://github.com/facebook/infer/blob/master/infer/src/IR/Sil.re#L55) means? I am trying to understand Reason syntax, while going through the source code of infer.
In OCaml, I know about user-defined types with a single type given after "of", but I do not know the behaviour when multiple types are mentioned after the "of" keyword.

**Comment by yunxing** [comment]
This means `Call` is a constructor with five arguments: 
their types are: (list Ident.t), Exp.t, (list (Exp.t, Typ.t)), Location.t and CallFlags.t

(Feel free to join @reasonml or https://gitter.im/facebook/reason for more realtime answers)
