### ISSUE TITLE
Merlin is not listed among the dependencies in the opam file

### ISSUE THREAD

**Issue by martinoluca** [facebook/reason#67]

**Comment by jmmk** [comment]
It looks like this is already complete? The `depends` list in `opam.in` looks like:

```
depends: [
  "easy-format"  {>= "1.2.0"}
  "ocamlfind"    {build}
  "utop"         {>= "1.17"}
  "menhir"       {>= "20160303"}
  "merlin"       {>= "2.5.0"}
  "merlin-extend"{>= "0.3"}
]
```

**Comment by jordwalke** [comment]
I actually don't think that merlin should be in the dependencies now. Only merlin-extend. If a project template wants to include merlin as a dependency, that would be a good thing to do there, but no in Reason directly. (We want to remove as many dependencies as we can).

**Comment by jmmk** [comment]
@jordwalke is this related: https://github.com/facebook/reason/pull/892?

**Comment by yunxing** [comment]
We removed merlin from the dependency list since people should add it as a dev-dependency of their project only if they need it.

**Comment by yunxing** [comment]
@jmmk Merlin is still listed as a dependency in opam.in and opam, do you mind send a PR and remove it?

**Comment by chenglou** [comment]
Superseded! We no longer depend on Merlin. Thanks and sorry for taking so long.

**Comment by jmmk** [comment]
@chenglou does that mean that it should indeed be removed from the opam files?

**Comment by chenglou** [comment]
oh, yeah I think. @yunxing Merlin isn't needed even by our opam setup anymore, right?

**Comment by yunxing** [comment]
@chenglou No, let's remove it.
