### ISSUE TITLE
[atom-reason] type hint for module has lots of empty space

### ISSUE THREAD

**Issue by jaredly** [facebook/reason#671]
could be tightened up a bit

<img width="904" alt="moreact_re_ __users_jared_clone_rsn" src="https://cloud.githubusercontent.com/assets/112170/17533172/e36a5878-5e40-11e6-9c5f-5df930a6101c.png">

**Comment by chenglou** [comment]
Hah, I just got that too! Also in a BS file. I wonder why. Ppx?

**Comment by chenglou** [comment]
@jaredly also, did you happen to use https://github.com/facebook/reason/issues/663#issuecomment-238466614

**Comment by jaredly** [comment]
yup. before that nothing was  showing up

**Comment by jaredly** [comment]
but it looks like a flowtype thing where type definitions have been replaced with blank lines

**Comment by jaredly** [comment]
well this is weird. It doesn't even include the whole type definition, and it puts in a bunch of blank space that I don't understand... 

![moreact_re_ __users_jared_clone_rsn](https://cloud.githubusercontent.com/assets/112170/17759763/97e95034-64b7-11e6-8930-d05f4712c638.png)

**Comment by chenglou** [comment]
Found the culprit:

![screenshot 2016-09-28 14 00 26](https://cloud.githubusercontent.com/assets/1909539/18932160/0a9ab162-8584-11e6-8e96-1a8ae2c37260.png)

I wonder what we can do about it.
