### ISSUE TITLE
analogue of `let open M in` that does not indent body

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#672]
I miss an analogue of `let open M in` that does not indent the body.  Am I overlooking something, or is the only way `M.(...)`, which when the body doesn't fit on a line is suboptimal due to excess indentation.

**Comment by chenglou** [comment]
`let open M;` works. The printer prints it into `M.()` because they're equivalent. I'll merge this into #641! cc @jordwalke

**Comment by yunxing** [comment]
Do you have an example where the body doesn't fit into one line? If it is a structure like M.({let a = a; a})

I think we have some syntax sugar like 
```
M.{
  let a = 1;
  a
} 
```
(if we have ever implemented it) that does break.

**Comment by jberdine** [comment]
I had just a long function application which broke the args onto separate lines, so I guess no sugar for that.

**Comment by yunxing** [comment]
how about something like ?
M.(
  F 
    arg1
    arg2 
    arg3
    ...
)

**Comment by jberdine** [comment]
Yes,

let f x =>
  M.(
    ...
  )

works, but it is an excess indent compared to

let f x =>
  let open M;
  ...

And when the scope of the module open is the entire body of the let binding, the indentation doesn't make anything any clearer.
