### ISSUE TITLE
Change `unit` to `void` for type declaration

### ISSUE THREAD

**Issue by SanderSpies** [facebook/reason#678]
Perhaps I'm missing something, but this seems like an obvious improvement.

Requires great search and replace skills.

**Comment by jberdine** [comment]
But 'unit' is the technically correct name.

**Comment by SanderSpies** [comment]
That is correct (see also: https://en.wikipedia.org/wiki/Unit_type).

However this aligns us closer to Flow - which is what I would prefer.

**Comment by hcarty** [comment]
But it's not void, which implies nothing. unit is a value. `f void void void` doesn't really make sense but `f () () ()` does.

**Comment by SanderSpies** [comment]
@hcarty apologies for the confusion, but this is about type declaration - what you mentioned should therefore stay the same.

**Comment by hcarty** [comment]
It's still a similar issue though, correct?  `void => void => void => ...` doesn't make much sense as a type definition.

**Comment by cristianoc** [comment]
Typically there is one element of unit type, but zero elements of void type.

**Comment by jordwalke** [comment]
It seems to me that `void` and `unit` are really not so different. Is there really a difference between a type with exactly one instance, and a type with zero instances but where that lack of instance must always be acknowledged? (Maybe not?)

But because of argument types, it seems hard to come up with a way to represent `unit` as `void` syntactically that is not going to confuse people.

**Comment by cristianoc** [comment]
I was thinking specifically about one aspect: that having nonzero instances is really the only choice for e.g.
```
  f : unit -> unit -> unit
```
Otherwise there's no way to call `f`.

**Comment by jberdine** [comment]
A properly supported `void` type would make sense semantically e.g. as the return type of `exit : int -> void` or `raise : exn -> void`.  But I expect that getting such things to be conveniently usable is not possible without essentially returning to the polymorphic return types.

**Comment by jordwalke** [comment]
@cristianoc Could `f ()` just be thought of as invoking `f`, but with zero arguments? Can `()` just be thought of as a way to say "and there are zero instances of the expected ?

**Comment by cristianoc** [comment]
@jordwalke one would need to interpret `f ()` in a special way, also `f () ()`, but then what about `let x = () in f x x`.

**Comment by jordwalke** [comment]
Yeah, I think with `let x = () in f x x`, the analogy begins to break down.

**Comment by jaredly** [comment]
this is quite stale, feel free to raise again if interested
