### ISSUE TITLE
Invalid record spread syntax

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#689]
```
{...foo};
```

This is invalid syntax. `[...bar]` works and prints as plain `bar`; for consistency, `{...foo}` should print as `foo`.

**Comment by jordwalke** [comment]
one question: Is it confusing that `{...foo}` would become `foo`? I believe the ES6 spread is supposed to make a new allocation when using `{...}` (which matters when there are mutable fields etc).

**Comment by chenglou** [comment]
Yeah mutable fields kinda suck here. Dunno but it shouldn't throw a syntax error I think.

**Comment by yunxing** [comment]
![image](https://cloud.githubusercontent.com/assets/1017689/17866097/165812ca-685a-11e6-8210-8158e5b446e2.png)

As discussed in #704, the diff works on syntax level, but fails at invariants in the compilation. Reopening the issue and will continue discussion in the diff.

**Comment by SanderSpies** [comment]
Close please
