### ISSUE TITLE
Old reason variant syntax with `of` accidentally prints correctly into ocaml

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#690]
cc @sanderspies
Repro:

```
type foo = A of string;
```

prints to:

```
type foo =
  | A of of* string
```

Without good tooling, it's hard to know why this happened. Maybe we should put a temp warning. Or maybe we should just let this be since people will upgrade.

**Comment by jordwalke** [comment]
Could you clarify what's happening here?

There's no issue converting `type foo = A string;` correct? It's only when you include the `of` token?

**Comment by chenglou** [comment]
Right. I forgot that some of my projects (jengaboot in this case) were still on the old `of` syntax and didn't use `reup` to convert. I ran `refmt` directly to convert to ml but Instead of erroring, they successfully got refmt-ed over to an invalid ocaml syntax.

**Comment by chenglou** [comment]
Generally this scenario probably doesn't happen often. If it does then it's tricky to debug because there's currently no way of knowing which version a file is (metadata outside of the file can get lost). If we ever have a mechanism that knows which version a file is by only looking at the file (e.g. comment header), we should take advantage of that.

Or we can just hurry up and get local syntaxes already. Can't wait!

**Comment by SanderSpies** [comment]
That should not be possible. I removed the of keyword from the lexer. Seems
like something is stuck on your system?

**Comment by chenglou** [comment]
refmt master:
```
echo "type foo = A of string" | refmt -use-stdin true -parse re -print ml -is-interface-pp false
```

**Comment by jordwalke** [comment]
So could it be a problem with the OCaml printer?

**Comment by yunxing** [comment]
As long as we don't parse "of" as a constructor argument, it should be fine.
