### ISSUE TITLE
Can't build atom-reason on Ubuntu 16.04

### ISSUE THREAD

**Issue by vramana** [facebook/reason#705]
When I try to build atom-reaon, I get the following errors

```
> atom-reason@0.0.4 start /home/vramana/Documents/facebook/reason/editorSupport/atom-reason
> compile && cp _build/top/app.{js,map} ./output_byte_debug_js

*** jenga: [1779] root=/home/vramana/Documents/facebook/reason/editorSupport/atom-reason, sys=Linux, j=7, f=2 (NO_VERSION_UTIL)
*** jenga: reading node_modules/jengaboot/jenga.conf (jengaroot)
*** jenga: finished reading node_modules/jengaboot/jenga.conf (2ms)
- build . scheme
+ bash -c 'ocamldep -pp refmt -ml-synonym .re -mli-synonym .rei -modules -one-line -impl src/Merlin.re'
src/Merlin.re:
Fatal error: exception Not_found
File "src/Merlin.re", line 1:
Error: Error while running external preprocessor
Command line: refmt 'src/Merlin.re' > /tmp/ocamlpp7ade51

- exit . scheme, 6ms, exited with code 2
- build . scheme
+ bash -c 'ocamldep -pp refmt -ml-synonym .re -mli-synonym .rei -modules -one-line -impl src/Atom.re'
src/Atom.re:
Fatal error: exception Not_found
File "src/Atom.re", line 1:
Error: Error while running external preprocessor
Command line: refmt 'src/Atom.re' > /tmp/ocamlpp3e87ba

- exit . scheme, 7ms, exited with code 2
- build . scheme
+ bash -c 'ocamldep -pp refmt -ml-synonym .re -mli-synonym .rei -modules -one-line -impl src/Nuclide.re'
src/Nuclide.re:
Fatal error: exception Not_found
File "src/Nuclide.re", line 1:
Error: Error while running external preprocessor
Command line: refmt 'src/Nuclide.re' > /tmp/ocamlpp448182

- exit . scheme, 8ms, exited with code 2
*** jenga: 20/23 targets are up to date
*** jenga: failed (#1, 13ms, heap=204.312m, stat=73, digest=0, ls=2, db-save=0)
*** jenga: todo: 0 (20 / 23) !2 ~1 j=0+0 con=23 save=0 act=3, finished
*** jenga: ERROR: (summary) _build/top/app.out: External command failed
      - build . scheme
      + bash -c 'ocamldep -pp refmt -ml-synonym .re -mli-synonym .rei -modules -one-line -impl src/Merlin.re'
      src/Merlin.re:
      Fatal error: exception Not_found
      File "src/Merlin.re", line 1:
      Error: Error while running external preprocessor
      Command line: refmt 'src/Merlin.re' > /tmp/ocamlpp7ade51
      
      - exit . scheme, 6ms, exited with code 2
*** jenga: ERROR: (summary) _build/top/app.out: External command failed
      - build . scheme
      + bash -c 'ocamldep -pp refmt -ml-synonym .re -mli-synonym .rei -modules -one-line -impl src/Atom.re'
      src/Atom.re:
      Fatal error: exception Not_found
      File "src/Atom.re", line 1:
      Error: Error while running external preprocessor
      Command line: refmt 'src/Atom.re' > /tmp/ocamlpp3e87ba
      
      - exit . scheme, 7ms, exited with code 2
*** jenga: ERROR: (summary) _build/top/app.out: External command failed
      - build . scheme
      + bash -c 'ocamldep -pp refmt -ml-synonym .re -mli-synonym .rei -modules -one-line -impl src/Nuclide.re'
      src/Nuclide.re:
      Fatal error: exception Not_found
      File "src/Nuclide.re", line 1:
      Error: Error while running external preprocessor
      Command line: refmt 'src/Nuclide.re' > /tmp/ocamlpp448182
      
      - exit . scheme, 8ms, exited with code 2
*** jenga: build finished; not in polling mode so quitting
*** jenga: Quit; exit_code = 1
```

This is the list of installed opam packages.
<details>
<summary>opam list</summary>
#### Installed packages for 4.02.3:
ANSITerminal                0.7  Basic control of ANSI compliant terminals and the windows shell.
async                 113.33.03  Monadic concurrency library
async_extra           113.33.03  Monadic concurrency library
async_find            113.33.03  Directory traversal with Async
async_inotify         113.33.03  Async wrapper for inotify
async_kernel          113.33.03  Monadic concurrency library
async_parallel        113.33.03  Distributed computing library
async_rpc_kernel      113.33.03  Platform-independent core of Async RPC library
async_unix            113.33.03  Monadic concurrency library
base-bigarray              base  Bigarray library distributed with the OCaml compiler
base-bytes                 base  Bytes library distributed with the OCaml compiler
base-ocamlbuild            base  OCamlbuild binary and libraries distributed with the OCaml compiler
base-threads               base  Threads library distributed with the OCaml compiler
base-unix                  base  Unix library distributed with the OCaml compiler
base64                    2.0.0  Base64 encoding and decoding library
batteries                 2.5.2  a community-maintained standard library extension
BetterErrors              0.0.1  Better compiler error output.
bin_prot              113.33.03  A binary protocol generator
biniou                   1.0.12  Binary data format designed for speed, safety, ease of use and backward compatibility as protocols evolve
camlp4                   4.02+7  Camlp4 is a system for writing extensible parsers for programming languages
camomile                  0.8.5  A comprehensive Unicode library
cmdliner                  0.9.8  Declarative definition of command line interfaces for OCaml
conf-m4                       1  Virtual package relying on m4
conf-ncurses                  1  Virtual package relying on ncurses
conf-pkg-config             1.0  Virtual package relying on pkg-config installation.
conf-which                    1  Virtual package relying on which
core                  113.33.03  Industrial strength alternative to OCaml's standard library
core_kernel           113.33.03  Industrial strength alternative to OCaml's standard library
cppo                      1.4.0  Equivalent of the C preprocessor for OCaml programs
easy-format               1.2.0  High-level and functional interface to the Format module of the OCaml standard library
fieldslib             113.33.03  Syntax extension to define first class values representing record fields, to get and set record fields, iterate and fold over all fields of a record and crea
inotify                     2.3  Inotify bindings for ocaml.
jenga                 113.33.03 (pinned)  Build system
js-build-tools        113.33.04  Collection of tools to help building Jane Street Packages
js_of_ocaml                 dev (pinned)  Compiler from OCaml bytecode to Javascript
lambda-term              1.10.1  Terminal manipulation library for OCaml
lwt                       2.5.2  A cooperative threads library for OCaml
menhir                 20160808  LR(1) parser generator
merlin                    2.3.1 (pinned)  Editor helper, provides completion, typing and source browsing in Vim and Emacs
merlin_extend               0.2 (pinned)  
oasis                     0.4.6  Architecture for building OCaml libraries and applications
ocaml-data-notation      0.0.11  Store data using OCaml notation
ocaml_plugin          113.33.03  Automatically build and dynlink OCaml source files
ocamlbuild                    0  Build system distributed with the OCaml compiler since OCaml 3.10.0
ocamlfind                 1.6.2  A library manager for OCaml
ocamlify                  0.0.1  Include files in OCaml code
ocamlmod                  0.0.8  Generate OCaml modules from source files
ppx_assert            113.33.03  Assert-like extension nodes that raise useful errors on failure
ppx_bench             113.33.03  Syntax extension for writing in-line benchmarks in ocaml code
ppx_bin_prot          113.33.03  Generation of bin_prot readers and writers from types
ppx_compare           113.33.03  Generation of comparison functions from types
ppx_core              113.33.03  Standard library for ppx rewriters
ppx_custom_printf     113.33.03  Printf-style format-strings for user-defined string conversion
ppx_deriving                4.0  Type-driven code generation for OCaml >=4.02
ppx_driver            113.33.03  Feature-full driver for OCaml AST transformers
ppx_enumerate         113.33.03  Generate a list containing all values of a finite type
ppx_expect            113.33.03  Cram like framework for OCaml
ppx_fail              113.33.03  Add location to calls to failwiths
ppx_fields_conv       113.33.03  Generation of accessor and iteration functions for ocaml records
ppx_here              113.33.03  Expands [%here] into its location
ppx_inline_test       113.33.03  Syntax extension for writing in-line tests in ocaml code
ppx_jane              113.33.03  Standard Jane Street ppx rewriters
ppx_let               113.33.03  Monadic let-bindings
ppx_optcomp           113.33.03  Optional compilation for OCaml
ppx_pipebang          113.33.03  A ppx rewriter that inlines reverse application operators `|>` and `|!`
ppx_sexp_conv         113.33.03  Generation of S-expression conversion functions from type definitions
ppx_sexp_message      113.33.03  A ppx rewriter for easy construction of s-expressions
ppx_sexp_value        113.33.03  A ppx rewriter that simplifies building s-expressions from ocaml values
ppx_tools            5.0+4.02.0  Tools for authors of ppx rewriters and other syntactic tools
ppx_type_conv         113.33.03  Support Library for type-driven code generators
ppx_typerep_conv      113.33.03  Generation of runtime types from type declarations
ppx_variants_conv     113.33.03  Generation of accessor and iteration functions for ocaml variant types
re                        1.6.1  RE is a regular expression library for OCaml
re2                   113.33.03  OCaml bindings for RE2, Google's regular expression library
react                     1.2.0  Declarative events and signals for OCaml
reason                    0.0.5 (pinned)  
result                      1.2  Compatibility Result module
sexplib               113.33.03  Library for serializing OCaml values to and from S-expressions
type_conv             113.00.02  Library for building type-driven syntax extensions
typerep               113.33.03  typerep is a library for runtime types.
uchar                     0.0.1  Compatibility library for OCaml's Uchar module
utop                     1.19.3  Universal toplevel for OCaml
variantslib           113.33.03  Part of Jane Street's Core library
yojson                    1.3.2  Yojson is an optimized parsing and printing library for the JSON format 
zed                         1.4  Abstract engine for text edition in OCaml
</details>

**Comment by chenglou** [comment]
Extra info from chat room:

```
→ refmt -is-interface-pp false -parse re -print ml src/Merlin.re
Fatal error: exception Not_found
Raised at file "src/reason_toolchain.ml", line 87, characters 10-13
Called from file "src/reason_toolchain.ml", line 233, characters 14-57
Called from file "src/refmt_impl.ml", line 156, characters 24-133
```

Pinned reason from README.

From https://github.com/facebook/reason/blob/7f3b09a75cacf828dd6be23c89a53a8a85d89912/src/refmt_impl.ml#L156

**Comment by jordwalke** [comment]
The pinned version of reason is `reason 0.0.5 (pinned)`. Can you try pinning master and seeing if you have the same issue?

**Comment by vramana** [comment]
@jordwalke I can successfully compile now. No issues.
