### ISSUE TITLE
Parse into bleeding edge "modern" AST data structure. Downgrade automatically.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#706]
### How can we use new OCaml features immediately?

Here's what we can do to start using all of the upcoming and recently released features `Ocaml` features in `Reason` the moment they are available in `ocaml`.
- Create a package called `MLAst` which only models the AST. It is independent of the compiler but for the most part is the exact same dat structure as the most recent version of the OCaml AST. The only difference is that it would have syntactic support for algebraic effects, and modular implicits in the AST, simultaneously, even though neither is in upstream ocaml yet (we don't need to add parsing rules for them in the first step of creating the package).
- Create a converter package for each major version of OCaml, that converts `MLAst` to the each respective version of the ocaml compiler's AST. Then when using Reason with `4.02.3` we would parse into `MLAst` which resembles `4.04` (or even higher), but would downgrade it to `4.02.3` at the final step so it can be used in older versions. If you use a feature that's only supported in `4.04` then the downgrade to `4.02.3` would give a helpful error such as ("This feature is only available in `4.04`").
### What does this give us?

This not only helps us immediately use any new features the moment they're merged, (even experimenting with ones _before_ they're merged), but it also makes it so that we can write the Reason parser once, keeping it up to date with new merged features (such as inline records in `4.03`/`4.04`), but use that one implementation in 4.02.3. So this is just as much about using these new upcoming features very soon, as it is about our own productivity maintaining the Reason parser/printer. Right now, we can't merge the PR for upgrading to `4.03` because then it would be incompatible with `4.02.3`.
### Why not just only support `4.04+`?

Because this isn't the only time we're going to need to keep up with compiler changes. This proposal here helps us keep up to date, without having to maintain several forks of `Reason` for each underlying compiler version.

**Comment by yunxing** [comment]
Like this idea. We need to be careful about some internal representation changes like this one: https://github.com/ocaml/ocaml/commit/9eca3e45191ef52ce519e2d5bb4688da62bf7496 where they store integer as strings in the AST tree.

**Comment by jaredly** [comment]
Oooh and can we have the `MLAst` types have names that are actually easy to read? :P been reading through ast code a lot, and the names are pretty dense

**Comment by jordwalke** [comment]
@jaredly I agree, they're not very readable. We can clean them up if we like, if we're okay that it may make it more difficult to keep up to with newer OCaml compiler changes. The AST would likely contain the union of all upcoming compiler features (Implicits, Algebraic Effects).

**Comment by jaredly** [comment]
Is anyone working on this? If not, I'd like to move it forward

**Comment by yunxing** [comment]
@jaredly Sorry, was working on this but got distracted by versioning our npm packages (which is important to make sure our change don't break existing libraries). I have a prototype for the AST+ and will put it for review soon.

**Comment by jaredly** [comment]
so [ocaml-migrate-parsetree](https://github.com/let-def/ocaml-migrate-parsetree) is fixing the same problem I believe -- should we close this in favor of adopting it?

**Comment by jordwalke** [comment]
Ah, yes - we already use ocaml-migrate-parsetree in Reason! :D
That's how we are able to support ocaml versions 4.02.3/4.04/4.05 and any other future version that is released.
