### ISSUE TITLE
Reason project helper 

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#71]
This area has a lot of unknowns. Just writing down some of the goals that we would like to achieve and potential solutions.

We want to have a reason project helper tool which:
- [ ] scaffolds a project 
  - set up directories and dummy files
  - able to specify compiler version
- [ ] bootstrap necessary build tools (ocaml & opam)
  - https://github.com/avsm/opam-boot
- [ ] bootstrap necessary editor tools (merlin & project aware editor support)
  - when editing any files, automatically traverse the project tree up until find a merlin file (similar to [finding a file in git](https://github.com/yunxing/git-find-file.el-/blob/master/git-find-file.el))
- [ ] adding / removing dependencies in a sandbox environment 
  - http://stackoverflow.com/questions/27640897/is-it-possible-to-make-an-opam-sandbox

**Comment by jaredly** [comment]
`bsb -init` does some of this. also `esy` will do some others of this
