### ISSUE TITLE
Better syntax for e.g. `bs.obj`

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#712]
I don't know whether we should do this, but it'd be nice to have e.g. `#{a: 1, b: 2}` instead of `[%bs.obj {a: 1, b: 2}]`. Maybe this would couple us too tightly with BuckleScript, or maybe there's a more general approach.

Good for react (props, style).

(obj set & get could be better too, but that's another discussion.)

cc @jordwalke @bobzhang

**Comment by jordwalke** [comment]
`#{a: 1, b: 2}` can be for FFI objects, and `{"a": 1, "b": 2}` could be sugar for string map data structures. There is no parser ambiguity for any of these with records/objects.

**Comment by chenglou** [comment]
By string map, do you mean js obj?

**Comment by bobzhang** [comment]
note `bs.obj` does more than that, collections also work

```ocaml
[%bs.obj [ { x = 3 } ; { x = 4} ] ]
```
But here `#` is so light weight so it does not really matter, I have a bunch of cool ideas to make FFI syntax exactly like typescript/flow, for example, the flow declaration below can also work in Reason+ Buckle

```js
declare module Misc {
  declare var DEBUG: bool;
  declare function isLeapYear(year: string): bool;
}
```

**Comment by jordwalke** [comment]
Clever.

**Comment by jordwalke** [comment]
@chenglou : By `string` map I meant an actual map data structure.

**Comment by chenglou** [comment]
do we need first-class support for Map? People still don't use it as much in the wild. I feel that `{
"foo": bar}` syntax could be much better spent on js obj. And that hash syntax could be spent on... hash map =)

**Comment by jordwalke** [comment]
Very well. :D

**Comment by jordwalke** [comment]
I suppose `{"foo": bar}` would be suitable for JS objects, since JS does have string keys and this is acknowledging that fact.

**Comment by SanderSpies** [comment]
@bobzhang - could you write your ideas down for using Flow syntax for FFI? I would like to help out with this.

**Comment by bobzhang** [comment]
@SanderSpies 

so 
```js
declare module Misc {
  declare var DEBUG: bool;
  declare function isLeapYear(year: string): bool;
}
```

can be interpreted as 
```ocaml
external debug : bool = "DEBUG" [@@bs.module "Misc"]
external isLeapYear : year:string -> bool = "" [@@bs.module "Misc"]
```

This translate can be done either in Reason side or Buckle side

**Comment by SanderSpies** [comment]
I'm curious how we would switch to a different interop like jsoo.

**Comment by chenglou** [comment]
@SanderSpies there's nothing BuckleScript-specific about transforming `{"foo": 1}` to `[%bs.obj {foo: 1}]`, apart from the name of the ppx. In the future, we can generalize it to call it `js.obj` for good measure. But right now, desugaring it to `bs.obj` gives you a nice syntax that compiles to nice javascript.

**Comment by bobzhang** [comment]
also would be nice 

```
#< x : int ; y : int >
```
desugared to 
```
[%bs.obj: <x : int ; y : int> ]
```

**Comment by chenglou** [comment]
Already done. Can't support empty js obj (e.g. `{}` is ambiguous) but we can hide it behind a util function.
