### ISSUE TITLE
Better priority for object/record keys

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#714]
```
// This errors:
type foo = {open: false};
// another:
bla.open;
```

In general, it'd be great if record/obj keys have "higher priority" than build-in keywords? Is that a good idea? If not, at least better errors.

**Comment by jordwalke** [comment]
I think this is doable even if a bit tricky. You have to create a new parse rule for identifiers suitable for use in places such as keys/record labels. Those identifiers would be the union of typical identifiers, and other tokens. We'd then just need to make sure that the compiler itself doesn't complain when handed an AST with record labels matching certain tokens - and if so, we'd have to do some escaping.

**Comment by jaredly** [comment]
I think that's probably not a great idea? keywords should be keywords.
but let's ditch `open` from the default reason syntax :D (we can just have it be `import * from SomeMod`

**Comment by jordwalke** [comment]
Yeah, maybe by trimming out the keywords, we can achieve the same effect.

**Comment by bloodyowl** [comment]
might be useful for external JS objects too. it's not uncommon to have `"type"` as a property name, and `jsObj##type` throws, forcing to create a FFI

**Comment by let-def** [comment]
Same as https://github.com/facebook/reason/issues/824#issuecomment-338384372 : 
- ocaml compatibility lost
- punning gets messy

Besides that, it could be implemented.

**Comment by chenglou** [comment]
Yeah then let's not for now. We'll have better errors for these soon
