### ISSUE TITLE
Native uncurry syntax support and regular function application in reason

### ISSUE THREAD

**Issue by bobzhang** [facebook/reason#722]
this is the only syntax extension introduced by BuckleScript which will be used a lot even in non-FFI code if they want performance or work with google closure advanced.
 Note the  attribute is non-intrusive, compiles fine in both native compiler and JS backend (Buckle or JSOO), but it is quite annoying to write annotation `[@bs]` in various places.

Here is my proposal:

``` rs
function (a0,a1,a2) {
  body
}
```

which will be 

``` ocaml
fun[@bs] a0 a1 a2 -> ..
  body
```

``` rs
f @(a0,a1,a2)
```

will be 

``` ocaml
f a0 a1 a2 [@bs]
```

``` rs
(a0,a1,a2) => b0
```

will be 

``` ocaml
a0 -> a1 -> a2 -> b0 [@bs]
```

**Comment by bobzhang** [comment]
Attributes are not a very robust mechanism across different ppxes, it would be really nice that
Reason has a dedicated syntax for uncurried support (and communicate via extension point instead)
CC @vramana

**Comment by jordwalke** [comment]
I would love to better understand this. Is the primary motivation performance? Not having to pay the price of currying, and partially applying many arguments, when in the common case, they are all supplied anyways?

**Comment by bsansouci** [comment]
@jordwalke I think the output of BS would be nicer too (not relying on the Curry module just in case)

**Comment by bobzhang** [comment]
Not relying on curry is huge especially when callback is applied in a loop

**Comment by jordwalke** [comment]
@bobzhang I'm just trying to understand what the feature is. Is this only for ffi to JS? Or would it also be used in Reason->Reason?

**Comment by bobzhang** [comment]
I really believe this is a high priority issue. see #1172

**Comment by jaredly** [comment]
we now have this
