### ISSUE TITLE
[atom-reason] Reformatting of `rei` files does not work on master.

### ISSUE THREAD

**Issue by cristianoc** [facebook/reason#726]
It formats OK `.re` files.

<img width="477" alt="screen shot 2016-08-29 at 10 22 14 am" src="https://cloud.githubusercontent.com/assets/7965335/18045309/8b93ea28-6dd2-11e6-9871-7cb496a708b8.png">

**Comment by chenglou** [comment]
Sorry, dumb mistake.

**Comment by cristianoc** [comment]
Thanks!
