### ISSUE TITLE
_build/bin/* disappeared

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#733]
cc @yunxing

**Comment by jordwalke** [comment]
Is something relying on those links? The OPAM installation?

**Comment by chenglou** [comment]
Nah I was personally, because they looked like more legit counterpart to e.g. `refmt_impl.native`. Guess I should really use dependency-env instead.

**Comment by jordwalke** [comment]
Yeah, that was a stop gap before yunxing implemented proper ocamlfind npm installation.

**Comment by yunxing** [comment]
what's _build/bin? Is it suppose to be there?

**Comment by chenglou** [comment]
It was a list of symlinked binaries we exposed, e.g. `refmt`. It was there recently until the package.json modification I think? Same thing as what we talked about yesterday.

**Comment by chenglou** [comment]
Not a bug.
