### ISSUE TITLE
Infix #= doesn't print correctly

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#736]
cc @Schmavery 

```
id #= (Some 2)
```

Gets printed as

```
id #= Some 2
```

And throws `Error: The constructor Some expects 1 argument(s),
       but is applied here to 0 argument(s): ...`

Funny printing with functions:

```
let foo a => a;
id #= (foo 2);
```

Becomes 

```
let foo a => a;
id #= foo 2;
```

Then becomes

```
let foo a => a;
(id #= foo) 2;
```

**Comment by jordwalke** [comment]
Is this holding you up?

**Comment by chenglou** [comment]
Not really; can't use the formatter though.

**Comment by Schmavery** [comment]
Look like I didn't manage to get this to be treated as having high enough precedence in the printer.

**Comment by bobzhang** [comment]
actually it is correct according to ocaml manual
```
f #= a b 
```
parsed as 
```
(f #= a) b 
```
you have to write
```
f #= ( a b )
```
I think `#=` is not the best operator for variable assigntment, but I could not find another one without introducing ambigiuity, do you have any ideas

**Comment by jordwalke** [comment]
This parsing precedence is incredibly weird. It also does the "intuitive thing" in some cases, but counter-intuitive things in others. For example:

```rust
/* Cool */
let res = myFunction objOne##field objTwo##field;

/* Uhh, this is weird: This doesn't parse how you'd expect! */
myThing  #= someFunction argOne argTwo;
/* It's actually parsed as: */
(myThing  #= someFunction) argOne argTwo;


/* You would have to do this to get the effect you wanted: */
myThing  #= (someFunction argOne argTwo);

```

I recommended getting rid of this special unique snowflake precedence, and instead making anything function application identifier beginning with `#` (with length `>= 2`) be parsed just like any other infix. That means if you want to pass `x##y` to a function as an argument, you must include parens around it.
