### ISSUE TITLE
Syntax error on "_"

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#738]
I have this line `external dirname : string => ("__dirname") [@@bs.val];` and I get

```
File "main.re", line 7, characters 32-43:
Error: 128: <UNKNOWN SYNTAX ERROR>
```

Maybe it's because `_` was special cased and the lexer will still eat it inside a string? If I try to escape it, I get 

```
File "main.re", line 7, characters 33-35:
Warning 14: illegal backslash escape in string.
File "main.re", line 7, characters 35-37:
Warning 14: illegal backslash escape in string.
File "main.re", line 7, characters 32-45:
Error: 128: <UNKNOWN SYNTAX ERROR>
```

**Comment by jordwalke** [comment]
I do not get errors with underscores in strings when declared like this:

```
let something = "_";
```

**Comment by bsansouci** [comment]
Wow I goofed up. 
This works `external dirname : string => unit = "__dirname" [@@bs.val];`
This works `let dirname : string = "__dirname" [@@bs.val];`
This works `external dirname : string = "__dirname"[@@bs.val ]`

I think it was the `=>` that was totally misplaced before. 
That said it seems like `external dirname : string = ("__dirname") [@@bs.val];` doesn't work because the of the parens (removing them parses fine).

**Comment by bobzhang** [comment]
btw, `__dirname` and `__filename` are macros in JS, the bindings you wrote is not 100% correct. so that we provide macros too: `[%bs.node __dirname]` and `[%bs.node __filename]` which has type `string Js.undefined`

**Comment by jordwalke** [comment]
I'm thinking we could close this task. Unless you can think of a way to improve the developer experience. (Add better syntax errors? Allow arbitrary parens around the string?)

**Comment by bsansouci** [comment]
We can close this. It was mostly my fault.
