### ISSUE TITLE
[atom-reason] merlin integration broken

### ISSUE THREAD

**Issue by freebroccolo** [facebook/reason#742]
It seems that merlin integration with atom/nuclide has stopped working with 814c110d4bda4219de5a4a4625cd7d44860aab0c (after applying the fix from #741). I don't have the error message in front of me at the moment, but IIRC, it said something about invalid arguments to merlin. Maybe the merlin interface has changed?

I think it's unrelated but I've been having a number of other issues with the merlin integration even before this latest commit. Sometimes type on hover will just stop working and if I open the Chrome console it says something about assertion errors in `printtyp.ml`. It doesn't seem to happen until after I start using a lot of modules so maybe it has something to do with a problem printing qualified items. Wondering if anyone else has encountered this.

**Comment by SanderSpies** [comment]
We are now using Merlin from master instead of a separate branch - see also: https://github.com/facebook/reason/pull/740. My fix PR is intended to align Travis with this change.

**Comment by freebroccolo** [comment]
I am also pinning merlin from master now but still seeing the problems with nuclide. I tried installing nuclide from master but didn't see any change in the behavior. Does nuclide itself need to be updated to work with master?

**Comment by jordwalke** [comment]
@freebroccolo Will look into it, but did you also pin `merlin-extend` from master?

**Comment by jordwalke** [comment]
I just tried repinning `Reason` master, with `merlin` master, and `merlin-extend` master, and Atom works well for me (version 1.11 beta). Let me know if you still see issues. I'll try to make a sticky post in the gitter channel.

**Comment by vramana** [comment]
`merlin` with latest `master` works for me too.

**Comment by jordwalke** [comment]
@vramana You had to pin `merlin-extend` master too right?

**Comment by vramana** [comment]
@jordwalke Yes. I followed the updated Contributors guide.

**Comment by freebroccolo** [comment]
@jordwalke yeah, I unpinned/uninstalled `reason`, `merlin_extend`, and `merlin` and repinned them all to master respectively. I also tried removing all the atom reason packages (3 of them) and nuclide and deleting the atom compile cache and reinstalling. At one point I tried using nuclide from master too.

It's possible that somehow my configuration got in a bad state but the last configuration I was able to get to work without merlin errors in the console was:

* release nuclide
* release atom reason packages
* `merlin#reason-0.0.1`
* `merlin-extend#reason-0.0.1`
* `reason#499c11d`

I will try again in a little while and see if I can get it working. It was definitely saying something about merlin throwing an "invalid arguments" but I couldn't tell much beyond that.

**Comment by jordwalke** [comment]
Linux right?

**Comment by freebroccolo** [comment]
I was using Mac OS actually (`10.11.6`). Most stuff installed via homebrew and then I was using an ocaml `4.02.3` switch via opam (from homebrew).

I'll try to give it another go tonight though and see if I run into problems again. Thanks for looking into it though. If nobody else is seeing it was probably just some fluke on my end.

**Comment by yunxing** [comment]
@freebroccolo No worries. This kind of fluke is a bad user experience that we want to avoid.

**Comment by jordwalke** [comment]
We hope that the new sandbox model will make all of these weird conflicts an impossibility.

**Comment by freebroccolo** [comment]
Okay, I just tested again and it is working for me now with `reason` pinned to master so I'll go ahead and close this.
