### ISSUE TITLE
[atom-reason] Limit the dimensions of type definitions element. 

### ISSUE THREAD

**Issue by vramana** [facebook/reason#743]
![image](https://cloud.githubusercontent.com/assets/3112509/18265646/5fbc9950-7434-11e6-9975-d1389433891b.png)

Also type definitions are shown while hovering or clicking over comments inside a `module`. It kind of makes navigating the code hard. 

cc @chenglou

**Comment by jordwalke** [comment]
Personally, I would rather not have them show up on hover. Merlin has a really great "expand"/"contract" feature. I'd like an Atom workflow where I can put the cursor somewhere, ask for the type, and then expand/contract to larger syntactic elements. Another Atom OCaml plugin implemented this, and we should port it over to the Atom Reason one (it will still work with OCaml).

**Comment by freebroccolo** [comment]
I'm starting to think I'd also prefer to not have them show by default simply on hover. In particular, the delay is short so I'm finding that in some cases it ends up becoming a nuisance.

The expand/contract idea sounds pretty nice though.

**Comment by chenglou** [comment]
We're deferring the work to nuclide-typehint. Maybe that hovering behavior should be a setting there.

(Also, @bobzhang what's happening with the external here? I've seen this a few times)

**Comment by bobzhang** [comment]
@chenglou which part in particular?

**Comment by chenglou** [comment]
The `BS_EXTERN` output in the type hint screenshot (uses merlin to get the result of ["type"](https://github.com/the-lambda-church/merlin/blob/master/doc/dev/PROTOCOL.md#type-checking))

**Comment by bobzhang** [comment]
@chenglou that's the magic for the extern, we encoding all attributes info into the second string, is it possible to ask merlin not display both extern strings? since it does not really matter for end users

**Comment by jordwalke** [comment]
This is probably unrelated, but I *do* have the following in my Atom css file, because sometimes the datatips render incorrectly:

```
.nuclide-type-hint-text-editor atom-text-editor::shadow .editor-contents--private > .scroll-view > .lines > div > div {
  position: relative!important;
}
```

Personally, I would much rather have a keyboard driven interaction, and I wouldn't mind it popping up in another unobtrusive, automatically-closing panel.

**Comment by chenglou** [comment]
Stale. Solved!
