### ISSUE TITLE
refmt incorrects formats curried arguments

### ISSUE THREAD

**Issue by vramana** [facebook/reason#744]
``` rust
external use : 
  t => (Request.t => Response.t => Next.t => unit [@bs]) => unit = "" 
[@@bs.send];
external static : 
  path::string => (Request.t => Response.t => Next.t => unit [@bs]) = "" 
[@@bs.module "express"];
```

is converted to 

``` ocaml
external use :
  t -> (Request.t -> Response.t -> Next.t -> ((unit)[@bs ])) -> unit = ""
[@@bs.send ]
external static :
  path:string -> Request.t -> Response.t -> Next.t -> ((unit)[@bs ]) = ""
[@@bs.module "express"]
```

Reproducible case here https://github.com/vramana/Rexpress/tree/e06f9fb14f4e06b8d9288da9da0827555b2c7858

cc @bobzhang

**Comment by jordwalke** [comment]
To be clear, this is when converting from `re` to `ml` right?

Are you passing the flags` -print re` or `-print ml` ?

**Comment by vramana** [comment]
@jordwalke Yes. 

https://github.com/vramana/Rexpress/blob/e06f9fb14f4e06b8d9288da9da0827555b2c7858/package.json#L17

**Comment by jordwalke** [comment]
Curious, why are you printing to `ml`? Btw: That looks like a bug in OCaml's printer (which we use for `refmt -print ml`). We could always fork the printer and fix the bug too.

**Comment by vramana** [comment]
@jordwalke I was just mimicing build steps from this repo https://github.com/bsansouci/ReSocket.io/

**Comment by jordwalke** [comment]
I wonder if that library does that because it was made when Reason didn't have bucklescript support?

**Comment by bsansouci** [comment]
@jordwalke I had to do this because Bucklescript doesn't support `bsc -c -bs-files *.ml` for `.re` files. At least at the time that I wrote this (a couple days ago lol)

**Comment by jordwalke** [comment]
okay, cc @bobzhang

**Comment by bobzhang** [comment]
I would like to support `-bs-files` for reason too, but I don't have reason parser.
Btw, you don't need print to ml files to get buckle support (CC @chenglou )

**Comment by jordwalke** [comment]
@bobzhang Can `bs-files` support raw binary ASTs, as you said the ocaml compiler can?

**Comment by jaredly** [comment]
or if `bs-files` supported `ml-synonym` and `pp` then it would work too

**Comment by bobzhang** [comment]
It is more complicated if we accept raw ASTs, we also need to mark it is applied(or not) the transformations by Buckle( e.g handling those external attributes). 
The main purpose of `-bs-files` is not to replace a build system, but just to make life easier for small to medium sized project(you don't need a build system for most of your projects)
It is nice to have Reason parser as a stand alone self contained library, we can also provide native windows support in that case

**Comment by chenglou** [comment]
Fixed in master. A bug from us. #1523
