### ISSUE TITLE
A way to force rebuilding binary dependencies from source.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#747]
We (thankfully) have `utop-bin` and `jenga-bin`. This _massively_ speeds up build times of projects. However:

We still need a way to build from source on some CIs. (Typically only `jenga`, typically no need to build `utop` from source).

We can look into `npm`'s "shrinkwrap" feature, which could allow this.

**Comment by jaredly** [comment]
I think this is stale - we have a much different build environment now
