### ISSUE TITLE
Incorrect statement in gh-pages doc about OCaml pattern matching

### ISSUE THREAD

**Issue by bcc32** [facebook/reason#748]
There's a section in the gh-pages doc that isn't quite correct:

> Can you spot the error in the `OCaml` example? This is one of the most common
> mistakes among `OCaml` programmers. The second `match` _must_ be wrapped in
> parentheses, otherwise the `Some` case is parsed as belonging to the outer
> `match`. `Reason`'s required `{}` blocks around match cases prevent this
> issue.

for the following example:

``` ocaml
let res = match x with
  | A (x, y) -> match y with
    | None -> 0
    | Some i -> 10
  | B (x, y) -> 0
```

OCaml will actually parse the `Some` and `B` patterns as belonging to the inner `match`, not the other way around.

For the visual thinkers, the non-misleading indentation would be this:

``` ocaml
let res = match x with
  | A (x, y) -> match y with
    | None -> 0
    | Some i -> 10
    | B (x, y) -> 0
```

and _not_ this:

``` ocaml
let res = match x with
  | A (x, y) -> match y with
    | None -> 0
  | Some i -> 10
  | B (x, y) -> 0
```

**Comment by jordwalke** [comment]
Ah, okay thank you for pointing it out! I suppose my mistake demonstrates how hard it is to get right :D

**Comment by chenglou** [comment]
Sorry for the late fix. About time!
