### ISSUE TITLE
Tuple syntax with 1 value needs better errors

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#749]
`let foo = (1);` prints as `let foo = 1;` Is there a way we could provide better warnings for this? Or not worth the trouble?

**Comment by jaredly** [comment]
don't think that's worth the trouble? tuples literally can't have 1 value. Also, putting parentheses around an expression is totally valid...

what I really want is for atom-reason to show me all(most?) inferred types all the time :D so I don't have to guess / mouseover

**Comment by chenglou** [comment]
Yeah I guess most languages have them, so this is fine. It's hard to give good error messages anyway since `(1)` can legit mean `1`.
