### ISSUE TITLE
Warn against npm2

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#756]
Our npm workflow fail on npm2 because `node_modules` wasn't flat. It's causing stuff to take over an hour to install (many copies of ocaml).

**Comment by jordwalke** [comment]
Thanks! Who was using NPM2? I did a survey and almost all respondents said they moved to npm3

**Comment by chenglou** [comment]
Corporate laptop users who never bothered to do `brew update` =P

**Comment by chenglou** [comment]
Another person just hit this. Where should the error message be?

**Comment by jordwalke** [comment]
I'll put it in ExampleProject and Reason itself for now. I think the combination of those should catch most cases (but dependency-env would be nice too).
