### ISSUE TITLE
New object syntax proposal

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#766]
From @jordwalke. I'm just paraphrasing here.

``` rust
let x = {
  pub myMethod argOne => ...
  pri myPrivateMethod argOne => ...
};

/* typed, open */
let x : {myMethod: t, ..} = someObjectDeclaration;
/* typed, closed. Rarely used? */
let x : {myMethod: t, .} = someObjectDeclaration;
```
## Proposal 1 for method call syntax:

``` rust
x.myMethod argOne;
```

This requires changing record function calling to

``` rust
record->myFunc argOne
```

The justification being that record function is rare.
## Proposal 2

Keep the same record function syntax, use the following for method call (notice the `:`):

``` rust
myObject.method: argOne argTwo
```
## Tradeoffs

The first proposal for method calling would play nicely if function application of multiple curried arguments were expressed via standard `(,,)` syntax - for example:

``` rust
let adder = {
   pub add (a, b) => a + b
};
let result = adder.add(100, 200);
/* Partially applying 4 */
let addFourTo = adder.add(4);
let seven = addFourTo(3);
```

The second proposal for method calling would play nicely with named arguments of the form `label:` - for example:

``` rust
let myObject = {
   pub someMethod x: xx y: yy => x + y
};
let result = myObject.someMethod: x:10 y:200;
```

**Comment by vramana** [comment]
Is there any drawback in making methods private by default?

**Comment by jordwalke** [comment]
the `pub` and `pri` are needed to distinguish the object from a block expression. After the `{` there always needs to be something that can determine the kind of object being parsed. Record vs. block expression, vs. method.

**Comment by jordwalke** [comment]
You need something there, even if it's not `pub`/`pri` (for example `met` for "method")

**Comment by SanderSpies** [comment]
Close please.
