### ISSUE TITLE
/** comment above a block gets pretty printed wrong

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#770]
``` rust
/** Create controls **/
{
    let a = 10;
};
```

gets pretty printed as

``` rust
{

    /** Create controls **/
    let a = 10;
    ()
};
```

Which isn't really what I was going for. This seems a bit less useful than comments right above the block (to separate and explain that block).

**Comment by yunxing** [comment]
ok, I made some special logic so it goes like this. I can remove that.

**Comment by bsansouci** [comment]
Why did you do it that way instead of leaving it above? It got my by surprise, maybe it's better that way?

**Comment by yunxing** [comment]
I was trying to format this case
```
let a = /* comment */ {
   ...
}
```
to
```
let a = {
   /* comment */
   ...
}
```
... It is pretty subjective and looks like people generally don't like it ...

**Comment by bsansouci** [comment]
Ah crap... Is there any way to check if the return value of the block is used?

**Comment by yunxing** [comment]
nah, let's not bother to do that and maybe just move the comment above the block.

**Comment by chenglou** [comment]
Fixed
