### ISSUE TITLE
Using reason with bucklescript introduces type error for test script

### ISSUE THREAD

**Issue by Charlesetc** [facebook/reason#795]
Hi! I'm working with [this example script](https://github.com/bloomberg/bucklescript/blob/master/jscomp/test/test_react.ml) from the bucklescript repo. It seems converting it to reason with `refmt` introduces a type error.

Here's a simpler repro though:

### simple.ml
```ocaml
class type con = 
  object
    method log : 'a -> unit 
  end[@bs]

type console = con Js.t 
external console : console  = "console" [@@bs.val ]

let v = console##log "hey";;
```
This compiles without a hitch with:
```
./node_modules/bs-platform/bin/bsc.exe -c simple.ml
```
Then converting to reason:
```bash
refmt -parse ml -print re simple.ml > simple.re
```
### simple.re
```rust
class type con = {
  method log: 'a => unit
};

type console = Js.t con;

external console : console = "console" [@@bs.val];

let v = console##log "hey";
```
Compile error:
```bash
$ ./node_modules/bs-platform/bin/bsc.exe -pp refmt -impl simple.re
File "simple.re", line 9, characters 15-17:
Error: This expression has type 'a -> unit
       but an expression was expected of type
         ([ `Arity_1 of 'b ], 'c) Js.meth
```
Commenting out the last line of the reason version solves the issue, so it might have something to do with the `console##log` notation.

**Comment by bobzhang** [comment]
the `[@bs]` attribute is dropped after refmt

**Comment by Charlesetc** [comment]
Ah I see that now - thanks! Is that intentional/is there something equivalent I can add in reason?

**Comment by chenglou** [comment]
Sorry for the trouble. This is #710

**Comment by Charlesetc** [comment]
Haha this seems related:
```ocaml
  (* TODO: TODOATTRIBUTES. *)
  method class_field x = ....
```
I'll give it a try from the instructions on that issue

**Comment by Charlesetc** [comment]
closing as a duplicate
