### ISSUE TITLE
refmt outputs invalid Unicode stuff

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#799]
Repro: `" │ "` (a unicode bar, for drawing boxes) formats into `" �\148\130 "` (literally)

**Comment by tekknolagi** [comment]
How are you running this?

**Comment by chenglou** [comment]
`echo '" │ "' | ./refmt_impl.native --parse re --print re`

**Comment by tekknolagi** [comment]
oh gross

**Comment by jordwalke** [comment]
Fortunately, parsing works correctly - it's just a matter of finding the right unicode printing library to use I believe.

Marking it as Good First Task.

**Comment by gorghoa** [comment]
@jordwalke, I experiment this issue too, how can I help?

Can you be more explicit than  “it's just a matter of finding the right unicode printing library to use I believe.” to see if I can help?

thanks!

**Comment by haskellcamargo** [comment]
I believe this has to do with how OCaml represents strings, as long as `{|│|}` prints it correctly.


![image](https://user-images.githubusercontent.com/7553006/34634402-e5bfe326-f26a-11e7-89be-f1c22b9c0366.png)

**Comment by kevinbarabash** [comment]
Does the AST token for the string store the start/end location within the source string for token?  If so, maybe we could use that when printing.

**Comment by chenglou** [comment]
Sorry, this is solved already. And yeah we do that
