### ISSUE TITLE
"//" as comments ?

### ISSUE THREAD

**Issue by yunxing** [facebook/reason#80]
Currently we only support "/*" as comment. 

Should we also support the format of "//" ?

**Comment by bordoley** [comment]
Any update on this. In my brief experience using reason, this is by far the most frustrating limitation of the syntax.

**Comment by jordwalke** [comment]
No update yet. We can probably just print any comment as a single line comment automatically that:

1. Contains no newline: So `/* this */` would be printed as `// this`.
2. Is guaranteed by the formatter to not have any content after it on the same line. For example, if we know that the following could never happen:

```
/*we have to make sure  */ this could never happen
```

**Comment by adnelson** [comment]
I believe this can be closed due to the merging of #2254

**Comment by IwanKaramazow** [comment]
Indeed, this is implemented and released
