### ISSUE TITLE
[atom-reason] Ligature for |> not working 

### ISSUE THREAD

**Issue by fineline** [facebook/reason#803]
Using Fira Code font, |> ligatures are shown for OCaml files but not Reason files. Same with ==.

Seems like it could be explained by [tonsky/FiraCode/issues/63](https://github.com/tonsky/FiraCode/issues/63)

**Comment by vramana** [comment]
@fineline This is already fixed in the language-reason. It will be fixed in the next release.

**Comment by chenglou** [comment]
fixed by 868b7908c2b76ffc8efc0652e19346516b5d1e12

**Comment by chenglou** [comment]
Sorry for the delay!
