### ISSUE TITLE
JSX line number is sometimes off

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#804]
The line number seems to be wrong for undefined modules.

``` rust
let module Blaa = {
  let createElement children => ()
};

let a = <Bla />;
```

I get an error on line 1 `Error: Unbound module Bla`.

When I do

``` rust
let module Blaa = {
  let createElement children => ()
};

let a = <Blaa> 

asd 

</Blaa>;
```

I get an error that the value is unbound on the line with `asd`.

**Comment by bsansouci** [comment]
Another error related:

```rust
let module Thing = {
  let createElement children => ()
};

let a = <Thing a=10 />;
```

This will point to line 1 and say `Error: This function has type 'a => unit It is applied to too many arguments; maybe you forgot a `;'.`. Very hard to debug :p

**Comment by SanderSpies** [comment]
I believe these issues have solved already. 

Can you check @bsansouci?

**Comment by chenglou** [comment]
Fixed a long time ago
