### ISSUE TITLE
adding a comment results in poor code formatting

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#811]
When adding a comment to:

```
let hash {csu, mgd} => Hashtbl.hash (csu, mgd);
```

I would like to get:

```
let hash {csu, mgd} =>
  /* exclude the scope from the hash since it is ignored by equal */
  Hashtbl.hash (csu, mgd);
```

but currently (1.4.0) I get:

```
let hash {csu, mgd} =>
  /* exclude the scope from the hash since it is ignored by equal */
  Hashtbl.hash (
  csu,
  mgd
);
```

**Comment by jordwalke** [comment]
Good find.

**Comment by yunxing** [comment]
Good find. Taking a look

**Comment by yunxing** [comment]
![image](https://cloud.githubusercontent.com/assets/1017689/19457027/4f9afd22-9479-11e6-9594-11311c158a34.png)

Looks like the highlighted area should be merged as direct siblings in the format tree.

**Comment by chenglou** [comment]
Solved by ^
