### ISSUE TITLE
Inconsistent syntax between interface/external/function with optional label

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#818]
```
external props : foo::string? => ...
val f: foo::string? => ...

/* note the `=` */
let f: foo::string=? => ...
```

Kinda makes sense that there's no `=` in external and interface type declaration, since there's no default value to be had there (which, in the function declaration type's case, would be `let f: foo::string="foo" => ...` which looks consistent).

**Comment by SanderSpies** [comment]
So to be clear, we want:

`let f: foo::string? => ...`

and

`let f: foo::string="bar" => ...`

?

**Comment by chenglou** [comment]
Not sure what we want here... cc @jordwalke whose new function syntax proposal is not posted yet (still =P)

**Comment by jordwalke** [comment]
I don't understand the problem. Is it the `val` keyword?

**Comment by chenglou** [comment]
No. The usual syntax for optional arg is `=?` but here it is `?`. It's a bit hard to discover.

**Comment by chenglou** [comment]
Fixed
