### ISSUE TITLE
Update error message "The value X is not an instance variable"

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#823]
This error message got me very confused for a bit. The code I had was:

``` rust
let circle_colors_indices = [];
for i in 0 to 360 {
  circle_colors_indices = [0, ...circle_colors_indices];
};
```

After googling the ocaml error message, I remembered that I couldn't that sort of mutation and I need a ref

``` rust
let circle_colors_indices = ref [];
for i in 0 to 360 {
  circle_colors_indices := [0, ...!circle_colors_indices];
};
```

This makes sense but the error message, which was pointing at `... circle_colors_indices` was not helpful.

**Comment by SanderSpies** [comment]
We could make the error message a bit more descriptive, but if we want to fix the error location - we need to fix this upstream: 
https://github.com/ocaml/ocaml/blob/2da2fcdb66249e50bffe57ec8002ae54b4781b12/typing/typecore.ml#L4302

**Comment by seliopou** [comment]
I just came across this error message in a slightly different context.

```ocaml
type t = { a : int; mutable b : string }

let set_b (t:t) str =
  t <- str
```

Of course, the update should have been `t.b <- str`, but the error message did nothing to steer me in that direction.

**Comment by chenglou** [comment]
Closed in favor of https://github.com/reasonml-community/error-message-improvement/issues/18
