### ISSUE TITLE
Special case keywords to be allowed as names for arguments

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#824]
It seems like I can't use `type` as a name for an argument because it's not an identifier. I'd like to allow those by adding special cases for the keywords we deem useful as named args.
`to` is another one (`let doThing from::0 to::10` dies of course).

**Comment by let-def** [comment]
Ideally, I would not be against this idea, however it would break compatibility with OCaml (because in OCaml you really cannot use reserved words), and the story with punning will be messy (punning would be disabled in these cases, which is quite ad-hoc).
