### ISSUE TITLE
attribute disappears on external

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#837]
Repro:

```
external debounce : int => ((unit => unit)[@bs.meth]) = "" [@@bs.module];
```

Turns into:

```
external debounce : int => unit => unit = "" [@@bs.module];
```

cc @bsansouci

**Comment by jordwalke** [comment]
I thought this was fixed. Did we not merge a PR?

**Comment by chenglou** [comment]
There are more than one of these issues.

**Comment by bobzhang** [comment]
Attributes are very easy to be dropped by ppx (not yours maybe others). I would suggest using extension points (but you can design a better syntax).
