### ISSUE TITLE
Formatting optional named arg with no default breaks when too long

### ISSUE THREAD

**Issue by bsansouci** [facebook/reason#842]
If I have a function like
```rust
let registerEventHandlers
      window::(window: Window.t)
      mouseDown::
        (
          mouseDown:
            option (
              button::Events.buttonStateT => state::Events.stateT => x::int => y::int => unit
            )
        )=?
      () => {
      ...
};
```

it'll get reformatted like
```rust
let registerEventHandlers
      window::(window: Window.t)
      mouseDown::
        (
          mouseDown:
            option (
              button::Events.buttonStateT => state::Events.stateT => x::int => y::int => unit
            )
        )=
            ?
      () => {
      ...
};
```
Notice the `?` that moved on a newline. This causes a parse error.

If I had to make a quick guess I'd say the problem occurs around https://github.com/facebook/reason/blob/5384e1b78422caae382ffae1dd0841dc17f6f34a/src/reason_pprint_ast.ml#L3010 where we allow to break between the `=` and the `?` even though at the lexer level we assume `=?` to be one token `OPTIONAL_NO_DEFAULT`. Maybe adding `break=`Never` for a label made of of the `=` and `?`. Or simply string concat ...

**Comment by jordwalke** [comment]
Yeah I would just make it one string concat so that they never break. Want to send a quick pr?

**Comment by chenglou** [comment]
Fixed, but this now formats to something ugly: https://github.com/facebook/reason/issues/1492

**Comment by chenglou** [comment]
That one's closed too now
