### ISSUE TITLE
Disable refmt for a section of code, specifically multi-line strings

### ISSUE THREAD

**Issue by jmmk** [facebook/reason#845]
My problem: I have a multi-line string (large SQL statement) that I want to be formatted in a specific way for readability. When I use refmt, it collapses the string and makes it unreadable.

A couple solutions I see:

1. Allow disabling formatting for a specific section of code. This is possible in IntelliJ for example by using the special comments  `@formatter:off` and `@formatter:on` surrounding the section of code you don't want it to touch.
2. refmt shouldn't touch multi-line strings. In this case, multi-line strings wouldn't be modified, assuming that they have been formatted that way by the user.

**Comment by hcarty** [comment]
My vote is for (2).  If code has any string literals they are most likely formatted how they are for a reason.

**Comment by vramana** [comment]
You can write something like this https://github.com/reasonml/rebel/blob/master/src/merlin.re#L93-L135. refmt doesn't touch it.

**Comment by jmmk** [comment]
@vramana what is the `{| |}` syntax? I can't find any documentation on it

**Comment by hcarty** [comment]
@jmmk https://caml.inria.fr/pub/docs/manual-ocaml-4.04/extn.html#sec250 - similar to `"""` in Python

**Comment by jmmk** [comment]
@hcarty Thanks, I think that's what I was looking for in the first place, but the only thing I found when searching ocaml multi-line strings is that all strings are multi-line, so I'm using:

```ocaml
"My
multi
line
string"
```

Using `{| |}` is a good workaround, but I'll let you decide if this issue is still valid.

**Comment by jordwalke** [comment]
`{| |}` are more than multiline strings - they also don't require you to escape quotes etc inside.

**Comment by jaredly** [comment]
`{||}` seems like a good solution here
