### ISSUE TITLE
Better syntax for external + bs.module

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#850]
Currently:

```
external foo : _ = "" [@@bs.module];
```

Maybe:

```
let foo = require "foo"
```

Or something similar to that, with the `require` keyword. no type annotation types it to `_` let's say. 

Thoughts?

**Comment by bobzhang** [comment]
How about piggyback flow syntax

**Comment by chenglou** [comment]
Like this? https://flowtype.org/docs/declarations.html

If so, it could be a troublesome because our function signature syntax is very different than flow/typescript's

**Comment by chenglou** [comment]
@bobzhang if you do `[%bs.require ...]` maybe we can lump this under `let%require` or something. Maybe.

**Comment by chenglou** [comment]
But in the meantime I think a `require` syntax for just this case is better than flow syntax; that flow syntax isn't used much in userland.

**Comment by bobzhang** [comment]
This looks interesting. Can u elaborate a bit more about the use case of '_' ? Fast prototyping?

**Comment by bobzhang** [comment]
We can have something like
external module foo;
Or
declare module foo;

**Comment by chenglou** [comment]
> Can u elaborate a bit more about the use case of '_' ? Fast prototyping?

Yeah it's just a fast path sugar for `: _`, which isn't that obvious for beginners.

If possible, I'd like to satisfy all needs of `[@@bs.module]`, e.g. `"" [@@bs.module]`, `[@@bs.module "Y", "U"]`, etc.

Maybe a MVP would be `external foo: bla = require "foo";`

**Comment by chenglou** [comment]
Let's hold off on the sugars a bit. Closing this for now.
