### ISSUE TITLE
Operator for list concatenation?

### ISSUE THREAD

**Issue by dchambers** [facebook/reason#852]
Given that `::` is used for labeled arguments, anybody know which operator is to be used instead of the double colons here?

**Comment by bsansouci** [comment]
Hey @dchambers, the list concatenation is similar to the JS's [spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) operator.
`el :: rest` in ocaml is `[el, ...rest]` in reason.

**Comment by dchambers** [comment]
Love it! Thanks so much! :smile:
