### ISSUE TITLE
No way to invoke as `rtop -safe-string`

### ISSUE THREAD

**Issue by dchambers** [facebook/reason#854]
or to pass `utop` arguments in general.

**Comment by chenglou** [comment]
Note: [this](https://github.com/facebook/reason/blob/a0adb09b8a34dbb8445eed70f42666d055356dca/src/rtop.sh) is our rtop wrapper

**Comment by dchambers** [comment]
Right. I've modified that file in the accompanying pull-request in case it's helpful.
