### ISSUE TITLE
Sugar for nullable accesses & calls

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#862]
`foo?.bar?.baz` -> `foo >== (fun bar => bar >== (fun baz => baz))` (or skip the infix sugar all together)

`foo?.barCall 1 2 3` -> etc.

`bazCall? 1 2 3` (or maybe the above should be `foo?.barCall? 1 2 3` for consistency, and then the first one would be `foo?.bar?.baz?`. ~~The version without `?` can turn into access with exception throwing. Just kidding.~~)

I guess likewise for `foo?#bar?#baz` and whatever syntax #849 ends up with.

**Comment by chenglou** [comment]
cc @jlongster @jordwalke @bobzhang

**Comment by jordwalke** [comment]
It would be nice to avoid paying for the infix >== and function allocations. Seems we could just use ? to special case option types making it just a switch statement (much faster). Is there another use case outside of option?

**Comment by chenglou** [comment]
On second thought, infix would actually be bad because if you accidentally open a module that overrides `>==` (sorry I meant `>>=`, but same thing) then it's not visible.

I think `option` is good then, yeah.

**Comment by jaredly** [comment]
closing in favor of #1928
