### ISSUE TITLE
Formatting makes `<></>` fragment dissapear

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#870]
```
<div onClick=this##handleClick>
  <>foo</>
</div>
```

Turns into

```
<div onClick=this##handleClick>
  foo
</div>

```

**Comment by SanderSpies** [comment]
I'll look at this and the other JSX issues after my new object syntax PR lands. This is most likely an issue with the "pretty" printer.

**Comment by jordwalke** [comment]
I would expect this one to preserve the `<></>` which would cause it to be interpreted as `[[foo]]` (a list with a single item, that is itself a list containing `foo`).

**Comment by anmonteiro** [comment]
I'm working on this!
