### ISSUE TITLE
JSX support for explicit passing of optional argument

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#879]
https://realworldocaml.org/v1/en/html/variables-and-functions.html#explicit-passing-of-an-optional-argument

This is very, very useful for react. We'd be able to have `<Foo bar=?props.bar />` when `props.bar` is `option 'a`.

(For those who are confused by this, `<Foo bar=props.bar />` requires `props.bar` to be non-nullable if you defined foo's `bar` as an optional argument and actually use it)

cc @jordwalke @SanderSpies maybe even more important than punning ¯\_(ツ)_/¯

**Comment by SanderSpies** [comment]
Close please.

**Comment by chenglou** [comment]
Great stuff. Time to tweak the API.
