### ISSUE TITLE
Refinement types

### ISSUE THREAD

**Issue by SanderSpies** [facebook/reason#881]
This is probably far off for now - still I like to share this slightly crazy idea.

Currently we have types like:
```
type foo = int;
```
which could basically be any number that the int type allows. With [refinement types](http://goto.ucsd.edu/~rjhala/liquid/haskell/blog/blog/2013/01/01/refinement-types-101.lhs/) we can be more precise. For example:
```
type foo = int { > 10 && < 1000 }
```
ps. this purely speculative code. 

I would love to explore this direction with Reason.

**Comment by hcarty** [comment]
As long as the plan is for run-time validation of the predicate(s), this could be done in a fairly straightforward way with ppx.  That should allow for easy experiments with interfaces and usability.

**Comment by SanderSpies** [comment]
Closing this to reduce noise.
