### ISSUE TITLE
in-place transformation for refmt

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#886]
Some switch that allows the transformation of a file in-place, since `cat foo.re | refmt ... > foo.re` doesn't work because of how unix pipes work.

**Comment by tekknolagi** [comment]
A workaround for now could be something like `echo "$(cat foo.re | refmt ...)" > foo.re` or even `echo "$(refmt ... foo.re)" > foo.re`.

**Comment by yunxing** [comment]
@tekknolagi The workaround should work. In the meantime I think we should still have a -in-place option (or -i). Are you still working on this?

**Comment by tekknolagi** [comment]
@yunxing Yep!

**Comment by tekknolagi** [comment]
Would it make more sense to add `--output`/`-o` and have `--in-place` be a special case of that?

**Comment by yunxing** [comment]
@tekknolagi Looks like the best solution so far given that "-i" is taken for "--intf"
