### ISSUE TITLE
Support trailing commas in tuples.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#889]
We can easily parse these to avoid accidental errors. When printing it will be very easy to omit them. Ideally, we would even print the trailing comma, but *only* when breaking on multiple lines, and otherwise not (but that advanced printing requires deeper hooks into our formatting library).

**Comment by jordwalke** [comment]
This is a great first task. You could look at how we do this for trailing commas in records.

**Comment by IwanKaramazow** [comment]
Merged, can be closed.

**Comment by yunxing** [comment]
@IwanKaramazow thanks!
