### ISSUE TITLE
JSX "applied to too many arguments" error report location doesn't exist

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#901]
Repro:

```
<Foo bar=1 baz=2 />
```

If the error is, for example, that `Foo.createElement` (the underlying function call) can't be applied with `baz`, or that we've forgotten to pass a required label, then everything errors at the correct location.

If the error is "It is applied to too many arguments; maybe you forgot a `;'." then there's no error location.

**Comment by SanderSpies** [comment]
I think this has been fixed already.

(I cannot reproduce it)

**Comment by chenglou** [comment]
I forgot how I got into that error in the first place. Closing. Thanks!
