### ISSUE TITLE
How to compile to JavaScript?

### ISSUE THREAD

**Issue by ccorcos** [facebook/reason#911]
It appears that Reason intends to compile to JavaScript. Is this working or still in progress?

**Comment by vramana** [comment]
You need to either use BuckleScript or js_of_ocaml to convert reason code to javascript.

**Comment by ccorcos** [comment]
I see. How exactly does JS interop work? 

These requires seem to come out of nowhere: https://github.com/bloomberg/bucklescript

A webpack loader would make it a lot easier to adopt.

**Comment by vramana** [comment]
@ccorcos You can configure your webpack config to look at the output of bucklescript as the entry point.

**Comment by chenglou** [comment]
May I suggest my own guide on this? https://github.com/chenglou/intro-to-reason-compilation

We're in the process of polishing things. It's definitely already viable (to a degree you wouldn't believe). Just needs more docs. If you're interested, come join us in discord.gg/reasonml

Leaving this open until we deem this done =)

**Comment by ccorcos** [comment]
@chenglou thanks for the link! I'm quite unfamiliar with OCaml and Reason so I'm not sure how much help I'd be. I just want to learn Reason and a webpack loader would be the easiest way for me to get started right now.

I'm just curious -- what are your thoughts on PureScript?

**Comment by chenglou** [comment]
Webpack loader is definitely viable. Heck, it's been done before and we just haven't released it =).

This place is a bit unwieldy to discuss about broad issues such as the tradeoff between reason and [Insert alternative]. I'll be glad to discuss about this in the chat though!

**Comment by ccorcos** [comment]
Fair point :)

**Comment by thewillhuang** [comment]
https://github.com/rrdelaney/bs-loader

**Comment by vramana** [comment]
@chenglou I think this issue can be closed

**Comment by kennetpostigo** [comment]
@chenglou This should be okay to close.
