### ISSUE TITLE
bs.obj sugar key wrapped for no reason

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#914]
Repro:

`{"/foo": bar}` gets formatted to `{"(/foo)": bar};`

@bsansouci

**Comment by IwanKaramazow** [comment]
I think the problem goes a little bit deeper:
`let somethingElse = [%bs.obj {x: {y: {z: 3}}}];`
becomes:
`let somethingElse = {"x": {y: {z: 3}}};`

**Comment by chenglou** [comment]
Not sure what you mean. That's intended?

**Comment by IwanKaramazow** [comment]
The second is post-refmt, `%bs.obj` disappears, the `x` fields gets wrapped in `"`.
Do you get this too?

**Comment by chenglou** [comment]
Yeah that's our object sugar! Just like JSX, desugared into an agnostic macro (which only bs implements currently but you can imagine `Js.Unsafe.*` from jsoo).

This way you can write `let foo = {"bar": 1}` and under BS it'd compile down to `var foo = {bar: 1}` =D

**Comment by bsansouci** [comment]
This isn't an issue as chenglou said. It does look ugly though, we could pretty print it better.
