### ISSUE TITLE
Fatal when refmt on `Some x y`

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#915]
When parsing this example, we should not fatal the parser, but rather give a graceful parsing error (like any other parse error).

Make sure to set `export CAMLRUNPARAM='b'` to see good stack traces as always.

Here's the command that triggers the error and the resulting error:
```
refmt ./examples/pure/logo.re
Fatal error: exception File "src/reason_parser.ml", line 3833, characters 17-23: Assertion failed
Raised at file "src/reason_toolchain.ml", line 87, characters 10-13
Called from file "src/reason_toolchain.ml", line 269, characters 14-57
Called from file "src/refmt_impl.ml", line 12, characters 48-157
Called from file "src/refmt_impl.ml", line 189, characters 18-69
```

Here's the contents of `logo.re` that causes the failure:

```rust
Some 10 20;
```

Here's the `assert false` where it occurs in our `parser.mly`:

```mly
  | as_loc(constr_longident) simple_non_labeled_expr_list_as_tuple
    {
      if List.mem (string_of_longident $1.txt)
         built_in_explicit_arity_constructors then
        (* unboxing the inner tupple *)
        match $2 with
          | {pexp_desc=Pexp_tuple [inner]; pexp_loc; pexp_attributes} -> mkexp (Pexp_construct($1, Some inner))
          | _ -> assert false
      else
        mkExplicitArityTupleExp (Pexp_construct($1, Some $2))
    }
```

The reason I think it is even unboxing the tuple like this is to make conversion from/to ml/reason more seamless. Reason uses explicit arity, and OCaml uses implicit arity. So we recognize it as a built in constructor type and make sure it has the right number of arguments and then auto-unbox. I actually think that not only are we ungracefully handling this case, but our general approach may be wrong because you can always redefine a type like:

```
type ttt = Some of int int | None of bytes
```

Then `Some x y` would cause a failure.

The auto-unboxing of tuple is still useful when *converting* a type from ML to Reason  (even if you can redefine the `Some` type) because it doesn't have to be a perfect conversion - the type checker will catch any incorrect guesses. But for standard parsing, I think we should not have any special behavior for Some/None unless the standard OCaml parser does.

Maybe @yunxing knows more about what this line of code does.

**Comment by jordwalke** [comment]
This is likely an easy fix, btw - I just want to make sure I have the right idea.

**Comment by yunxing** [comment]
@jordwalke Catching up. Yes, What happens is this line makes sure the right number of arguments get passed down to the constructor. We should remove this check and let the underlying type checker does its job.

**Comment by chenglou** [comment]
Stale!
