### ISSUE TITLE
Extensible variants reformat to Ocaml

### ISSUE THREAD

**Issue by IwanKaramazow** [facebook/reason#918]
```
module Attr = {
    type t = int;
};
type tag 'props = ..;
type ttype = Type;
type description 'props = {
  ttype: ttype,
  props: 'props
};
type element = Native (tag 'props) (description 'props): element;

type attrProps = { attr: Attr.t };

type tag 'props += Attr: tag attrProps;

```

```
module Attr = {
  type t = int;
};

type tag 'props = ..;

type ttype =
  | Type;

type description 'props = {ttype: ttype, props: 'props};

type attrProps = {attr: Attr.t};

type 'props tag +=
  | Attr: attrProps tag;
```
Notice how the extension of the variant gets reformatted to something halfway Ocaml, halfway Reason.

**Comment by jordwalke** [comment]
Whoever fixes this, please mark yourself as the assignee. Please add test cases as well.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=40407524)](https://www.bountysource.com/issues/40407524-extensible-variants-reformat-to-ocaml?utm_source=40407524&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by jordwalke** [comment]
@IwanKaramazow are you on master? If not, which version.

**Comment by IwanKaramazow** [comment]
I'm on master. My package.json includes `"reason": "facebook/reason"`.
Will fix this myself, is blocking me too much on RED

**Comment by jordwalke** [comment]
Okay thank you. I'll assign it to you.

**Comment by chenglou** [comment]
This is done. @jordwalke cough up the money! lol

**Comment by jordwalke** [comment]
Let me know if bounty source doesn't do its thing correctly.
