### ISSUE TITLE
Underscore in numbers

### ISSUE THREAD

**Issue by rickyvetter** [facebook/reason#929]
OCaml and Reason support underscores in numbers - usually used for readability - `3_000_000`. When you refmt, these underscores get removed. Is this intentional? It seems like these underscores should be preserved if possible to maintain readability and intent.

**Comment by hcarty** [comment]
This should be possible/more possible once the move to the 4.04.0 OCaml AST happens. The newer AST keeps the string representation of each numeric literal from the original code.

**Comment by yunxing** [comment]
Kind of duplicated with #511, let's merge this two.

**Comment by jordwalke** [comment]
@hcarty Wow, I didn't know that. Seems like a great feature.

**Comment by hcarty** [comment]
@jordwalke From this PR - https://github.com/ocaml/ocaml/pull/170
