### ISSUE TITLE
Parse comments *into* the AST.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#94]
4.03 parses the documentation _into_ the AST attributes, whereas `Reason` currently recovers them later at printing time. I'm told that parsing into the AST is slightly more accurate, and furthermore, we will be able to take advantage of tools such as `codoc` which automatically generate documentation among opening up other capabilities.

**Comment by jmmk** [comment]
@jordwalke What was the reasoning behind keeping the comments separate from the AST?

**Comment by jordwalke** [comment]
This is done now.
