### ISSUE TITLE
refmt produces untypable output for exception match cases

### ISSUE THREAD

**Issue by jberdine** [facebook/reason#940]
refmt on
```
switch (f ()) {
| x => Some x
| exception (Sys_error _ as exc) => raise exc
};
```
yields
```
switch (f ()) {
| x => Some x
| exception Sys_error _ as exc => raise exc
};
```
which does not type-check with `Error: Unbound value exc`.  Warning 11 (unused match case) is also triggered.

It seems that the parens in the exception match case are required for correct parsing, but refmt removes them anyway.

**Comment by jordwalke** [comment]
Thanks, I'll get to this next.

**Comment by IwanKaramazow** [comment]
Made a pr with a fix above.

**Comment by chenglou** [comment]
Pretty good response rate we're getting =D
