### ISSUE TITLE
Invokation of refmt without arguments produces unfriendly error message

### ISSUE THREAD

**Issue by andreypopp** [facebook/reason#945]
That's what I got:
```
% ./_install/bin/refmt                                                                                                                                                         
Fatal error: exception Refmt_impl.Invalid_config("Cannot determine default implementation parser for filename ''.")
```
I understand the origin of this error now but I thought that compiled version of refmt is broken at first.

**Comment by chenglou** [comment]
Doesn't it display the help page now? Which version are you on?

**Comment by andreypopp** [comment]
Tried this branch which is a port of 52c3b0215c89d82422322e31db4098fd0f8ca7e3

**Comment by jasonrose** [comment]
I caused this regression with my latest PR so I'll fix it.

**Comment by yunxing** [comment]
Should be fixed now, thanks!
