### ISSUE TITLE
Unused `newlinesAboveComments` in reason_pprint_ast.ml

### ISSUE THREAD

**Issue by IwanKaramazow** [facebook/reason#948]
While working on https://github.com/facebook/reason/issues/41, in an episode of severe bikeshedding, I found that `newlinesAboveComments` doesn't get used anywhere.
You can write `makeList ~newlinesAboveComments:1000`, but those newlines are never printed.
`prependSingleLineComment` (https://github.com/facebook/reason/blob/master/src/reason_pprint_ast.ml#L1780) only prints newlines above doc comments.

I noticed it would clash with `newLinesAboveItems`. Is that the reason it doesn't get used anywhere? 

An example:
```rust
type x = int;


/* Two newlines above */
let res = 1 + 1;
```
If you would write `makeList ~newLinesAboveItems:1 ~newLinesAboveComments:1`, with an implementation that considers `newLinesAboveItems`. There are two newlines inserted, when in fact I only want to get one newline for https://github.com/facebook/reason/issues/41.

Just putting this up here, no idea if this is intended?

**Comment by yunxing** [comment]
Looks like we don't actually need this. 

We changed the implementation of comments interleaving completely a few months back, this could be what's the remnant of previous implementation.

**Comment by chenglou** [comment]
Killed
