### ISSUE TITLE
Document contributor section

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#959]
cc @yunxing 

- [ ] basic knowledge of LR1 (Some good tutorial online)
- [ ] basic syntax of Menhir (syntax should be pretty simple)
- [ ] what do menhir/yacc do to auto matically resolve conflicts based on precedency and associativity specified (Menhir's manual)
- [ ] tutorial to work people through a simple syntax change in our parser that requires to resolve a conflict
- [ ] (bonus) add an error message description with the new syntax(edited)

**Comment by yunxing** [comment]
I didn't find a shortcut in this, it was very painful to me at first to understand all the conflicts when I make a simple change (Menhir's error messages helped a lot, but still). Not sure what do other parser contributors think?

**Comment by yunxing** [comment]
Let's work on this soon as we will have more syntaxes changes coming soon, and any help would be very appreciated.

**Comment by chenglou** [comment]
Done through https://github.com/facebook/reason/blob/88bd4db0e7ef1aab4dc9e7cde3db673f9f487151/src/README.md
