### ISSUE TITLE
Support and document having multiple versions of Reason installed.

### ISSUE THREAD

**Issue by jordwalke** [facebook/reason#96]
People will have many projects locally, each potentially requiring a different version of the Reason, and a different version of the compiler.
- [ ] We need to document how to do this and how to support it.
- [ ] We need to make it so that we don't rely on a global installation of Reason in that case.
- [ ] This is blocked on figuring out installation/package management story.

This will help us upgrade without breaking people (we will be aggressively upgrading the syntax). Not everyone will upgrade every project at once.

Imagine that we fix/improve syntax and when upgrading to a new version of `Reason`, some of the old code doesn't parse. We have a couple of options:
1.  Know that when a file was written with `v0` (maybe it's encoded at the top of the file?), we have Reason `v1` capable of parsing Reason `v0` as well.
2. Of course we will have a simple upgrade script (see the current hacky `./upgradeSyntax.sh`), but that requires that you supply the paths to both versions. It would be better if Reason `v1` somehow _included_ Reason `v0` as well.

Are there any problems I'm not thinking about yet?

**Comment by jaredly** [comment]
with bs-platform & esy, this is done.
