### ISSUE TITLE
Put reason version in `refmt -v`

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#976]
Good for debugging.

**Comment by yunxing** [comment]
On my list!

**Comment by tekknolagi** [comment]
I can tackle this, I think.

**Comment by chenglou** [comment]
Would be nice if doing master `refmt -v` shows the git hash or something, and not `1.4.0`. That was the context for this issue. Asking about someone's refmt installed version.

**Comment by yunxing** [comment]
Should be doable.

**Comment by tekknolagi** [comment]
Oh! That is different. I had already completed the version number. I think that can also be tackled, though.
