### ISSUE TITLE
Float formatting shouldn't have parentheses

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#988]
`2. *. -60.` formats to `2. *. (-60.)`

**Comment by bsansouci** [comment]
@jordwalke Any reason why we wrap unary minus with parens?

**Comment by chenglou** [comment]
@yunxing is fixing this right now afaik

**Comment by yunxing** [comment]
@bsansouci It's a legacy from ocaml https://github.com/ocaml/ocaml/blob/4.02.3/parsing/pprintast.ml#L183

**Comment by yunxing** [comment]
With the current function application syntax, it is actually hard to implement this properly as explained in #989. We can revisit if we move the the new function application syntax.

**Comment by chenglou** [comment]
¯\_(ツ)_/¯
