### ISSUE TITLE
Extension points should line break and not be on the same line when it's too long

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#997]
Repro:

```
let isArrayPolyfill: (Obj.t => Js.boolean) [@bs] = [%bs.raw "function(a) {return Object.prototype.toString.call(a) === '[object Array]'}"];
```

This is the new behavior after some attribute line break changes I think. Extensions should be legit expressions here.

**Comment by IwanKaramazow** [comment]
This isn't just extensions though: 

```
let x = "some super long string some super long stringsome super long stringsome super longstringsome super long string some super long string some super long string";
```

We can't break strings over multiple lines? Or what do you wanna see in this case?

**Comment by chenglou** [comment]
Before it was

```
let isArrayPolyfill: (Obj.t => Js.boolean) [@bs] = [%bs.raw 
  "function(a) {return Object.prototype.toString.call(a) === '[object Array]'}
"];
```

extension points aren't quite like attributes so maybe they should format like a function application or something.

**Comment by IwanKaramazow** [comment]
_Opens MacVim, starts debugging_

**Comment by chenglou** [comment]
cc @jordwalke to assess what I just said.

**Comment by IwanKaramazow** [comment]
No need for anything crazy, surgical insertion of `~break:IfNeed` in the right places gives us the best of both worlds. PR ready for review.

**Comment by chenglou** [comment]
Done! Thanks.
