### ISSUE TITLE
Atom locks up because of highlighting (likely)

### ISSUE THREAD

**Issue by chenglou** [facebook/reason#998]
I think some regexes triggered some edge-case regex behavior. Repro:

```reason
let foo: componentBagaaa props bar => state;
```
 Keep adding `a` to `componentBagaaa` and you'll see the editor getting slower and slower.

cc @freebroccolo @jordwalke

**Comment by freebroccolo** [comment]
Okay, I can reproduce. I'll take a look at it.

**Comment by chenglou** [comment]
Btw does VSCode slow down too? I guess so since it's the same regex engine right

**Comment by freebroccolo** [comment]
Yeah, it also slowed down.
